/* global Object */

const SPRITE_AUDIT_CONFIG = Object.freeze({
  assetRoot: "../../../",
  frameSize: Object.freeze([341, 341]),
  gameDisplaySizePx: 89,
  localStorageKey: "jkd-runtime-sprite-frame-audit-v2",
  issueTypes: Object.freeze([
    "direction",
    "transition",
    "anchor-drift",
    "clipping",
    "halo",
    "gray-leakage",
    "silhouette",
    "timing",
  ]),
  animations: Object.freeze([
    { id: "idle", label: "Idle", file: "sprites/character/character-v8/runtime/legacy-idle-clean-sheet.webp", frames: 34, columns: 16, fps: 8, orientation: "front", piskelSource: "sprites/character/character-v8/piskel/idle.piskel", sourceStatus: "feedback-polished Piskel source" },
    { id: "walk", label: "Walk", file: "sprites/character/character-v8/runtime/legacy-walk-clean-sheet.webp", frames: 51, columns: 16, fps: 14, orientation: "right", piskelSource: "sprites/character/character-v8/piskel/walk.piskel", sourceStatus: "feedback-polished Piskel source" },
    { id: "dig-sideways", label: "Dig Sideways", file: "sprites/character/character-v8/runtime/legacy-dig-sideways-clean-sheet.webp", frames: 18, columns: 16, fps: 30, orientation: "left", piskelSource: "sprites/character/character-v8/piskel/dig-sideways.piskel", sourceStatus: "foot-anchored Piskel source", views: Object.freeze([
      { id: "source", label: "Source: left", flipX: false },
      { id: "runtime-left", label: "Game: LEFT (unflipped)", flipX: false },
      { id: "runtime-right", label: "Game: RIGHT (flipped)", flipX: true },
    ]) },
    { id: "dig-up", label: "Dig Up", file: "sprites/character/character-v8/runtime/legacy-dig-up-clean-sheet.webp", frames: 9, columns: 9, fps: 30, orientation: "front-up", piskelSource: "sprites/character/character-v8/piskel/dig-up.piskel", sourceStatus: "scale-normalized Piskel source" },
    { id: "dig-up-sideways", label: "Dig Up Sideways", file: "sprites/character/character-v8/runtime/legacy-dig-up-sideways-clean-sheet.webp", frames: 13, columns: 13, fps: 30, orientation: "right-up", piskelSource: "markdown/audit/animation-audit/2026-07-02-legacy-miner-v8-frame-review/by-animation/dig-up-sideways/dig-up-sideways-review.piskel", sourceStatus: "review Piskel source", views: Object.freeze([
      { id: "source", label: "Source: UP-RIGHT", flipX: false },
      { id: "runtime-up-right", label: "Game: UP-RIGHT (fixed)", flipX: false },
      { id: "runtime-up-left", label: "Game: UP-LEFT (fixed)", flipX: true },
      { id: "expected-up-right", label: "Expected: UP-RIGHT", flipX: false },
      { id: "expected-up-left", label: "Expected: UP-LEFT", flipX: true },
    ]) },
    { id: "fly-climb", label: "Fly / Climb", file: "sprites/character/character-v8/runtime/legacy-fly-climb-clean-sheet.webp", frames: 25, columns: 16, fps: 14, orientation: "front", piskelSource: "markdown/audit/animation-audit/2026-07-02-legacy-miner-v8-frame-review/by-animation/fly-climb/fly-climb-review.piskel", sourceStatus: "review Piskel source" },
    { id: "dig-up-look", label: "Dig Up Look", file: "sprites/character/character-v8/runtime/legacy-dig-up-look-clean.png", frames: 1, columns: 1, fps: 1, orientation: "front-up", piskelSource: "sprites/character/character-v8/piskel/dig-up-look.piskel", sourceStatus: "scale-normalized Piskel source" },
    { id: "duck", label: "Duck", file: "sprites/character/character-v8/runtime/duck-downwards-sheet.webp", frames: 4, columns: 4, fps: 10, orientation: "front", piskelSource: "sprites/character/character-v8/piskel/duck-downwards.piskel", sourceStatus: "Piskel source with reverse recovery sequence" },
    { id: "dig-down", label: "Dig Down", file: "sprites/character/character-v8/runtime/dig-down-sheet.webp", frames: 5, columns: 5, fps: 12, orientation: "front", piskelSource: "markdown/audit/animation-audit/2026-07-02-legacy-miner-v8-frame-review/by-animation/dig-down/dig-down-review.piskel", sourceStatus: "review Piskel source", views: Object.freeze([
      { id: "source", label: "Source", flipX: false },
      { id: "runtime-facing-right", label: "Game: normal, facing RIGHT", flipX: false },
      { id: "runtime-facing-left", label: "Game: normal, facing LEFT", flipX: true },
      { id: "runtime-third-hit", label: "Game: every third hit", flipX: true },
    ]) },
    { id: "falling", label: "Falling", file: "sprites/character/character-v8/runtime/falling-downward-through-sky-sheet.webp", frames: 7, columns: 7, fps: 12, orientation: "front", piskelSource: "sprites/character/character-v8/piskel/falling-downward-through-sky.piskel", sourceStatus: "alpha-reconstructed Piskel source" },
    { id: "lean-wall", label: "Lean Against Wall", file: "sprites/character/character-v8/runtime/leans-against-wall-sheet.webp", frames: 4, columns: 4, fps: 8, orientation: "side", piskelSource: "sprites/character/character-v8/piskel/leans-against-wall.piskel", sourceStatus: "wall-aligned Piskel source" },
    { id: "combat-return", label: "Combat Return", file: "sprites/character/character-v8/runtime/combat-idle-to-normal-idle-sheet.webp", frames: 46, columns: 16, fps: 14, orientation: "action-facing", piskelSource: "sprites/character/character-v8/piskel/combat-idle-to-normal-idle.piskel", sourceStatus: "feedback-polished Piskel source", views: Object.freeze([
      { id: "source", label: "Source", flipX: false },
      { id: "combat-facing-right", label: "Combat lock: action faced RIGHT", flipX: false },
      { id: "combat-facing-left", label: "Combat lock: action faced LEFT", flipX: true },
    ]) },
    { id: "quickslash", label: "Quickslash", files: ["sprites/character/character-v2/digging/abilities/quickslash/uickslash-1.webp", "sprites/character/character-v2/digging/abilities/quickslash/uickslash-2 .webp"], frames: 2, columns: 1, fps: 12, orientation: "left", piskelSource: "sprites/character/piskel/runtime-active/quickslash.piskel", sourceStatus: "Piskel editable source", views: Object.freeze([
      { id: "source", label: "Source: LEFT", flipX: false },
      { id: "runtime-right", label: "Game: RIGHT (fixed)", flipX: true },
      { id: "runtime-left", label: "Game: LEFT (fixed)", flipX: false },
      { id: "expected-right", label: "Expected: RIGHT", flipX: true },
      { id: "expected-left", label: "Expected: LEFT", flipX: false },
    ]) },
    { id: "quickslash-v2", label: "Quickslash V2 (feedback polish)", file: "sprites/character/character-v8/runtime/quickslash-v2-clean-sheet.webp", frames: 39, columns: 16, fps: 30, orientation: "right", displaySizePx: 98, piskelSource: "sprites/character/character-v8/piskel/quickslash-v2.piskel", sourceStatus: "feedback-polished Piskel + refreshed Blender envelope", blenderSource: "sprites/character/character-v8/reports/blender-motion-profiles/quickslash-v2-motion-profile.json", views: Object.freeze([
      { id: "source", label: "Source: RIGHT", flipX: false },
      { id: "review-right", label: "Review: RIGHT", flipX: false },
      { id: "review-left", label: "Review: LEFT (mirrored)", flipX: true },
    ]) },
    { id: "teleport-in", label: "Teleport In (feedback polish)", file: "sprites/character/character-v8/runtime/teleport-in-clean-sheet.webp", frames: 38, columns: 16, fps: 30, orientation: "front-action", piskelSource: "sprites/character/character-v8/piskel/teleport-in.piskel", sourceStatus: "scale-normalized Piskel + refreshed Blender envelope", blenderSource: "sprites/character/character-v8/reports/blender-motion-profiles/teleport-in-motion-profile.json" },
    { id: "thunder-charge", label: "Thunder Charge", file: "sprites/character/character-v8/runtime/thunder-charge-sheet.webp", frames: 1, columns: 1, fps: 6, orientation: "front", piskelSource: "markdown/audit/animation-audit/2026-07-02-legacy-miner-v8-frame-review/by-animation/thunder-charge/thunder-charge-review.piskel", sourceStatus: "review Piskel source" },
    { id: "thunder-strike", label: "Thunder Strike", file: "sprites/character/character-v8/runtime/thunder-strike-sheet.webp", frames: 1, columns: 1, fps: 12, orientation: "front", piskelSource: "markdown/audit/animation-audit/2026-07-02-legacy-miner-v8-frame-review/by-animation/thunder-strike/thunder-strike-review.piskel", sourceStatus: "review Piskel source" },
  ]),
  reportedTargets: Object.freeze([
    { id: "dig-up-sideways-direction", animationId: "dig-up-sideways", issue: "direction", label: "Fixed: UP-LEFT / UP-RIGHT mirror mapping", codeRef: "world/playScene/PlaySceneGameplay.js", expected: "The right-up source is unflipped for UP-RIGHT and flipped for UP-LEFT." },
    { id: "quickslash-direction", animationId: "quickslash", issue: "direction", label: "Fixed: Quickslash mirror mapping", codeRef: "world/playScene/PlaySceneUpdate.js", expected: "The left-facing source is flipped for RIGHT and unflipped for LEFT." },
    { id: "idle-feedback-polish", animationId: "idle", issue: "halo", label: "Feedback applied: frame 4 removed; late-frame white fringe rebuilt", codeRef: "tools/build_legacy_miner_v8_runtime.py", expected: "Verify the 34-frame loop has no pop at frames 3→4 and no white/gray edge leakage in frames 21→34." },
    { id: "walk-feedback-polish", animationId: "walk", issue: "gray-leakage", label: "Feedback applied: hand, foot, and leg alpha holes reconstructed", codeRef: "tools/build_legacy_miner_v8_runtime.py", expected: "Check flagged phases on checker matte; real open silhouette remains transparent while small enclosed holes are filled." },
    { id: "dig-sideways-foot-anchor", animationId: "dig-sideways", issue: "anchor-drift", label: "Feedback applied: foot-based root anchoring", codeRef: "tools/build_legacy_miner_v8_runtime.py", expected: "The feet should remain planted through frames 1–2, 7–9, and the final recovery instead of following arm/tool reach." },
    { id: "dig-up-scale", animationId: "dig-up", issue: "silhouette", label: "Feedback applied: Dig Up scale normalized", codeRef: "tools/build_legacy_miner_v8_runtime.py", expected: "All nine frames are 3.5% larger with a stable bottom anchor and should match Idle body scale." },
    { id: "duck-recovery", animationId: "duck", issue: "transition", label: "Review: reverse Duck recovery before Idle", codeRef: "sandbox transition: duck-to-idle", expected: "Release should play 4→3→2→1, then enter Idle without a standing pop." },
    { id: "falling-alpha", animationId: "falling", issue: "gray-leakage", label: "Feedback applied: Falling alpha reconstructed and scale normalized", codeRef: "tools/build_legacy_miner_v8_runtime.py", expected: "Inspect feet and dust on checker matte; no see-through pinholes should remain inside the character." },
    { id: "lean-wall-contact", animationId: "lean-wall", issue: "anchor-drift", label: "Feedback applied: wall guide removed and contact offsets corrected", codeRef: "tools/build_legacy_miner_v8_runtime.py", expected: "Frames 3–4 use the stronger contact offset and no baked gray wall line remains." },
    { id: "combat-return-polish", animationId: "combat-return", issue: "transition", label: "Feedback applied: frame 9 culled; frames 11–12 tone/scale matched", codeRef: "tools/build_legacy_miner_v8_runtime.py", expected: "The 46-frame return should cross the former frame-9 cut without a jump or pale flash." },
    { id: "combat-dig-transition", animationId: "combat-return", issue: "transition", label: "Reported: combat-to-dig direction jump", codeRef: "world/playScene/PlaySceneSetup.js:455-465; world/playScene/PlaySceneGameplay.js:347-377", expected: "The combat lock and the following dig action must agree on their horizontal orientation." },
    { id: "dig-down-alternate", animationId: "dig-down", issue: "direction", label: "Fixed: Dig Down alternates without changing walk facing", codeRef: "world/playScene/PlaySceneGameplay.js; world/playScene/PlaySceneSetup.js", expected: "Hits may alternate left/right, then the combat return and next walk must restore the controller-facing direction." },
    { id: "quickslash-v2-impact-cull", animationId: "quickslash-v2", issue: "timing", label: "Feedback applied: local frame 23 removed", codeRef: "sprites/character/character-v8/runtime/legacy-miner-v8-runtime-manifest.json", expected: "Review the new local frames 22 to 23 transition; the rejected starburst frame is no longer present." },
    { id: "quickslash-v2-edge-touch", animationId: "quickslash-v2", issue: "clipping", label: "Review: large slash FX touches the square frame edge", codeRef: "sprites/character/character-v8/previews/quickslash-v2-runtime-contact-drift-report.json", expected: "Decide in Piskel whether the edge contact reads as intentional impact or needs selective FX pull-in; do not shrink the character globally." },
    { id: "teleport-in-curated-cut", animationId: "teleport-in", issue: "timing", label: "Curated cut: source 08 to 14 (confirmed intentional)", codeRef: "sprites/character/character-v8/runtime/legacy-miner-v8-runtime-manifest.json", expected: "Review local frames 7 to 8 for timing only; preserve the user's removed frames." },
    { id: "teleport-in-scale", animationId: "teleport-in", issue: "silhouette", label: "Feedback applied: visible-character phase reduced", codeRef: "tools/build_legacy_miner_v8_runtime.py", expected: "Local frames 9–27 ease from 96% to 90% and back; verify the portal transition stays smooth." },
  ]),
  transitions: Object.freeze([
    { id: "combat-to-dig-down", label: "Combat lock to Dig Down", codeRef: "PlaySceneGameplay.js:347-377", steps: Object.freeze([
      { animationId: "combat-return", frames: [43, 44, 45], viewId: "combat-facing-right" },
      { animationId: "dig-down", frames: [0, 1, 2], viewId: "runtime-facing-right" },
    ]) },
    { id: "combat-to-side-right", label: "Combat lock to Side Dig RIGHT", codeRef: "PlaySceneGameplay.js:358-377", steps: Object.freeze([
      { animationId: "combat-return", frames: [43, 44, 45], viewId: "combat-facing-right" },
      { animationId: "dig-sideways", frames: [0, 1, 2], viewId: "runtime-right" },
    ]) },
    { id: "combat-to-side-left", label: "Combat lock to Side Dig LEFT", codeRef: "PlaySceneGameplay.js:358-377", steps: Object.freeze([
      { animationId: "combat-return", frames: [43, 44, 45], viewId: "combat-facing-left" },
      { animationId: "dig-sideways", frames: [0, 1, 2], viewId: "runtime-left" },
    ]) },
    { id: "duck-to-idle", label: "Duck release to Idle", codeRef: "proposed recovery: reverse duck frames before idle", steps: Object.freeze([
      { animationId: "duck", frames: [3, 2, 1, 0], viewId: "source" },
      { animationId: "idle", frames: [0, 1, 2], viewId: "source" },
    ]) },
    { id: "quickslash-v2-curated-cut", label: "Quickslash V2 rejected-frame cut", codeRef: "local frame 23 removed", steps: Object.freeze([
      { animationId: "quickslash-v2", frames: [20, 21, 22], viewId: "review-right" },
      { animationId: "quickslash-v2", frames: [23, 24, 25], viewId: "review-right" },
    ]) },
    { id: "teleport-in-curated-cut", label: "Teleport In curated phase cut", codeRef: "source 08 -> 14 (intentional)", steps: Object.freeze([
      { animationId: "teleport-in", frames: [5, 6, 7], viewId: "source" },
      { animationId: "teleport-in", frames: [8, 9, 10], viewId: "source" },
    ]) },
  ]),
});
