/* global Object */
const LEGACY_MINER_REVIEW = Object.freeze({
  runtimeBase: "../../../sprites/character/character-v8/runtime",
  reviewBase: "../../../markdown/audit/animation-audit/2026-07-03-legacy-miner-demo-review",
  cache: "legacy-miner-review-demo-20260703",
  frame: { frameWidth: 341, frameHeight: 341 },
  displaySize: 178,
  sheets: {
    walk: "legacy-walk-clean-sheet.webp",
    digSideways: "legacy-dig-sideways-clean-sheet.webp",
    digUp: "legacy-dig-up-clean-sheet.webp",
    digDown: "dig-down-sheet.webp",
    duck: "duck-downwards-sheet.webp",
    lean: "leans-against-wall-sheet.webp",
    falling: "falling-downward-through-sky-sheet.webp",
    combatReturn: "combat-idle-to-normal-idle-sheet.webp",
    quickslash: "legacy-quickslash-clean-sheet.webp",
    thunderCharge: "thunder-charge-sheet.webp",
    thunderStrike: "thunder-strike-sheet.webp",
    digDownCandidate: "../review/dig-down-candidate-sheet.webp",
    fallingCandidate: "../review/falling-candidate-sheet.webp",
  },
  reviewSheets: {
    digDownCandidate: "sheets/dig-down-candidate-sheet.webp",
    fallingCandidate: "sheets/falling-candidate-sheet.webp",
  },
  motionProfile: "legacy-miner-motion-profile.json",
  specs: [
    { id: "dig-down", label: "Dig Down A/B", currentSheet: "digDown", candidateSheet: "digDownCandidate", frames: 5, fps: 18, repeat: 0, mode: "dig-down", guide: "dig-down", currentLabel: "current", candidateLabel: "candidate" },
    { id: "falling", label: "Falling A/B", currentSheet: "falling", candidateSheet: "fallingCandidate", frames: 7, fps: 12, repeat: 0, mode: "fall", guide: "falling", currentLabel: "current", candidateLabel: "candidate" },
    { id: "side-right", label: "Side Dig Right", currentSheet: "digSideways", candidateSheet: "digSideways", frames: 18, fps: 30, repeat: 0, mode: "side-right", guide: "dig-sideways", currentLabel: "approved sheet", candidateLabel: "right target", currentFlip: false, candidateFlip: false },
    { id: "side-left", label: "Side Dig Left", currentSheet: "digSideways", candidateSheet: "digSideways", frames: 18, fps: 30, repeat: 0, mode: "side-left", guide: "dig-sideways", currentLabel: "approved sheet", candidateLabel: "left target", currentFlip: false, candidateFlip: true },
    { id: "walk", label: "Walk", currentSheet: "walk", frames: 51, fps: 14, repeat: -1, mode: "walk" },
    { id: "dig-up", label: "Dig Up", currentSheet: "digUp", frames: 9, fps: 30, repeat: 0, mode: "dig-up" },
    { id: "duck", label: "Duck", currentSheet: "duck", frames: 4, fps: 8, repeat: 0, mode: "duck" },
    { id: "lean", label: "Lean Wall", currentSheet: "lean", frames: 4, fps: 8, repeat: 0, mode: "wall" },
    { id: "combat-return", label: "Combat Return", currentSheet: "combatReturn", frames: 47, fps: 14, repeat: 0, mode: "idle" },
    { id: "quickslash", label: "Quickslash", currentSheet: "quickslash", frames: 2, fps: 12, repeat: 0, mode: "idle" },
    { id: "thunder-charge", label: "Thunder Charge", currentSheet: "thunderCharge", frames: 1, fps: 6, repeat: -1, mode: "idle" },
    { id: "thunder-strike", label: "Thunder Strike", currentSheet: "thunderStrike", frames: 1, fps: 12, repeat: 0, mode: "dig-down" },
  ],
});
