/* global Object */
const LEGACY_MINER_REVIEW = Object.freeze({
  runtimeBase: "../../../sprites/character/character-v8/runtime",
  frame: { frameWidth: 341, frameHeight: 341 },
  displaySize: 178,
  defaultPack: "candidate",
  visualModes: Object.freeze({
    defaultMode: "off",
    off: Object.freeze({
      label: "Off",
      spriteScale: 1.0,
      swapCurrentToCandidate: false,
      glowTint: 0x7bbfff,
      glowStrength: 0,
      trailLength: 0,
      outlineAlpha: 0,
      backgroundTop: 0x161616,
      backgroundBottom: 0x0f1115,
      vignetteStrength: 0,
      grainStrength: 0,
      fxPulseSpeed: 0,
      conceptBackdropEnabled: false,
      outlineTint: 0x7bbfff,
      trailTint: 0x95c7ff,
    }),
    swap: Object.freeze({
      label: "Swap",
      spriteScale: 1.06,
      swapCurrentToCandidate: true,
      glowTint: 0x7de7ff,
      glowStrength: 0.24,
      trailLength: 5,
      outlineAlpha: 0.28,
      backgroundTop: 0x181820,
      backgroundBottom: 0x1c1414,
      vignetteStrength: 0.25,
      grainStrength: 0.07,
      fxPulseSpeed: 0.065,
      conceptBackdropEnabled: false,
      motionStreak: false,
      outlineTint: 0x85e4ff,
      trailTint: 0x97e8ff,
    }),
    impact: Object.freeze({
      label: "Impact",
      spriteScale: 1.18,
      swapCurrentToCandidate: true,
      glowTint: 0xff9f55,
      glowStrength: 0.68,
      trailLength: 9,
      outlineAlpha: 0.55,
      backgroundTop: 0x0a101e,
      backgroundBottom: 0x1f1411,
      vignetteStrength: 0.56,
      grainStrength: 0.2,
      fxPulseSpeed: 0.16,
      conceptBackdropEnabled: false,
      motionStreak: true,
      outlineTint: 0xffa16d,
      trailTint: 0xffc18f,
    }),
    meshyOrHiggs: Object.freeze({
      label: "Meshy/Higgs",
      spriteScale: 1.08,
      swapCurrentToCandidate: true,
      glowTint: 0xde8dff,
      glowStrength: 0.82,
      trailLength: 11,
      outlineAlpha: 0.68,
      backgroundTop: 0x0d0d15,
      backgroundBottom: 0x240e2b,
      vignetteStrength: 0.75,
      grainStrength: 0.3,
      fxPulseSpeed: 0.14,
      conceptBackdropEnabled: true,
      motionStreak: true,
      conceptFallback: "../../../sprites/character/character-v8/runtime/legacy-idle-clean-sheet.webp",
      outlineTint: 0xd5a8ff,
      trailTint: 0xf4c2ff,
    }),
  }),
  packs: Object.freeze({
    candidate: Object.freeze({
      label: "Candidate cleanup (2026-07-03)",
      reviewBase: "../../../markdown/audit/animation-audit/2026-07-03-legacy-miner-demo-review",
      cache: "legacy-miner-review-demo-20260703f",
      motionProfileBase: "../../../markdown/audit/animation-audit/2026-07-03-legacy-miner-demo-review",
      motionProfile: "legacy-miner-motion-profile.json",
      reviewSheets: {
        walkCandidate: "sheets/walk-candidate-sheet.webp",
        idleKeptCurrent: "sheets/idle-current-kept-sheet.webp",
        idleCandidate: "sheets/idle-candidate-sheet.webp",
        digDownCandidate: "sheets/dig-down-candidate-sheet.webp",
        fallingCandidate: "sheets/falling-downward-through-sky-candidate-sheet.webp",
        flyClimbCandidate: "sheets/fly-climb-candidate-sheet.webp",
        leanCandidate: "sheets/leans-against-wall-candidate-sheet.webp",
        thunderStrikeCandidate: "sheets/thunder-strike-candidate-sheet.webp",
        thunderChargeCandidate: "sheets/thunder-charge-candidate-sheet.webp",
        combatReturnCandidate: "sheets/combat-idle-to-normal-idle-candidate-sheet.webp",
        quickslashCandidate: "sheets/quickslash-candidate-sheet.webp",
        digSidewaysCandidate: "sheets/dig-sideways-candidate-sheet.webp",
        digUpCandidate: "sheets/dig-up-candidate-sheet.webp",
        digUpSidewaysCandidate: "sheets/dig-up-sideways-candidate-sheet.webp",
        duckCandidate: "sheets/duck-downwards-candidate-sheet.webp",
      },
    }),
    runtimeMirror: Object.freeze({
      label: "Legacy runtime mirror",
      reviewBase: "../../../sprites/character/character-v8/runtime",
      cache: "legacy-miner-review-demo-runtime-v1",
      motionProfileBase: "../../../markdown/audit/animation-audit/2026-07-03-legacy-miner-demo-review",
      motionProfile: "legacy-miner-motion-profile.json",
      candidateFromRuntime: true,
      currentSheets: {
        idleKeptCurrent: "legacy-idle-clean-sheet.webp",
      },
    }),
  }),
  sheets: {
    walk: "legacy-walk-clean-sheet.webp",
    idle: "legacy-idle-clean-sheet.webp",
    digSideways: "legacy-dig-sideways-clean-sheet.webp",
    digUp: "legacy-dig-up-clean-sheet.webp",
    digUpSideways: "legacy-dig-up-sideways-clean-sheet.webp",
    digDown: "dig-down-sheet.webp",
    duck: "duck-downwards-sheet.webp",
    lean: "leans-against-wall-sheet.webp",
    falling: "falling-downward-through-sky-sheet.webp",
    flyClimb: "legacy-fly-climb-clean-sheet.webp",
    combatReturn: "combat-idle-to-normal-idle-sheet.webp",
    quickslash: "legacy-quickslash-clean-sheet.webp",
    thunderCharge: "thunder-charge-sheet.webp",
    thunderStrike: "thunder-strike-sheet.webp",
  },
  motionProfile: "legacy-miner-motion-profile.json",
  specs: [
    { id: "dig-down", label: "Dig Down A/B", currentSheet: "digDown", candidateSheet: "digDownCandidate", frames: 5, fps: 18, repeat: 0, mode: "dig-down", guide: "dig-down", currentLabel: "runtime", candidateLabel: "candidate" },
    { id: "falling", label: "Falling A/B", currentSheet: "falling", candidateSheet: "fallingCandidate", frames: 7, fps: 12, repeat: 0, mode: "fall", guide: "falling", currentLabel: "current", candidateLabel: "candidate" },
    { id: "fly", label: "Flying A/B", currentSheet: "flyClimb", candidateSheet: "flyClimbCandidate", frames: 25, fps: 14, repeat: -1, mode: "fly", guide: "fly-climb", currentLabel: "current alpha", candidateLabel: "solid candidate" },
    { id: "side-right", label: "Side Dig Right", currentSheet: "digSideways", candidateSheet: "digSidewaysCandidate", frames: 18, fps: 30, repeat: 0, mode: "side-right", guide: "dig-sideways", currentLabel: "right current", candidateLabel: "right target", currentFlip: true, candidateFlip: true },
    { id: "side-left", label: "Side Dig Left", currentSheet: "digSideways", candidateSheet: "digSidewaysCandidate", frames: 18, fps: 30, repeat: 0, mode: "side-left", guide: "dig-sideways", currentLabel: "left current", candidateLabel: "left target", currentFlip: false, candidateFlip: false },
    { id: "walk", label: "Walk A/B", currentSheet: "walk", candidateSheet: "walkCandidate", frames: 51, fps: 14, repeat: -1, mode: "walk", currentLabel: "current leak", candidateLabel: "matte solid" },
    { id: "idle", label: "Idle A/B", currentSheet: "idleKeptCurrent", candidateSheet: "idleCandidate", frames: 22, fps: 8, repeat: -1, mode: "idle", currentLabel: "kept current", candidateLabel: "removed halo tail" },
    { id: "dig-up", label: "Dig Up A/B", currentSheet: "digUp", candidateSheet: "digUpCandidate", frames: 9, fps: 30, repeat: 0, mode: "dig-up" },
    { id: "dig-up-sideways", label: "Dig Up Side A/B", currentSheet: "digUpSideways", candidateSheet: "digUpSidewaysCandidate", frames: 13, fps: 30, repeat: 0, mode: "up-side-right" },
    { id: "duck", label: "Duck A/B", currentSheet: "duck", candidateSheet: "duckCandidate", frames: 4, fps: 8, repeat: 0, mode: "duck" },
    { id: "lean", label: "Lean Wall A/B", currentSheet: "lean", candidateSheet: "leanCandidate", frames: 4, fps: 8, repeat: 0, mode: "wall" },
    { id: "combat-return", label: "Combat Return A/B", currentSheet: "combatReturn", candidateSheet: "combatReturnCandidate", frames: 47, fps: 14, repeat: 0, mode: "idle" },
    { id: "quickslash-right", label: "Quickslash Right", currentSheet: "quickslash", candidateSheet: "quickslashCandidate", frames: 2, fps: 12, repeat: 0, mode: "side-right", guide: "quickslash", currentFlip: true, candidateFlip: true },
    { id: "quickslash-left", label: "Quickslash Left", currentSheet: "quickslash", candidateSheet: "quickslashCandidate", frames: 2, fps: 12, repeat: 0, mode: "side-left", guide: "quickslash", currentFlip: false, candidateFlip: false },
    { id: "thunder-charge", label: "Thunder Charge A/B", currentSheet: "thunderCharge", candidateSheet: "thunderChargeCandidate", frames: 1, fps: 6, repeat: -1, mode: "idle" },
    { id: "thunder-strike", label: "Thunder Strike A/B", currentSheet: "thunderStrike", candidateSheet: "thunderStrikeCandidate", frames: 1, fps: 12, repeat: 0, mode: "dig-down", guide: "thunder-strike" },
  ],
});
