import { UI_FONTS } from "./uiLayout.js";

export const APPROVED_HUD_SKIN = Object.freeze({
  enabled: true,
  assetPrefix: "ui-hud-approved-",
  referenceViewport: Object.freeze({ width: 1280, height: 720 }),
  paths: Object.freeze({
    playerCore: "sprites/UI/hud-approved-v1/player-core.png",
    playerCoreTorchOff: "sprites/UI/hud-approved-v1/player-core-torch-off.png",
    buffChip: "sprites/UI/hud-approved-v1/buff-chip.png",
    combo: "sprites/UI/hud-approved-v1/combo-frame.png",
    notification: "sprites/UI/hud-approved-v1/notification-frame.png",
    worldState: "sprites/UI/weather-indicator-v1/world-state-weather-v2.png",
    audioMusic: "sprites/UI/hud-approved-v1/audio-music.png",
    audioSfx: "sprites/UI/hud-approved-v1/audio-sfx.png",
    xp: "sprites/UI/hud-approved-v1/xp-frame.png",
    inventory: "sprites/UI/loot-pickups/inventory-bag-approved-full.png",
    inventoryFullness01: "sprites/UI/inventory-fullness-v3/inventory-fullness-01.png",
    inventoryFullness02: "sprites/UI/inventory-fullness-v3/inventory-fullness-02.png",
    inventoryFullness03: "sprites/UI/inventory-fullness-v3/inventory-fullness-03.png",
    inventoryFullness04: "sprites/UI/inventory-fullness-v3/inventory-fullness-04.png",
    inventoryFullness05: "sprites/UI/inventory-fullness-v3/inventory-fullness-05.png",
    inventoryFullness06: "sprites/UI/inventory-fullness-v3/inventory-fullness-06.png",
    inventoryFullness07: "sprites/UI/inventory-fullness-v3/inventory-fullness-07.png",
    inventoryFullness08: "sprites/UI/inventory-fullness-v3/inventory-fullness-08.png",
    inventoryFullness09: "sprites/UI/inventory-fullness-v3/inventory-fullness-09.png",
    inventoryFullness10: "sprites/UI/inventory-fullness-v3/inventory-fullness-10.png",
    inventoryKeycap: "sprites/UI/hud-cohesion-v1/inventory-keycap-v1.png",
    tutorialCurrentAction: "sprites/UI/hud-cohesion-v1/tutorial-current-action-v1.png",
  }),
  font: Object.freeze({
    family: UI_FONTS.display,
    color: "#f4e8c8",
    secondary: "#b9c8d3",
    cyan: "#65d8f2",
    gold: "#f0c765",
    shadow: "#02060a",
    strokeThickness: 2,
  }),
  layout: Object.freeze({
    playerCore: Object.freeze({ x: 12, y: 14, width: 320, height: 71 }),
    torchBurn: Object.freeze({
      sourceWidth: 417,
      sourceHeight: 93,
      sourceCrop: Object.freeze({ x: 347, y: 13, width: 59, height: 73 }),
    }),
    depth: Object.freeze({ x: 95, y: 29, fontSize: 18 }),
    gemPower: Object.freeze({ x: 109, y: 57, width: 169, height: 17, radius: 2, labelX: 112, labelY: 56, fontSize: 14 }),
    torchIntensity: Object.freeze({ x: 190, y: 84, width: 142, height: 29, fontSize: 11, lineSpacing: -2 }),
    buffs: Object.freeze({ x: 14, y: 120, width: 131, height: 30, gap: 6, maxVisible: 3, fontSize: 12 }),
    combo: Object.freeze({ y: 14, width: 221, height: 55, textY: 14, fontSize: 17, timerX: 12, timerY: 42, timerWidth: 197, timerHeight: 4 }),
    notification: Object.freeze({
      y: 360,
      width: 430,
      minHeight: 76,
      iconInset: 82,
      rightInset: 92,
      verticalPadding: 42,
      titleFontSize: 11,
      fontSize: 15,
      counterFontSize: 11,
      controlSize: 38,
      dismissSize: 30,
      titleTopInset: 14,
      counterBottomInset: 10,
      previousInsetX: 20,
      nextInsetX: 30,
      dismissInsetX: 17,
      dismissInsetY: 14,
      cycleOffsetY: 8,
      controlHitWidth: 52,
      controlHitHeight: 48,
      lineSpacing: 1,
    }),
    worldState: Object.freeze({
      right: 80,
      y: 14,
      width: 250,
      height: 42,
      sourceCrop: Object.freeze({ x: 192, y: 4, width: 554, height: 91 }),
      timeX: 12,
      dayX: 116,
      topY: 21,
      timeFontSize: 13,
      dayFontSize: 12,
    }),
    audio: Object.freeze({ right: 12, y: 14, width: 52, height: 38, gap: 4 }),
    xp: Object.freeze({ bottom: 13, width: 504, height: 38, barX: 92, barY: 13, barWidth: 286, barHeight: 12, levelX: 18, xpRight: 18, fontSize: 13 }),
  }),
});
