import { UI_FONTS } from "./uiLayout.js";

export const APPROVED_HUD_SKIN = Object.freeze({
  enabled: true,
  assetPrefix: "ui-hud-approved-",
  referenceViewport: Object.freeze({ width: 1280, height: 720 }),
  paths: Object.freeze({
    playerCore: "sprites/UI/hud-approved-v1/player-core.png",
    playerCoreTorchOff: "sprites/UI/hud-approved-v1/player-core-torch-off.png",
    buffChip: "sprites/UI/hud-approved-v1/buff-chip.png",
    combo: "sprites/UI/hud-approved-v1/combo-frame.png",
    notification: "sprites/UI/hud-approved-v1/notification-frame.png",
    worldState: "sprites/UI/hud-approved-v1/world-state.png",
    audioMusic: "sprites/UI/hud-approved-v1/audio-music.png",
    audioSfx: "sprites/UI/hud-approved-v1/audio-sfx.png",
    xp: "sprites/UI/hud-approved-v1/xp-frame.png",
    inventory: "sprites/UI/loot-pickups/inventory-bag-approved-full.png",
  }),
  font: Object.freeze({
    family: UI_FONTS.display,
    color: "#f4e8c8",
    secondary: "#b9c8d3",
    cyan: "#65d8f2",
    gold: "#f0c765",
    shadow: "#02060a",
    strokeThickness: 2,
  }),
  layout: Object.freeze({
    playerCore: Object.freeze({ x: 12, y: 14, width: 320, height: 71 }),
    depth: Object.freeze({ x: 95, y: 29, fontSize: 18 }),
    gemPower: Object.freeze({ x: 109, y: 57, width: 169, height: 17, radius: 2, labelX: 112, labelY: 56, fontSize: 14 }),
    buffs: Object.freeze({ x: 14, y: 91, width: 131, height: 30, gap: 6, maxVisible: 3, fontSize: 12 }),
    combo: Object.freeze({ y: 20, width: 221, height: 55, textY: 14, fontSize: 17, timerX: 12, timerY: 42, timerWidth: 197, timerHeight: 4 }),
    notification: Object.freeze({
      y: 360,
      width: 430,
      minHeight: 76,
      iconInset: 82,
      rightInset: 92,
      verticalPadding: 42,
      titleFontSize: 11,
      fontSize: 15,
      counterFontSize: 11,
      controlSize: 38,
      dismissSize: 30,
      titleTopInset: 14,
      counterBottomInset: 10,
      previousInsetX: 20,
      nextInsetX: 30,
      dismissInsetX: 17,
      dismissInsetY: 14,
      cycleOffsetY: 8,
      controlHitWidth: 52,
      controlHitHeight: 48,
      lineSpacing: 1,
    }),
    worldState: Object.freeze({ right: 80, y: 20, width: 264, height: 64, timeX: 16, dayX: 123, weatherX: 16, temperatureX: 165, topY: 12, bottomY: 39, fontSize: 14 }),
    weatherBar: Object.freeze({ xInset: 56, y: 57, width: 192, height: 3 }),
    audio: Object.freeze({ right: 12, y: 20, width: 52, height: 38, gap: 4 }),
    xp: Object.freeze({ bottom: 20, width: 504, height: 38, barX: 92, barY: 13, barWidth: 286, barHeight: 12, levelX: 18, xpRight: 18, fontSize: 13 }),
  }),
});
