import { UI_FONTS } from "./uiLayout.js";

export const APPROVED_HUD_SKIN = Object.freeze({
  enabled: true,
  assetPrefix: "ui-hud-approved-",
  referenceViewport: Object.freeze({ width: 1280, height: 720 }),
  paths: Object.freeze({
    playerCoreShell: "sprites/UI/baked-copy-v1/player-core-integrated-v2.png",
    playerCore: "sprites/UI/hud-approved-v1/player-core.png",
    playerCoreTorchOff: "sprites/UI/hud-approved-v1/player-core-torch-off.png",
    buffChip: "sprites/UI/hud-approved-v1/buff-chip.png",
    combo: "sprites/UI/hud-approved-v1/combo-frame.png",
    notification: "sprites/UI/hud-approved-v1/notification-frame.png",
    hardcoreStatusShell: "sprites/UI/dynamic-feedback-v2/hardcore-status-shell-v2.png",
    levelUpShell: "sprites/UI/baked-copy-v1/level-up-integrated-v2.png",
    worldState: "sprites/UI/weather-indicator-v1/world-state-weather-v2.png",
    audioMusic: "sprites/UI/hud-approved-v1/audio-music.png",
    audioSfx: "sprites/UI/hud-approved-v1/audio-sfx.png",
    xp: "sprites/UI/baked-copy-v1/xp-integrated-v2.png",
    inventory: "sprites/UI/loot-pickups/inventory-bag-approved-full.png",
    inventoryFullness01: "sprites/UI/inventory-fullness-v3/inventory-fullness-01.png",
    inventoryFullness02: "sprites/UI/inventory-fullness-v3/inventory-fullness-02.png",
    inventoryFullness03: "sprites/UI/inventory-fullness-v3/inventory-fullness-03.png",
    inventoryFullness04: "sprites/UI/inventory-fullness-v3/inventory-fullness-04.png",
    inventoryFullness05: "sprites/UI/inventory-fullness-v3/inventory-fullness-05.png",
    inventoryFullness06: "sprites/UI/inventory-fullness-v3/inventory-fullness-06.png",
    inventoryFullness07: "sprites/UI/inventory-fullness-v3/inventory-fullness-07.png",
    inventoryFullness08: "sprites/UI/inventory-fullness-v3/inventory-fullness-08.png",
    inventoryFullness09: "sprites/UI/inventory-fullness-v3/inventory-fullness-09.png",
    inventoryFullness10: "sprites/UI/inventory-fullness-v3/inventory-fullness-10.png",
    inventoryKeycap: "sprites/UI/hud-cohesion-v1/inventory-keycap-v1.png",
    tutorialCurrentAction: "sprites/UI/hud-cohesion-v1/tutorial-current-action-v1.png",
  }),
  frames: Object.freeze({
    playerCoreShell: Object.freeze({ frame: "integrated-player", rect: Object.freeze([30, 94, 2015, 552]) }),
    levelUpShell: Object.freeze({ frame: "integrated-level-up", rect: Object.freeze([0, 135, 2172, 402]) }),
    xp: Object.freeze({ frame: "integrated-xp", rect: Object.freeze([25, 268, 2090, 215]) }),
  }),
  font: Object.freeze({
    family: UI_FONTS.display,
    color: "#f4e8c8",
    secondary: "#b9c8d3",
    cyan: "#65d8f2",
    gold: "#f0c765",
    shadow: "#02060a",
    strokeThickness: 2,
  }),
  layout: Object.freeze({
    layers: Object.freeze({
      shellOffset: 2,
      artOffset: 3,
      contentOffset: 4,
      interactionOffset: 5,
    }),
    playerCore: Object.freeze({ x: 12, y: 14, width: 336, height: 92 }),
    torchArtwork: Object.freeze({
      icon: "torch", x: 326, y: 61, size: 22, offTint: 0x687581,
    }),
    depth: Object.freeze({ x: 136, y: 32, width: 104, fontSize: 13 }),
    gemPower: Object.freeze({ x: 132, y: 77, width: 123, height: 14, radius: 2, labelX: 134, labelY: 76, fontSize: 11 }),
    torchIntensity: Object.freeze({
      hitX: 266, hitY: 26, hitWidth: 76, hitHeight: 72,
      titleX: 289, titleY: 38, titleFontSize: 8,
      textX: 289, textY: 62, fontSize: 17, textWidth: 36,
      statusY: 84, statusFontSize: 8,
      label: "TORCH", overdriveLabel: "BOOST", onLabel: "ON", offLabel: "OFF",
      restAlpha: 1, hoverAlpha: 1,
      tooltip: Object.freeze({
        width: 338, height: 118, gap: 8, viewportMargin: 8,
        titleY: -31, bodyY: 12, bodyWidth: 292,
        titleFontSize: 14, bodyFontSize: 12, lineSpacing: 5,
        depthOffset: 12, drainDecimals: 1,
        title: "TORCH {percent}%  |  {state}",
        wheelHint: "Scroll mouse wheel to adjust brightness.",
        stepsHint: "Up +{scroll}% / Down -{scroll}%  |  Click +{click}%",
        toggleHint: "[{key}] Toggle torch  |  {drain} GP/s while on",
      }),
    }),
    buffs: Object.freeze({
      x: 14,
      y: 161,
      width: 131,
      height: 30,
      gap: 6,
      maxVisible: 3,
      fontSize: 11,
      iconSize: 16,
      iconInsetX: 18,
      textCenterOffsetX: 8,
      textWidth: 86,
      textHeight: 18,
      hitHeight: 44,
      hitOffsetY: 4,
      restAlpha: 0.94,
      hoverAlpha: 1,
      tooltip: Object.freeze({
        width: 320,
        height: 92,
        gap: 8,
        viewportMargin: 6,
        titleY: -22,
        titleHeight: 18,
        bodyY: 12,
        bodyWidth: 274,
        bodyHeight: 44,
        titleFontSize: 14,
        bodyFontSize: 12,
      }),
    }),
    combo: Object.freeze({ y: 14, width: 221, height: 55, textY: 14, fontSize: 17, timerX: 12, timerY: 42, timerWidth: 197, timerHeight: 4 }),
    notification: Object.freeze({
      y: 360,
      width: 430,
      minHeight: 76,
      iconInset: 82,
      rightInset: 92,
      verticalPadding: 42,
      titleFontSize: 11,
      fontSize: 15,
      counterFontSize: 11,
      controlSize: 38,
      dismissSize: 30,
      titleTopInset: 14,
      counterBottomInset: 10,
      previousInsetX: 20,
      nextInsetX: 30,
      dismissInsetX: 17,
      dismissInsetY: 14,
      cycleOffsetY: 8,
      controlHitWidth: 52,
      controlHitHeight: 48,
      lineSpacing: 1,
    }),
    worldState: Object.freeze({
      right: 80,
      y: 14,
      width: 250,
      height: 42,
      sourceCrop: Object.freeze({ x: 192, y: 4, width: 554, height: 91 }),
      timeX: 12,
      dayX: 116,
      topY: 21,
      timeFontSize: 13,
      dayFontSize: 12,
    }),
    audio: Object.freeze({ right: 12, y: 14, width: 52, height: 38, gap: 4 }),
    xp: Object.freeze({ bottom: 13, width: 504, height: 52, barX: 120, barY: 21, barWidth: 234, barHeight: 12, levelX: 74, levelWidth: 38, xpRight: 60, xpWidth: 74, fontSize: 13 }),
  }),
});
