import {
  WORLD_VISUAL_PROP_ATLASES_V3,
  WORLD_VISUAL_SKY_PROP_ASSETS_V3,
  WORLD_VISUAL_SURFACE_PROP_ASSETS_V3,
} from "./generated/worldVisualPropLibraryV3/index.js";
import {
  WORLD_VISUAL_SURFACE_HERO_LANDMARK_ASSETS,
  resolveWorldVisualSurfaceHeroLandmarksEnabled,
} from "./worldVisualSurfaceHeroLandmarks.js";

const HEAVENBLOCKS_SKY_ALTAR_ASSET_ROOT =
  "sprites/environment/heavenblocks-sky-altars-v1";

const createGeneratedPropAssetMap = assets => Object.freeze(Object.fromEntries(
  assets.map(asset => [
    asset.id,
    Object.freeze({ key: asset.atlasKey, frame: asset.frame }),
  ]),
));

const SURFACE_PROP_ASSETS_V3 = createGeneratedPropAssetMap(
  WORLD_VISUAL_SURFACE_PROP_ASSETS_V3,
);
const SKY_PROP_ASSETS_V3 = createGeneratedPropAssetMap(
  WORLD_VISUAL_SKY_PROP_ASSETS_V3,
);

const createSkyAltarAsset = (familyId, stageId) => Object.freeze({
  key: `environment-sky-altar-${familyId}-${stageId}-v1`,
  path: `${HEAVENBLOCKS_SKY_ALTAR_ASSET_ROOT}/${familyId}-${stageId}-v1.png`,
});

const HEAVENBLOCKS_SKY_ALTAR_ASSETS = Object.freeze({
  cloudReef: Object.freeze([
    createSkyAltarAsset("cloud-reef", "stage-1-dormant"),
    createSkyAltarAsset("cloud-reef", "stage-2-attuning"),
    createSkyAltarAsset("cloud-reef", "stage-3-awakened"),
  ]),
  angelHeavenblock: Object.freeze([
    createSkyAltarAsset("angel-heavenblock", "stage-1-dormant"),
    createSkyAltarAsset("angel-heavenblock", "stage-2-attuning"),
    createSkyAltarAsset("angel-heavenblock", "stage-3-awakened"),
  ]),
  devilEclipse: Object.freeze([
    createSkyAltarAsset("devil-eclipse", "stage-1-dormant"),
    createSkyAltarAsset("devil-eclipse", "stage-2-attuning"),
    createSkyAltarAsset("devil-eclipse", "stage-3-awakened"),
  ]),
});

export const ASSET_KEYS = Object.freeze({
  branding: {
    logo: "brand-logo",
  },
  ui: {
    barHp:            "ui-bar-hp",
    barGp:            "ui-bar-gp",
    barFrameEmpty:    "ui-bar-frame-empty",
    hudBars:          "ui-hud-bars",
    panelLarge:       "ui-panel-large",
    panelOverlay:     "ui-panel-overlay",
    panelDeath:       "ui-panel-death",
    panelHudStat:     "ui-panel-hud-stat",
    popupLevelup:     "ui-popup-levelup",
    btnSelect:        "ui-btn-select",
    btnStates:        "ui-btn-states",
    btnCloseStates:   "ui-btn-close-states",
    btnMusicStates:   "ui-btn-music-states",
    btnSfxStates:     "ui-btn-sfx-states",
    cardShopStates:   "ui-card-shop-states",
    barXp:            "ui-bar-xp",
    resourceBar4slot: "ui-resource-bar-4slot",
    slotFrame:        "ui-slot-frame",
    iconsResources:   "ui-icons-resources",
    iconCoin:         "ui-icon-coin",
    iconPickaxe:      "ui-icon-pickaxe",
    pickaxeIcons: Object.freeze({
      bronzePickaxe: Object.freeze({
        key: "ui-pickaxe-bronze-v1",
        path: "sprites/UI/pickaxe-icons-v1/bronze-pickaxe-v1.png",
      }),
      ironPickaxe: Object.freeze({
        key: "ui-pickaxe-iron-v1",
        path: "sprites/UI/pickaxe-icons-v1/iron-pickaxe-v1.png",
      }),
      steelPickaxe: Object.freeze({
        key: "ui-pickaxe-steel-v1",
        path: "sprites/UI/pickaxe-icons-v1/steel-pickaxe-v1.png",
      }),
      mithrilPickaxe: Object.freeze({
        key: "ui-pickaxe-mithril-v1",
        path: "sprites/UI/pickaxe-icons-v1/mithril-pickaxe-v1.png",
      }),
      adamantPickaxe: Object.freeze({
        key: "ui-pickaxe-adamant-v1",
        path: "sprites/UI/pickaxe-icons-v1/adamant-pickaxe-v1.png",
      }),
      runePickaxe: Object.freeze({
        key: "ui-pickaxe-rune-v1",
        path: "sprites/UI/pickaxe-icons-v1/rune-pickaxe-v1.png",
      }),
      dragonPickaxe: Object.freeze({
        key: "ui-pickaxe-dragon-v1",
        path: "sprites/UI/pickaxe-icons-v1/dragon-pickaxe-v1.png",
      }),
    }),
    pickaxeHud: Object.freeze({
      bronzePickaxe: Object.freeze({
        key: "ui-pickaxe-hud-bronze-v1",
        path: "sprites/UI/pickaxe-hud-v1/bronze-pickaxe-hud-overlay-v1.png",
      }),
      ironPickaxe: Object.freeze({
        key: "ui-pickaxe-hud-iron-v1",
        path: "sprites/UI/pickaxe-hud-v1/iron-pickaxe-hud-overlay-v1.png",
      }),
      steelPickaxe: Object.freeze({
        key: "ui-pickaxe-hud-steel-v1",
        path: "sprites/UI/pickaxe-hud-v1/steel-pickaxe-hud-overlay-v1.png",
      }),
      mithrilPickaxe: Object.freeze({
        key: "ui-pickaxe-hud-mithril-v1",
        path: "sprites/UI/pickaxe-hud-v1/mithril-pickaxe-hud-overlay-v1.png",
      }),
      adamantPickaxe: Object.freeze({
        key: "ui-pickaxe-hud-adamant-v1",
        path: "sprites/UI/pickaxe-hud-v1/adamant-pickaxe-hud-overlay-v1.png",
      }),
      runePickaxe: Object.freeze({
        key: "ui-pickaxe-hud-rune-v1",
        path: "sprites/UI/pickaxe-hud-v1/rune-pickaxe-hud-overlay-v1.png",
      }),
      dragonPickaxe: Object.freeze({
        key: "ui-pickaxe-hud-dragon-v1",
        path: "sprites/UI/pickaxe-hud-v1/dragon-pickaxe-hud-overlay-v1.png",
      }),
    }),
    lootBag:          "ui-loot-inventory-bag",
    thunderStrikeChainFrame: "ui-thunderstrike-chain-frame-v1",
    thunderStrikeTargetGate: "ui-thunderstrike-target-gate-v2",
    thunderStrikeNeedle: "ui-thunderstrike-needle-v2",
    thunderStrikeIndicator: Object.freeze({
      milestoneDormant: "ui-thunderstrike-milestone-dormant-v3",
      milestoneChallenge: "ui-thunderstrike-milestone-challenge-v3",
      milestoneCompleted: "ui-thunderstrike-milestone-completed-v3",
      milestoneCheck: "ui-thunderstrike-milestone-check-v3",
      promptPlate: "ui-thunderstrike-prompt-plate-v3",
      stagePlate: "ui-thunderstrike-stage-plate-v3",
      badgePlate: "ui-thunderstrike-badge-plate-v3",
      glyphI: "ui-thunderstrike-glyph-i-v3",
      glyphV: "ui-thunderstrike-glyph-v-v3",
      glyphX: "ui-thunderstrike-glyph-x-v3",
    }),
    approvedHud: {
      playerCore: "ui-hud-approved-player-core",
      playerCoreTorchOff: "ui-hud-approved-player-core-torch-off",
      buffChip: "ui-hud-approved-buff-chip",
      combo: "ui-hud-approved-combo",
      notification: "ui-hud-approved-notification",
      worldState: "ui-hud-approved-world-state",
      audioMusic: "ui-hud-approved-audio-music",
      audioSfx: "ui-hud-approved-audio-sfx",
      xp: "ui-hud-approved-xp",
      inventory: "ui-hud-approved-inventory",
      inventoryKeycap: "ui-hud-approved-inventory-keycap-v1",
      tutorialCurrentAction: "ui-hud-approved-tutorial-current-action-v1",
    },
    notificationControls: Object.freeze({
      previous: Object.freeze({
        key: "ui-notification-previous-v1",
        path: "sprites/UI/notification-controls-v1/notification-previous-v1.png",
      }),
      next: Object.freeze({
        key: "ui-notification-next-v1",
        path: "sprites/UI/notification-controls-v1/notification-next-v1.png",
      }),
      clear: Object.freeze({
        key: "ui-notification-clear-v1",
        path: "sprites/UI/notification-controls-v1/notification-clear-v1.png",
      }),
    }),
    hardcore: {
      oathPanel: "ui-hardcore-oath-panel-v1",
      oathCrest: "ui-hardcore-oath-crest-v1",
      deathActionButton: "ui-hardcore-death-action-v1",
    },
    worldMapFrame: "ui-world-map-frame-foundation-v1",
    resources: {
      dirt: "ui-resource-dirt",
      stone: "ui-resource-stone",
      copper: "ui-resource-copper",
      darkDirt: "ui-resource-dark-dirt",
      bronze: "ui-resource-bronze",
      steel: "ui-resource-steel",
      iron: "ui-resource-iron",
      silver: "ui-resource-silver",
      gold: "ui-resource-gold",
      lavaDirt: "ui-resource-lava-dirt",
      obsidian: "ui-resource-obsidian",
      emberOre: "ui-resource-ember-ore",
      magmaCrystal: "ui-resource-magma-crystal",
    },
    lootPickups: {
      dirt: "loot-pickup-dirt",
      stone: "loot-pickup-stone",
      copper: "loot-pickup-copper",
      darkDirtNormal: "loot-pickup-dark-dirt-normal",
      darkDirtStrong: "loot-pickup-dark-dirt-strong",
      steel: "loot-pickup-steel",
      iron: "loot-pickup-iron",
      bronze: "loot-pickup-bronze",
      silver: "loot-pickup-silver",
      gold: "loot-pickup-gold",
      lavaDirt: "loot-pickup-lava-dirt",
      obsidian: "loot-pickup-obsidian",
      emberOre: "loot-pickup-ember-ore",
      magmaCrystal: "loot-pickup-magma-crystal",
    },
    heavenblocks: {
      ancientRelicToken: "heavenblocks-ancient-relic-token-v1",
      ancientRelicIcon: "heavenblocks-ancient-relic-icon-v1",
      aetherTurbine: "heavenblocks-aether-turbine-v1",
      haloRegulator: "heavenblocks-halo-regulator-v1",
      eclipseCrucible: "heavenblocks-eclipse-crucible-v1",
    },
    starlightTalentTree: {
      modalShell: "ui-starlight-modal-shell-v2",
      modalCrest: "ui-starlight-modal-crest-v2",
      modalClose: "ui-starlight-modal-close-v2",
      treePanel: "ui-starlight-tree-panel-v2",
      detailPanel: "ui-starlight-detail-panel-v2",
      enginePage: "ui-starlight-engine-page-v2",
      nodeQuickslash: "ui-starlight-node-quickslash-v2",
      nodeThunderstrike: "ui-starlight-node-thunderstrike-v2",
      nodeLocked: "ui-starlight-node-bobo-locked-v2",
      nodeSelected: "ui-starlight-node-selected-v2",
      boboLock: "ui-starlight-bobo-lock-v2",
      starHeartSocket: "ui-starlight-heart-socket-v2",
      connectorQuickslash: "ui-starlight-connector-quickslash-v2",
      connectorThunderstrike: "ui-starlight-connector-thunderstrike-v2",
      starHeart: "ui-starlight-star-heart-v2",
      waywardStar: "ui-starlight-wayward-star-v2",
      hollowSun: "ui-starlight-hollow-sun-v2",
      cometEngine: "ui-starlight-comet-engine-v2",
      ultrawideFoundation: "ui-starlight-ultrawide-foundation-v3",
      navigationPlaqueIdle: "ui-starlight-navigation-plaque-idle-v3",
      navigationPlaqueSelected: "ui-starlight-navigation-plaque-selected-v3",
      talentRibbonIdle: "ui-starlight-talent-ribbon-idle-v3",
      talentRibbonSelected: "ui-starlight-talent-ribbon-selected-v3",
      statusSeal: "ui-starlight-status-seal-v3",
      progressPlaque: "ui-starlight-progress-plaque-v3",
      carouselLeft: "ui-starlight-carousel-left-v3",
      carouselRight: "ui-starlight-carousel-right-v3",
      carouselStepIdle: "ui-starlight-carousel-step-idle-v3",
      carouselStepActive: "ui-starlight-carousel-step-active-v3",
    },
  },
  constellations: {
    signs: {
      dirt: "constellation-sign-dirt-shovel",
      stone: "constellation-sign-stone-mountain",
      copper: "constellation-sign-copper-anvil",
      darkDirtNormal: "constellation-sign-dark-dirt-cave",
      darkDirtStrong: "constellation-sign-hard-dirt-fortress",
      bronze: "constellation-sign-bronze-shield",
      steel: "constellation-sign-steel-sword",
      iron: "constellation-sign-iron-hammer",
      silver: "constellation-sign-silver-crescent",
      gold: "constellation-sign-gold-crown",
    },
  },
  celestialEngines: {
    starHeart: "celestial-star-heart-core-v1",
    waywardStar: "celestial-wayward-star-core-v1",
    hollowSun: "celestial-hollow-sun-core-v1",
    cometEngine: "celestial-comet-engine-core-v1",
  },
  onboarding: {
    openingFlightV2: {
      artifact: "opening-flight-v2-artifact",
      shaftMarker: "opening-flight-v2-shaft-marker",
      flightRing: "opening-flight-v2-flight-ring",
      ascentCache: "opening-flight-v2-ascent-cache",
      objectiveHudFrame: "opening-flight-v2-objective-hud-frame",
      paths: {
        artifact: "sprites/onboarding/opening-flight-v2/runtime/flight-artifact-v2.webp",
        shaftMarker: "sprites/onboarding/opening-flight-v2/runtime/shaft-marker-v2.webp",
        flightRing: "sprites/onboarding/opening-flight-v2/runtime/flight-ring-v2.webp",
        ascentCache: "sprites/onboarding/opening-flight-v2/runtime/first-ascent-cache-compact-v3.webp",
        objectiveHudFrame: "sprites/onboarding/opening-flight-v2/runtime/objective-hud-frame-v2.webp",
      },
    },
  },
  background: {
    world1: "bg-world-1",
    loading: "bg-loading",
    understarEnding: Object.freeze({
      key: "bg-understar-ending-v1",
      path: "sprites/backgrounds/understar-ending-v1/understar-ending-backdrop-v1.webp",
    }),
    secondWorldTown: "bg-second-world-town",
    startZoneScenic: "bg-start-zone-scenic-v1",
    startZoneGroundFacade: "bg-start-zone-ground-solid-v1",
    levelOneGroundFacade: {
      chunks: Object.freeze([
        "bg-level1-ground-facade-01-v2",
        "bg-level1-ground-facade-02-v2",
        "bg-level1-ground-facade-03-v2",
        "bg-level1-ground-facade-04-v2",
        "bg-level1-ground-facade-05-v2",
        "bg-level1-ground-facade-06-v2",
        "bg-level1-ground-facade-07-v2",
        "bg-level1-ground-facade-08-v2",
        "bg-level1-ground-facade-09-v2",
      ]),
      recognitionAtlas: "bg-level1-ground-recognition-atlas-v7",
    },
    skyIslands: {
      level1Platform: "v11-sky-island-level-1-platform",
      level1Portal: "v11-sky-island-level-1-portal",
      level2Platform: "v11-sky-island-level-2-platform",
      level2Portal: "v11-sky-island-level-2-portal",
    },
    // Town houses
    houseMoneyMonster: "bg-house-money-monster",
    housePlayerUpgrade: "bg-house-player-upgrade",
    // Random background database images
    dbImage1: "bg-db-f1frtjf1frtjf1fr",
    dbImage2: "bg-db-g6ozmlg6ozmlg6oz",
    dbImage3: "bg-db-i30bfci30bfci30b",
    dbImage4: "bg-db-kjwykkjwykkjwykk",
    dbImage5: "bg-db-rimx2primx2primx",
    dbImage6: "bg-db-wocn9hwocn9hwocn",
    // Static town layers are composited into a seamless runtime texture.
    townLoop: {
      aboveFloor: "bg-town-loop-above-floor",
      floor: "bg-town-loop-floor",
      runtime: "bg-town-loop-runtime",
    },
    // Seam-processed at runtime and repeated through five 200 m depth bands.
    undergroundLoops: [
      { source: "bg-underground-000-200-source", runtime: "bg-underground-000-200-runtime" },
      { source: "bg-underground-200-400-source", runtime: "bg-underground-200-400-runtime" },
      { source: "bg-underground-400-600-source", runtime: "bg-underground-400-600-runtime" },
      { source: "bg-underground-600-800-source", runtime: "bg-underground-600-800-runtime" },
      { source: "bg-underground-800-1000-source", runtime: "bg-underground-800-1000-runtime" },
    ],
    // Sky backgrounds (above ground)
    skyBackgrounds: {
      base: "bg-sky-v3-base",
      nebula: "bg-sky-v3-nebula",
      aurora: "bg-sky-v3-aurora",
      horizon: "bg-sky-v3-horizon",
      cloudsFar: "bg-sky-v3-clouds-far",
      cloudsNear: "bg-sky-v3-clouds-near",
      planet1: "bg-sky-v3-planet-1",
      planet2: "bg-sky-v3-planet-2",
    },
    // Town NPC houses (background-town directory)
    bgElements: {
      boboHouse: "bg-town-house-bobo",
      gearMerchantHouse: "bg-town-house-gear-merchant",
      gemMonsterHouse: "bg-town-house-gem-monster",
      moneyMonsterHouse: "bg-town-house-money-monster",
      playerUpgradeHouse: "bg-town-house-player-upgrade",
    },
  },
  npcs: {
    merchantSprites: {
      moneyMonster: "npc-v13-money-monster-baseline",
      magmaMoneyMonster: "npc-v13-magma-money-monster-baseline",
      playerUpgrades: "npc-v13-player-upgrades-baseline",
      gearMerchant: "npc-v13-gear-merchant-baseline",
      boboMerchant: "npc-v13-bobo-merchant-baseline",
      gemPowerMerchant: "npc-v13-gem-power-merchant-baseline",
    },
    merchantIdleVideos: {
      moneyMonster: "npc-v13-money-monster-idle-video",
      playerUpgrades: "npc-v13-player-upgrades-idle-video",
      gearMerchant: "npc-v13-gear-merchant-idle-video",
      boboMerchant: "npc-v13-bobo-merchant-idle-video",
      gemPowerMerchant: "npc-v13-gem-power-merchant-idle-video",
    },
    merchantActivities: {
      moneyMonster: {
        work: "npc-v13-money-monster-work",
        rare: "npc-v13-money-monster-rare",
        player: "npc-v13-money-monster-player",
        inspect: "npc-v13-money-monster-inspect",
        habit: "npc-v13-money-monster-habit",
        signature: "npc-v13-money-monster-signature",
        showcase: "npc-v13-money-monster-showcase",
      },
      magmaMoneyMonster: {
        work: "npc-v13-magma-money-monster-work",
        rare: "npc-v13-magma-money-monster-rare",
        player: "npc-v13-magma-money-monster-player",
        inspect: "npc-v13-magma-money-monster-inspect",
        habit: "npc-v13-magma-money-monster-habit",
        signature: "npc-v13-magma-money-monster-signature",
        showcase: "npc-v13-magma-money-monster-showcase",
      },
      playerUpgrades: {
        work: "npc-v13-player-upgrades-work",
        rare: "npc-v13-player-upgrades-rare",
        player: "npc-v13-player-upgrades-player",
        inspect: "npc-v13-player-upgrades-inspect",
        habit: "npc-v13-player-upgrades-habit",
        signature: "npc-v13-player-upgrades-signature",
        showcase: "npc-v13-player-upgrades-showcase",
      },
      gearMerchant: {
        work: "npc-v13-gear-merchant-work",
        rare: "npc-v13-gear-merchant-rare",
        player: "npc-v13-gear-merchant-player",
        inspect: "npc-v13-gear-merchant-inspect",
        habit: "npc-v13-gear-merchant-habit",
        signature: "npc-v13-gear-merchant-signature",
        showcase: "npc-v13-gear-merchant-showcase",
      },
      boboMerchant: {
        work: "npc-v13-bobo-merchant-work",
        rare: "npc-v13-bobo-merchant-rare",
        player: "npc-v13-bobo-merchant-player",
        inspect: "npc-v13-bobo-merchant-inspect",
        habit: "npc-v13-bobo-merchant-habit",
        signature: "npc-v13-bobo-merchant-signature",
        showcase: "npc-v13-bobo-merchant-showcase",
      },
      gemPowerMerchant: {
        work: "npc-v13-gem-power-merchant-work",
        rare: "npc-v13-gem-power-merchant-rare",
        player: "npc-v13-gem-power-merchant-player",
        inspect: "npc-v13-gem-power-merchant-inspect",
        habit: "npc-v13-gem-power-merchant-habit",
        signature: "npc-v13-gem-power-merchant-signature",
        showcase: "npc-v13-gem-power-merchant-showcase",
      },
    },
    boboIdleSheet: "npc-v3-bobo-idle-sheet",
    boboIdleFrames: [0,1,2,3,4,5,6,7],
    boboIdleAnim: "npc-v3-bobo-idle-anim",
  },
  vehicles: {
    arcCore: {
      legacy: "vehicle-arc-core-v1",
      pack: "arc-core-v3-piskel-pack",
      reviewStage: "arc-core-v3-stage-background",
    },
  },
  shadowMiner: {
    sheet: "npc-v3-shadow-miner-sheet",
    idleSheet: "npc-v3-shadow-miner-idle-sheet",
    idleFrame: 0,
    idleFrames: [0,1,2,3,4,5,6,7],
    idleAnim: "npc-v3-shadow-miner-idle-anim",
    digSidewaysFrame: 1,
    runFrame: 2,
    runAnim: "npc-v3-shadow-miner-run-anim",
  },
  player: {
    displaySizePx:    89,
    textureFilter:    "LINEAR",
    walkSheet:       "char-v5-walk-sheet",
    idleSheet:       "char-v5-idle-sheet",
    digSidewaysSheet: "char-v5-dig-sideways-sheet",
    digUpSheet:      "char-v5-dig-up-sheet",
    digUpSidewaysSheet: "char-v5-dig-up-sideways-sheet",
    flightSheet:     "char-v5-fly-climb-sheet",
    wallPushSheet:    "char-v8-wall-push-sheet",
    digDownSheet:     "char-v8-dig-down-sheet",
    duckSheet:        "char-v8-duck-downwards-sheet",
    leanAgainstWallSheet: "char-v8-leans-against-wall-sheet",
    fallingSheet:     "char-v8-falling-downward-sheet",
    walkRunSheet:     "char-v8-walk-run-sheet",
    combatIdleRecoverSheet: "char-v8-combat-idle-recover-sheet",
    combatIdleToNormalIdleSheet: "char-v8-combat-idle-to-normal-idle-sheet",
    quickslashSheet: "char-v8-quickslash-v2-sheet",
    teleportInSheet: "char-v8-teleport-in-sheet",
    thunderStrikeChargeSheet: "char-v8-thunder-charge-sheet",
    thunderStrikeStrikeSheet: "char-v8-thunder-strike-sheet",
    digUpLookFrame:  "char-v5-dig-up-look-frame",
    idleFrames:      Array.from({ length: 34 }, (_, index) => index),
    walkFrames:      Array.from({ length: 51 }, (_, index) => index),
    walkStartFrames: [0, 1, 2, 3],
    walkLoopFrames:  [...Array.from({ length: 47 }, (_, index) => index + 4), 0, 1, 2, 3],
    walkStopFrames:  [3, 2, 1, 0],
    digSidewaysFrames: Array.from({ length: 18 }, (_, index) => index),
    digUpFrames:     Array.from({ length: 9 }, (_, index) => index),
    digUpSidewaysFrames: Array.from({ length: 13 }, (_, index) => index),
    flightFrames:     Array.from({ length: 25 }, (_, index) => index),
    wallPushFrames:   [],
    digDownFrames:    Array.from({ length: 5 }, (_, index) => index),
    duckFrames:       Array.from({ length: 4 }, (_, index) => index),
    leanAgainstWallFrames: Array.from({ length: 4 }, (_, index) => index),
    fallingFrames:    Array.from({ length: 7 }, (_, index) => index),
    walkRunFrames:    [],
    combatIdleRecoverFrames: [],
    combatIdleToNormalIdleFrames: Array.from({ length: 46 }, (_, index) => index),
    thunderStrikeChargeFrames: [0],
    thunderStrikeStrikeFrames: [0],
    digSidewaysHitFrames: [
      [0, 1],
      [2, 3, 4, 5],
      [6, 7, 8],
      [9, 10, 11, 12, 13],
      [14, 15, 16, 17],
    ],
    digUpHitFrames: [
      [0, 1, 2],
      [3, 4, 5],
      [6, 7, 8],
    ],
    digUpSidewaysHitFrames: [
      [0, 1, 2],
      [3, 4],
      [5, 6],
      [7, 8],
      [9, 10],
      [11, 12],
    ],
    airborneFrames:  ["char-v2-airborne-1"],
    flyFrames:       Array.from({ length: 25 }, (_, index) => index),
    quickslashFrames: Array.from({ length: 39 }, (_, index) => index),
    teleportInFrames: Array.from({ length: 38 }, (_, index) => index),
    idleAnim:        "char-v5-idle-anim",
    walkAnim:        "char-v5-walk-loop-anim",
    walkStartAnim:   "char-v5-walk-start-anim",
    walkLoopAnim:    "char-v5-walk-loop-anim",
    walkStopAnim:    "char-v5-walk-stop-anim",
    airborneAnim:    "char-v2-airborne-anim",
    duckAnim:        "char-v2-duck-anim",
    digDownAnim:     "char-v2-dig-down-anim",
    digSidewaysAnim: "char-v5-dig-sideways-hit-1-anim",
    digUpAnim:       "char-v5-dig-up-hit-1-anim",
    digUpSidewaysAnim: "char-v5-dig-up-sideways-hit-1-anim",
    digUpLookAnim:   "char-v5-dig-up-look-anim",
    wallPushAnim:    "char-v8-wall-push-anim",
    leanAgainstWallAnim: "char-v8-leans-against-wall-anim",
    fallingAnim:     "char-v8-falling-downward-anim",
    walkRunAnim:     "char-v8-walk-run-anim",
    combatIdleRecoverAnim: "char-v8-combat-idle-recover-anim",
    combatIdleToNormalIdleAnim: "char-v8-combat-idle-to-normal-idle-anim",
    flyAnim:         "char-v5-fly-anim",
    digSidewaysHitAnims: Array.from({ length: 5 }, (_, index) => `char-v5-dig-sideways-hit-${index + 1}-anim`),
    digUpHitAnims: Array.from({ length: 3 }, (_, index) => `char-v5-dig-up-hit-${index + 1}-anim`),
    digUpSidewaysHitAnims: Array.from({ length: 6 }, (_, index) => `char-v5-dig-up-sideways-hit-${index + 1}-anim`),
    quickslashAnim:  "char-v2-quickslash-anim",
    teleportInAnim:  "char-v8-teleport-in-anim",
    thunderStrikeChargeAnim: "char-v2-thunder-strike-charge-anim",
    thunderStrikeStrikeAnim: "char-v2-thunder-strike-strike-anim",
    digAnims:        [
      "char-v2-dig-down-anim",
      ...Array.from({ length: 5 }, (_, index) => `char-v5-dig-sideways-hit-${index + 1}-anim`),
      ...Array.from({ length: 3 }, (_, index) => `char-v5-dig-up-hit-${index + 1}-anim`),
      ...Array.from({ length: 6 }, (_, index) => `char-v5-dig-up-sideways-hit-${index + 1}-anim`),
    ],
    walkAnims:       ["char-v5-walk-start-anim", "char-v5-walk-loop-anim", "char-v5-walk-stop-anim"],
    walkMovingAnims: ["char-v5-walk-start-anim", "char-v5-walk-loop-anim"],
    duckSourceFacesRight: false,
    quickslashSourceFacesRight: true,
    quickslashDisplaySizePx: 98,
    quickslashAnimationFps: 30,
    teleportInDisplaySizePx: 89,
    teleportInAnimationFps: 30,
    wallPushAnimationFps: 8,
    digDownAnimationFps: 12,
    duckAnimationFps: 8,
    leanAgainstWallAnimationFps: 8,
    fallingAnimationFps: 12,
    walkRunAnimationFps: 16,
    combatIdleRecoverAnimationFps: 8,
    combatIdleToNormalIdleAnimationFps: 14,
    thunderStrikeChargeAnimationFps: 6,
    thunderStrikeStrikeAnimationFps: 12,
    idleAnimationFps: 8,
    digSidewaysAnimationFps: 30,
    digUpAnimationFps: 30,
    flightAnimationFps: 14,
    walkAnimation: {
      baseSpeedPxPerSec: 200,
      baseFps: 14,
      minTimeScale: 0.75,
      maxTimeScale: 1.85,
      runSpeedRatioThreshold: 1.35,
    },
  },
  tiles: {
    dynamicSoil: {
      bases: Array.from({ length: 5 }, (_, band) =>
        Array.from({ length: 3 }, (_, variant) => `tile-soil-band-${band}-variant-${variant}`)
      ),
      deepBases: Array.from({ length: 4 }, (_, band) =>
        Array.from({ length: 6 }, (_, variant) => `tile-deep-soil-band-${band}-variant-${variant}`)
      ),
      cracks: Array.from({ length: 5 }, (_, stage) => `tile-soil-crack-stage-${stage + 1}`),
      hardness: {
        compact: "tile-soil-hardness-compact",
        strong: "tile-soil-hardness-strong",
      },
      rarity: {
        rich: "tile-soil-rarity-rich",
        packed: "tile-soil-rarity-packed",
        ancient: "tile-soil-rarity-ancient",
      },
      material: {
        damp: "tile-soil-material-damp",
        ash: "tile-soil-material-ash",
        rubble: "tile-soil-material-rubble",
      },
    },
    dirtHp1: "tile-dirt-hp1",
    dirtHp2: "tile-dirt-hp2",
    dirtHp3: "tile-dirt-hp3",
    dirtHp4: "tile-dirt-hp4",
    dirtHp5: "tile-dirt-hp5",
    stoneHp1: "tile-stone-hp1",
    stoneHp2: "tile-stone-hp2",
    stoneHp3: "tile-stone-hp3",
    stoneHp4: "tile-stone-hp4",
    stoneHp5: "tile-stone-hp5",
    copperHp1: "tile-copper-hp1",
    copperHp2: "tile-copper-hp2",
    copperHp3: "tile-copper-hp3",
    copperHp4: "tile-copper-hp4",
    copperHp5: "tile-copper-hp5",
    bedrock: "tile-bedrock",
    caveWall: "tile-approved-cave-wall",
    caveEdge: "tile-approved-cave-edge",
    caveCeiling: "tile-approved-cave-ceiling",
    caveCeilingChains: "tile-approved-cave-ceiling-chains",
    treasureStone: "tile-approved-treasure-stone",
    skyIslandTop: "tile-approved-sky-island-top",
    chestNormal: "tile-approved-chest-normal",
    chestRare: "tile-approved-chest-rare",
    ancientRelicCache: "tile-approved-ancient-relic-cache-v1",
    townExit: "tile-approved-town-exit",
    darkDirtNormal: "tile-dark-dirt-normal",
    darkDirtNormalHp1: "tile-dark-dirt-normal-hp1",
    darkDirtNormalHp2: "tile-dark-dirt-normal-hp2",
    darkDirtNormalHp3: "tile-dark-dirt-normal-hp3",
    darkDirtNormalHp4: "tile-dark-dirt-normal-hp4",
    darkDirtNormalHp5: "tile-dark-dirt-normal-hp5",
    darkDirtStrong: "tile-dark-dirt-strong",
    darkDirtStrongHp1: "tile-dark-dirt-strong-hp1",
    darkDirtStrongHp2: "tile-dark-dirt-strong-hp2",
    darkDirtStrongHp3: "tile-dark-dirt-strong-hp3",
    darkDirtStrongHp4: "tile-dark-dirt-strong-hp4",
    darkDirtStrongHp5: "tile-dark-dirt-strong-hp5",
    bronze: "tile-bronze",
    bronzeHp1: "tile-bronze-hp1",
    bronzeHp2: "tile-bronze-hp2",
    bronzeHp3: "tile-bronze-hp3",
    bronzeHp4: "tile-bronze-hp4",
    bronzeHp5: "tile-bronze-hp5",
    steel: "tile-steel",
    steelHp1: "tile-steel-hp1",
    steelHp2: "tile-steel-hp2",
    steelHp3: "tile-steel-hp3",
    steelHp4: "tile-steel-hp4",
    steelHp5: "tile-steel-hp5",
    iron: "tile-iron",
    ironHp1: "tile-iron-hp1",
    ironHp2: "tile-iron-hp2",
    ironHp3: "tile-iron-hp3",
    ironHp4: "tile-iron-hp4",
    ironHp5: "tile-iron-hp5",
    silver: "tile-silver",
    silverHp1: "tile-silver-hp1",
    silverHp2: "tile-silver-hp2",
    silverHp3: "tile-silver-hp3",
    silverHp4: "tile-silver-hp4",
    silverHp5: "tile-silver-hp5",
    gold: "tile-gold",
    goldHp1: "tile-gold-hp1",
    goldHp2: "tile-gold-hp2",
    goldHp3: "tile-gold-hp3",
    goldHp4: "tile-gold-hp4",
    goldHp5: "tile-gold-hp5",
    lavaDirt: "tile-lava-dirt",
    lavaDirtHp1: "tile-lava-dirt-hp1",
    lavaDirtHp2: "tile-lava-dirt-hp2",
    lavaDirtHp3: "tile-lava-dirt-hp3",
    lavaDirtHp4: "tile-lava-dirt-hp4",
    lavaDirtHp5: "tile-lava-dirt-hp5",
    obsidian: "tile-obsidian",
    obsidianHp1: "tile-obsidian-hp1",
    obsidianHp2: "tile-obsidian-hp2",
    obsidianHp3: "tile-obsidian-hp3",
    obsidianHp4: "tile-obsidian-hp4",
    obsidianHp5: "tile-obsidian-hp5",
    emberOre: "tile-ember-ore",
    emberOreHp1: "tile-ember-ore-hp1",
    emberOreHp2: "tile-ember-ore-hp2",
    emberOreHp3: "tile-ember-ore-hp3",
    emberOreHp4: "tile-ember-ore-hp4",
    emberOreHp5: "tile-ember-ore-hp5",
    magmaCrystal: "tile-magma-crystal",
    magmaCrystalHp1: "tile-magma-crystal-hp1",
    magmaCrystalHp2: "tile-magma-crystal-hp2",
    magmaCrystalHp3: "tile-magma-crystal-hp3",
    magmaCrystalHp4: "tile-magma-crystal-hp4",
    magmaCrystalHp5: "tile-magma-crystal-hp5",
    teleportTile: "tile-teleport",
    gambleTile: "tile-gamble",
    floorTown1: "tile-floor-town-1",
    floorTown2: "tile-floor-town-2",
    // Special Blocks
    gemPowerBlock: "gempower-block",
    gemPowerBlockTiers: Object.freeze({
      gp100: "gempower-block",
      gp250: "gempower-block-250",
      gp500: "gempower-block-500",
      gp1000: "gempower-block-1000",
      gp1700: "gempower-block-1700",
    }),
    speedBlock: "speed-block",
    xpBlock: "xp-block",
    sellBlock: "sell-block",
    critBlock: "crit-block",
    berserkBlock: "berserk-block",
    comboBlock: "combo-block",
    legendBlock: "crown-block",
    // Geode interior
    geodeInterior: "tile-geode-interior",
  },
  fx: {
    break1: "fx-break-1",
    break2: "fx-break-2",
  },
  environment: {
    heavenblocksSkyAltars: HEAVENBLOCKS_SKY_ALTAR_ASSETS,
    pillars: {
      milestoneStages: Object.freeze([
        "environment-milestone-pillar-stage-1-v1",
        "environment-milestone-pillar-stage-2-v1",
        "environment-milestone-pillar-stage-3-v1",
        "environment-milestone-pillar-stage-4-v1",
        "environment-milestone-pillar-stage-5-v1",
      ]),
      starStages: Object.freeze([
        "environment-star-pillar-stage-1-v1",
        "environment-star-pillar-stage-2-v1",
        "environment-star-pillar-stage-3-v1",
        "environment-star-pillar-stage-4-v1",
        "environment-star-pillar-stage-5-v1",
      ]),
    },
    graveborerWurm: {
      head: "graveborer-wurm-head-v1",
      body: "graveborer-wurm-body-v1",
      tail: "graveborer-wurm-tail-v1",
      medallion: "graveborer-wurm-medallion-v1",
      warning: "graveborer-wurm-warning-v1",
    },
    hardcoreMemorial: "environment-hardcore-memorial-v1",
    surfaceProps: {
      level1: {
        well: { key: "surface-prop-level1-well-v1", path: "sprites/environment/surface-props-v1/level1-well-v1.webp" },
        wagon: { key: "surface-prop-level1-wagon-v1", path: "sprites/environment/surface-props-v1/level1-wagon-v1.webp" },
        pergola: { key: "surface-prop-level1-pergola-v1", path: "sprites/environment/surface-props-v1/level1-pergola-v1.webp" },
        bench: { key: "surface-prop-level1-bench-v1", path: "sprites/environment/surface-props-v1/level1-bench-v1.webp" },
        handcart: { key: "surface-prop-level1-handcart-v1", path: "sprites/environment/surface-props-v1/level1-handcart-v1.webp" },
        supplies: { key: "surface-prop-level1-supplies-v1", path: "sprites/environment/surface-props-v1/level1-supplies-v1.webp" },
        fence: { key: "surface-prop-level1-fence-v1", path: "sprites/environment/surface-props-v1/level1-fence-v1.webp" },
        plants: { key: "surface-prop-level1-plants-v1", path: "sprites/environment/surface-props-v1/level1-plants-v1.webp" },
        lantern: { key: "surface-prop-level1-lantern-v1", path: "sprites/environment/surface-props-v1/level1-lantern-v1.webp" },
      },
      level2: {
        well: { key: "surface-prop-level2-well-v2", path: "sprites/environment/surface-props-v1/level2-well-v2.webp" },
        wagon: { key: "surface-prop-level2-wagon-v2", path: "sprites/environment/surface-props-v1/level2-wagon-v2.webp" },
        pergola: { key: "surface-prop-level2-pergola-v2", path: "sprites/environment/surface-props-v1/level2-pergola-v2.webp" },
        bench: { key: "surface-prop-level2-bench-v2", path: "sprites/environment/surface-props-v1/level2-bench-v2.webp" },
        handcart: { key: "surface-prop-level2-handcart-v2", path: "sprites/environment/surface-props-v1/level2-handcart-v2.webp" },
        supplies: { key: "surface-prop-level2-supplies-v2", path: "sprites/environment/surface-props-v1/level2-supplies-v2.webp" },
        fence: { key: "surface-prop-level2-fence-v2", path: "sprites/environment/surface-props-v1/level2-fence-v2.webp" },
        plants: { key: "surface-prop-level2-plants-v2", path: "sprites/environment/surface-props-v1/level2-plants-v2.webp" },
        lantern: { key: "surface-prop-level2-lantern-v2", path: "sprites/environment/surface-props-v1/level2-lantern-v2.webp" },
        forgeShelter: { key: "surface-prop-level2-forge-shelter-v2", path: "sprites/environment/surface-props-v2/level2-forge-shelter-v2.webp" },
        campKitchen: { key: "surface-prop-level2-camp-kitchen-v2", path: "sprites/environment/surface-props-v2/level2-camp-kitchen-v2.webp" },
        herbStation: { key: "surface-prop-level2-herb-station-v2", path: "sprites/environment/surface-props-v2/level2-herb-station-v2.webp" },
        timberGantry: { key: "surface-prop-level2-timber-gantry-v2", path: "sprites/environment/surface-props-v2/level2-timber-gantry-v2.webp" },
        observatory: { key: "surface-prop-level2-observatory-v2", path: "sprites/environment/surface-props-v2/level2-observatory-v2.webp" },
        surveyStation: { key: "surface-prop-level2-survey-station-v2", path: "sprites/environment/surface-props-v2/level2-survey-station-v2.webp" },
        expeditionShelter: { key: "surface-prop-level2-expedition-shelter-v2", path: "sprites/environment/surface-props-v2/level2-expedition-shelter-v2.webp" },
      },
    },
    surfaceHeroLandmarksV4: WORLD_VISUAL_SURFACE_HERO_LANDMARK_ASSETS,
    surfaceSkyPropAtlasesV3: WORLD_VISUAL_PROP_ATLASES_V3,
    surfacePropsV3: SURFACE_PROP_ASSETS_V3,
    skyPropsV3: SKY_PROP_ASSETS_V3,
    skylineWeatherVfx: {
      clouds: "weather-v11-clouds",
      atmosphere: "weather-v11-atmosphere",
      lightning: "weather-v11-lightning",
      particles: "weather-v11-particles-v2",
    },
  },
  runtime: {
    tilesheet: "tilesheet",
  },
  audio: {
    music: {
      track1: "music-track-1",
      track2: "music-track-2",
      track3: "music-track-3",
      playlist: ["music-track-1", "music-track-2", "music-track-3"],
      bootSeedKey: "",
    },
    sfx: {
      footstep: "sfx-footstep",
      footstep2: "sfx-footstep-2",
      footstep3: "sfx-footstep-3",
      footsteps: ["sfx-footstep", "sfx-footstep-2", "sfx-footstep-3"],
      dig: "sfx-dig",
      digStep: "sfx-dig-step", // louder dig step
      tileBreak: "sfx-tile-break",
      tileHit: "sfx-tile-hit",
      copperCollect: "sfx-copper-collect",
      reward: "sfx-reward",
      uiSelect: "sfx-ui-select",
      uiConfirm: "sfx-ui-confirm",
    },
    voiceLines: {
      line1: "voice-line-1",
      line2: "voice-line-2",
      line3: "voice-line-3",
      line4: "voice-line-4",
      line5: "voice-line-5",
      line6: "voice-line-6",
      line7: "voice-line-7",
      line8: "voice-line-8",
      line9: "voice-line-9",
      line10: "voice-line-10",
      line11: "voice-line-11",
      line12: "voice-line-12",
      line13: "voice-line-13",
      line14: "voice-line-14",
      line15: "voice-line-15",
      line16: "voice-line-16",
      line17: "voice-line-17",
      line18: "voice-line-18",
      all: ["voice-line-1", "voice-line-2", "voice-line-3", "voice-line-4", "voice-line-5", "voice-line-6", "voice-line-7", "voice-line-8", "voice-line-9", "voice-line-10", "voice-line-11", "voice-line-12", "voice-line-13", "voice-line-14", "voice-line-15", "voice-line-16", "voice-line-17", "voice-line-18"],
      // Populated dynamically from manifest.json — add/remove files there, no code changes needed
      playerRandomFiles: [],
    },
    runtime: {
      paths: {},
      streamingEnabled: true,
      bootQueuedKeys: [],
    },
  },
});

export function getSurfacePropPreloadAssets(
  assetKeys = ASSET_KEYS,
  levels = Object.keys(assetKeys.environment.surfaceProps),
) {
  return levels
    .flatMap(level => Object.values(assetKeys.environment.surfaceProps[level] || {}))
    .map(({ key, path }) => Object.freeze({ key, path }));
}

export function getSurfaceHeroLandmarkPreloadAssets(
  assetKeys = ASSET_KEYS,
  search = globalThis.location?.search || "",
) {
  const enabled = resolveWorldVisualSurfaceHeroLandmarksEnabled(undefined, search);
  return Object.entries(assetKeys.environment.surfaceHeroLandmarksV4)
    .filter(([assetId]) => enabled[assetId])
    .map(([, { key, path }]) => Object.freeze({ key, path }));
}

export function getSurfaceSkyPropAtlasPreloadAssets(assetKeys = ASSET_KEYS) {
  return assetKeys.environment.surfaceSkyPropAtlasesV3.map(
    ({ key, path, dataPath }) => Object.freeze({ key, path, dataPath }),
  );
}

export function getPickaxeIconPreloadAssets(assetKeys = ASSET_KEYS) {
  return Object.values(assetKeys.ui.pickaxeIcons)
    .map(({ key, path }) => Object.freeze({ key, path }));
}

export function getPickaxeHudPreloadAssets(assetKeys = ASSET_KEYS) {
  return Object.values(assetKeys.ui.pickaxeHud)
    .map(({ key, path }) => Object.freeze({ key, path }));
}

export function getHeavenblocksSkyAltarPreloadAssets(assetKeys = ASSET_KEYS) {
  return Object.values(assetKeys.environment.heavenblocksSkyAltars)
    .flatMap(stageAssets => stageAssets)
    .map(({ key, path }) => Object.freeze({ key, path }));
}
