export const ASSET_KEYS = Object.freeze({
  branding: {
    logo: "brand-logo",
  },
  ui: {
    barHp:            "ui-bar-hp",
    barGp:            "ui-bar-gp",
    barFrameEmpty:    "ui-bar-frame-empty",
    hudBars:          "ui-hud-bars",
    panelLarge:       "ui-panel-large",
    panelOverlay:     "ui-panel-overlay",
    panelDeath:       "ui-panel-death",
    panelHudStat:     "ui-panel-hud-stat",
    popupLevelup:     "ui-popup-levelup",
    btnSelect:        "ui-btn-select",
    btnStates:        "ui-btn-states",
    btnCloseStates:   "ui-btn-close-states",
    btnMusicStates:   "ui-btn-music-states",
    btnSfxStates:     "ui-btn-sfx-states",
    cardShopStates:   "ui-card-shop-states",
    barXp:            "ui-bar-xp",
    resourceBar4slot: "ui-resource-bar-4slot",
    slotFrame:        "ui-slot-frame",
    iconsResources:   "ui-icons-resources",
    iconCoin:         "ui-icon-coin",
    iconPickaxe:      "ui-icon-pickaxe",
    lootBag:          "ui-loot-inventory-bag",
    resources: {
      dirt: "ui-resource-dirt",
      stone: "ui-resource-stone",
      copper: "ui-resource-copper",
      darkDirt: "ui-resource-dark-dirt",
      bronze: "ui-resource-bronze",
      steel: "ui-resource-steel",
      iron: "ui-resource-iron",
      silver: "ui-resource-silver",
      gold: "ui-resource-gold",
    },
    lootPickups: {
      dirt: "loot-pickup-dirt",
      stone: "loot-pickup-stone",
      copper: "loot-pickup-copper",
      darkDirtNormal: "loot-pickup-dark-dirt-normal",
      darkDirtStrong: "loot-pickup-dark-dirt-strong",
      steel: "loot-pickup-steel",
      iron: "loot-pickup-iron",
      bronze: "loot-pickup-bronze",
      silver: "loot-pickup-silver",
      gold: "loot-pickup-gold",
    },
  },
  constellations: {
    signs: {
      dirt: "constellation-sign-dirt-shovel",
      stone: "constellation-sign-stone-mountain",
      copper: "constellation-sign-copper-anvil",
      darkDirtNormal: "constellation-sign-dark-dirt-cave",
      darkDirtStrong: "constellation-sign-hard-dirt-fortress",
      bronze: "constellation-sign-bronze-shield",
      steel: "constellation-sign-steel-sword",
      iron: "constellation-sign-iron-hammer",
      silver: "constellation-sign-silver-crescent",
      gold: "constellation-sign-gold-crown",
    },
  },
  background: {
    world1: "bg-world-1",
    loading: "bg-loading",
    // Town houses
    houseMoneyMonster: "bg-house-money-monster",
    housePlayerUpgrade: "bg-house-player-upgrade",
    // Random background database images
    dbImage1: "bg-db-f1frtjf1frtjf1fr",
    dbImage2: "bg-db-g6ozmlg6ozmlg6oz",
    dbImage3: "bg-db-i30bfci30bfci30b",
    dbImage4: "bg-db-kjwykkjwykkjwykk",
    dbImage5: "bg-db-rimx2primx2primx",
    dbImage6: "bg-db-wocn9hwocn9hwocn",
    // Static town layers are composited into a seamless runtime texture.
    townLoop: {
      aboveFloor: "bg-town-loop-above-floor",
      floor: "bg-town-loop-floor",
      runtime: "bg-town-loop-runtime",
    },
    // Seam-processed at runtime and repeated through five 200 m depth bands.
    undergroundLoops: [
      { source: "bg-underground-000-200-source", runtime: "bg-underground-000-200-runtime" },
      { source: "bg-underground-200-400-source", runtime: "bg-underground-200-400-runtime" },
      { source: "bg-underground-400-600-source", runtime: "bg-underground-400-600-runtime" },
      { source: "bg-underground-600-800-source", runtime: "bg-underground-600-800-runtime" },
      { source: "bg-underground-800-1000-source", runtime: "bg-underground-800-1000-runtime" },
    ],
    // Sky backgrounds (above ground)
    skyBackgrounds: {
      base: "bg-sky-v3-base",
      nebula: "bg-sky-v3-nebula",
      aurora: "bg-sky-v3-aurora",
      horizon: "bg-sky-v3-horizon",
      cloudsFar: "bg-sky-v3-clouds-far",
      cloudsNear: "bg-sky-v3-clouds-near",
      planet1: "bg-sky-v3-planet-1",
      planet2: "bg-sky-v3-planet-2",
    },
    // Town NPC houses (background-town directory)
    bgElements: {
      boboHouse: "bg-town-house-bobo",
      gearMerchantHouse: "bg-town-house-gear-merchant",
      gemMonsterHouse: "bg-town-house-gem-monster",
      moneyMonsterHouse: "bg-town-house-money-monster",
      playerUpgradeHouse: "bg-town-house-player-upgrade",
    },
  },
  npcs: {
    merchantSprites: {
      moneyMonster: "npc-v5-money-monster-single",
      playerUpgrades: "npc-v5-player-upgrades-single",
      gearMerchant: "npc-v5-gear-merchant-single",
      boboMerchant: "npc-v5-bobo-merchant-single",
      gemPowerMerchant: "npc-v5-gem-power-merchant-single",
    },
    boboIdleSheet: "npc-v3-bobo-idle-sheet",
    boboIdleFrames: [0,1,2,3,4,5,6,7],
    boboIdleAnim: "npc-v3-bobo-idle-anim",
  },
  shadowMiner: {
    sheet: "npc-v3-shadow-miner-sheet",
    idleSheet: "npc-v3-shadow-miner-idle-sheet",
    idleFrame: 0,
    idleFrames: [0,1,2,3,4,5,6,7],
    idleAnim: "npc-v3-shadow-miner-idle-anim",
    digSidewaysFrame: 1,
    runFrame: 2,
    runAnim: "npc-v3-shadow-miner-run-anim",
  },
  player: {
    displaySizePx:    89,
    walkSheet:       "char-v5-walk-sheet",
    idleSheet:       "char-v5-idle-sheet",
    digSidewaysSheet: "char-v5-dig-sideways-sheet",
    digUpSheet:      "char-v5-dig-up-sheet",
    digUpSidewaysSheet: "char-v5-dig-up-sideways-sheet",
    flyClimbSheet:   "char-v5-fly-climb-sheet",
    wallPushSheet:    "char-v8-wall-push-sheet",
    digDownSheet:     "char-v8-dig-down-sheet",
    duckSheet:        "char-v8-duck-downwards-sheet",
    leanAgainstWallSheet: "char-v8-leans-against-wall-sheet",
    fallingSheet:     "char-v8-falling-downward-sheet",
    walkRunSheet:     "char-v8-walk-run-sheet",
    combatIdleRecoverSheet: "char-v8-combat-idle-recover-sheet",
    combatIdleToNormalIdleSheet: "char-v8-combat-idle-to-normal-idle-sheet",
    quickslashSheet: "char-v8-quickslash-clean-sheet",
    thunderStrikeChargeSheet: "char-v8-thunder-charge-sheet",
    thunderStrikeStrikeSheet: "char-v8-thunder-strike-sheet",
    digUpLookFrame:  "char-v5-dig-up-look-frame",
    idleFrames:      Array.from({ length: 35 }, (_, index) => index),
    walkFrames:      Array.from({ length: 51 }, (_, index) => index),
    walkStartFrames: [0, 1, 2, 3],
    walkLoopFrames:  [...Array.from({ length: 47 }, (_, index) => index + 4), 0, 1, 2, 3],
    walkStopFrames:  [3, 2, 1, 0],
    digSidewaysFrames: Array.from({ length: 18 }, (_, index) => index),
    digUpFrames:     Array.from({ length: 9 }, (_, index) => index),
    digUpSidewaysFrames: Array.from({ length: 13 }, (_, index) => index),
    flyClimbFrames:  Array.from({ length: 25 }, (_, index) => index),
    wallPushFrames:   [],
    digDownFrames:    Array.from({ length: 5 }, (_, index) => index),
    duckFrames:       Array.from({ length: 4 }, (_, index) => index),
    leanAgainstWallFrames: Array.from({ length: 4 }, (_, index) => index),
    fallingFrames:    Array.from({ length: 7 }, (_, index) => index),
    walkRunFrames:    Array.from({ length: 2 }, (_, index) => index),
    combatIdleRecoverFrames: [],
    combatIdleToNormalIdleFrames: Array.from({ length: 47 }, (_, index) => index),
    thunderStrikeChargeFrames: [0],
    thunderStrikeStrikeFrames: [0],
    digSidewaysHitFrames: [
      [0, 1],
      [2, 3, 4, 5],
      [6, 7, 8],
      [9, 10, 11, 12, 13],
      [14, 15, 16, 17],
    ],
    digUpHitFrames: [
      [0, 1, 2],
      [3, 4, 5],
      [6, 7, 8],
    ],
    digUpSidewaysHitFrames: [
      [0, 1, 2],
      [3, 4],
      [5, 6],
      [7, 8],
      [9, 10],
      [11, 12],
    ],
    airborneFrames:  ["char-v2-airborne-1"],
    climbFrames:     Array.from({ length: 25 }, (_, index) => index),
    flyFrames:       Array.from({ length: 25 }, (_, index) => index),
    quickslashFrames: [0, 1],
    idleAnim:        "char-v5-idle-anim",
    walkAnim:        "char-v5-walk-loop-anim",
    walkStartAnim:   "char-v5-walk-start-anim",
    walkLoopAnim:    "char-v5-walk-loop-anim",
    walkStopAnim:    "char-v5-walk-stop-anim",
    airborneAnim:    "char-v2-airborne-anim",
    duckAnim:        "char-v2-duck-anim",
    digDownAnim:     "char-v2-dig-down-anim",
    digSidewaysAnim: "char-v5-dig-sideways-hit-1-anim",
    digUpAnim:       "char-v5-dig-up-hit-1-anim",
    digUpSidewaysAnim: "char-v5-dig-up-sideways-hit-1-anim",
    digUpLookAnim:   "char-v5-dig-up-look-anim",
    wallPushAnim:    "char-v8-wall-push-anim",
    leanAgainstWallAnim: "char-v8-leans-against-wall-anim",
    fallingAnim:     "char-v8-falling-downward-anim",
    walkRunAnim:     "char-v8-walk-run-anim",
    combatIdleRecoverAnim: "char-v8-combat-idle-recover-anim",
    combatIdleToNormalIdleAnim: "char-v8-combat-idle-to-normal-idle-anim",
    climbAnim:       "char-v5-climb-anim",
    flyAnim:         "char-v5-fly-anim",
    digSidewaysHitAnims: Array.from({ length: 5 }, (_, index) => `char-v5-dig-sideways-hit-${index + 1}-anim`),
    digUpHitAnims: Array.from({ length: 3 }, (_, index) => `char-v5-dig-up-hit-${index + 1}-anim`),
    digUpSidewaysHitAnims: Array.from({ length: 6 }, (_, index) => `char-v5-dig-up-sideways-hit-${index + 1}-anim`),
    quickslashAnim:  "char-v2-quickslash-anim",
    thunderStrikeChargeAnim: "char-v2-thunder-strike-charge-anim",
    thunderStrikeStrikeAnim: "char-v2-thunder-strike-strike-anim",
    digAnims:        [
      "char-v2-dig-down-anim",
      ...Array.from({ length: 5 }, (_, index) => `char-v5-dig-sideways-hit-${index + 1}-anim`),
      ...Array.from({ length: 3 }, (_, index) => `char-v5-dig-up-hit-${index + 1}-anim`),
      ...Array.from({ length: 6 }, (_, index) => `char-v5-dig-up-sideways-hit-${index + 1}-anim`),
    ],
    walkAnims:       ["char-v5-walk-start-anim", "char-v5-walk-loop-anim", "char-v5-walk-stop-anim"],
    walkMovingAnims: ["char-v5-walk-start-anim", "char-v5-walk-loop-anim"],
    wallPushAnimationFps: 8,
    digDownAnimationFps: 12,
    duckAnimationFps: 8,
    leanAgainstWallAnimationFps: 8,
    fallingAnimationFps: 12,
    walkRunAnimationFps: 16,
    combatIdleRecoverAnimationFps: 8,
    combatIdleToNormalIdleAnimationFps: 14,
    thunderStrikeChargeAnimationFps: 6,
    thunderStrikeStrikeAnimationFps: 12,
    idleAnimationFps: 8,
    digSidewaysAnimationFps: 30,
    digUpAnimationFps: 30,
    flyClimbAnimationFps: 14,
    walkAnimation: {
      baseSpeedPxPerSec: 200,
      baseFps: 14,
      minTimeScale: 0.75,
      maxTimeScale: 1.85,
      runSpeedRatioThreshold: 1.35,
    },
  },
  tiles: {
    dynamicSoil: {
      bases: Array.from({ length: 5 }, (_, band) =>
        Array.from({ length: 3 }, (_, variant) => `tile-soil-band-${band}-variant-${variant}`)
      ),
      cracks: Array.from({ length: 5 }, (_, stage) => `tile-soil-crack-stage-${stage + 1}`),
      hardness: {
        compact: "tile-soil-hardness-compact",
        strong: "tile-soil-hardness-strong",
      },
      rarity: {
        rich: "tile-soil-rarity-rich",
        packed: "tile-soil-rarity-packed",
        ancient: "tile-soil-rarity-ancient",
      },
      material: {
        damp: "tile-soil-material-damp",
        ash: "tile-soil-material-ash",
        rubble: "tile-soil-material-rubble",
      },
    },
    dirtHp1: "tile-dirt-hp1",
    dirtHp2: "tile-dirt-hp2",
    dirtHp3: "tile-dirt-hp3",
    dirtHp4: "tile-dirt-hp4",
    dirtHp5: "tile-dirt-hp5",
    stoneHp1: "tile-stone-hp1",
    stoneHp2: "tile-stone-hp2",
    stoneHp3: "tile-stone-hp3",
    stoneHp4: "tile-stone-hp4",
    stoneHp5: "tile-stone-hp5",
    copperHp1: "tile-copper-hp1",
    copperHp2: "tile-copper-hp2",
    copperHp3: "tile-copper-hp3",
    copperHp4: "tile-copper-hp4",
    copperHp5: "tile-copper-hp5",
    bedrock: "tile-bedrock",
    caveWall: "tile-approved-cave-wall",
    caveEdge: "tile-approved-cave-edge",
    caveCeiling: "tile-approved-cave-ceiling",
    caveCeilingChains: "tile-approved-cave-ceiling-chains",
    treasureStone: "tile-approved-treasure-stone",
    skyIslandTop: "tile-approved-sky-island-top",
    chestNormal: "tile-approved-chest-normal",
    chestRare: "tile-approved-chest-rare",
    townExit: "tile-approved-town-exit",
    darkDirtNormal: "tile-dark-dirt-normal",
    darkDirtNormalHp1: "tile-dark-dirt-normal-hp1",
    darkDirtNormalHp2: "tile-dark-dirt-normal-hp2",
    darkDirtNormalHp3: "tile-dark-dirt-normal-hp3",
    darkDirtNormalHp4: "tile-dark-dirt-normal-hp4",
    darkDirtNormalHp5: "tile-dark-dirt-normal-hp5",
    darkDirtStrong: "tile-dark-dirt-strong",
    darkDirtStrongHp1: "tile-dark-dirt-strong-hp1",
    darkDirtStrongHp2: "tile-dark-dirt-strong-hp2",
    darkDirtStrongHp3: "tile-dark-dirt-strong-hp3",
    darkDirtStrongHp4: "tile-dark-dirt-strong-hp4",
    darkDirtStrongHp5: "tile-dark-dirt-strong-hp5",
    bronze: "tile-bronze",
    bronzeHp1: "tile-bronze-hp1",
    bronzeHp2: "tile-bronze-hp2",
    bronzeHp3: "tile-bronze-hp3",
    bronzeHp4: "tile-bronze-hp4",
    bronzeHp5: "tile-bronze-hp5",
    steel: "tile-steel",
    steelHp1: "tile-steel-hp1",
    steelHp2: "tile-steel-hp2",
    steelHp3: "tile-steel-hp3",
    steelHp4: "tile-steel-hp4",
    steelHp5: "tile-steel-hp5",
    iron: "tile-iron",
    ironHp1: "tile-iron-hp1",
    ironHp2: "tile-iron-hp2",
    ironHp3: "tile-iron-hp3",
    ironHp4: "tile-iron-hp4",
    ironHp5: "tile-iron-hp5",
    silver: "tile-silver",
    silverHp1: "tile-silver-hp1",
    silverHp2: "tile-silver-hp2",
    silverHp3: "tile-silver-hp3",
    silverHp4: "tile-silver-hp4",
    silverHp5: "tile-silver-hp5",
    gold: "tile-gold",
    goldHp1: "tile-gold-hp1",
    goldHp2: "tile-gold-hp2",
    goldHp3: "tile-gold-hp3",
    goldHp4: "tile-gold-hp4",
    goldHp5: "tile-gold-hp5",
    teleportTile: "tile-teleport",
    gambleTile: "tile-gamble",
    floorTown1: "tile-floor-town-1",
    floorTown2: "tile-floor-town-2",
    // Special Blocks
    gemPowerBlock: "gempower-block",
    speedBlock: "speed-block",
    xpBlock: "xp-block",
    sellBlock: "sell-block",
    critBlock: "crit-block",
    berserkBlock: "berserk-block",
    comboBlock: "combo-block",
    legendBlock: "crown-block",
    // Root overlays
    rootOverlay: "overlay-roots",
    rootOverlayDeep: "overlay-roots-deep",
    // Geode interior
    geodeInterior: "tile-geode-interior",
  },
  fx: {
    break1: "fx-break-1",
    break2: "fx-break-2",
  },
  runtime: {
    tilesheet: "tilesheet",
  },
  audio: {
    music: {
      track1: "music-track-1",
      track2: "music-track-2",
      track3: "music-track-3",
      playlist: ["music-track-1", "music-track-2", "music-track-3"],
    },
    sfx: {
      footstep: "sfx-footstep",
      footstep2: "sfx-footstep-2",
      footstep3: "sfx-footstep-3",
      footsteps: ["sfx-footstep", "sfx-footstep-2", "sfx-footstep-3"],
      dig: "sfx-dig",
      digStep: "sfx-dig-step", // louder dig step
      tileBreak: "sfx-tile-break",
      tileHit: "sfx-tile-hit",
      copperCollect: "sfx-copper-collect",
      reward: "sfx-reward",
      uiSelect: "sfx-ui-select",
      uiConfirm: "sfx-ui-confirm",
    },
    voiceLines: {
      line1: "voice-line-1",
      line2: "voice-line-2",
      line3: "voice-line-3",
      line4: "voice-line-4",
      line5: "voice-line-5",
      line6: "voice-line-6",
      line7: "voice-line-7",
      line8: "voice-line-8",
      line9: "voice-line-9",
      line10: "voice-line-10",
      line11: "voice-line-11",
      line12: "voice-line-12",
      line13: "voice-line-13",
      line14: "voice-line-14",
      line15: "voice-line-15",
      line16: "voice-line-16",
      line17: "voice-line-17",
      line18: "voice-line-18",
      all: ["voice-line-1", "voice-line-2", "voice-line-3", "voice-line-4", "voice-line-5", "voice-line-6", "voice-line-7", "voice-line-8", "voice-line-9", "voice-line-10", "voice-line-11", "voice-line-12", "voice-line-13", "voice-line-14", "voice-line-15", "voice-line-16", "voice-line-17", "voice-line-18"],
      // Populated dynamically from manifest.json — add/remove files there, no code changes needed
      playerRandomFiles: [],
    },
  },
});
