export const CAVE_GAMEPLAY_CONFIG = Object.freeze({
  salts: Object.freeze({
    seamCandidate: 0x19a7c2d1,
    seamType: 0x2cb4e803,
    hazardChance: 0x3d91f5a7,
    hazardKind: 0x4e07b9c5,
    hazardPosition: 0x5f2ac781,
    hazardPhase: 0x6a48d3ef,
  }),
  resourceSeams: Object.freeze({
    enabled: true,
    source: "cave-resource-seam",
    minimumRadiusX: 2,
    minimumBlocks: 2,
    blocksPerRadiusTiles: 5,
    maximumBlocks: 7,
    largeCaveRadiusX: 12,
    largeCaveFormationCount: 2,
    entranceClearanceTiles: 2,
    clusterSearchTiles: 4,
    minimumFormationSeparationTiles: 5,
    preserveCenterTravelLane: true,
    archetypeBiasWeight: 4,
    depthPools: Object.freeze([
      Object.freeze({
        maxDepthExclusive: 80,
        entries: Object.freeze([
          Object.freeze({ tileTypeKey: "COPPER", weight: 5 }),
          Object.freeze({ tileTypeKey: "STONE", weight: 2 }),
        ]),
      }),
      Object.freeze({
        maxDepthExclusive: 180,
        entries: Object.freeze([
          Object.freeze({ tileTypeKey: "COPPER", weight: 5 }),
          Object.freeze({ tileTypeKey: "IRON", weight: 3 }),
          Object.freeze({ tileTypeKey: "STONE", weight: 1 }),
        ]),
      }),
      Object.freeze({
        maxDepthExclusive: 400,
        entries: Object.freeze([
          Object.freeze({ tileTypeKey: "IRON", weight: 5 }),
          Object.freeze({ tileTypeKey: "STEEL", weight: 3 }),
          Object.freeze({ tileTypeKey: "SILVER", weight: 2 }),
          Object.freeze({ tileTypeKey: "COPPER", weight: 1 }),
        ]),
      }),
      Object.freeze({
        maxDepthExclusive: 800,
        entries: Object.freeze([
          Object.freeze({ tileTypeKey: "STEEL", weight: 4 }),
          Object.freeze({ tileTypeKey: "BRONZE", weight: 4 }),
          Object.freeze({ tileTypeKey: "SILVER", weight: 2 }),
          Object.freeze({ tileTypeKey: "GOLD", weight: 1 }),
        ]),
      }),
      Object.freeze({
        maxDepthExclusive: 2000,
        entries: Object.freeze([
          Object.freeze({ tileTypeKey: "BRONZE", weight: 4 }),
          Object.freeze({ tileTypeKey: "STEEL", weight: 3 }),
          Object.freeze({ tileTypeKey: "SILVER", weight: 2 }),
          Object.freeze({ tileTypeKey: "GOLD", weight: 2 }),
          Object.freeze({ tileTypeKey: "EMBER_ORE", weight: 1 }),
        ]),
      }),
      Object.freeze({
        maxDepthExclusive: Number.POSITIVE_INFINITY,
        entries: Object.freeze([
          Object.freeze({ tileTypeKey: "OBSIDIAN", weight: 5 }),
          Object.freeze({ tileTypeKey: "EMBER_ORE", weight: 5 }),
          Object.freeze({ tileTypeKey: "MAGMA_CRYSTAL", weight: 2 }),
          Object.freeze({ tileTypeKey: "GOLD", weight: 1 }),
        ]),
      }),
    ]),
    archetypeBiases: Object.freeze({
      "echo-gallery": Object.freeze(["STONE", "COPPER", "IRON"]),
      "rootbound-hollow": Object.freeze(["COPPER", "IRON", "BRONZE"]),
      "prism-nursery": Object.freeze(["SILVER", "GOLD", "MAGMA_CRYSTAL"]),
      "storm-scar": Object.freeze(["IRON", "STEEL", "SILVER"]),
      "gilded-burrow": Object.freeze(["GOLD", "SILVER"]),
      "ember-fault": Object.freeze(["EMBER_ORE", "OBSIDIAN", "MAGMA_CRYSTAL"]),
    }),
  }),

  hazards: Object.freeze({
    enabled: true,
    source: "cave-hazard",
    minimumRadiusX: 4,
    featuredChallengesGuaranteed: true,
    baseChance: 0.25,
    depthChancePerThousandTiles: 0.05,
    maximumChance: 0.40,
    maximumPerCave: 2,
    secondHazardMinimumRadiusX: 14,
    secondHazardChance: 0.24,
    entranceClearanceTiles: 3,
    placementEdgeMarginTiles: 3,
    minimumHazardSpacingTiles: 5,
    checkpointSearchTiles: 6,
    minimumOpenHeightTiles: 1,
    tallHazardMinimumOpenHeightTiles: 2,
    spikeRunMinimumWidthTiles: 2,
    spikeRunMaximumWidthTiles: 3,
    renderRangeTiles: 52,
    updateIntervalMs: 30,
    collisionInsetPx: 3,
    failureCooldownMs: 1250,
    hazardLightRadiusTiles: 2.4,
    hazardLightAlpha: 0.86,
    warningSeparator: "  •  ",
    warningKeyPrefix: "cave-hazard-warning:",
    warningDurationMs: 3000,
    failureNotificationKey: "cave-hazard-failure",
    hit: Object.freeze({
      notification: "CAVE HAZARD  •  ALL GP LOST",
      recoveryStatus: "Recover on safe ground, then retry.",
      notificationDurationMs: 2800,
      statusDurationMs: 2200,
      statusColor: "#ff6677",
      emptyFloatingText: "GP EMPTY",
      floatingColor: "#ff3f6c",
      floatingDurationMs: 1600,
      floatingFontSize: 28,
      knockbackHorizontalPxPerSecond: 170,
      knockbackVerticalPxPerSecond: -120,
      shakeSignature: "misc.playerHit",
      shakeIntensityScale: 1.25,
      soundMethod: "playTileHit",
    }),
    render: Object.freeze({
      baseDepth: 18,
      glowDepth: 18.05,
      inactiveAlpha: 0.20,
      telegraphAlpha: 0.62,
      activeAlpha: 0.94,
      glowAlpha: 0.28,
      lineWidthTiles: 0.045,
      gateWidthTiles: 0.16,
      gateJitterTiles: 0.11,
      gateSegments: 9,
      gateActiveWidthScale: 1.4,
      gateTelegraphWidthScale: 0.75,
      gateGlowWidthScale: 2.8,
      nodeRadiusTiles: 0.11,
      sparkRadiusTiles: 0.035,
      sparkCount: 7,
      spikeHeightTiles: 0.34,
      spikeWidthTiles: 0.40,
      spikeTipGlowTiles: 0.035,
      spikeAlternatingAmplitude: 0.35,
      spikeAlternatingBase: 0.65,
      ventWidthTiles: 1.35,
      ventHeightTiles: 2.35,
      ventCeilingClearanceTiles: 0.12,
      ventCoreWidthRatio: 0.34,
      ventParticleCount: 8,
      ventTelegraphEllipseHeightRatio: 0.24,
      ventParticleSwayRatio: 0.34,
      floorMarkHeightTiles: 0.06,
      motionRadiansPerMs: 0.009,
      segmentPhaseStep: 1.37,
      telegraphPulseMin: 0.55,
      telegraphPulseMax: 0.92,
      activePulseMin: 0.82,
      activePulseMax: 1,
    }),
    timings: Object.freeze({
      "timed-gate": Object.freeze({
        periodMs: 2650,
        activeMs: 900,
        telegraphMs: 620,
        static: false,
      }),
      "spike-run": Object.freeze({
        periodMs: 1,
        activeMs: 1,
        telegraphMs: 0,
        static: true,
      }),
      "ember-vent": Object.freeze({
        periodMs: 2450,
        activeMs: 760,
        telegraphMs: 680,
        static: false,
      }),
    }),
    profiles: Object.freeze({
      "echo-gallery": Object.freeze({
        label: "Resonance Curtain",
        hint: "Cross between pulses. Contact empties all GP.",
        preferredKinds: Object.freeze(["timed-gate"]),
        color: 0x4a9ed4,
        glowColor: 0x9be8ff,
      }),
      "rootbound-hollow": Object.freeze({
        label: "Root Snare",
        hint: "Time the root snap—or fly over a tall snare.",
        preferredKinds: Object.freeze(["spike-run", "timed-gate"]),
        color: 0x58733e,
        glowColor: 0xbde889,
      }),
      "prism-nursery": Object.freeze({
        label: "Crystal Teeth",
        hint: "Use Flight above the teeth; a touch empties all GP.",
        preferredKinds: Object.freeze(["spike-run", "timed-gate"]),
        color: 0x7952c7,
        glowColor: 0x68edff,
      }),
      "storm-scar": Object.freeze({
        label: "Arc Curtain",
        hint: "Move through during the dark interval.",
        preferredKinds: Object.freeze(["timed-gate"]),
        color: 0x2f74da,
        glowColor: 0x8ff7ff,
      }),
      "gilded-burrow": Object.freeze({
        label: "Vault Ward",
        hint: "The ward drops briefly. Failure empties all GP.",
        preferredKinds: Object.freeze(["timed-gate"]),
        color: 0xa77a22,
        glowColor: 0xffe28a,
      }),
      "ember-fault": Object.freeze({
        label: "Ember Vent",
        hint: "Read the floor glow, then cross between eruptions.",
        preferredKinds: Object.freeze(["ember-vent", "timed-gate"]),
        color: 0xc63d23,
        glowColor: 0xffc15c,
      }),
    }),
  }),
});
