// Save-free encounter review fixtures. Production balance stays with each system.
export const DYNAMIC_EVENT_REVIEW = Object.freeze({
  sceneKey: "DynamicEventReview",
  viewport: Object.freeze({ width: 1280, height: 720, zoom: 0.65 }),
  seed: 7331,
  stepMs: 25,
  maxFrameMs: 100,
  maxStepsPerFrame: 40,
  refreshMs: 200,
  logLimit: 160,
  sequenceTimeoutMs: 90000,
  sequenceGapMs: 1800,
  sequence: Object.freeze(["shadow", "wurm", "earthquake", "shadow", "wurm", "earthquake"]),
  world: Object.freeze({
    tileSize: 94, topAirRows: 64, widthTiles: 72, depth: 300,
    centerTx: 36, airRows: 5, chamberHalfWidth: 16, depthPadding: 40,
    tileHp: 100, bodyWidth: 31, bodyHeight: 75, moveSpeed: 200,
    displaySize: 109, playerOriginY: 0.890625, backgroundAlpha: 0.7,
    terrainColor: 0x26292c, terrainEdgeColor: 0x59616b,
  }),
  trail: Object.freeze({ durationMs: 9000, distanceTiles: 7, intervalMs: 45 }),
  movement: Object.freeze({ patrolTiles: 6, patrolSpeedTilesPerSecond: 1.8 }),
  audio: Object.freeze({ volume: 0.16, minimumGapMs: 350 }),
  assets: Object.freeze({
    background: Object.freeze({ key: "event-lab-background",
      path: "sprites/backgrounds/world-visual-v2/depth/biome-variation-v2/weathered-roots-quiet-loam-pocket-v2.webp" }),
    idle: Object.freeze({ key: "event-lab-idle", frameWidth: 256, frameHeight: 256,
      path: "sprites/character/survival-character-unified-v1/runtime/2026-08-25-survival-blender-v2-idle-sheet.webp",
      frames: 48, fps: 30 }),
    walk: Object.freeze({ key: "event-lab-walk", frameWidth: 256, frameHeight: 256,
      path: "sprites/character/survival-character-unified-v1/runtime/2026-08-25-survival-mixamo-v1-walk-loop-sheet.webp",
      frames: 24, fps: 24 }),
  }),
  blockers: Object.freeze({
    depth: "Below minimum depth",
    chance: "Random roll did not pass",
    placement: "No visible replay trail at a safe distance",
    space: "Replay enters personal space",
    texture: "Replay texture unavailable",
  }),
});
