export const DYNAMIC_EVENT_HEALTH = Object.freeze({
  ids: Object.freeze(["shadow", "wurm", "earthquake", "signal"]),
  phaseMaximumMs: Object.freeze({
    shadow: Object.freeze({ spawning: 4000, approaching: 4000, observing: 20000, fleeing: 5000, vanishing: 5000 }),
    wurm: Object.freeze({ warning: 15000, burrowing: 20000 }),
    earthquake: Object.freeze({ warning: 15000, earthquake: 25000, aftermath: 60000 }),
  }),
  sampleIntervalMs: 150,
  stalledMs: 5000, maximumEncounterMs: 120000, requestTimeoutMs: 12000,
  retryMs: 750, historyLimit: 24, completeHoldMs: 4000,
  globalKey: "__jkdDynamicEvents", invariantCode: "dynamic-event-invariant",
  invariantMessage: "Dynamic encounter stopped progressing",
  names: Object.freeze({ signal: "SIGNAL", shadow: "SHADOWMINER", wurm: "GRAVEBORER WURM", earthquake: "EARTHQUAKE" }),
  actions: Object.freeze({
    shadow: "A miner works in the dark. Approach with light.",
    wurm: "Move off the marked tunnel now.",
    wurmWarning: "Leave the marked tunnel before the breach.",
    earthquake: "Leave marked ground. Solid cover stops rocks.",
  }),
  labels: Object.freeze({
    events: "EVENTS · F2", accepted: "REQUEST ACCEPTED", started: "STARTED", completed: "PASSED",
    waiting: "WAITING", blocked: "BLOCKED", fault: "FAULT", queued: "QUEUED",
    healthy: "All encounter controllers are responding",
    pending: "Walk to leave a visible trail · retrying",
    timeout: "No visible trail found before the request expired",
    busy: "Another encounter is still active",
    missing: "Controller missing", disabled: "Disabled",
    intro: "Hazard introduction locked", suppressed: "Seismic Suppression owned",
    depth: "Below minimum depth", hardcore: "Hardcore is not armed", flight: "Flight is locked",
    noise: "Waiting for mining noise", cooldown: "Cooldown", chance: "Waiting for the next random check",
    textures: "Encounter artwork unavailable", animation: "Mining animation unavailable",
    stalled: "Controller stopped updating", lifetime: "Encounter did not finish",
    cancelled: "Cancelled by developer", left: "LEFT", right: "RIGHT", near: "NEARBY",
    size: "Size", difficulty: "Behaviour", cancel: "Cancel encounter", lab: "Open sandbox",
    signalLab: "Signal practice", signalLabPath: "/testing/signal-event-sandbox/index.html",
    signalProfiles: Object.freeze(["random", "ivo", "bram", "oren", "mia", "explosive"]),
    trigger: "Trigger", labPath: "/testing/dynamic-event-sandbox/index.html",
  }),
  results: Object.freeze({
    shadow: Object.freeze({ title: "SHADOWMINER VANISHED", empty: "It left the terrain unchanged.",
      one: "1 block mined nearby.", many: "{blocks} blocks mined nearby." }),
    wurm: Object.freeze({ title: "WURM RETREATED", detail: "{passes} passes completed",
      brood: " · {brood} smaller Wurms", interruptedTitle: "WURM LEFT", interrupted: "The encounter ended early." }),
    earthquake: Object.freeze({ title: "EARTHQUAKE SETTLED", empty: "No rocks fell nearby.",
      one: "1 rock fell", many: "{rocks} rocks fell", hits: " · {hits} hits" }),
  }),
  phaseLabels: Object.freeze({ spawning: "APPEARING", approaching: "NEARBY", observing: "MINING",
    fleeing: "RETREATING", vanishing: "FADING", warning: "INCOMING", burrowing: "BURROWING" }),
  notice: Object.freeze({
    // Only the short earthquake completion cue is player-facing. Encounter
    // controls and the other events keep their information in-world.
    visibleEventIds: Object.freeze(["earthquake"]),
    width: 340, height: 64, top: 88, gap: 76, depth: 3490,
    iconX: -135, iconSize: 40, textX: -94, titleY: -14, detailY: 8,
    titleSize: "14px", detailSize: "12px", textWidth: 220, titleHeight: 18, detailHeight: 22, inset: 12,
  }),
  dev: Object.freeze({
    key: "F2", width: 500, height: 395, x: 270, bottom: 445, depth: 5000,
    buttonWidth: 190, buttonHeight: 34, buttonTextWidth: 162, buttonTextHeight: 20, launcherBottom: 220,
    rowStart: -110, rowGap: 50, textSize: "12px", headerSize: "14px", headingWidth: 440, headingHeight: 40,
    rowStatusX: -25, rowButtonX: -135, statusWidth: 245, statusHeight: 42,
    signalSelectY: 83, selectX: 105, selectY: 124, footerY: 168, launcherX: 115,
    intensities: Object.freeze(["minor", "medium", "major", "cataclysmic"]),
  }),
});
