const REVIEW_BASE = "testing/animation-sandbox/earthquake-dodge-world-v1";

export const EARTHQUAKE_DODGE_REVIEW = Object.freeze({
  sceneKey: "EarthquakeDodgeWorldReview",
  queryKey: "shot",
  defaultShot: "warning",
  interactiveShot: "play",
  viewport: Object.freeze({
    width: 1280,
    height: 720,
    backgroundColor: "#080b0c",
  }),
  world: Object.freeze({
    tileSize: 94,
    floorY: 610,
    ceilingY: 156,
    targetX: 792,
    playerStartX: 792,
    safePlayerX: 615,
    flightY: 440,
    backgroundAlpha: 0.88,
    backgroundTint: 0xb6aa91,
  }),
  player: Object.freeze({
    frameWidth: 256,
    frameHeight: 256,
    frameCount: 48,
    frameRate: 30,
    displaySize: 109,
    bodyWidth: 31,
    bodyHeight: 75,
    moveSpeed: 200,
    flightSpeed: 170,
    safeMargin: 4,
  }),
  hazard: Object.freeze({
    warningMs: 1800,
    fallMs: 850,
    impactMs: 900,
    resetMs: 650,
    rockWidthTiles: 0.62,
    landingFootprintWidth: 210,
    landingFootprintHeight: 132,
    ceilingFractureWidth: 238,
    ceilingFractureHeight: 148,
    fallingBoulderWidth: 112,
    fallingBoulderHeight: 112,
    impactDebrisWidth: 264,
    impactDebrisHeight: 214,
    footprintMinAlpha: 0.42,
    footprintMaxAlpha: 0.94,
    seamMinAlpha: 0.54,
    seamMaxAlpha: 1,
    warningPulseMs: 520,
    rockRotation: 0.28,
    impactHoldRatio: 0.64,
  }),
  layers: Object.freeze({
    background: 0,
    landingFootprint: 18,
    ceilingFracture: 19,
    player: 20,
    fallingBoulder: 22,
    impactCore: 23,
    foregroundDebris: 25,
    hud: 3500,
  }),
  hud: Object.freeze({
    x: 640,
    y: 78,
    frameWidth: 292,
    frameHeight: 55,
    medallionX: 524,
    medallionSize: 47,
    textX: 564,
    titleY: 64,
    detailY: 84,
    titleFont: "700 13px Arial",
    detailFont: "600 10px Arial",
    titleColor: "#f4dfbd",
    detailColor: "#b9c5c5",
    shotLabelX: 24,
    shotLabelY: 682,
    shotLabelFont: "600 11px Arial",
    shotLabelColor: "#c8d0cb",
  }),
  controls: Object.freeze({
    left: "A",
    right: "D",
    flight: "SHIFT + W/S",
  }),
  shots: Object.freeze({
    warning: Object.freeze({
      phase: "warning",
      title: "CAVE-IN",
      detail: "MOVE OUT OF THE LIT FOOTPRINT",
      playerX: 792,
      playerY: 610,
      footprintAlpha: 0.88,
      seamAlpha: 1,
      rockProgress: 0,
      impactAlpha: 0,
    }),
    dodge: Object.freeze({
      phase: "falling",
      title: "ROCK FALLING",
      detail: "DODGE LATERALLY OR USE FLIGHT",
      playerX: 615,
      playerY: 610,
      footprintAlpha: 0.96,
      seamAlpha: 0.72,
      rockProgress: 0.56,
      impactAlpha: 0,
    }),
    impact: Object.freeze({
      phase: "impact",
      title: "CLEAR",
      detail: "IMPACT MISSED — ROUTE MAY CHANGE",
      playerX: 615,
      playerY: 610,
      footprintAlpha: 0.24,
      seamAlpha: 0.18,
      rockProgress: 1,
      impactAlpha: 1,
    }),
    hit: Object.freeze({
      phase: "hit",
      title: "DIRECT HIT",
      detail: "CURRENT BUILD DRAINS ALL GEM POWER",
      playerX: 792,
      playerY: 610,
      footprintAlpha: 0.2,
      seamAlpha: 0.18,
      rockProgress: 1,
      impactAlpha: 1,
    }),
  }),
  assets: Object.freeze({
    background: Object.freeze({
      key: "quake-review-background",
      path: "sprites/backgrounds/world-visual-v2/depth/biome-variation-v2/weathered-roots-quiet-loam-pocket-v2.webp",
    }),
    playerIdle: Object.freeze({
      key: "quake-review-player-idle",
      path: "sprites/character/survival-character-blender-v2/runtime/survival-character-blender-v2-idle-sheet.png",
    }),
    statusFrame: Object.freeze({
      key: "quake-review-status-frame",
      path: "sprites/UI/earthquake-feedback-v2/seismic-status-frame-v2.png",
    }),
    medallion: Object.freeze({
      key: "quake-review-medallion",
      path: "sprites/UI/earthquake-feedback-v2/seismic-medallion-v2.png",
    }),
    landingFootprint: Object.freeze({
      key: "quake-review-landing-footprint",
      path: `${REVIEW_BASE}/earthquake-landing-footprint-v1.png`,
    }),
    fallingBoulder: Object.freeze({
      key: "quake-review-falling-boulder",
      path: `${REVIEW_BASE}/earthquake-falling-boulder-v1.png`,
    }),
    ceilingFracture: Object.freeze({
      key: "quake-review-ceiling-fracture",
      path: `${REVIEW_BASE}/earthquake-ceiling-fracture-v1.png`,
    }),
    impactDebris: Object.freeze({
      key: "quake-review-impact-debris",
      path: `${REVIEW_BASE}/earthquake-impact-debris-v1.png`,
    }),
  }),
});

export function getEarthquakeDodgeReviewAssets(
  config = EARTHQUAKE_DODGE_REVIEW,
) {
  return Object.values(config.assets);
}
