const ASSET_BASE = "sprites/UI/earthquake-feedback-v2";

export const EARTHQUAKE_FEEDBACK_CONFIG = Object.freeze({
  enabled: true,
  hudDepth: 3500,
  worldDepth: 58,
  notificationActiveBaseY: 154,
  assets: Object.freeze({
    statusFrame: Object.freeze({
      key: "ui-earthquake-status-frame-v2",
      path: `${ASSET_BASE}/seismic-status-frame-v2.png`,
    }),
    medallion: Object.freeze({
      key: "ui-earthquake-medallion-v2",
      path: `${ASSET_BASE}/seismic-medallion-v2.png`,
    }),
    tileFracture: Object.freeze({
      key: "fx-earthquake-tile-fracture-v1",
      path: `${ASSET_BASE}/seismic-tile-fracture-v1.png`,
    }),
    tileCollapse: Object.freeze({
      key: "fx-earthquake-tile-collapse-v1",
      path: `${ASSET_BASE}/seismic-tile-collapse-v1.png`,
    }),
    rubbleReturn: Object.freeze({
      key: "fx-earthquake-rubble-return-v1",
      path: `${ASSET_BASE}/seismic-rubble-return-v1.png`,
    }),
    landingFootprint: Object.freeze({
      key: "fx-earthquake-landing-footprint-v1",
      path: `${ASSET_BASE}/seismic-landing-footprint-v1.png`,
    }),
    fallingBoulder: Object.freeze({
      key: "fx-earthquake-falling-boulder-v1",
      path: `${ASSET_BASE}/seismic-falling-boulder-v1.png`,
    }),
    ceilingFracture: Object.freeze({
      key: "fx-earthquake-ceiling-fracture-v1",
      path: `${ASSET_BASE}/seismic-ceiling-fracture-v1.png`,
    }),
    impactDebris: Object.freeze({
      key: "fx-earthquake-impact-debris-v1",
      path: `${ASSET_BASE}/seismic-impact-debris-v1.png`,
    }),
  }),
  timing: Object.freeze({
    enterMs: 130,
    exitMs: 180,
    hideFailsafePaddingMs: 140,
    phaseVisibleMs: Object.freeze({
      warning: 2400,
      earthquake: 2600,
      aftermath: 1400,
    }),
    escapeVisibleMs: 3400,
    iconPulsePeriodMs: 650,
  }),
  card: Object.freeze({
    width: 320,
    height: 60,
    topY: 112,
    bottomMargin: 84,
    enterOffsetY: -7,
    exitOffsetY: -5,
    iconX: -126,
    iconSize: 52,
    iconPulseScale: 0.012,
    textX: -92,
    titleY: -10,
    detailY: 10,
    titleFontSize: "13px",
    detailFontSize: "10px",
    textWidth: 220,
  }),
  tileFx: Object.freeze({
    depth: 23,
    poolSize: 20,
    cameraPaddingTiles: 1.25,
    dedupeMs: 90,
    rotationRadians: Object.freeze([-0.08, 0, 0.08]),
    variants: Object.freeze({
      fracture: Object.freeze({
        asset: "tileFracture",
        displayTiles: 1.42,
        startScale: 0.34,
        peakScale: 1,
        endScale: 1.12,
        enterMs: 110,
        holdMs: 170,
        exitMs: 500,
        alpha: 0.94,
        driftYTiles: -0.04,
      }),
      collapse: Object.freeze({
        asset: "tileCollapse",
        displayTiles: 1.86,
        startScale: 0.24,
        peakScale: 1,
        endScale: 1.18,
        enterMs: 120,
        holdMs: 150,
        exitMs: 600,
        alpha: 1,
        driftYTiles: 0.03,
      }),
      restore: Object.freeze({
        asset: "rubbleReturn",
        displayTiles: 1.56,
        startScale: 0.48,
        peakScale: 0.98,
        endScale: 0.88,
        enterMs: 140,
        holdMs: 130,
        exitMs: 610,
        alpha: 0.88,
        driftYTiles: 0.06,
      }),
    }),
  }),
  hazards: Object.freeze({
    maxFallZones: 24,
    maxImpactFx: 10,
    landingFootprintDepth: 18,
    ceilingFractureDepth: 19,
    fallingBoulderDepth: 22,
    impactDebrisDepth: 25,
    footprintWidthTiles: 2.42,
    footprintHeightTiles: 1.12,
    footprintOriginY: 0.68,
    footprintMinAlpha: 0.68,
    footprintMaxAlpha: 1,
    footprintMinScale: 0.94,
    footprintPulseMs: 460,
    fractureWidthTiles: 2.2,
    fractureHeightTiles: 1.28,
    fractureOriginY: 0.38,
    fractureMinAlpha: 0.72,
    fractureMaxAlpha: 1,
    boulderWidthTiles: 1.5,
    boulderHeightTiles: 1.5,
    boulderOriginY: 0.92,
    boulderMinAlpha: 0.96,
    settledBoulderDepth: 24,
    impactRockScale: 1.02,
    impactRockSquashX: 1.12,
    impactRockSquashY: 0.78,
    impactRockEmbedTiles: 0.04,
    impactRockSettleRotation: 0.07,
    impactRockSquashMs: 90,
    impactWidthTiles: 2.8,
    impactHeightTiles: 1.9,
    impactOriginY: 0.76,
    impactStartScale: 0.72,
    impactPeakScale: 1,
    impactEnterMs: 150,
    impactHoldMs: 170,
    impactExitMs: 560,
    impactDriftTiles: -0.05,
    restoredOutlineMs: 4800,
    openedPassageHighlightMs: 6000,
    edgeInset: 24,
    edgeWidth: 146,
    edgeHeight: 46,
    edgeIconSize: 42,
    edgeIconX: -46,
    edgeTextX: -19,
    edgeFontSize: "12px",
    edgeTextStroke: "#06090c",
    edgeTextStrokeWidth: 3,
    viewportMargin: 30,
  }),
  colors: Object.freeze({
    warning: 0xe6a24d,
    danger: 0xef6a4a,
    gold: 0xd8b45f,
    cyan: 0x65d8f2,
    calm: 0x8cb8c2,
  }),
  labels: Object.freeze({
    warningTitle: "TREMOR",
    quakeTitle: "QUAKE",
    aftermathTitle: "SETTLING",
    escapeTitle: "BLOCKED",
    aftershockWatch: "AFTERSHOCK",
    escapeAction: "DIG RUBBLE",
    safePortal: "PORTAL",
    caveIn: "CAVE-IN",
    aftershock: "AFTERSHOCK",
    danger: "CAVE-IN",
    intensity: Object.freeze({
      minor: "MINOR",
      medium: "MEDIUM",
      major: "MAJOR",
      cataclysmic: "CATACLYSMIC",
    }),
  }),
});

export function getEarthquakeFeedbackPreloadAssets(
  config = EARTHQUAKE_FEEDBACK_CONFIG,
) {
  return Object.values(config.assets).map(({ key, path }) => ({ key, path }));
}
