export const EARTHQUAKE_FEEDBACK_CONFIG = Object.freeze({
  enabled: true,
  hudDepth: 3500,
  worldDepth: 58,
  notificationActiveBaseY: 116,
  top: Object.freeze({
    marginY: 12,
    maxWidth: 720,
    sideMargin: 280,
    minWidth: 420,
    height: 88,
    cornerRadius: 7,
    borderWidth: 2,
    titleY: 12,
    titleFontSize: "22px",
    subtitleY: 40,
    subtitleFontSize: "15px",
    phaseY: 62,
    phaseFontSize: "12px",
    progressY: 82,
    progressHeight: 4,
  }),
  objective: Object.freeze({
    sideMargin: 32,
    maxWidth: 660,
    normalHeight: 50,
    escapeWidth: 540,
    escapeHeight: 116,
    bottomMargin: 26,
    cornerRadius: 7,
    actionFontSize: "18px",
    escapeTitleFontSize: "18px",
    escapeActionFontSize: "30px",
    escapeDetailFontSize: "14px",
  }),
  hazards: Object.freeze({
    maxMarkers: 2,
    maxRockLanes: 2,
    markerRadius: 30,
    markerOffsetY: 46,
    markerFontSize: "14px",
    markerStrokeWidth: 3,
    rockLaneWidthTiles: 1.1,
    rockLaneAlpha: 0.12,
    rockLaneBorderAlpha: 0.9,
    restoredOutlineMs: 6000,
    restoredOutlineWidth: 3,
    openedPassageHighlightMs: 9000,
    openedPassageOutlineWidth: 4,
    edgeInset: 24,
    edgePillWidth: 126,
    edgePillHeight: 36,
    edgeFontSize: "14px",
    viewportMargin: 30,
  }),
  colors: Object.freeze({
    panelAlpha: 0.94,
    panelBorderAlpha: 0.96,
    warning: 0xe07030,
    danger: 0xff5638,
    gold: 0xd6a84a,
    cyan: 0x70b9c4,
    purple: 0xaa66ff,
    inactive: 0x4a4033,
  }),
  labels: Object.freeze({
    warningTitle: "SEISMIC WARNING",
    quakeTitle: "EARTHQUAKE",
    aftermathTitle: "AFTERMATH",
    collapsedTitle: "TUNNEL COLLAPSED",
    warningPhase: "WARNING  →  QUAKE  →  ESCAPE",
    quakePhase: "WARNING ✓  →  QUAKE  →  AFTERMATH",
    aftermathPhase: "WARNING ✓  →  QUAKE ✓  →  AFTERMATH",
    escapePhase: "WARNING ✓  →  QUAKE ✓  →  ESCAPE ROUTE",
    warningAction: "MOVE CLEAR OF CRACKING CEILINGS",
    quakeAction: "KEEP MOVING • DIG SIDEWAYS TO ESCAPE",
    aftermathAction: "WATCH FOR AFTERSHOCKS",
    escapeTitle: "YOU'RE STUCK!",
    escapeAction: "DIG DOWN ↓",
    escapeDetail: "Find a Teleport Gate to get back up",
    caveIn: "CAVE-IN",
    aftershock: "AFTERSHOCK",
    danger: "DANGER",
    impactIn: "IMPACT IN",
    remaining: "REMAINING",
    aftershockPossible: "AFTERSHOCK POSSIBLE",
    groundSettling: "GROUND SETTLING",
    escapeRoute: "ESCAPE ROUTE",
    intensity: Object.freeze({
      minor: "MINOR",
      medium: "MEDIUM",
      major: "MAJOR",
      cataclysmic: "CATACLYSMIC",
    }),
  }),
});
