const ASSET_BASE = "sprites/UI/earthquake-feedback-v2";

export const EARTHQUAKE_FEEDBACK_CONFIG = Object.freeze({
  enabled: true,
  hudDepth: 3500,
  worldDepth: 58,
  notificationActiveBaseY: 188,
  assets: Object.freeze({
    statusFrame: Object.freeze({
      key: "ui-earthquake-status-frame-v2",
      path: `${ASSET_BASE}/seismic-status-frame-v2.png`,
    }),
    medallion: Object.freeze({
      key: "ui-earthquake-medallion-v2",
      path: `${ASSET_BASE}/seismic-medallion-v2.png`,
    }),
  }),
  timing: Object.freeze({
    enterMs: 180,
    exitMs: 240,
    hideFailsafePaddingMs: 180,
    phaseVisibleMs: Object.freeze({
      warning: 4800,
      earthquake: 5200,
      aftermath: 3200,
    }),
    recapVisibleMs: 3200,
    escapeVisibleMs: 6500,
    iconPulsePeriodMs: 520,
  }),
  card: Object.freeze({
    width: 480,
    height: 90,
    topY: 112,
    bottomMargin: 132,
    enterOffsetY: -12,
    exitOffsetY: -8,
    iconX: -184,
    iconSize: 82,
    iconPulseScale: 0.018,
    textX: -126,
    titleY: -18,
    detailY: 7,
    titleFontSize: "17px",
    detailFontSize: "13px",
    textWidth: 330,
    progressX: -126,
    progressY: 31,
    progressWidth: 334,
    progressHeight: 4,
    progressRadius: 2,
  }),
  hazards: Object.freeze({
    maxMarkers: 2,
    maxRockLanes: 2,
    markerDisplaySize: 66,
    markerRadius: 35,
    markerOffsetY: 44,
    markerLabelOffsetY: 40,
    markerFontSize: "12px",
    markerStrokeWidth: 2,
    rockLaneWidthTiles: 0.72,
    rockLaneAlpha: 0.32,
    rockLandingWidthTiles: 0.7,
    restoredOutlineMs: 4800,
    restoredOutlineWidth: 2,
    openedPassageHighlightMs: 6000,
    openedPassageOutlineWidth: 3,
    edgeInset: 24,
    edgeWidth: 146,
    edgeHeight: 46,
    edgeIconSize: 42,
    edgeIconX: -46,
    edgeTextX: -19,
    edgeFontSize: "12px",
    viewportMargin: 30,
  }),
  colors: Object.freeze({
    warning: 0xe6a24d,
    danger: 0xef6a4a,
    gold: 0xd8b45f,
    cyan: 0x65d8f2,
    calm: 0x8cb8c2,
  }),
  labels: Object.freeze({
    warningTitle: "TREMOR NEARBY",
    quakeTitle: "TREMOR ACTIVE",
    aftermathTitle: "GROUND SETTLING",
    recapTitle: "TREMOR PASSED",
    escapeTitle: "ROUTE BLOCKED",
    impactIn: "IMPACT",
    remaining: "REMAINING",
    moveClear: "MOVE FROM CRACKS",
    dustClearing: "DUST CLEARING",
    aftershockWatch: "AFTERSHOCK WATCH",
    escapeAction: "DIG THROUGH FRESH RUBBLE",
    safePortal: "SAFE PORTAL",
    passageOpened: "PASSAGE OPENED",
    passagesOpened: "PASSAGES OPENED",
    noPassagesOpened: "GROUND STABLE",
    caveIn: "CAVE-IN",
    aftershock: "AFTERSHOCK",
    danger: "CAVE-IN",
    intensity: Object.freeze({
      minor: "MINOR",
      medium: "MEDIUM",
      major: "MAJOR",
      cataclysmic: "CATACLYSMIC",
    }),
  }),
});

export function getEarthquakeFeedbackPreloadAssets(
  config = EARTHQUAKE_FEEDBACK_CONFIG,
) {
  return Object.values(config.assets).map(({ key, path }) => ({ key, path }));
}
