export const EARTHQUAKE_SUPPRESSION_UPGRADE = Object.freeze({
  id: "seismicSuppression",
  effectType: "earthquakesDisabled",
  name: "Seismic Suppression",
  description: "Permanently stills the mine. No new earthquakes, cave-ins, or seismic rubble.",
  purchaseCopy: "The mine falls permanently still.",
  merchant: "playerUpgrades",
  uiIcon: "warning",
  goldCost: 75000,
});

export const EARTHQUAKE_CONFIG = Object.freeze({
  enabled: true,
  suppression: EARTHQUAKE_SUPPRESSION_UPGRADE,
  debugFlags: Object.freeze({
    Earthquakes: false,
  }),
  debugFrequencyMultiplier: 10,
  firstEventIntervalMs: Object.freeze([120000, 180000]),
  baseIntervalMs: Object.freeze([360000, 600000]),
  minimumDepth: 1,
  depthBands: Object.freeze([
    { min: 0, max: 99, cooldown: 1, weights: { minor: 1 } },
    { min: 100, max: 299, cooldown: 0.9, weights: { minor: 0.85, medium: 0.15 } },
    { min: 300, max: 599, cooldown: 0.75, weights: { minor: 0.65, medium: 0.32, major: 0.03 } },
    { min: 600, max: 999, cooldown: 0.6, weights: { minor: 0.55, medium: 0.38, major: 0.07 } },
    { min: 1000, max: Infinity, cooldown: 0.5, weights: { minor: 0.45, medium: 0.42, major: 0.125, cataclysmic: 0.005 } },
  ]),
  intensities: Object.freeze({
    minor: { warningMs: [3000, 5000], quakeMs: [5000, 8000], mutationsPerPulse: 1, caveIns: [1, 1], chainChance: 0 },
    medium: { warningMs: [4000, 7000], quakeMs: [8000, 12000], mutationsPerPulse: 2, caveIns: [1, 2], chainChance: 0.15 },
    major: { warningMs: [6000, 9000], quakeMs: [12000, 17000], mutationsPerPulse: 3, caveIns: [2, 4], chainChance: 0.35 },
    cataclysmic: { warningMs: [8000, 10000], quakeMs: [17000, 20000], mutationsPerPulse: 5, caveIns: [4, 7], chainChance: 0.6 },
  }),
  aftermathMs: Object.freeze([5000, 8000]),
  mutationPulseMs: 1000,
  radiusTiles: 12,
  worldSpawn: Object.freeze({
    horizontalMarginTiles: 8,
    bottomMarginTiles: 3,
    playerEncounterDistanceTiles: Object.freeze([1, 3]),
    playerEncounterCandidateAttempts: 24,
    randomCandidateAttempts: 24,
    cavitySearchRadiusTiles: 14,
    cavitySearchAttempts: 56,
    ceilingSearchHalfWidthTiles: 10,
    ceilingSearchAboveTiles: 7,
    ceilingSearchBelowTiles: 4,
    maxAirDropTiles: 12,
    minAirDropTiles: 2,
    caveInSpacingTiles: 3,
    mutationSampleAttempts: 48,
    cooldownMultiplier: 1,
  }),
  playerFeedback: Object.freeze({
    awarenessRadiusTiles: 42,
    shakeRadiusTiles: 24,
    flashRadiusTiles: 18,
    flashColor: 0xd98c45,
    flashAlpha: 0.045,
    flashDurationMs: 180,
    audioRadiusTiles: 32,
    collapseShakeRadiusTiles: 18,
    trapGuidanceRadiusTiles: 5,
    rewardRadiusTiles: 6,
  }),
  localHazards: Object.freeze({
    searchHalfWidthTiles: 5, horizontalPriority: 8, scoreJitter: 0.5,
    leadSeconds: 0.35, maximumLeadTiles: 2, replenishMs: 2600, maximumLive: 3,
    maximumFallTiles: 40,
    budget: Object.freeze({ minor: 3, medium: 5, major: 8, cataclysmic: 12 }),
  }),
  caveInWarningMs: 2100,
  caveInWarningStageRatios: Object.freeze([0.34, 0.72]),
  maxConcurrentFallZones: 24,
  collapseWidths: Object.freeze({
    minor: 1,
    medium: 1,
    major: 2,
    cataclysmic: 3,
  }),
  fallingRock: Object.freeze({
    initialVelocityPxPerSecond: 100,
    gravityPxPerSecondSq: 1500,
    angularVelocityDegPerSecond: 160,
    initialAngleRadians: Object.freeze([-0.2, 0.2]),
    hitboxWidthTiles: 0.62,
    hitboxHeightTiles: 0.68,
    knockbackX: 430,
    knockbackY: -520,
  }),
  impactCooldownMs: 750,
  chainDelayMs: Object.freeze([6000, 10000]),
  rubbleRestoreDelayMs: 3000,
  rubbleOccupiedRetryMs: 320,
  rubbleRestoreStaggerMs: Object.freeze([60, 160]),
  rubbleRestoresPerFrame: 24,
  rubbleHpRatio: 0.25,
  rubbleRespawnRadiusTiles: 12,
  rubbleRespawnCounts: Object.freeze({
    minor: 8,
    medium: 18,
    major: 32,
    cataclysmic: 55,
  }),
  rubbleDepthScaling: Object.freeze([
    { min: 0, max: 99, multiplier: 3, radiusTiles: 12, spreadMs: 2000 },
    { min: 100, max: 299, multiplier: 4, radiusTiles: 14, spreadMs: 2600 },
    { min: 300, max: 599, multiplier: 5.5, radiusTiles: 16, spreadMs: 3300 },
    { min: 600, max: 999, multiplier: 7, radiusTiles: 19, spreadMs: 4000 },
    { min: 1000, max: Infinity, multiplier: 10, radiusTiles: 22, spreadMs: 5000 },
  ]),
});
