import { ASSET_KEYS } from "./assetKeys.js";

export const EMBER_DISCOVERY_EVENT_CONFIG = Object.freeze({
  enabled: true,
  assets: Object.freeze({
    icon: ASSET_KEYS.ui.lootPickups.emberOre,
  }),
  depth: 3560,
  timing: Object.freeze({
    enterMs: 220,
    holdMs: 3200,
    exitMs: 260,
    minimumSkipMs: 650,
  }),
  layout: Object.freeze({
    referenceWidth: 1280,
    referenceHeight: 720,
    centerY: 320,
    cardWidth: 760,
    cardHeight: 228,
    iconX: -286,
    iconSize: 64,
    iconGlowSize: 88,
    textX: -34,
    titleY: -77,
    rewardY: -35,
    connectionY: 10,
    hintY: 66,
    textWidth: 366,
  }),
  presentation: Object.freeze({
    frameAlpha: 0.99,
    glowAlpha: 0.22,
    startScale: 0.9,
    titleColor: "#FFB05E",
    rewardColor: "#FFF0C8",
    connectionColor: "#FF9A52",
    hintColor: "#AFC4D2",
    shadowColor: "#05080B",
    titleFontSize: 15,
    rewardFontSize: 24,
    connectionFontSize: 14,
    hintFontSize: 11,
    glowPulseScale: 1.12,
    glowPulseMs: 420,
  }),
  evolution: Object.freeze({
    reducedMotionQuery: "(prefers-reduced-motion: reduce)",
    hearthX: -154, hearthGroundY: 39, hearthHeight: 98, hearthMaxWidth: 112,
    captionX: -216, captionY: 78, captionSize: 12,
    flightSize: 34, flightDelayMs: 280, flightMs: 580, flightEndY: -18,
    settleMs: 460, pulseScale: 1.14, initialAlpha: 0.48,
    slotSize: 19, slotSpacing: 27, slotY: 54, emptySlotAlpha: 0.14,
    capacity: "{before} USE → {after} USES", stored: "CHARGE STORED",
  }),
  copy: Object.freeze({
    title: "RARE FIND — EMBER",
    reward: "+1 EMBER CHARGE",
    rewardCount: "+{count} EMBER CHARGES",
    evolvedReward: "REFILL {before} → {after} USES",
    chargeReserve: "+{count} EMBER CHARGE · RESERVE {charges}",
    connection: "EMBER FUELS CAMPFIRE BLESSINGS",
    firstFind: "TOWN + CAMPFIRE REFILL UPGRADED TO 2",
    repeatFind: "CAMPFIRE RESERVE: {charges} CHARGES",
    continueHint: "CLICK / SPACE / E TO CONTINUE",
  }),
});
