import { ASSET_KEYS } from "./assetKeys.js";

export const EMBER_DISCOVERY_EVENT_CONFIG = Object.freeze({
  enabled: true,
  assets: Object.freeze({
    frame: ASSET_KEYS.ui.approvedHud.notification,
    icon: ASSET_KEYS.ui.lootPickups.emberOre,
  }),
  depth: 3560,
  timing: Object.freeze({
    enterMs: 220,
    holdMs: 2200,
    exitMs: 260,
    minimumSkipMs: 450,
  }),
  layout: Object.freeze({
    referenceWidth: 1280,
    referenceHeight: 720,
    centerY: 320,
    cardWidth: 570,
    cardHeight: 176,
    iconX: -194,
    iconSize: 78,
    iconGlowSize: 112,
    textX: -118,
    titleY: -54,
    rewardY: -16,
    connectionY: 24,
    hintY: 61,
    textWidth: 356,
  }),
  presentation: Object.freeze({
    frameAlpha: 0.99,
    glowAlpha: 0.22,
    startScale: 0.9,
    titleColor: "#FFB05E",
    rewardColor: "#FFF0C8",
    connectionColor: "#FF9A52",
    hintColor: "#AFC4D2",
    shadowColor: "#05080B",
    titleFontSize: 15,
    rewardFontSize: 24,
    connectionFontSize: 14,
    hintFontSize: 11,
  }),
  copy: Object.freeze({
    title: "RARE FIND — EMBER",
    reward: "+1 EMBER CHARGE",
    connection: "EMBER FUELS CAMPFIRE BLESSINGS",
    firstFind: "TOWN + CAMPFIRE REFILL UPGRADED TO 2",
    repeatFind: "CAMPFIRE RESERVE: {charges} CHARGES",
    continueHint: "CLICK / SPACE / E TO CONTINUE",
  }),
});
