const source = (definition) => Object.freeze(definition);
const candidate = (definition) => Object.freeze(definition);

const SOURCES = Object.freeze({
  idle: source({ sheet: "survival-ual-player-v1-idle-sheet.webp", frameCount: 75, sourceClip: "Idle_Loop", loop: true }),
  idleTalk: source({ sheet: "survival-ual-player-v1-idle-talk-sheet.webp", frameCount: 88, sourceClip: "Idle_Talking_Loop", loop: true }),
  crouch: source({ sheet: "survival-ual-player-v1-crouch-sheet.webp", frameCount: 88, sourceClip: "Crouch_Idle_Loop", loop: true }),
  walk: source({ sheet: "survival-ual-player-v1-walk-sheet.webp", frameCount: 28, sourceClip: "Jog_Fwd_Loop", loop: true }),
  run: source({ sheet: "survival-ual-player-v1-run-sheet.webp", frameCount: 28, sourceClip: "Jog_Fwd_Loop", loop: true }),
  gaspIdle: source({ sheet: "survival-ual-player-v1-gasp-idle-sheet.webp", frameCount: 75, sourceClip: "MM_Idle", loop: true }),
  gaspWalk: source({ sheet: "survival-ual-player-v1-gasp-walk-sheet.webp", frameCount: 47, sourceClip: "MF_Unarmed_Walk_Fwd", loop: true }),
  gaspRun: source({ sheet: "survival-ual-player-v1-gasp-run-sheet.webp", frameCount: 55, sourceClip: "MF_Unarmed_Jog_Fwd", loop: true }),
  airborne: source({ sheet: "survival-ual-player-v1-airborne-sheet.webp", frameCount: 41, sourceClip: "Jump_Start", loop: false }),
  falling: source({ sheet: "survival-ual-player-v1-falling-sheet.webp", frameCount: 75, sourceClip: "Jump_Loop", loop: true }),
  gaspFall: source({ sheet: "survival-ual-player-v1-gasp-fall-sheet.webp", frameCount: 92, sourceClip: "MM_Fall_Loop", loop: true }),
  landing: source({ sheet: "survival-ual-player-v1-landing-sheet.webp", frameCount: 39, sourceClip: "Jump_Land", loop: false }),
  climb: source({ sheet: "survival-ual-player-v1-climb-sheet.webp", frameCount: 20, sourceClip: "ClimbUp_1m", loop: true }),
  fly: source({ sheet: "survival-ual-player-v1-fly-sheet.webp", frameCount: 14, sourceClip: "Shield_Dash", loop: false }),
  teleport: source({ sheet: "survival-ual-player-v1-teleport-sheet.webp", frameCount: 45, sourceClip: "Roll", loop: false }),
  wallPush: source({ sheet: "survival-ual-player-v1-wall-push-sheet.webp", frameCount: 80, sourceClip: "Push_Loop", loop: true }),
  pickaxe: source({ sheet: "survival-ual-player-v1-pickaxe-mining-sheet.webp", frameCount: 29, sourceClip: "TreeChopping_Loop", loop: true }),
  gaspAttack: source({ sheet: "survival-ual-player-v1-gasp-attack-sheet.webp", frameCount: 32, sourceClip: "MM_Attack_01", loop: false }),
  gaspUp: source({ sheet: "survival-ual-player-v1-gasp-dig-up-sheet.webp", frameCount: 32, sourceClip: "MM_Attack_02", loop: false }),
  gaspDown: source({ sheet: "survival-ual-player-v1-gasp-dig-down-sheet.webp", frameCount: 52, sourceClip: "MM_Attack_03", loop: false }),
  gaspCharge: source({ sheet: "survival-ual-player-v1-gasp-mining-strike-sheet.webp", frameCount: 57, sourceClip: "MM_ChargedAttack", loop: false }),
  groundStrike: source({ sheet: "survival-ual-player-v1-ground-strike-sheet.webp", frameCount: 41, sourceClip: "OverhandThrow", loop: false }),
  jab: source({ sheet: "survival-ual-player-v1-punch-jab-sheet.webp", frameCount: 27, sourceClip: "Punch_Jab", loop: false }),
  cross: source({ sheet: "survival-ual-player-v1-punch-cross-sheet.webp", frameCount: 31, sourceClip: "Punch_Cross", loop: false }),
  uppercut: source({ sheet: "survival-ual-player-v1-punch-uppercut-sheet.webp", frameCount: 15, sourceClip: "Melee_Hook", loop: false }),
  hitReact: source({ sheet: "survival-ual-player-v1-hit-react-sheet.webp", frameCount: 11, sourceClip: "Hit_Chest", loop: false }),
  death: source({ sheet: "survival-ual-player-v1-death-sheet.webp", frameCount: 73, sourceClip: "Death01", loop: false }),
  thunder: source({ sheet: "survival-ual-player-v1-thunder-charge-sheet.webp", frameCount: 63, sourceClip: "Spell_Simple_Idle_Loop", loop: true }),
});

const make = (id, group, label, badge, sourceId, summary, evidence, placeholder = false) => candidate({ id, group, label, badge, sourceId, summary, evidence, placeholder });

export const EPIC_GASP_ANIMATION_CATALOG_CONFIG = Object.freeze({
  version: "epic-gasp-animation-catalog-v1-20260721",
  runtimeRoot: "../../../sprites/character/survival-ual-player-v1/runtime/",
  display: Object.freeze({ columns: 16, defaultFps: 30, displaySizePx: 109, originY: 247 / 256 }),
  totalCandidateCount: 50,
  noRuntimeWiring: true,
  candidates: Object.freeze([
    make("traversal-01", "TRAVERSAL", "GASP idle", "LOCOMOTION", "gaspIdle", "Neutral breathing and stance for the Survival base state.", "Epic GASP retargeted current character"),
    make("traversal-02", "TRAVERSAL", "UAL idle", "LOCOMOTION", "idle", "Existing UAL neutral fallback.", "UAL runtime sheet on current character"),
    make("traversal-03", "TRAVERSAL", "Idle talking hold", "LOCOMOTION", "idleTalk", "Longer neutral hold for menus, vendors, and safe rooms.", "UAL runtime candidate"),
    make("traversal-04", "TRAVERSAL", "Crouch idle", "TRAVERSAL", "crouch", "Low-profile stance for tunnels and stealthy approach.", "UAL runtime candidate"),
    make("traversal-05", "TRAVERSAL", "UAL walk", "TRAVERSAL", "walk", "Compact walk fallback for low-speed movement.", "UAL runtime candidate"),
    make("traversal-06", "TRAVERSAL", "GASP walk", "TRAVERSAL", "gaspWalk", "Controlled forward walk with grounded weight.", "Epic GASP retargeted current character"),
    make("traversal-07", "TRAVERSAL", "Compact UAL jog", "SELECTED RUN", "run", "Current selected run sample; kept as the control.", "Existing approved UAL runtime"),
    make("traversal-08", "TRAVERSAL", "Epic GASP forward jog", "RUN CANDIDATE", "gaspRun", "Forward jog with clear foot travel and forward intent.", "Epic GASP retargeted current character"),
    make("traversal-09", "TRAVERSAL", "Jump start", "AIRBORNE", "airborne", "Takeoff candidate for ledges and vertical traversal.", "UAL runtime candidate"),
    make("traversal-10", "TRAVERSAL", "Jump loop", "AIRBORNE", "falling", "Sustained airborne loop while crossing gaps.", "UAL runtime candidate"),
    make("traversal-11", "TRAVERSAL", "GASP fall loop", "AIRBORNE", "gaspFall", "Alternative fall read from Epic GASP.", "Epic GASP retargeted current character"),
    make("traversal-12", "TRAVERSAL", "Landing recovery", "AIRBORNE", "landing", "Landing settle for a heavier character read.", "UAL runtime candidate"),
    make("traversal-13", "TRAVERSAL", "Climb one metre", "TRAVERSAL", "climb", "Vertical ladder or ledge climb placeholder.", "UAL clip; environment hook still pending"),
    make("traversal-14", "TRAVERSAL", "Shield dash", "TRAVERSAL", "fly", "Short burst movement placeholder for cave gaps.", "UAL clip; gameplay role still pending"),
    make("traversal-15", "TRAVERSAL", "Roll traversal", "TRAVERSAL", "teleport", "Roll-like evade and gap reposition candidate.", "UAL clip; naming retained from source"),
    make("traversal-16", "TRAVERSAL", "Wall push", "TRAVERSAL", "wallPush", "Wall contact / squeeze-through placeholder.", "UAL clip; collision hook still pending"),
    make("traversal-17", "TRAVERSAL", "Heavy walk", "TRAVERSAL", "walk", "Slower presentation pass using the same grounded walk.", "Placeholder speed role; same real current-character sheet", true),
    make("traversal-18", "TRAVERSAL", "Heavy jog", "TRAVERSAL", "gaspRun", "Weightier traversal read for loaded inventory.", "Placeholder speed role; same real current-character sheet", true),
    make("traversal-19", "TRAVERSAL", "Crouch approach", "TRAVERSAL", "crouch", "Crouch movement placeholder until a dedicated clip is sourced.", "Placeholder role; current-character crouch sheet", true),
    make("traversal-20", "TRAVERSAL", "Landing into walk", "TRAVERSAL", "landing", "Recovery-to-traversal transition placeholder.", "Placeholder transition; real landing sheet", true),
    make("mining-01", "PICKAXE / MINING", "Pickaxe mining loop", "PICKAXE", "pickaxe", "Best local tool-less pickaxe motion source.", "UAL2 TreeChopping_Loop on current character"),
    make("mining-02", "PICKAXE / MINING", "Pickaxe anticipation", "PICKAXE PLACEHOLDER", "pickaxe", "Anticipation trim candidate for a readable first hit.", "Placeholder trim; real current-character pickaxe sheet", true),
    make("mining-03", "PICKAXE / MINING", "Pickaxe impact", "PICKAXE PLACEHOLDER", "pickaxe", "Impact trim candidate for hitstop and tile contact.", "Placeholder trim; real current-character pickaxe sheet", true),
    make("mining-04", "PICKAXE / MINING", "Pickaxe recovery", "PICKAXE PLACEHOLDER", "pickaxe", "Recovery trim candidate for chaining the next swing.", "Placeholder trim; real current-character pickaxe sheet", true),
    make("mining-05", "PICKAXE / MINING", "Pickaxe short tap", "PICKAXE PLACEHOLDER", "pickaxe", "Short tap candidate for low-health tiles.", "Placeholder timing role; real current-character pickaxe sheet", true),
    make("mining-06", "PICKAXE / MINING", "Pickaxe charged hold", "PICKAXE PLACEHOLDER", "gaspCharge", "Charge-up placeholder before a stronger tool strike.", "GASP charged body motion; no tool layer", true),
    make("mining-07", "PICKAXE / MINING", "GASP 6 upward dig", "GASP 6", "gaspUp", "Upward-facing attack that can be judged as a dig-up shape.", "MM_Attack_02; no tool layer"),
    make("mining-08", "PICKAXE / MINING", "GASP 6 upward-side hit", "GASP 6 PLACEHOLDER", "gaspUp", "Frame-window candidate for a sideways digging beat.", "GASP 6 trim placeholder; no gameplay wiring", true),
    make("mining-09", "PICKAXE / MINING", "GASP 6 high-wall dig", "GASP 6 PLACEHOLDER", "gaspUp", "Higher-angle wall contact placeholder.", "GASP 6 role placeholder; no tool layer", true),
    make("mining-10", "PICKAXE / MINING", "GASP 7 downward dig", "GASP 7", "gaspDown", "Downward strike shape retained for comparison only.", "MM_Attack_03; no tool layer"),
    make("mining-11", "PICKAXE / MINING", "GASP 7 final finisher", "GASP 7 PLACEHOLDER", "gaspDown", "Potential final attack / downward mining finisher.", "GASP 7 trim placeholder; no gameplay wiring", true),
    make("mining-12", "PICKAXE / MINING", "Charged mining strike", "MINING-ADJACENT", "gaspCharge", "Largest local GASP mining-adjacent body strike.", "MM_ChargedAttack; no visible pickaxe"),
    make("mining-13", "PICKAXE / MINING", "Ground strike", "MINING-ADJACENT", "groundStrike", "Heavy downward body shape for impact comparison.", "UAL OverhandThrow; no tool layer"),
    make("mining-14", "PICKAXE / MINING", "Upward tool punch", "PICKAXE PLACEHOLDER", "uppercut", "Upward punch placeholder while a dedicated upward pickaxe clip is sourced.", "UAL2 Melee_Hook; no tool layer", true),
    make("mining-15", "PICKAXE / MINING", "Side tool jab", "PICKAXE PLACEHOLDER", "jab", "Sideways tool-hit placeholder for a quick combo beat.", "UAL Punch_Jab; no tool layer", true),
    make("action-01", "ACTION / RESPONSE", "GASP attack", "COMBAT", "gaspAttack", "Forward attack option for hostile encounters.", "Epic GASP MM_Attack_01"),
    make("action-02", "ACTION / RESPONSE", "UAL jab", "COMBAT", "jab", "Fast close-range hit option.", "UAL Punch_Jab"),
    make("action-03", "ACTION / RESPONSE", "UAL cross", "COMBAT", "cross", "Committed cross for a stronger hit.", "UAL Punch_Cross"),
    make("action-04", "ACTION / RESPONSE", "UAL uppercut", "COMBAT", "uppercut", "Upward punch candidate requested from UAL2.", "UAL2 Melee_Hook"),
    make("action-05", "ACTION / RESPONSE", "Hit react", "RESPONSE", "hitReact", "Damage response for combat and cave hazards.", "UAL Hit_Chest"),
    make("action-06", "ACTION / RESPONSE", "Death", "RESPONSE", "death", "Terminal state candidate for enemies or player failure.", "UAL Death01"),
    make("action-07", "ACTION / RESPONSE", "Thunder charge", "ABILITY", "thunder", "Ability charge stance for a special action.", "UAL Spell_Simple_Idle_Loop"),
    make("action-08", "ACTION / RESPONSE", "GASP attack recovery", "COMBAT PLACEHOLDER", "gaspAttack", "Recovery timing placeholder after a GASP attack.", "Placeholder trim; real GASP attack sheet", true),
    make("action-09", "ACTION / RESPONSE", "Ground impact recovery", "COMBAT PLACEHOLDER", "groundStrike", "Recovery timing placeholder after a heavy impact.", "Placeholder trim; real ground-strike sheet", true),
    make("action-10", "ACTION / RESPONSE", "Mining damage reaction", "MINING PLACEHOLDER", "hitReact", "Damage response placeholder for tool recoil or tile hazard.", "Placeholder role; real hit-react sheet", true),
    make("action-11", "ACTION / RESPONSE", "Ability-to-traversal exit", "ABILITY PLACEHOLDER", "thunder", "Exit pose placeholder before movement resumes.", "Placeholder transition; real charge sheet", true),
    make("action-12", "ACTION / RESPONSE", "Airborne attack", "COMBAT PLACEHOLDER", "gaspAttack", "Airborne attack role placeholder for later blend testing.", "Placeholder role; real GASP attack sheet", true),
    make("action-13", "ACTION / RESPONSE", "Crouch damage reaction", "RESPONSE PLACEHOLDER", "hitReact", "Low-profile hit response placeholder.", "Placeholder role; real hit-react sheet", true),
    make("action-14", "ACTION / RESPONSE", "Climb exit", "TRAVERSAL PLACEHOLDER", "climb", "Climb-to-stand transition placeholder.", "Placeholder role; real climb sheet", true),
    make("action-15", "ACTION / RESPONSE", "Landing impact", "TRAVERSAL PLACEHOLDER", "landing", "Landing impact variant for deeper drops.", "Placeholder role; real landing sheet", true),
  ].map((entry, index) => Object.freeze({
    ...entry,
    option: `${entry.group} ${String(index + 1).padStart(2, "0")}`,
    ...SOURCES[entry.sourceId],
  }))),
});
