export const FREIGHT_LIFT_PROTOTYPE = Object.freeze({
  title: "Freight Lift — Isolated Vertical Shaft Prototype",
  reviewOnly: true,
  viewport: Object.freeze({ widthPx: 1280, heightPx: 720 }),
  world: Object.freeze({
    widthPx: 1280,
    heightPx: 1760,
    backgroundColor: "#071014",
  }),
  assets: Object.freeze({
    background: Object.freeze({
      key: "freight-lift-pressure-foundry-background",
      path: "../../../sprites/backgrounds/world-visual-v2/depth/biome-variation-v2/pressure-foundry-quiet-maintenance-bay-v2.webp",
    }),
    foreground: Object.freeze({
      key: "freight-lift-pressure-foundry-foreground",
      path: "../../../sprites/backgrounds/world-visual-v2/depth/foreground-cohesion-v1/2026-07-28-underground-08-pressure-foundry-foreground-v1.webp",
    }),
    landing: Object.freeze({
      key: "freight-lift-pressure-foundry-landing",
      path: "../../../sprites/backgrounds/world-visual-v2/depth/biome-ground-structures-v4/pressure-foundry-steel-stone-buttress-v4.webp",
    }),
    lift: Object.freeze({
      key: "freight-lift-pressure-foundry-states",
      path: "../../../sprites/environment/interactive-world-states-v1/pressure-foundry-freight-lift-states-atlas-v1.webp",
      frameWidthPx: 448,
      frameHeightPx: 448,
      endFrame: 9,
    }),
    player: Object.freeze({
      key: "freight-lift-real-miner-idle",
      path: "../../../sprites/character/ual-native-player-v1/runtime/ual-native-player-v1-idle-sheet.webp",
      frameWidthPx: 256,
      frameHeightPx: 256,
      endFrame: 74,
    }),
  }),
  shaft: Object.freeze({
    centerXPx: 640,
    leftWallXPx: 235,
    rightWallXPx: 1045,
    wallWidthPx: 310,
    backdropAlpha: 0.76,
    foregroundAlpha: 0.88,
  }),
  stops: Object.freeze({
    upper: Object.freeze({ id: "upper", platformYPx: 350, label: "UPPER MAINTENANCE BAY" }),
    lower: Object.freeze({ id: "lower", platformYPx: 1435, label: "LOWER FREIGHT BAY" }),
    arrivalTolerancePx: 2,
  }),
  lift: Object.freeze({
    displaySizePx: 330,
    platformWidthPx: 238,
    platformHeightPx: 26,
    visualBottomOffsetPx: 35,
    accelerationPxPerSec2: 720,
    decelerationPxPerSec2: 930,
    maxSpeedPxPerSec: 245,
    activationDurationMs: 405,
    resolvedDurationMs: 460,
    activeFramePeriodMs: 170,
    proximityFrame: 1,
    activationFrames: Object.freeze([2, 3, 4]),
    activeFrames: Object.freeze([5, 6]),
    resolvedFrame: 7,
    dormantFrame: 0,
  }),
  player: Object.freeze({
    spawnOffsetXPx: 0,
    feetOffsetAbovePlatformPx: 7,
    displaySizePx: 109,
    bodyWidthPx: 31,
    bodyHeightPx: 75,
    bodyOffsetXPx: 112,
    bodyOffsetYPx: 167,
    walkSpeedPxPerSec: 205,
    gravityYPxPerSec2: 1400,
    maxFallSpeedPxPerSec: 995,
    carryTolerancePx: 12,
    carryInsetPx: 18,
    idleAnimationKey: "freight-lift-real-miner-idle-animation",
    idleFrameRate: 30,
  }),
  landings: Object.freeze({
    widthPx: 430,
    heightPx: 44,
    imageWidthPx: 510,
    imageHeightPx: 230,
    imageYOffsetPx: 94,
    leftCenterXPx: 112,
    rightCenterXPx: 1168,
  }),
  camera: Object.freeze({
    lerpX: 0.12,
    lerpY: 0.1,
    deadzoneWidthPx: 240,
    deadzoneHeightPx: 160,
  }),
  input: Object.freeze({
    left: "A",
    right: "D",
    interact: "E",
    reset: "R",
  }),
  copy: Object.freeze({
    instruction: "A / D MOVE  •  E CALL / RIDE  •  R RESET",
    noJump: "The platform carries the miner physically; no jump or portal transition is used.",
    ready: "E  •  RIDE TO THE OTHER AUTHORED STOP",
    travellingUp: "LIFT ASCENDING",
    travellingDown: "LIFT DESCENDING",
    arrived: "AUTHORED STOP REACHED",
  }),
  colors: Object.freeze({
    uiText: "#eefaff",
    uiAccent: "#71e8ff",
    uiMuted: "#9bb0b7",
    uiShadow: "#000000",
  }),
  depth: Object.freeze({
    background: -4,
    shaft: -3,
    landing: 1,
    lift: 4,
    player: 8,
    ui: 100,
  }),
});
