export const GAME_WIKI = Object.freeze({
  url: "https://www.nextgen.run/game/undersstar-wiki/",
  target: "_blank",
  windowFeatures: "noopener,noreferrer",
  shortcut: Object.freeze({
    enabled: true,
    label: "WIKI",
    right: 14,
    gapAboveMap: 7,
    width: 154,
    height: 36,
    minimumDisplayWidth: 116,
    minimumDisplayHeight: 32,
    minimumHitSize: 48,
    hitPaddingX: 5,
    hitPaddingY: 4,
    fontSize: 13,
    color: "#9cecff",
    stroke: "#02060a",
    strokeThickness: 3,
    hoverAlpha: 0.86,
    pressScale: 0.97,
    pressMs: 70,
  }),
});
