window.GROUND_STRIKE_REVIEW = Object.freeze({
  id: "ground-strike-body-follow-5way-v1",
  title: "Ground-strike body-follow review",
  runtimeAnimationKey: "survival-ual-player-v1-attack-down-ground-strike-anim",
  frameCount: 34,
  frameRate: 14,
  contactFrame: 16,
  framePathTemplate: "testing/blender-animation-lab-v1/review-drafts/ground-strike-body-follow-5way-v1/{id}/frames/frame_{frame}.png",
  reviewOnly: true,
  productionChanged: false,
  decision: "complete-reject",
  decisionLabel: "Complete reject — none are eligible for runtime wiring",
  activeDownStrike: "OverhandThrow",
  locomotionNote: "Jog_Fwd_Loop remains the approved run clip; it is not a down-strike replacement.",
  variants: Object.freeze([
    Object.freeze({
      id: "01-upper-body-hinge",
      number: 1,
      label: "Upper-body hinge",
      description: "Restrained hip drop with more of the reach carried through the chest and neck.",
      note: "Rejected",
      rejected: true,
    }),
    Object.freeze({
      id: "02-balanced-chain",
      number: 2,
      label: "Balanced chain",
      description: "The hips, spine, neck, and knees share the distance to the floor.",
      note: "Rejected",
      rejected: true,
    }),
    Object.freeze({
      id: "03-deep-athletic-crouch",
      number: 3,
      label: "Deep athletic crouch",
      description: "The knees and hips absorb most of the downward reach.",
      note: "Rejected",
      rejected: true,
    }),
    Object.freeze({
      id: "04-forward-lunge",
      number: 4,
      label: "Forward lunge",
      description: "The pelvis travels toward the strike while the feet remain planted.",
      note: "Rejected",
      rejected: true,
    }),
    Object.freeze({
      id: "05-impact-compression",
      number: 5,
      label: "Impact compression",
      description: "Faster whole-body compression with a short weighted contact hold.",
      note: "Rejected",
      rejected: true,
    }),
  ]),
});
