export const HARDCORE_MEMORIAL_CONFIG = Object.freeze({
  version: 1,
  assets: Object.freeze({
    grave: Object.freeze({
      key: "environment-hardcore-memorial-v1",
      path: "sprites/environment/hardcore-memorial-v1/hardcore-memorial-runtime-v1.webp",
    }),
    actionButton: Object.freeze({
      key: "ui-hardcore-death-action-v1",
      path: "sprites/UI/hardcore-mode-v1/hardcore-death-action-runtime-v1.webp",
    }),
  }),
  persistence: Object.freeze({
    storageKey: "dig-game-hardcore-memorials-v1",
    maximumRecords: 24,
    maximumRecordsPerSlot: 12,
    maximumCoordinatePx: 100000000,
    maximumTimestamp: 9007199254740991,
    maximumStringLength: 180,
    maximumJourneyEvents: 24,
  }),
  world: Object.freeze({
    depth: 14,
    widthTiles: 3.15,
    heightTiles: 4.72,
    baseAlpha: 0.98,
    pulseAlpha: 0.04,
    pulseScale: 0.012,
    pulseDurationMs: 1750,
    hoverScale: 1.045,
    pressScale: 0.975,
    interactionTweenMs: 110,
    pixelAlphaTolerance: 24,
    clusterDistanceTiles: 2.25,
    clusterOffsetsTiles: Object.freeze([0, -0.82, 0.82, -1.55, 1.55]),
    noticeDurationMs: 5200,
    noticeKeyPrefix: "hardcore-memorial-",
  }),
  recap: Object.freeze({
    statsPerPage: 9,
    achievementsPerPage: 4,
    titleY: -205,
    subtitleY: -168,
    reasonY: -132,
    pageTitleY: -92,
    pageBodyY: -62,
    pageBodyWidth: 770,
    pageIndicatorY: 119,
    statusY: 145,
    detailY: 167,
    actionY: 222,
    actionOffsetX: 172,
    actionWidth: 286,
    actionHeight: 94,
    footerY: 286,
    actionHoverScale: 1.045,
    actionPressScale: 0.975,
    actionTweenMs: 105,
    readyPanelPulseMs: 420,
    font: Object.freeze({
      titlePx: 30,
      subtitlePx: 12,
      reasonPx: 15,
      pageTitlePx: 17,
      pageBodyPx: 13,
      pageIndicatorPx: 11,
      statusPx: 12,
      detailPx: 12,
      actionPx: 17,
      footerPx: 11,
    }),
  }),
  copy: Object.freeze({
    deathTitle: "THE OATH IS CLAIMED",
    deathSubtitlePrefix: "PERMADEATH",
    depthLabel: "DEPTH",
    meterUpperSuffix: "M",
    overviewTitle: "FINAL RUN RECORD",
    statsTitle: "MINER STATISTICS",
    achievementsTitle: "ACHIEVEMENTS EARNED",
    erasingLabel: "ERASING HARDCORE RUN...",
    readyLabel: "HARDCORE RUN ERASED • MEMORIAL RECORDED",
    retryLabel: "TRY AGAIN",
    menuLabel: "BACK TO MENU",
    readyFooter:
      "ENTER  TRY AGAIN   •   ESC  BACK TO MENU   •   ←/→  CHANGE PAGE   •   CASUAL SAVES UNTOUCHED",
    busyFooter: "←/→  REVIEW RUN WHILE THE HARDCORE SLOT IS PURGED",
    noAchievements: "No Journey milestones were recorded before this death.",
    memorialPrefix: "FALLEN HARDCORE RUN",
    memorialInspectHint: "The grave preserves this erased run.",
    unknownDeathReason: "Your Gem Power reached zero.",
    unknownDeathSource: "unknown",
    defaultCharacterId: "default",
    pagePrefix: "PAGE",
    ofLabel: "OF",
    slotPrefix: "SLOT",
    backupsErasedSuffix: "BACKUPS ERASED",
    eraseForcedSuffix: "HARDCORE SAVE ERASE FORCED",
  }),
  overviewRows: Object.freeze([
    Object.freeze({ key: "depth", label: "DEPTH", format: "depth" }),
    Object.freeze({
      key: "activePlayMs",
      label: "ACTIVE HARDCORE TIME",
      format: "duration",
    }),
    Object.freeze({ key: "level", label: "PLAYER LEVEL" }),
    Object.freeze({ key: "gemPowerMax", label: "GEM POWER CAP", suffix: " GP" }),
    Object.freeze({ key: "peakStress", label: "PEAK STRESS", suffix: "%" }),
    Object.freeze({ key: "wurmEncounters", label: "WURM HUNTS" }),
    Object.freeze({ key: "unstuckUses", label: "LAST RESORT RETURNS" }),
    Object.freeze({ key: "paidTeleports", label: "PAID TELEPORTS" }),
    Object.freeze({ key: "teleportMoneySpent", label: "TELEPORT MONEY SPENT" }),
    Object.freeze({ key: "carriedResourceUnits", label: "CARRIED UNITS LOST" }),
  ]),
  statRows: Object.freeze([
    Object.freeze({ key: "bestDepth", label: "BEST DEPTH", suffix: "m" }),
    Object.freeze({ key: "currentDepth", label: "FINAL DEPTH", suffix: "m" }),
    Object.freeze({ key: "totalTilesBroken", label: "TILES BROKEN" }),
    Object.freeze({ key: "totalResources", label: "RESOURCES MINED" }),
    Object.freeze({ key: "moneyEarned", label: "MONEY EARNED" }),
    Object.freeze({ key: "resourcesSold", label: "RESOURCES SOLD" }),
    Object.freeze({ key: "upgradesPurchased", label: "UPGRADES BOUGHT" }),
    Object.freeze({ key: "portalsActivated", label: "PORTALS ACTIVATED" }),
    Object.freeze({ key: "chestsOpened", label: "CHESTS OPENED" }),
    Object.freeze({ key: "starsCollected", label: "STARS COLLECTED" }),
    Object.freeze({ key: "relicsFound", label: "RELICS FOUND" }),
    Object.freeze({ key: "criticalHits", label: "CRITICAL HITS" }),
    Object.freeze({ key: "highestCombo", label: "HIGHEST COMBO" }),
    Object.freeze({ key: "luckyDrops", label: "LUCKY DROPS" }),
    Object.freeze({ key: "overkills", label: "OVERKILLS" }),
    Object.freeze({ key: "earthquakesSurvived", label: "QUAKES SURVIVED" }),
    Object.freeze({ key: "passagesOpened", label: "PASSAGES OPENED" }),
    Object.freeze({ key: "expeditionsCompleted", label: "RETURNS COMPLETED" }),
  ]),
});

export function getHardcoreMemorialPreloadAssets() {
  return Object.values(HARDCORE_MEMORIAL_CONFIG.assets).map(asset => ({
    key: asset.key,
    path: asset.path,
  }));
}
