const TILE_SIZE_PX = 94;
const REGION_WIDTH_TILES = 21;
const REGION_HEIGHT_TILES = 12;

const freeze = (value) => {
  if (!value || typeof value !== "object" || Object.isFrozen(value)) return value;
  Object.freeze(value);
  Object.values(value).forEach(freeze);
  return value;
};

const point = (tx, ty) => ({ tx, ty });

function region({
  id,
  label,
  levelId,
  leftTile,
  topTile,
  color,
  layoutRows,
  arrivalLocal,
  entryShaftLocal,
  entryDirection,
  returnAltarLocal,
  arcVaultLocal,
  coreLocal,
  surfaceGate,
  surfaceReturn,
  requiredUpgradeId = null,
  partId,
  partLabel,
  vaultId,
  componentAssetKey,
  heartAssetKey,
  heartAssetPath,
  backdropKey,
  backdropPath,
  tileStyle,
  materialPalette,
  materialHealthScale,
  coreHealth,
}) {
  return {
    id,
    label,
    levelId,
    leftTile,
    topTile,
    widthTiles: REGION_WIDTH_TILES,
    heightTiles: REGION_HEIGHT_TILES,
    displayWidthPx: REGION_WIDTH_TILES * TILE_SIZE_PX,
    displayHeightPx: REGION_HEIGHT_TILES * TILE_SIZE_PX,
    color,
    layoutRows,
    arrival: point(leftTile + arrivalLocal.tx, topTile + arrivalLocal.ty),
    entryShaft: point(leftTile + entryShaftLocal.tx, topTile + entryShaftLocal.ty),
    entryDirection,
    returnAltar: point(leftTile + returnAltarLocal.tx, topTile + returnAltarLocal.ty),
    arcVault: point(leftTile + arcVaultLocal.tx, topTile + arcVaultLocal.ty),
    core: point(leftTile + coreLocal.tx, topTile + coreLocal.ty),
    surfaceGate,
    surfaceReturn,
    requiredUpgradeId,
    partId,
    partLabel,
    vaultId,
    componentAssetKey,
    heartAssetKey,
    heartAssetPath,
    backdropKey,
    backdropPath,
    tileStyle,
    materialPalette,
    materialHealthScale,
    coreHealth,
    portalAssetKey: levelId === 1
      ? "v11-sky-island-level-1-portal"
      : "v11-sky-island-level-2-portal",
  };
}

export const HEAVENBLOCK_CELL_MARKERS = Object.freeze({
  AIR: ".",
  MATERIAL: "#",
  PROTECTED: "A",
  RELIC_CACHE: "R",
  COMPONENT_HEART: "C",
});

export const HEAVENBLOCKS_WORLD_CONFIG = freeze({
  version: 3,
  tileSize: TILE_SIZE_PX,
  regionWidthTiles: REGION_WIDTH_TILES,
  regionHeightTiles: REGION_HEIGHT_TILES,
  coreTileTypeKey: "HEAVENBLOCK_CORE",
  visual: {
    backdropDepth: -9.8,
    tileDepth: 3.1,
    crackDepth: 3.2,
    heartDepth: 3.25,
    portalDepth: 3.3,
    relicPlateDepth: 3.18,
    relicTokenDepth: 3.24,
    backdropOverscan: 1.08,
    heartDisplayTiles: 1.72,
    relicPlateDisplayTiles: 1,
    relicTokenDisplayTiles: 0.78,
    relicPulseScale: 1.1,
    relicPulseDurationMs: 1050,
    portalWidthTiles: 1.45,
    portalHeightTiles: 1.45,
    lockedPortalAlpha: 0.32,
    unlockedPortalAlpha: 1,
    pulseScale: 1.06,
    pulseDurationMs: 1400,
  },
  regions: [
    region({
      id: "lower-sky-cloud-reef",
      label: "Lower Sky Cloud Reef",
      levelId: 1,
      leftTile: 54,
      topTile: 38,
      color: 0x79ddff,
      layoutRows: [
        ".....................",
        ".....###AA.AA##......",
        "...###############...",
        "...###############...",
        "...###############...",
        "...###############...",
        "....#############....",
        ".......####R####.....",
        "........#######......",
        ".........##C##.......",
        ".....................",
        ".....................",
      ],
      arrivalLocal: point(9, 0),
      entryShaftLocal: point(10, 1),
      entryDirection: "RIGHT",
      returnAltarLocal: point(8, 0),
      arcVaultLocal: point(12, 0),
      coreLocal: point(11, 9),
      surfaceGate: point(64, 64),
      surfaceReturn: point(64, 64),
      partId: "aether-turbine",
      partLabel: "Aether Turbine",
      vaultId: "cloud-reef-omega-vault",
      componentAssetKey: "heavenblocks-aether-turbine-v1",
      heartAssetKey: "heavenblocks-aether-turbine-heart-v2",
      heartAssetPath: "sprites/backgrounds/heavenblocks-v1/aether-turbine-heart-v2.png",
      backdropKey: "heavenblocks-lower-sky-backdrop-v1",
      backdropPath: "sprites/backgrounds/heavenblocks-v1/lower-sky-backdrop-v1.png",
      tileStyle: {
        surfaceAssetSlots: ["skyIslandTop"],
        edgeAssetSlots: ["skyIslandCorner"],
        undersideAssetSlots: ["skyIslandUnder"],
        interiorAssetSlots: ["stoneHp5"],
        stylizedSurfaceTypeKeys: ["STONE"],
        surfaceTint: 0xc9f6ff,
        edgeTint: 0xa8e7f4,
        undersideTint: 0x79cfe8,
        materialTint: 0xe6fbff,
        backdropAlpha: 0.9,
      },
      materialPalette: [
        { tileTypeKey: "STONE", weight: 46 },
        { tileTypeKey: "COPPER", weight: 24 },
        { tileTypeKey: "SILVER", weight: 18 },
        { tileTypeKey: "GOLD", weight: 12 },
      ],
      materialHealthScale: 0.62,
      coreHealth: 900,
    }),
    region({
      id: "angel-heavenblock",
      label: "Angel Heavenblock",
      levelId: 1,
      leftTile: 98,
      topTile: 8,
      color: 0xffe9a6,
      layoutRows: [
        "......#..............",
        "......#####..........",
        ".....#####AAAAA.##...",
        "....##############...",
        "...##############....",
        "...#######R#######...",
        "...###############...",
        "....#############....",
        ".....#############...",
        ".....#####C#######...",
        ".....#############...",
        ".....############....",
      ],
      arrivalLocal: point(14, 1),
      entryShaftLocal: point(15, 2),
      entryDirection: "RIGHT",
      returnAltarLocal: point(13, 1),
      arcVaultLocal: point(10, 1),
      coreLocal: point(10, 9),
      surfaceGate: point(110, 64),
      surfaceReturn: point(110, 64),
      partId: "halo-regulator",
      partLabel: "Halo Regulator",
      vaultId: "angelic-omega-vault",
      componentAssetKey: "heavenblocks-halo-regulator-v1",
      heartAssetKey: "heavenblocks-halo-regulator-heart-v2",
      heartAssetPath: "sprites/backgrounds/heavenblocks-v1/halo-regulator-heart-v2.png",
      backdropKey: "heavenblocks-angel-backdrop-v1",
      backdropPath: "sprites/backgrounds/heavenblocks-v1/angel-heavenblock-backdrop-v1.png",
      tileStyle: {
        surfaceAssetSlots: ["silverHp5", "goldHp5"],
        edgeAssetSlots: ["goldHp5", "silverHp5"],
        undersideAssetSlots: ["skyIslandUnder"],
        interiorAssetSlots: ["silverHp5", "goldHp5"],
        stylizedSurfaceTypeKeys: ["STONE"],
        surfaceTint: 0xfff6dc,
        edgeTint: 0xffe7a4,
        undersideTint: 0xffd783,
        materialTint: 0xfff3cf,
        backdropAlpha: 0.84,
      },
      materialPalette: [
        { tileTypeKey: "STONE", weight: 30 },
        { tileTypeKey: "STEEL", weight: 20 },
        { tileTypeKey: "SILVER", weight: 30 },
        { tileTypeKey: "GOLD", weight: 20 },
      ],
      materialHealthScale: 0.78,
      coreHealth: 1350,
    }),
    region({
      id: "devil-eclipse-scar",
      label: "Devil Eclipse Scar",
      levelId: 2,
      leftTile: 220,
      topTile: 26,
      color: 0xd96aff,
      layoutRows: [
        ".....................",
        "..##.###...........#.",
        "..########...###.####",
        "..#######A.AAA#######",
        "...##################",
        "....################.",
        ".....#####R#######...",
        ".......##########....",
        "........########.....",
        ".........##C###......",
        ".........#####.......",
        "..........###........",
      ],
      arrivalLocal: point(11, 2),
      entryShaftLocal: point(10, 3),
      entryDirection: "LEFT",
      returnAltarLocal: point(12, 2),
      arcVaultLocal: point(9, 2),
      coreLocal: point(11, 9),
      surfaceGate: point(231, 64),
      surfaceReturn: point(231, 64),
      requiredUpgradeId: "worldTwoTunnelAccess",
      partId: "eclipse-crucible",
      partLabel: "Eclipse Crucible",
      vaultId: "eclipse-omega-vault",
      componentAssetKey: "heavenblocks-eclipse-crucible-v1",
      heartAssetKey: "heavenblocks-eclipse-crucible-heart-v2",
      heartAssetPath: "sprites/backgrounds/heavenblocks-v1/eclipse-crucible-heart-v2.png",
      backdropKey: "heavenblocks-devil-eclipse-backdrop-v1",
      backdropPath: "sprites/backgrounds/heavenblocks-v1/devil-eclipse-backdrop-v1.png",
      tileStyle: {
        surfaceAssetSlots: ["obsidianHp5", "magmaCrystalHp5"],
        edgeAssetSlots: ["obsidianHp5", "lavaDirtHp5"],
        undersideAssetSlots: ["skyIslandUnder"],
        interiorAssetSlots: ["obsidianHp5", "lavaDirtHp5"],
        stylizedSurfaceTypeKeys: ["LAVA_DIRT"],
        surfaceTint: 0xffc2d5,
        edgeTint: 0xff7b9e,
        undersideTint: 0xe94f89,
        materialTint: 0xffd0d5,
        backdropAlpha: 0.8,
      },
      materialPalette: [
        { tileTypeKey: "LAVA_DIRT", weight: 38 },
        { tileTypeKey: "OBSIDIAN", weight: 34 },
        { tileTypeKey: "EMBER_ORE", weight: 18 },
        { tileTypeKey: "MAGMA_CRYSTAL", weight: 10 },
      ],
      materialHealthScale: 0.56,
      coreHealth: 2200,
    }),
  ],
});

export function getHeavenblockWorldRegion(regionId) {
  return HEAVENBLOCKS_WORLD_CONFIG.regions.find((entry) => entry.id === regionId) || null;
}

export function getHeavenblockCellDescriptor(tileX, tileY) {
  for (const entry of HEAVENBLOCKS_WORLD_CONFIG.regions) {
    const localX = tileX - entry.leftTile;
    const localY = tileY - entry.topTile;
    if (
      localX < 0
      || localY < 0
      || localX >= entry.widthTiles
      || localY >= entry.heightTiles
    ) continue;
    return {
      region: entry,
      localX,
      localY,
      marker: entry.layoutRows[localY]?.[localX] || HEAVENBLOCK_CELL_MARKERS.AIR,
    };
  }
  return null;
}
