export const HUD_QUICK_CONTROLS = Object.freeze({
  enabled: true,
  referenceViewport: Object.freeze({ width: 1280, height: 720 }),
  depthOffset: 4,
  inventory: Object.freeze({
    right: 14,
    bottom: 13,
    width: 94,
    height: 94,
    hitPadding: 4,
    keyOffsetX: 25,
    keyOffsetY: 21,
    keyFontSize: 15,
    keyColor: "#f6df9a",
    keyStroke: "#061019",
    keyStrokeThickness: 4,
    hoverAlpha: 0.86,
    pressScale: 0.96,
    pulseScale: 1.14,
    strongPulseScale: 1.24,
  }),
  pause: Object.freeze({
    right: 14,
    gapAboveInventory: 9,
    width: 154,
    height: 36,
    hitPaddingX: 5,
    hitPaddingY: 4,
    label: "{key}  MENU",
    fontSize: 13,
    color: "#f4e8c8",
    stroke: "#02060a",
    strokeThickness: 3,
    hoverAlpha: 0.86,
    pressScale: 0.97,
  }),
  motion: Object.freeze({
    pressMs: 70,
    pulseMs: 90,
  }),
});
