const soilSlot = (group, band, variant, label) => Object.freeze({
  group,
  band,
  variant,
  label,
});

export const INVENTORY_RESOURCE_GUIDE = Object.freeze({
  resourceKeys: Object.freeze([
    "dirt",
    "stone",
    "copper",
    "darkDirtNormal",
    "darkDirtStrong",
    "bronze",
    "steel",
    "iron",
    "silver",
    "gold",
    "lavaDirt",
    "obsidian",
    "emberOre",
    "magmaCrystal",
  ]),
  formationKeys: Object.freeze([
    "stone",
    "copper",
    "bronze",
    "steel",
    "iron",
    "silver",
    "gold",
    "obsidian",
    "emberOre",
    "magmaCrystal",
  ]),
  groundTypeIndices: Object.freeze({
    dirt: 0,
    darkDirtNormal: 1,
    darkDirtStrong: 2,
  }),
  descriptions: Object.freeze({
    dirt: "Loose natural soil and small stone fragments.",
    stone: "Pale fractured rock plates.",
    copper: "Copper seams with green patina.",
    darkDirtNormal: "Compact dark soil with a denser surface.",
    darkDirtStrong: "Reinforced hard soil with heavy dark ridges.",
    bronze: "Warm bronze shard fans.",
    iron: "Dark parallel iron bands.",
    steel: "Cool silver-blue needle bands.",
    silver: "Bright flowing silver seams.",
    gold: "Gold nodules joined by a rich vein.",
    lavaDirt: "Volcanic soil split by hot orange fissures.",
    obsidian: "Black glass shards with violet edges.",
    emberOre: "Charcoal ore packed with ember cores.",
    magmaCrystal: "Red-orange crystal spires in hot stone.",
  }),
  grounds: Object.freeze([
    soilSlot("bases", 0, 0, "0–200M GROUND"),
    soilSlot("bases", 2, 1, "400–600M GROUND"),
    soilSlot("bases", 4, 2, "800–1000M GROUND"),
    soilSlot("deepBases", 0, 2, "1000–1200M GROUND"),
    soilSlot("deepBases", 2, 0, "1400–1600M GROUND"),
    soilSlot("deepBases", 3, 4, "1600M+ GROUND"),
  ]),
  groundMaterialSlots: Object.freeze({
    dirt: Object.freeze([
      soilSlot("bases", 0, 0, "SHALLOW V1"),
      soilSlot("bases", 0, 1, "SHALLOW V2"),
      soilSlot("bases", 0, 2, "SHALLOW V3"),
      soilSlot("bases", 1, 0, "LOWER V1"),
      soilSlot("bases", 1, 1, "LOWER V2"),
      soilSlot("bases", 1, 2, "LOWER V3"),
    ]),
    darkDirtNormal: Object.freeze([
      soilSlot("bases", 2, 0, "DARK V1"),
      soilSlot("bases", 2, 1, "DARK V2"),
      soilSlot("bases", 2, 2, "DARK V3"),
      soilSlot("bases", 3, 0, "LOWER V1"),
      soilSlot("bases", 3, 1, "LOWER V2"),
      soilSlot("bases", 3, 2, "LOWER V3"),
    ]),
    darkDirtStrong: Object.freeze([
      soilSlot("bases", 4, 0, "HARD V1"),
      soilSlot("bases", 4, 1, "HARD V2"),
      soilSlot("bases", 4, 2, "HARD V3"),
      soilSlot("deepBases", 0, 0, "DEEP V1"),
      soilSlot("deepBases", 0, 1, "DEEP V2"),
      soilSlot("deepBases", 0, 2, "DEEP V3"),
    ]),
  }),
  lavaDirtStages: Object.freeze([
    Object.freeze({ stage: 5, label: "INTACT" }),
    Object.freeze({ stage: 4, label: "CHIPPED" }),
    Object.freeze({ stage: 3, label: "CRACKED" }),
    Object.freeze({ stage: 2, label: "DAMAGED" }),
    Object.freeze({ stage: 1, label: "NEAR BREAK" }),
  ]),
  copy: Object.freeze({
    inventoryTab: "HOLDINGS",
    guideTab: "RESOURCE CODEX",
    guideSubtitle: "Browse every material • inspect a clean specimen and your discovery record",
    selectorTitle: "CHOOSE A RESOURCE",
    selectorHint: "Every identity is always visible",
    formationArtLabel: "EXACT IN-GAME ART • 6 WORLD VARIANTS",
    groundArtLabel: "EXACT IN-GAME GROUND • 6 WORLD VARIANTS",
    damageArtLabel: "EXACT IN-GAME GROUND • 5 DIG STAGES",
    formationHint: "Production ground and approved resource layers, combined exactly as they appear in the mine.",
    groundHint: "These are the production ground textures used for this mineable material.",
    damageHint: "The same production tile shown from intact to near-break condition.",
  }),
  layout: Object.freeze({
    tabTopInset: 17,
    tabBodyGap: 42,
    tabSpacing: 150,
    tabButtonWidth: 140,
    tabButtonHeight: 30,
    desktopThreshold: 760,
    desktopSelectorWidth: 332,
    desktopSelectorColumns: 2,
    compactSelectorColumns: 5,
    panelGap: 14,
    panelPadding: 12,
    selectorHeaderHeight: 46,
    selectorGap: 7,
    previewHeaderHeight: 102,
    previewColumns: 3,
    previewGap: 10,
    previewLabelHeight: 18,
    maxPreviewTileSize: 132,
    maxSelectorThumbnailSize: 48,
  }),
});
