const asset = (key, path) => Object.freeze({ key, path });

const portraitFrames = Object.freeze({
  dirt: 0,
  stone: 1,
  copper: 2,
  darkDirtNormal: 3,
  darkDirtStrong: 4,
  bronze: 5,
  steel: 6,
  iron: 7,
  silver: 8,
  gold: 9,
  lavaDirt: 10,
  obsidian: 11,
  emberOre: 12,
  magmaCrystal: 13,
});

export const INVENTORY_CODEX_CONFIG = Object.freeze({
  assets: Object.freeze({
    foundation: asset(
      "resource-codex-foundation-v1",
      "sprites/UI/resource-codex-v1/resource-codex-foundation-v1.png?v=20260826b",
    ),
    portraits: Object.freeze({
      ...asset(
        "resource-dossier-atlas-v1",
        "sprites/UI/resource-codex-v1/resource-dossier-atlas-v1.png?v=20260826",
      ),
      widthPx: 1254,
      heightPx: 1254,
      columns: 4,
      rows: 4,
      cellInsetPx: 11,
      framePrefix: "resource-codex-portrait-",
      frameIndices: portraitFrames,
    }),
  }),
  copy: Object.freeze({
    title: "RESOURCE CODEX",
    subtitle: "See every material, its appearance, and whether you found it",
    collectionTitle: "MATERIALS",
    collectionHint: "14 MATERIALS • CHOOSE ONE",
    discovered: "FOUND",
    undiscovered: "NOT FOUND",
    fieldNotes: "FIELD NOTES",
    specimen: "MATERIAL",
    carried: "CARRIED",
    status: "STATUS",
    materialClass: "CLASS",
    entry: "ENTRY",
    navigationHint: "CHOOSE A MATERIAL • ARROWS / WASD TO MOVE",
  }),
  layout: Object.freeze({
    sourceWidthPx: 1738,
    sourceHeightPx: 905,
    aspectRatio: 1.920441989,
    maximumWidthPx: 900,
    selectorColumnCentersXPx: Object.freeze([257, 639]),
    selectorPortraitCentersXPx: Object.freeze([123, 505]),
    selectorTextLeftXPx: Object.freeze([171, 553]),
    selectorRowCentersYPx: Object.freeze([205, 296, 387, 478, 569, 659, 746]),
    selectorHitWidthPx: 372,
    selectorHitHeightPx: 78,
    selectorPortraitSizePx: 58,
    selectorNameOffsetYPx: -10,
    selectorStatusOffsetYPx: 10,
    selectorNameFontSizePx: 11,
    selectorStatusFontSizePx: 8,
    collectionTitleXPx: 312,
    collectionTitleYPx: 108,
    collectionCountXPx: 676,
    collectionCountYPx: 108,
    collectionTitleFontSizePx: 14,
    collectionCountFontSizePx: 9,
    navigationHintXPx: 447,
    navigationHintYPx: 827,
    navigationHintFontSizePx: 9,
    previewCenterXPx: 1028,
    previewCenterYPx: 259,
    previewSizePx: 314,
    nameCenterXPx: 1447,
    nameCenterYPx: 204,
    nameFontSizePx: 24,
    identityCenterYPx: 246,
    identityFontSizePx: 10,
    recordCenterXPx: 1447,
    recordCenterYPx: 350,
    recordFontSizePx: 12,
    notesCenterXPx: 1260,
    notesTitleYPx: 492,
    notesBodyYPx: 557,
    notesWidthPx: 760,
    notesTitleFontSizePx: 11,
    notesBodyFontSizePx: 13,
    statCentersXPx: Object.freeze([978, 1248, 1523]),
    statCenterYPx: 741,
    statFontSizePx: 13,
    selectedStrokeWidthPx: 4,
    selectedStrokeColor: 0xf2c96f,
    idlePortraitAlpha: 0.78,
    selectedPortraitAlpha: 1,
  }),
});

export function getInventoryCodexPreloadAssets(
  config = INVENTORY_CODEX_CONFIG,
) {
  return Object.freeze([
    config.assets.foundation,
    config.assets.portraits,
  ]);
}
