export const INVENTORY_SPECIAL_BLOCKS = Object.freeze({
  tabLabel: "SPECIAL BLOCKS",
  subtitle: "See each special block's effect and when to mine it",
  selectorTitle: "CHOOSE A BLOCK",
  detailTitle: "EFFECT",
  useTitle: "WHEN TO USE IT",
  entries: Object.freeze([
    Object.freeze({ id: "gemPowerBlock", renderKey: "GEM_POWER_BLOCK", name: "Gem Power Block", rarity: "RARE", color: "#c88cff", effect: "Restores GP instantly. The restored amount grows at deeper tiers.", use: "Mine it when your GP reserve is low; it does not create a timed buff." }),
    Object.freeze({ id: "speedBlock", renderKey: "SPEED_BLOCK", name: "Speed Block", rarity: "VERY RARE", color: "#ffd76b", effect: "+50% mining speed for 20 seconds. Multiple boosts can stack.", use: "Best used before a dense route or timed objective." }),
    Object.freeze({ id: "xpBlock", renderKey: "XP_BLOCK", name: "XP Block", rarity: "RARE", color: "#fff36b", effect: "Grants 10% progress toward your next player level.", use: "The progress is immediate and can trigger a level-up." }),
    Object.freeze({ id: "berserkBlock", renderKey: "BERSERK_BLOCK", name: "Berserk Block", rarity: "VERY RARE", color: "#ff6d8b", effect: "+50% mining damage for 20 seconds. Multiple boosts can stack.", use: "Pairs well with a speed boost on hard materials." }),
    Object.freeze({ id: "comboBlock", renderKey: "COMBO_BLOCK", name: "Combo Block", rarity: "RARE", color: "#bcecff", effect: "Adds 50 combo immediately.", use: "Opening any UI pauses the combo timer; the added combo is safe in menus." }),
    Object.freeze({ id: "legendBlock", renderKey: "LEGEND_BLOCK", name: "Crown Block", rarity: "ULTRA RARE", color: "#f2c96b", effect: "Grants one complete player level and carries your existing progress forward.", use: "Its gold corona marks one of the rarest rewards in the world." }),
    Object.freeze({ id: "abilityBlock", renderKey: "ABILITY_BLOCK", name: "Ability Block", rarity: "MYTHIC", color: "#c69bff", effect: "Choose any action-bar power. It is unlocked and costs no GP for 20 seconds.", use: "Mining pauses at the choice; click a power or press its action-bar number, then change how you dig." }),
  ]),
  layout: Object.freeze({
    desktopThresholdPx: 760,
    selectorWidthPx: 330,
    panelGapPx: 14,
    panelPaddingPx: 14,
    selectorHeaderHeightPx: 42,
    selectorGapPx: 7,
    previewTileSizePx: 164,
    previewTileCompactSizePx: 104,
    detailTextWidthInsetPx: 34,
  }),
});
