export const JOURNEY_EVENT_TYPES = Object.freeze({
  UPGRADE: "upgrade",
  DEPTH: "depth",
  DEPTH_GATE: "depthGate",
  PORTAL: "portal",
  CAMPFIRE: "campfire",
  RELIC: "relic",
  CONSTELLATION: "constellation",
  HEAVENBLOCK: "heavenblock",
  FORGE: "forge",
  TITAN: "titan",
  JACKPOT: "jackpot",
  LEVEL: "level",
});
export const JOURNEY_CONFIG = Object.freeze({
  saveVersion: 1,
  maxStoredEvents: 24,
  maxVisibleHistory: 4,
  maxVisibleGoals: 3,
  pollIntervalMs: 250,
  playerLevelMilestones: Object.freeze([2, 3, 4, 6, 11]),
  copy: Object.freeze({
    tabLabel: "JOURNEY",
    buildTitle: "CURRENT BUILD",
    buildSubtitle: "Exact permanent values used by gameplay",
    goalsTitle: "NEXT THREADS",
    historyTitle: "WHAT CHANGED",
    emptyGoals: "No immediate thread is blocked. Keep shaping the build.",
    emptyHistory: "Permanent upgrades and milestones will be recorded here.",
    progressSeparator: " / ",
    starterPickaxe: "Starter Pickaxe",
  }),
  layout: Object.freeze({
    sectionLabelHeight: 20,
    buildCardHeight: 82,
    buildCardGap: 8,
    buildBottomGap: 14,
    columnGap: 12,
    goalsWidthRatio: 0.59,
    goalCardGap: 7,
    historyCardGap: 7,
    cardInset: 12,
  }),
  eventCopy: Object.freeze({
    depthTitle: "Depth milestone",
    depthDetail: "A deeper layer now connects to new materials, routes, and upgrades.",
    gateTitle: "Depth gate accepted",
    gateDetail: "The next progression layer is now part of this save.",
    portalTitle: "Return route activated",
    portalDetail: "This descent now has a reusable route through the Sky Island.",
    campfireTitle: "Campfire improved",
    campfireDetail: "Town spending now strengthens future mining blessings.",
    relicTitle: "Ancient Relic total",
    relicDetail: "Relics feed Heavenblock and Arc Forge requirements.",
    constellationTitle: "Constellation unlocked",
    constellationDetail: "Collected stars became a permanent ability bonus.",
    heavenblockTitle: "Heavenblock installed",
    heavenblockDetail: "A World Two discovery is now connected to the Arc Forge.",
    vaultTitle: "Arc Vault reopened",
    vaultDetail: "Vault progress feeds the Zenith Keystone.",
    titanTitle: "Titan discovered",
    titanDetail: "A purchased clue has resolved into a permanent discovery.",
    levelTitle: "Player level milestone",
    levelDetail: "Level bonuses now support the permanent build.",
    forgeDetail: "Separated progression requirements converged into one crafted unlock.",
    upgradeDetail: "A shop purchase changed a permanent gameplay value.",
  }),
});

export const JOURNEY_UPGRADE_STAT_MAP = Object.freeze({
  walkSpeed: Object.freeze({
    statKey: "movementSpeedPxPerSec",
    label: "Movement Speed",
    unit: "px/s",
    precision: 0,
  }),
  digDamageAdditive: Object.freeze({
    effectKey: "digDamageAdditive",
    label: "Mining Power Bonus",
    unit: "",
    precision: 0,
  }),
  mineCooldownReduction: Object.freeze({
    statKey: "mineCooldownMs",
    label: "Mining Cooldown",
    unit: "ms",
    precision: 0,
  }),
  gemPowerMax: Object.freeze({
    statKey: "gemPowerMax",
    label: "Gem Power Capacity",
    unit: "GP",
    precision: 0,
  }),
  gemPowerDrainReduction: Object.freeze({
    effectKey: "gemPowerDrainReduction",
    label: "Flight Drain Reduction",
    unit: "GP/s",
    precision: 1,
  }),
  gemPowerRegenIncrease: Object.freeze({
    effectKey: "gemPowerRegenIncrease",
    label: "Gem Power Regeneration",
    unit: "GP/s",
    precision: 1,
  }),
  torchDrainReduction: Object.freeze({
    effectKey: "torchDrainReduction",
    label: "Torch Drain Reduction",
    unit: "GP/s",
    precision: 1,
  }),
  torchBonusRadius: Object.freeze({
    effectKey: "torchBonusRadius",
    label: "Torch Vision Radius",
    unit: "tiles",
    precision: 1,
  }),
  levitationSpeed: Object.freeze({
    statKey: "flightSpeedPxPerSec",
    label: "Flight Speed",
    unit: "px/s",
    precision: 0,
  }),
});
