export const JOURNEY_EVENT_TYPES = Object.freeze({
  UPGRADE: "upgrade",
  DEPTH: "depth",
  DEPTH_GATE: "depthGate",
  PORTAL: "portal",
  CAMPFIRE: "campfire",
  RELIC: "relic",
  CONSTELLATION: "constellation",
  HEAVENBLOCK: "heavenblock",
  FORGE: "forge",
  TITAN: "titan",
  JACKPOT: "jackpot",
  LEVEL: "level",
});
export const JOURNEY_CONFIG = Object.freeze({
  saveVersion: 1,
  maxStoredEvents: 24,
  maxVisibleHistory: 4,
  maxVisibleGoals: 3,
  pollIntervalMs: 250,
  playerLevelMilestones: Object.freeze([2, 3, 4, 6, 11]),
  copy: Object.freeze({
    tabLabel: "JOURNEY",
    buildTitle: "YOUR UPGRADES",
    buildSubtitle: "Permanent stats that carry into every expedition",
    goalsTitle: "WHAT TO DO NEXT",
    historyTitle: "RECENT PROGRESS",
    emptyGoals: "No urgent goal right now. Choose a route and keep digging.",
    emptyHistory: "Your upgrades and milestones will appear here.",
    progressSeparator: " / ",
    starterPickaxe: "Starter Pickaxe",
  }),
  layout: Object.freeze({
    sectionLabelHeight: 20,
    buildCardHeight: 82,
    buildCardGap: 8,
    buildBottomGap: 14,
    columnGap: 12,
    goalsWidthRatio: 0.59,
    goalCardGap: 7,
    historyCardGap: 7,
    cardInset: 12,
  }),
  eventCopy: Object.freeze({
    depthTitle: "Depth milestone",
    depthDetail: "You reached a new layer with more materials, routes, and upgrades.",
    gateTitle: "Depth gate accepted",
    gateDetail: "The next depth range is now open on this save.",
    portalTitle: "Return route activated",
    portalDetail: "You can now reuse this Sky Island route.",
    campfireTitle: "Campfire improved",
    campfireDetail: "Your Campfire now grants stronger mining blessings.",
    relicTitle: "Ancient Relic total",
    relicDetail: "Relics feed Heavenblock and Arc Forge requirements.",
    constellationTitle: "Constellation unlocked",
    constellationDetail: "Your collected Stars unlocked a permanent ability bonus.",
    heavenblockTitle: "Heavenblock installed",
    heavenblockDetail: "This World Two discovery is ready at the Arc Forge.",
    vaultTitle: "Arc Vault reopened",
    vaultDetail: "Vault progress feeds the Zenith Keystone.",
    titanTitle: "Titan discovered",
    titanDetail: "A purchased clue has resolved into a permanent discovery.",
    levelTitle: "Player level milestone",
    levelDetail: "Your new level added permanent bonuses.",
    forgeDetail: "You combined the required discoveries into one crafted unlock.",
    upgradeDetail: "A shop purchase permanently improved your miner.",
  }),
});

export const JOURNEY_UPGRADE_STAT_MAP = Object.freeze({
  walkSpeed: Object.freeze({
    statKey: "movementSpeedPxPerSec",
    label: "Movement Speed",
    unit: "px/s",
    precision: 0,
  }),
  digDamageAdditive: Object.freeze({
    effectKey: "digDamageAdditive",
    label: "Mining Power Bonus",
    unit: "",
    precision: 0,
  }),
  mineCooldownReduction: Object.freeze({
    statKey: "mineCooldownMs",
    label: "Mining Cooldown",
    unit: "ms",
    precision: 0,
  }),
  gemPowerMax: Object.freeze({
    statKey: "gemPowerMax",
    label: "Gem Power Capacity",
    unit: "GP",
    precision: 0,
  }),
  gemPowerCostReduction: Object.freeze({
    effectKey: "gemPowerCostReduction",
    label: "All GP Costs Reduced",
    unit: "%",
    precision: 0,
    multiplier: 100,
  }),
  gemPowerRegenIncrease: Object.freeze({
    effectKey: "gemPowerRegenIncrease",
    label: "Gem Power Regeneration",
    unit: "GP/s",
    precision: 1,
  }),
  torchDrainReduction: Object.freeze({
    effectKey: "torchDrainReduction",
    label: "Torch Drain Reduction",
    unit: "GP/s",
    precision: 1,
  }),
  torchBonusRadius: Object.freeze({
    effectKey: "torchBonusRadius",
    label: "Torch Vision Radius",
    unit: "tiles",
    precision: 1,
  }),
  levitationSpeed: Object.freeze({
    statKey: "flightSpeedPxPerSec",
    label: "Flight Speed",
    unit: "px/s",
    precision: 0,
  }),
});
