export const LEVEL_UP_PRESENTATION = Object.freeze({
  referenceViewport: Object.freeze({ width: 1280, height: 720 }),
  width: 620,
  height: 116,
  centerYRatio: 0.24,
  minimumScale: 0.72,
  maximumScale: 1,
  depth: 2400,
  iconX: -262,
  iconY: 0,
  iconSize: 72,
  textOffsetX: 43,
  textWidth: 490,
  titleY: -25,
  panicY: 3,
  rewardY: 26,
  titleFontSize: 23,
  panicFontSize: 17,
  rewardFontSize: 13,
  entryScale: 0.86,
  emphasisScale: 1.018,
  entryOffsetYPx: 24,
  enterMs: 260,
  emphasisMs: 180,
  holdMs: 2500,
  exitMs: 320,
  exitOffsetYPx: 18,
  colors: Object.freeze({
    title: "#f0c765",
    panic: "#65d8f2",
    reward: "#f4e8c8",
  }),
  copy: Object.freeze({
    level: "LEVEL",
    reached: "REACHED",
    levels: "LEVELS",
    talentPoint: "TALENT POINT",
    talentPoints: "TALENT POINTS",
    panicResistance: "PANIC RESISTANCE",
    total: "TOTAL",
    miningPower: "MINING POWER",
    maxGemPower: "MAX GP",
    gemPowerRefilled: "GP REFILLED",
    separator: "  •  ",
  }),
});
