export const LEVEL_UP_PRESENTATION = Object.freeze({
  referenceViewport: Object.freeze({ width: 1280, height: 720 }),
  width: 620,
  height: 132,
  centerYRatio: 0.24,
  minimumScale: 0.72,
  maximumScale: 1,
  depth: 1105,
  textOffsetX: 49,
  titleY: -35,
  darknessY: 0,
  rewardY: 31,
  titleFontSize: 23,
  darknessFontSize: 17,
  rewardFontSize: 13,
  entryScale: 0.86,
  emphasisScale: 1.018,
  entryOffsetYPx: 24,
  enterMs: 260,
  emphasisMs: 180,
  holdMs: 2500,
  exitMs: 320,
  exitOffsetYPx: 18,
  colors: Object.freeze({
    title: "#f0c765",
    darkness: "#65d8f2",
    reward: "#f4e8c8",
  }),
  copy: Object.freeze({
    level: "LEVEL",
    reached: "REACHED",
    levels: "LEVELS",
    darknessResistance: "DARKNESS RESISTANCE",
    total: "TOTAL",
    miningPower: "MINING POWER",
    maxGemPower: "MAX GP",
    gemPowerRefilled: "GP REFILLED",
    separator: "  •  ",
  }),
});
