// Review-only tuning. Production scheduling remains owned by npcActivityConfig.
export const MERCHANT_IDLE_PERSONALITY = Object.freeze({
  cycleSeconds: 12,
  actionSeconds: 6.8,
  firstActivity: 1.1,
  naturalStagger: 1.22,
  previewStagger: 0.12,
  fadeInStart: 0.24,
  fadeInSeconds: 0.18,
  fadeOutStart: 4.9,
  fadeOutSeconds: 0.22,
  groundFraction: 0.91,
  detailFit: 0.94,
  paneFit: 0.98,
  maxPixelRatio: 2,
  maxDeltaSeconds: 0.1,
  infoIntervalMs: 150,
  fpsIntervalMs: 1000,
  millisecondsPerSecond: 1000,
  scrubEndEpsilon: 0.001,
  activeLabelThreshold: 0.02,
  poseBodyAngle: 0.16,
  poseBodyLift: 1.05,
  poseHeadAngle: 0.38,
  poseHeadLift: 0.65,
  activityPath: '/sprites/npc/npc-v13-piskel-polished-activities/singles/',
  baselinePath: '/sprites/npc/npc-v13-polished-baselines/static/',
  activities: Object.freeze([
    { id: 'habit', label: 'Little habits' },
    { id: 'signature', label: 'Signature pose' },
    { id: 'player', label: 'Greeting' },
    { id: 'work', label: 'At work' },
    { id: 'inspect', label: 'Inspecting' },
    { id: 'showcase', label: 'Showing off' },
    { id: 'rare', label: 'Rare flourish' },
  ]),
});
