// Milestone Pillar modal layout and typography.

export const MILESTONE_PILLAR_UI = Object.freeze({
  modal: Object.freeze({
    title: "MILESTONE PILLAR",
    subtitle: "Your depth rewards, mining record, and discoveries",
    maxWidth: 1080,
    maxHeight: 690,
    // Keep this read-heavy modal above earthquake, tutorial, and timing HUDs.
    depth: 4000,
    tabTopInset: 22,
    tabHeight: 42,
    tabGap: 12,
    viewTopOffset: 70,
  }),
  milestones: Object.freeze({
    wideLayoutMinWidth: 760,
    twoColumnMinWidth: 560,
    tallLayoutMinHeight: 390,
    summaryRailWidth: 232,
    summaryGap: 14,
    compactSummaryHeight: 104,
    cardGap: 10,
    wideRows: 4,
    shortRows: 3,
    footerHeight: 48,
    pageButtonWidth: 110,
    pageButtonHeight: 34,
    pageButtonEdgeInset: 56,
    summaryInset: 16,
    summaryLineGap: 22,
    cardInsetX: 14,
    cardInsetY: 11,
    cardRadius: 7,
    depthBadgeWidth: 72,
    statusWidth: 92,
    progressBarHeight: 8,
    fonts: Object.freeze({
      section: "15px",
      depth: "20px",
      cardDepth: "17px",
      cardTitle: "14px",
      reward: "12px",
      status: "11px",
      body: "12px",
      detail: "11px",
      page: "12px",
    }),
  }),
  journal: Object.freeze({
    wideLayoutMinWidth: 700,
    panelGap: 14,
    wideLeftRatio: 0.48,
    inset: 18,
    rowHeight: 33,
    compactRowHeight: 27,
    compactStatsColumns: 2,
    recentWideLimit: 9,
    recentCompactLimit: 4,
    fonts: Object.freeze({
      section: "16px",
      label: "11px",
      value: "14px",
      body: "12px",
      detail: "11px",
    }),
  }),
});
