// Review-only milestone pillar art directions and Phaser presentation values.

export const MILESTONE_PILLAR_REVIEW = Object.freeze({
  reviewOnly: true,
  productionChanged: false,
  manifestPath: "stage-manifest.json",
  gameplayBackgroundPath: "../village-floor-concepts-v1/04-option-a-wired-runtime.png",
  defaultOptionId: "a",
  defaultStageIndex: 4,
  stageDepths: Object.freeze([0, 400, 800, 1200, 1600]),
  stageLabels: Object.freeze([
    "SHALLOW START",
    "400M STRATA",
    "800M DEEPWORKS",
    "1200M ABYSS",
    "1600-2000M CROWN",
  ]),
  options: Object.freeze([
    Object.freeze({
      id: "a",
      label: "CARVED SLATE",
      title: "Carved Slate Depth Chronicle",
      summary: "Village-readable stonework; each descent adds a permanent brass depth ring.",
      accent: 0x62c9dc,
    }),
    Object.freeze({
      id: "b",
      label: "LIVING CRYSTAL",
      title: "Living Crystal Strata",
      summary: "The pillar becomes a geological record as new mineral bands awaken.",
      accent: 0x7cc9ff,
    }),
    Object.freeze({
      id: "c",
      label: "DEPTH ENGINE",
      title: "Dwarven Depth Engine",
      summary: "A practical brass recorder upgraded into a monumental mining machine.",
      accent: 0xd6a84a,
    }),
    Object.freeze({
      id: "d",
      label: "ROOT RUNE",
      title: "Ancient Root Rune Cairn",
      summary: "Old roots claim each new carved tier while buried star runes relight.",
      accent: 0xe0a94c,
    }),
    Object.freeze({
      id: "e",
      label: "STARFORGE",
      title: "Starforge Abyss Obelisk",
      summary: "A severe basalt monument unlocks star-metal layers and an abyss crown.",
      accent: 0xb6eaff,
    }),
  ]),
  worldPreview: Object.freeze({
    backgroundAlpha: 0.72,
    detailPillarX: 282,
    detailGroundY: 438,
    detailMaxPillarHeight: 330,
    worldPillarX: 654,
    worldGroundY: 394,
    worldMaxPillarHeight: 94,
    playerGuideX: 584,
    playerHeightPx: 75,
    controlsTop: 18,
    optionButtonWidth: 170,
    optionButtonHeight: 38,
    optionButtonGap: 10,
    stageButtonWidth: 156,
    stageButtonHeight: 38,
    stageButtonGap: 8,
    stageControlsY: 667,
    titleX: 530,
    titleY: 104,
    summaryWidth: 650,
    summaryY: 145,
    openUiX: 1040,
    openUiY: 660,
  }),
});
