const runtime = (file, frameCount, columns, fps, frames = null) => Object.freeze({
  file, frameCount, columns, fps, frames,
  frameWidth: 256,
  frameHeight: 256,
});

const candidate = (id, category, role, mode, current, name, description, motionId, rationale, risks = []) => Object.freeze({
  id, category, role, mode, current, name, description, motionId, rationale,
  risks: Object.freeze(risks),
  thumbnail: `https://d99n9xvb9513w.cloudfront.net/thumbnails/motions/${motionId}/animated.gif`,
});

export const MIXAMO_REPLACEMENT_REVIEW = Object.freeze({
  version: "mixamo-current-role-review-v1-20260819",
  reviewOnly: true,
  productionChanged: false,
  storageKey: "dig-game-mixamo-current-role-review-v1",
  verdicts: Object.freeze(["accept", "maybe", "reject"]),
  defaultVerdict: "unreviewed",
  categories: Object.freeze([
    Object.freeze({ id: "flight", label: "Flight and descent" }),
    Object.freeze({ id: "locomotion", label: "Ground locomotion" }),
    Object.freeze({ id: "mining", label: "Mining and strikes" }),
    Object.freeze({ id: "states", label: "Idle and crouch" }),
    Object.freeze({ id: "abilities", label: "Abilities and wall" }),
    Object.freeze({ id: "reactions", label: "Reactions and death" }),
  ]),
  stage: Object.freeze({
    canvasWidthPx: 260,
    canvasHeightPx: 240,
    displaySizePx: 188,
    runtimeDisplaySizePx: 109,
    groundYRatio: 0.88,
    originX: 0.5,
    originY: 0.96484375,
    maxDeltaMs: 80,
  }),
  current: Object.freeze({
    idle: runtime("../../../sprites/character/survival-character-blender-v2/runtime/survival-character-blender-v2-idle-sheet.png", 48, 16, 12),
    run: runtime("../../../sprites/character/survival-ual-player-v1/runtime/survival-ual-player-v1-animation-polish-run-sheet.webp", 28, 16, 30),
    walkStart: runtime("../../../sprites/character/survival-ual-player-v1/runtime/survival-ual-player-v1-animation-polish-transitions-sheet.webp", 2, 16, 30, [0, 1]),
    walkStop: runtime("../../../sprites/character/survival-ual-player-v1/runtime/survival-ual-player-v1-animation-polish-transitions-sheet.webp", 2, 16, 30, [2, 3]),
    flight: runtime("../../../sprites/character/survival-character-blender-v2/runtime/survival-character-blender-v2-superman-flight-prone-v3-sheet.png", 36, 12, 16),
    landing: runtime("../../../sprites/character/survival-ual-player-v1/runtime/survival-ual-player-v1-animation-polish-transitions-sheet.webp", 14, 16, 40, [43,44,45,46,47,48,49,50,51,52,53,54,55,56]),
    crouch: runtime("../../../sprites/character/survival-ual-player-v1/runtime/survival-ual-player-v1-crouch-sheet.webp", 88, 16, 30),
    digSide: runtime("../../../sprites/character/survival-ual-player-v1/runtime/survival-ual-player-v1-punch-jab-sheet.webp", 27, 16, 30),
    digUp: runtime("../../../sprites/character/survival-character-blender-v2/runtime/survival-character-blender-v2-dig-up-piskel-polished-sheet.png", 24, 16, 27),
    digDown: runtime("../../../sprites/character/survival-ual-player-v1/runtime/survival-ual-player-v1-ground-strike-sheet.webp", 41, 16, 30),
    wallPush: runtime("../../../sprites/character/survival-ual-player-v1/runtime/survival-ual-player-v1-animation-polish-transitions-sheet.webp", 16, 16, 30, [60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75]),
    thunder: runtime("../../../sprites/character/survival-ual-player-v1/runtime/survival-ual-player-v1-thunder-charge-sheet.webp", 63, 16, 30),
    teleport: runtime("../../../sprites/character/survival-ual-player-v1/runtime/survival-ual-player-v1-teleport-sheet.webp", 45, 16, 30),
    hit: runtime("../../../sprites/character/survival-ual-player-v1/runtime/survival-ual-player-v1-hit-react-sheet.webp", 11, 11, 30),
    death: runtime("../../../sprites/character/survival-ual-player-v1/runtime/survival-ual-player-v1-death-sheet.webp", 73, 16, 30),
  }),
  candidates: Object.freeze([
    candidate("flight-hover", "flight", "Flight hover/travel loop", "replacement", "flight", "Flying", "Flying Idle", "111080901", "Directly tests the user-selected relaxed airborne loop against the current prone Superman pose.", ["retarget", "loop-seam", "facing"]),
    candidate("flight-exit", "flight", "Flight exit into descent", "addition", "landing", "Jumping Down", "Jumping Down From Falling Idle Game Blend", "118110905", "A game-blend transition that can bridge flight into falling or landing without adding a jump mechanic.", ["root-motion", "no-jump", "contact"]),
    candidate("hard-landing", "flight", "Hard landing", "replacement", "landing", "Jumping Down", "Jumping Down From Higher Level", "135970901", "A stronger impact and recovery candidate for the existing hard-landing state.", ["root-motion", "contact", "scale"]),
    candidate("walk-start", "locomotion", "Idle to movement", "replacement", "walkStart", "Start Walking", "Walking From Standing", "135950901", "Replaces the current two-frame visual bridge with an authored weight transfer.", ["root-motion", "foot-lock", "timing"]),
    candidate("walk-stop", "locomotion", "Movement to idle", "replacement", "walkStop", "Stop Walking", "Walking To Standing Idle", "136220901", "Adds a real planted slowdown instead of the current two-frame stop bridge.", ["root-motion", "foot-lock", "phase-match"]),
    candidate("run-loop", "locomotion", "Ground movement loop", "replacement", "run", "Unarmed Run Forward", "Running Forward", "128650943", "A clean unarmed forward run that can be stride-matched to gameplay speed.", ["root-motion", "stride", "loop-seam"]),
    candidate("dig-side-horizontal", "mining", "Side mining hit", "replacement", "digSide", "Standing Melee Attack Horizontal", "Right To Left Attack With Axe", "128650913", "The axe arc matches a side tile better than the current jab-shaped mining hit.", ["prop-hands", "contact", "facing"]),
    candidate("dig-down", "mining", "Down mining hit", "replacement", "digDown", "Standing Melee Attack Downward", "Downward Attack With Axe", "128650912", "Purpose-built downward tool mechanics are closer to mining than the current overhand throw source.", ["prop-hands", "contact", "pelvis"]),
    candidate("dig-up", "mining", "Up mining hit", "replacement", "digUp", "Standing Melee Attack Backhand", "Backhanded Upward Attack With Axe", "128650911", "The rising backhand arc can become an upward pickaxe strike while keeping the feet planted.", ["prop-hands", "contact", "wrist"]),
    candidate("dig-combo-two", "mining", "Two-hit held mining chain", "addition", "digSide", "Standing Melee Combo Attack Ver. 1", "Two Hit Combo Attack With Axe", "128650918", "A native two-hit tool chain may remove the reset between repeated mining hits.", ["prop-hands", "multi-contact", "timing"]),
    candidate("dig-combo-three", "mining", "Three-hit held mining chain", "addition", "digSide", "Standing Melee Combo Attack Ver. 2", "Three Hit Combo Attack With Axe", "128650919", "A native three-hit chain is a direct candidate for the existing repeated-hit combo selector.", ["prop-hands", "multi-contact", "cooldown"]),
    candidate("idle-fidget", "states", "Idle fidget", "addition", "idle", "Unarmed Idle Looking Ver. 1", "Looking Around", "128650938", "Adds restrained observation without changing the approved main idle.", ["loop-seam", "frequency"]),
    candidate("crouch-idle", "states", "Crouch/duck hold", "replacement", "crouch", "Crouch Idle", "Crouch Idle", "128670901", "A neutral crouch without rifle posture is a cleaner replacement candidate.", ["scale", "hitbox"]),
    candidate("crouch-enter", "states", "Standing to crouch", "addition", "crouch", "Standing Idle To Crouch", "Transition From Standing Idle To Crouch Idle", "128670929", "Adds the missing authored entry into the existing crouch state.", ["timing", "hitbox-handoff"]),
    candidate("crouch-exit", "states", "Crouch to standing", "addition", "crouch", "Crouch To Standing Idle", "Transition From Crouch To Standing Idle", "128670902", "Adds a matched recovery instead of snapping from crouch to idle.", ["timing", "hitbox-handoff"]),
    candidate("wall-push", "abilities", "Wall brace/push loop", "replacement", "wallPush", "Pushing", "Pushing A Heavy Object", "118350902", "The sustained two-hand weight transfer directly matches the wall-push role.", ["hand-contact", "loop-seam", "pelvis"]),
    candidate("thunder-ground", "abilities", "Thunder ground strike", "replacement", "thunder", "Standing 2H Magic Area Attack 01", "Two Handed Casting Spell Towards Ground", "128670914", "A two-hand ground-directed cast better supports the current thunder impact.", ["contact", "effect-sync"]),
    candidate("teleport-roll", "abilities", "Teleport roll", "replacement", "teleport", "Stand To Roll", "Dive Roll From Standing", "118140901", "A compact standing-to-roll candidate can replace the current generic roll while preserving the same ability role.", ["root-motion", "collider", "facing"]),
    candidate("hit-front", "reactions", "General hit reaction", "replacement", "hit", "Hit Reaction", "Hit Reaction", "113860902", "A neutral impact response can replace the very short current chest-hit clip.", ["timing", "recovery"]),
    candidate("hit-left", "reactions", "Directional hit from left", "addition", "hit", "Reaction", "Male Reaction Hit On The Left Side", "100540901", "Adds directionality without changing damage or knockback authority.", ["facing", "recovery"]),
    candidate("hit-right", "reactions", "Directional hit from right", "addition", "hit", "Reaction", "Male Reaction Hit On The Right Side", "100530901", "Pairs with the left reaction for readable directional feedback.", ["facing", "recovery"]),
    candidate("death", "reactions", "Death", "replacement", "death", "Death", "Death From Standing Idle", "116070901", "A neutral standing death candidate avoids weapon-specific posture and can be compared cleanly with current.", ["ground-contact", "final-pose"]),
  ]),
});
