const frameRange = (from, to) => Object.freeze({ from, to });

const motion = ({ id, label, role, category = "Punch", fileName, frames, contacts, comboRange }) => Object.freeze({
  id,
  label,
  role,
  category,
  file: `../../blender-animation-lab-v1/review-drafts/mixamo-punch-sequence-sandbox-v1/renders/candidate/${fileName}`,
  sheet: `../../blender-animation-lab-v1/review-drafts/mixamo-punch-sequence-sandbox-v1/renders/candidate/survival-mixamo-punch-v1-${id}-sheet.png`,
  frames,
  columns: 16,
  frameWidth: 256,
  frameHeight: 256,
  fps: 30,
  contacts: Object.freeze(contacts),
  comboRange: Object.freeze(comboRange),
});

const segment = (clip, from, to, holdAfterFrames = 0) => Object.freeze({
  clip,
  from,
  to,
  holdAfterFrames,
});

const current = (id, file, frames, fps, contacts) => Object.freeze({
  id,
  label: `Current ${id}`,
  role: "Current runtime comparison",
  sheet: file,
  frames,
  columns: 16,
  frameWidth: 256,
  frameHeight: 256,
  fps,
  contacts: Object.freeze(contacts),
  comboRange: frameRange(0, frames - 1),
});

export const MIXAMO_PUNCH_SEQUENCE_REVIEW = Object.freeze({
  version: "mixamo-punch-sequence-review-v1-20260819",
  reviewOnly: true,
  productionChanged: false,
  storageKey: "dig-game-mixamo-punch-sequence-review-v1",
  verdicts: Object.freeze(["accept", "maybe", "reject"]),
  stage: Object.freeze({
    canvasWidthPx: 338,
    canvasHeightPx: 286,
    reviewDisplaySizePx: 218,
    gameDisplaySizePx: 109,
    groundYpx: 246,
    characterXpx: 142,
    originX: 0.5,
    originY: 0.89,
    tileSizePx: 94,
    colliderWidthPx: 31,
    colliderHeightPx: 75,
    maximumDeltaMs: 80,
  }),
  current: Object.freeze({
    side: current(
      "side",
      "../../../sprites/character/survival-ual-player-v1/runtime/survival-ual-player-v1-punch-jab-sheet.webp",
      27,
      30,
      [7]
    ),
    up: current(
      "up",
      "../../../sprites/character/survival-character-blender-v2/runtime/survival-character-blender-v2-dig-up-piskel-polished-sheet.png",
      24,
      27,
      [6]
    ),
    down: current(
      "down",
      "../../../sprites/character/survival-ual-player-v1/runtime/survival-ual-player-v1-ground-strike-sheet.webp",
      41,
      30,
      [14]
    ),
  }),
  motions: Object.freeze([
    motion({ id: "jab", label: "Jab Punch", role: "Fast opener", fileName: "jab.gif", frames: 18, contacts: [9], comboRange: frameRange(3, 13) }),
    motion({ id: "cross", label: "Cross Punch", role: "Power follow-up", fileName: "cross.gif", frames: 18, contacts: [10], comboRange: frameRange(3, 14) }),
    motion({ id: "hook", label: "Hook Punch", role: "Rotational finisher", fileName: "hook.gif", frames: 22, contacts: [11], comboRange: frameRange(4, 17) }),
    motion({ id: "uppercut", label: "Uppercut", role: "UP strike", fileName: "uppercut.gif", frames: 24, contacts: [17], comboRange: frameRange(3, 19) }),
    motion({ id: "body-low", label: "Low Body Punch", role: "DOWN strike", fileName: "body-low.gif", frames: 24, contacts: [12], comboRange: frameRange(2, 18) }),
    motion({ id: "jab-cross", label: "Boxing Jab–Cross", role: "Native two-hit chain", fileName: "jab-cross.gif", frames: 30, contacts: [9, 20], comboRange: frameRange(0, 29) }),
    motion({ id: "four-combo", label: "Four-Punch Combo", role: "Native four-hit rhythm", fileName: "four-combo.gif", frames: 44, contacts: [12, 17, 22, 26], comboRange: frameRange(0, 43) }),
    motion({ id: "eight-combo", label: "Eight-Punch Combo", role: "Rapid pressure chain", fileName: "eight-combo.gif", frames: 29, contacts: [4, 7, 10, 13, 16, 19, 22, 25], comboRange: frameRange(0, 28) }),
    motion({ id: "boxing-lead-jab", label: "Boxing Lead Jab", role: "Alternate compact opener", category: "Boxing", fileName: "boxing-lead-jab.gif", frames: 18, contacts: [9], comboRange: frameRange(3, 13) }),
    motion({ id: "boxing-back-cross", label: "Boxing Back Cross", role: "Rear-hand power variant", category: "Boxing", fileName: "boxing-back-cross.gif", frames: 20, contacts: [10], comboRange: frameRange(3, 15) }),
    motion({ id: "boxing-lead-hook", label: "Boxing Lead Hook", role: "Short rotational connector", category: "Boxing", fileName: "boxing-lead-hook.gif", frames: 20, contacts: [10], comboRange: frameRange(3, 15) }),
    motion({ id: "boxing-back-uppercut", label: "Boxing Back Uppercut", role: "Rising rear-hand finisher", category: "Boxing", fileName: "boxing-back-uppercut.gif", frames: 22, contacts: [13], comboRange: frameRange(3, 17) }),
    motion({ id: "elbow-single", label: "Single Elbow", role: "Short-range heavy contact", category: "Elbow", fileName: "elbow-single.gif", frames: 18, contacts: [10], comboRange: frameRange(3, 13) }),
    motion({ id: "jab-elbow", label: "Jab → Elbow", role: "Native two-contact chain", category: "Elbow", fileName: "jab-elbow.gif", frames: 30, contacts: [9, 20], comboRange: frameRange(1, 28) }),
    motion({ id: "elbow-uppercut", label: "Elbow → Uppercut", role: "Native close-range launcher", category: "Elbow", fileName: "elbow-uppercut.gif", frames: 28, contacts: [11, 22], comboRange: frameRange(1, 26) }),
    motion({ id: "kick-low", label: "Low MMA Kick", role: "Low interruption strike", category: "Kick", fileName: "kick-low.gif", frames: 20, contacts: [8], comboRange: frameRange(2, 16) }),
    motion({ id: "kick-side", label: "MMA Side Kick", role: "Long lateral silhouette", category: "Kick", fileName: "kick-side.gif", frames: 22, contacts: [8], comboRange: frameRange(2, 18) }),
    motion({ id: "kick-roundhouse", label: "MMA Roundhouse", role: "Mid-height rotational strike", category: "Kick", fileName: "kick-roundhouse.gif", frames: 22, contacts: [8], comboRange: frameRange(2, 18) }),
    motion({ id: "kick-high", label: "High MMA Kick", role: "Tall high-line finisher", category: "Kick", fileName: "kick-high.gif", frames: 24, contacts: [9], comboRange: frameRange(2, 20) }),
    motion({ id: "kick-spinning-back", label: "Spinning Back Kick", role: "Full-turn power finisher", category: "Kick", fileName: "kick-spinning-back.gif", frames: 26, contacts: [16], comboRange: frameRange(2, 23) }),
    motion({ id: "kick-front-snap", label: "Lead Front Snap Kick", role: "Fast linear stop-kick", category: "Kick", fileName: "kick-front-snap.gif", frames: 20, contacts: [10], comboRange: frameRange(2, 17) }),
    motion({ id: "leg-sweep", label: "Back Leg Sweep", role: "Ground-level circular attack", category: "Kick", fileName: "leg-sweep.gif", frames: 26, contacts: [16], comboRange: frameRange(2, 23) }),
    motion({ id: "knee-muay-thai", label: "Muay Thai Knee", role: "Single close-range knee", category: "Knee", fileName: "knee-muay-thai.gif", frames: 24, contacts: [9], comboRange: frameRange(2, 20) }),
    motion({ id: "knee-triple-uppercut", label: "Triple Knee → Uppercut", role: "Native four-contact pressure chain", category: "Knee", fileName: "knee-triple-uppercut.gif", frames: 44, contacts: [10, 19, 28, 37], comboRange: frameRange(0, 43) }),
  ]),
  recipes: Object.freeze([
    Object.freeze({
      id: "side-rhythm",
      label: "SIDE · Jab → Cross → Hook",
      mode: "side",
      description: "Three different silhouettes with a short-short-heavy cadence and no full idle reset between hits.",
      candidate: Object.freeze([
        segment("jab", 3, 13, 1),
        segment("cross", 3, 14, 1),
        segment("hook", 4, 17, 3),
      ]),
      baseline: Object.freeze([
        segment("current-side", 3, 16, 2),
        segment("current-side", 3, 16, 2),
        segment("current-side", 3, 16, 3),
      ]),
    }),
    Object.freeze({
      id: "up-rising",
      label: "UP · Jab → Cross → Uppercut",
      mode: "up",
      description: "Two compact setup beats feed a readable rising finisher aimed at the tile above.",
      candidate: Object.freeze([
        segment("jab", 3, 11, 1),
        segment("cross", 3, 11, 1),
        segment("uppercut", 3, 19, 4),
      ]),
      baseline: Object.freeze([
        segment("current-up", 0, 23, 3),
        segment("current-up", 0, 23, 3),
      ]),
    }),
    Object.freeze({
      id: "down-breaker",
      label: "DOWN · Jab → Low Body → Hook",
      mode: "down",
      description: "A quick guard break flows into the kneeling low punch, then recovers through a rotational hook.",
      candidate: Object.freeze([
        segment("jab", 3, 10, 1),
        segment("body-low", 2, 18, 1),
        segment("hook", 4, 16, 4),
      ]),
      baseline: Object.freeze([
        segment("current-down", 0, 25, 3),
        segment("current-down", 0, 25, 3),
      ]),
    }),
    Object.freeze({
      id: "native-two",
      label: "SIDE · Native Jab–Cross",
      mode: "side",
      description: "Mixamo's authored two-hit clip tests whether native shoulder and pelvis continuity beats manual splicing.",
      candidate: Object.freeze([segment("jab-cross", 0, 29, 4)]),
      baseline: Object.freeze([
        segment("current-side", 3, 16, 2),
        segment("current-side", 3, 16, 4),
      ]),
    }),
    Object.freeze({
      id: "native-four",
      label: "SIDE · Native Four-Punch",
      mode: "side",
      description: "A longer authored chain with four distinct contacts and continuous guard recovery.",
      candidate: Object.freeze([segment("four-combo", 0, 43, 4)]),
      baseline: Object.freeze(Array.from({ length: 4 }, () => segment("current-side", 3, 16, 2))),
    }),
    Object.freeze({
      id: "rapid-eight",
      label: "SIDE · Rapid Eight-Punch",
      mode: "side",
      description: "An intentionally aggressive stress test for rhythmic held mining; likely too fast, but useful as an upper bound.",
      candidate: Object.freeze([segment("eight-combo", 0, 28, 5)]),
      baseline: Object.freeze(Array.from({ length: 4 }, () => segment("current-side", 3, 12, 1))),
    }),
    Object.freeze({
      id: "alternate-boxing",
      label: "SIDE · Alternate Boxing Three",
      mode: "side",
      description: "A second jab-cross-hook family tests tighter guard recovery and less repeated shoulder posing.",
      candidate: Object.freeze([segment("boxing-lead-jab", 3, 13, 1), segment("boxing-back-cross", 3, 15, 1), segment("boxing-lead-hook", 3, 15, 3)]),
      baseline: Object.freeze(Array.from({ length: 3 }, () => segment("current-side", 3, 16, 2))),
    }),
    Object.freeze({
      id: "close-elbows",
      label: "SIDE · Jab → Elbow → Uppercut",
      mode: "side",
      description: "A compact close-range family with changing contact joints and continuous hip rotation.",
      candidate: Object.freeze([segment("boxing-lead-jab", 3, 12, 1), segment("elbow-single", 3, 13, 1), segment("elbow-uppercut", 1, 26, 4)]),
      baseline: Object.freeze(Array.from({ length: 3 }, () => segment("current-side", 3, 16, 2))),
    }),
    Object.freeze({
      id: "kick-triad",
      label: "SIDE · Front → Side → Roundhouse",
      mode: "side",
      description: "Three grounded kick directions progress from linear stop to lateral reach to rotational finish.",
      candidate: Object.freeze([segment("kick-front-snap", 2, 17, 1), segment("kick-side", 2, 18, 1), segment("kick-roundhouse", 2, 18, 4)]),
      baseline: Object.freeze(Array.from({ length: 3 }, () => segment("current-side", 3, 16, 2))),
    }),
    Object.freeze({
      id: "low-high-kicks",
      label: "SIDE · Low Kick → High Kick",
      mode: "side",
      description: "A readable low-high contrast test with one short setup and a tall finishing silhouette.",
      candidate: Object.freeze([segment("kick-low", 2, 16, 1), segment("kick-high", 2, 20, 4)]),
      baseline: Object.freeze([segment("current-side", 3, 16, 2), segment("current-side", 3, 16, 4)]),
    }),
    Object.freeze({
      id: "spin-finisher",
      label: "SIDE · Jab → Cross → Spin Kick",
      mode: "side",
      description: "Two fast hand beats establish facing before the larger spinning-back-kick finisher.",
      candidate: Object.freeze([segment("boxing-lead-jab", 3, 12, 1), segment("boxing-back-cross", 3, 14, 1), segment("kick-spinning-back", 2, 23, 5)]),
      baseline: Object.freeze(Array.from({ length: 3 }, () => segment("current-side", 3, 16, 2))),
    }),
    Object.freeze({
      id: "down-sweep-breaker",
      label: "DOWN · Body Punch → Leg Sweep",
      mode: "down",
      description: "A low hand contact transitions into a circular ground-level leg attack instead of repeating one downward pose.",
      candidate: Object.freeze([segment("body-low", 2, 18, 1), segment("leg-sweep", 2, 23, 4)]),
      baseline: Object.freeze([segment("current-down", 0, 25, 3), segment("current-down", 0, 25, 3)]),
    }),
    Object.freeze({
      id: "knee-pressure",
      label: "UP · Knee → Triple Knee–Uppercut",
      mode: "up",
      description: "A heavy close-range pressure stress test ending in a rising uppercut; useful as an upper bound, not an automatic replacement.",
      candidate: Object.freeze([segment("knee-muay-thai", 2, 20, 1), segment("knee-triple-uppercut", 0, 43, 5)]),
      baseline: Object.freeze([segment("current-up", 0, 23, 3), segment("current-up", 0, 23, 3)]),
    }),
    Object.freeze({
      id: "native-elbow-chain",
      label: "SIDE · Native Jab–Elbow",
      mode: "side",
      description: "The authored jab-to-elbow motion tests whether one continuous source clip outperforms manually spliced contact beats.",
      candidate: Object.freeze([segment("jab-elbow", 1, 28, 4)]),
      baseline: Object.freeze([segment("current-side", 3, 16, 2), segment("current-side", 3, 16, 4)]),
    }),
  ]),
});
