// ==================== CONTEXTUAL MUSIC DIRECTOR ====================
// Semantic routing for the complete sound/playlists catalog. Track filenames
// remain the inventory SSOT; these rules assign them to gameplay moments.
export const MUSIC_CONTEXT_IDS = Object.freeze({
  menu: "menu",
  tutorial: "tutorial",
  surfaceDawn: "surface-dawn",
  surfaceDay: "surface-day",
  surfaceEvening: "surface-evening",
  surfaceNight: "surface-night",
  shallow: "depth-shallow",
  blueCavern: "depth-blue-cavern",
  amberDepths: "depth-amber-depths",
  crystalVoid: "depth-crystal-void",
  silverVein: "depth-silver-vein",
  theCore: "depth-the-core",
  storm: "danger-storm",
  earthquake: "danger-earthquake",
  graveborerWurm: "danger-graveborer-wurm",
  hardcoreWarning: "danger-hardcore-warning",
  hardcoreCritical: "danger-hardcore-critical",
});

export const MUSIC_CUE_IDS = Object.freeze({
  discovery: "discovery",
  milestone: "milestone",
  recovery: "recovery",
  deathRevive: "death-revive",
  deathFinal: "death-final",
  finale: "finale",
});
const AMBIENT_CONTEXTS = Object.freeze([
  MUSIC_CONTEXT_IDS.menu, MUSIC_CONTEXT_IDS.tutorial,
  MUSIC_CONTEXT_IDS.surfaceDawn, MUSIC_CONTEXT_IDS.surfaceDay,
  MUSIC_CONTEXT_IDS.surfaceEvening, MUSIC_CONTEXT_IDS.surfaceNight,
  MUSIC_CONTEXT_IDS.shallow, MUSIC_CONTEXT_IDS.blueCavern,
  MUSIC_CONTEXT_IDS.amberDepths, MUSIC_CONTEXT_IDS.crystalVoid,
  MUSIC_CONTEXT_IDS.silverVein, MUSIC_CONTEXT_IDS.theCore,
]);

export const MUSIC_DIRECTOR_CONFIG = Object.freeze({
  schemaVersion: 1,
  defaultContext: MUSIC_CONTEXT_IDS.surfaceDay,
  menuContext: MUSIC_CONTEXT_IDS.menu,
  contextStableMs: 1800,
  minimumTransitionIntervalMs: 8000,
  urgentTransitionIntervalMs: 1500,
  crossfadeMs: 2000,
  errorRetryDelayMs: 1000,
  recentTrackHistory: 4,
  shallowDepthTiles: 20,
  urgentContexts: Object.freeze([
    MUSIC_CONTEXT_IDS.earthquake, MUSIC_CONTEXT_IDS.graveborerWurm,
    MUSIC_CONTEXT_IDS.hardcoreCritical,
  ]),
  surfacePhaseContexts: Object.freeze({
    midnight: MUSIC_CONTEXT_IDS.surfaceNight, dawn: MUSIC_CONTEXT_IDS.surfaceDawn,
    morning: MUSIC_CONTEXT_IDS.surfaceDay, afternoon: MUSIC_CONTEXT_IDS.surfaceDay,
    dusk: MUSIC_CONTEXT_IDS.surfaceEvening, sunset: MUSIC_CONTEXT_IDS.surfaceEvening,
    night: MUSIC_CONTEXT_IDS.surfaceNight,
  }),
  biomeContexts: Object.freeze({
    surface: MUSIC_CONTEXT_IDS.surfaceDay, blueCavern: MUSIC_CONTEXT_IDS.blueCavern,
    amberDepths: MUSIC_CONTEXT_IDS.amberDepths, crystalVoid: MUSIC_CONTEXT_IDS.crystalVoid,
    silverVein: MUSIC_CONTEXT_IDS.silverVein, theCore: MUSIC_CONTEXT_IDS.theCore,
  }),
  earthquakeStates: Object.freeze(["warning", "earthquake", "aftermath"]),
  graveborerWurmPhases: Object.freeze(["warning", "burrowing"]),
  cuePolicies: Object.freeze({
    [MUSIC_CUE_IDS.discovery]: Object.freeze({
      priority: 100,
      holdMs: 90000,
      cooldownMs: 60000,
    }),
    [MUSIC_CUE_IDS.milestone]: Object.freeze({
      priority: 110,
      holdMs: 90000,
      cooldownMs: 90000,
    }),
    [MUSIC_CUE_IDS.recovery]: Object.freeze({
      priority: 90,
      holdMs: 75000,
      cooldownMs: 60000,
    }),
    [MUSIC_CUE_IDS.deathRevive]: Object.freeze({
      priority: 300,
      holdMs: 120000,
      cooldownMs: 0,
    }),
    [MUSIC_CUE_IDS.deathFinal]: Object.freeze({
      priority: 300,
      holdMs: 120000,
      cooldownMs: 0,
    }),
    [MUSIC_CUE_IDS.finale]: Object.freeze({
      priority: 400,
      holdMs: 180000,
      cooldownMs: 0,
    }),
  }),
  trackRoutes: Object.freeze([
    Object.freeze({
      id: "legacy-ambient",
      match: Object.freeze({ prefixAny: Object.freeze(["j-k-d-amb-", "amb song-"]) }),
      contexts: AMBIENT_CONTEXTS,
      cues: Object.freeze([]),
    }),
    Object.freeze({
      id: "title",
      match: Object.freeze({ categoryAny: Object.freeze(["title"]) }),
      contexts: Object.freeze([MUSIC_CONTEXT_IDS.menu]),
      cues: Object.freeze([]),
    }),
    Object.freeze({
      id: "practice",
      match: Object.freeze({ categoryAny: Object.freeze(["practice"]) }),
      contexts: Object.freeze([MUSIC_CONTEXT_IDS.tutorial]),
      cues: Object.freeze([]),
    }),
    Object.freeze({
      id: "first-departure",
      match: Object.freeze({ includesAny: Object.freeze(["road-first-departure"]) }),
      contexts: Object.freeze([MUSIC_CONTEXT_IDS.tutorial]),
      cues: Object.freeze([]),
    }),
    Object.freeze({
      id: "surface-dawn",
      match: Object.freeze({ includesAny: Object.freeze(["safe-dawn", "dawn-fully-prepared"]) }),
      contexts: Object.freeze([MUSIC_CONTEXT_IDS.surfaceDawn]),
      cues: Object.freeze([]),
    }),
    Object.freeze({
      id: "surface-day",
      match: Object.freeze({ includesAny: Object.freeze(["safe-day", "safe-preparation"]) }),
      contexts: Object.freeze([MUSIC_CONTEXT_IDS.surfaceDay]),
      cues: Object.freeze([]),
    }),
    Object.freeze({
      id: "surface-evening-recovery",
      match: Object.freeze({ includesAny: Object.freeze([
        "safe-evening",
        "safe-hearth",
        "wounded-return-recovery",
        "return-alive",
        "boundary-safety-in-sight",
      ]) }),
      contexts: Object.freeze([MUSIC_CONTEXT_IDS.surfaceEvening]),
      cues: Object.freeze([MUSIC_CUE_IDS.recovery]),
    }),
    Object.freeze({
      id: "surface-night",
      match: Object.freeze({ includesAny: Object.freeze(["safe-night"]) }),
      contexts: Object.freeze([MUSIC_CONTEXT_IDS.surfaceNight]),
      cues: Object.freeze([]),
    }),
    Object.freeze({
      id: "shallow-world",
      match: Object.freeze({ includesAny: Object.freeze([
        "world-beginner-pocket",
        "world-greywood",
        "global-beginner-pocket",
      ]) }),
      contexts: Object.freeze([MUSIC_CONTEXT_IDS.shallow]),
      cues: Object.freeze([]),
    }),
    Object.freeze({
      id: "blue-cavern-world",
      match: Object.freeze({ includesAny: Object.freeze(["world-frostlands", "world-storm-coast"]) }),
      contexts: Object.freeze([MUSIC_CONTEXT_IDS.blueCavern, MUSIC_CONTEXT_IDS.storm]),
      cues: Object.freeze([]),
    }),
    Object.freeze({
      id: "amber-depths-world",
      match: Object.freeze({ includesAny: Object.freeze(["world-alchemy-marsh", "world-jungle-ruins"]) }),
      contexts: Object.freeze([MUSIC_CONTEXT_IDS.amberDepths]),
      cues: Object.freeze([]),
    }),
    Object.freeze({
      id: "crystal-void-world",
      match: Object.freeze({ includesAny: Object.freeze(["world-memory"]) }),
      contexts: Object.freeze([MUSIC_CONTEXT_IDS.crystalVoid]),
      cues: Object.freeze([]),
    }),
    Object.freeze({
      id: "silver-vein-world",
      match: Object.freeze({ includesAny: Object.freeze(["world-ashen-quarry"]) }),
      contexts: Object.freeze([MUSIC_CONTEXT_IDS.silverVein]),
      cues: Object.freeze([]),
    }),
    Object.freeze({
      id: "deep-core-world",
      match: Object.freeze({ categoryAny: Object.freeze(["tower"]) }),
      contexts: Object.freeze([MUSIC_CONTEXT_IDS.theCore]),
      cues: Object.freeze([]),
    }),
    Object.freeze({
      id: "late-run-pressure",
      match: Object.freeze({ includesAny: Object.freeze(["global-world-clock"]) }),
      contexts: Object.freeze([MUSIC_CONTEXT_IDS.theCore, MUSIC_CONTEXT_IDS.hardcoreWarning]),
      cues: Object.freeze([]),
    }),
    Object.freeze({
      id: "seismic-danger",
      match: Object.freeze({ categoryAny: Object.freeze(["boss", "combat"]) }),
      contexts: Object.freeze([
        MUSIC_CONTEXT_IDS.earthquake,
        MUSIC_CONTEXT_IDS.graveborerWurm,
      ]),
      cues: Object.freeze([]),
    }),
    Object.freeze({
      id: "hardcore-player-danger",
      match: Object.freeze({ categoryAny: Object.freeze(["player"]) }),
      contexts: Object.freeze([MUSIC_CONTEXT_IDS.hardcoreCritical]),
      cues: Object.freeze([]),
    }),
    Object.freeze({
      id: "hardcore-run-pressure",
      match: Object.freeze({ categoryAny: Object.freeze(["run"]) }),
      contexts: Object.freeze([MUSIC_CONTEXT_IDS.hardcoreWarning, MUSIC_CONTEXT_IDS.hardcoreCritical]),
      cues: Object.freeze([]),
    }),
    Object.freeze({
      id: "attrition-pressure",
      match: Object.freeze({ includesAny: Object.freeze(["global-attrition"]) }),
      contexts: Object.freeze([MUSIC_CONTEXT_IDS.hardcoreWarning, MUSIC_CONTEXT_IDS.hardcoreCritical]),
      cues: Object.freeze([]),
    }),
    Object.freeze({
      id: "discovery",
      match: Object.freeze({ categoryAny: Object.freeze(["discovery"]) }),
      contexts: Object.freeze([]),
      cues: Object.freeze([MUSIC_CUE_IDS.discovery]),
    }),
    Object.freeze({
      id: "rare-loot-discovery",
      match: Object.freeze({ includesAny: Object.freeze(["rare-loot-unsafe-return", "karma-immediate-reward"]) }),
      contexts: Object.freeze([]),
      cues: Object.freeze([MUSIC_CUE_IDS.discovery]),
    }),
    Object.freeze({
      id: "milestone",
      match: Object.freeze({ includesAny: Object.freeze([
        "milestone-celebration",
        "build-complete",
        "checkpoint-milestone",
        "floor-clear",
        "next-floor-door",
        "boss-breakthrough",
        "ten-floor-milestone",
      ]) }),
      contexts: Object.freeze([]),
      cues: Object.freeze([MUSIC_CUE_IDS.milestone]),
    }),
    Object.freeze({
      id: "choice-recovery",
      match: Object.freeze({ categoryAny: Object.freeze(["choice"]) }),
      contexts: Object.freeze([]),
      cues: Object.freeze([MUSIC_CUE_IDS.recovery]),
    }),
    Object.freeze({
      id: "escape-recovery",
      match: Object.freeze({ includesAny: Object.freeze(["impossible-escape"]) }),
      contexts: Object.freeze([]),
      cues: Object.freeze([MUSIC_CUE_IDS.recovery]),
    }),
    Object.freeze({
      id: "death-revive",
      match: Object.freeze({ includesAny: Object.freeze(["death-graveyard-respawn"]) }),
      contexts: Object.freeze([]),
      cues: Object.freeze([MUSIC_CUE_IDS.deathRevive]),
    }),
    Object.freeze({
      id: "death-final",
      match: Object.freeze({
        categoryAny: Object.freeze(["legacy"]),
        includesAny: Object.freeze(["death-final-life"]),
        matchMode: "any",
      }),
      contexts: Object.freeze([MUSIC_CONTEXT_IDS.crystalVoid]),
      cues: Object.freeze([MUSIC_CUE_IDS.deathFinal]),
    }),
    Object.freeze({
      id: "finale",
      match: Object.freeze({
        categoryAny: Object.freeze(["victory"]),
        includesAny: Object.freeze(["final-ascent", "final-opening", "final-phase"]),
        matchMode: "any",
      }),
      contexts: Object.freeze([]),
      cues: Object.freeze([MUSIC_CUE_IDS.finale]),
    }),
    Object.freeze({
      id: "moment-base",
      match: Object.freeze({ categoryAny: Object.freeze(["moment"]) }),
      contexts: Object.freeze([MUSIC_CONTEXT_IDS.surfaceDay]),
      cues: Object.freeze([]),
    }),
  ]),
});
