export const NEW_RUN_SETUP_CONFIG = Object.freeze({
  depth: 4250,
  assets: Object.freeze({
    foundation: "sprites/UI/expedition-setup-v2/new-expedition-foundation-v2.png",
    selection: "sprites/UI/expedition-setup-v2/new-expedition-selection-v2.png",
  }),
  panel: Object.freeze({ width: 1040, height: 694 }),
  title: Object.freeze({ y: -276, fontSize: 30 }),
  subtitle: Object.freeze({ y: -242, fontSize: 11 }),
  sectionLabels: Object.freeze({
    mode: Object.freeze({ x: 0, y: -211, text: "1  •  CHOOSE EXPEDITION RULES" }),
    tutorial: Object.freeze({ x: 0, y: -9, text: "2  •  CHOOSE OPENING ROUTE" }),
  }),
  cards: Object.freeze({
    xOffset: 252,
    modeY: -117,
    tutorialY: 99,
    width: 404,
    height: 168,
    iconX: -127,
    iconY: 0,
    iconSize: 58,
    casualIconName: "health",
    hardcoreIconName: "gem",
    guidedIconName: "pickaxe",
    skipIconName: "inventory",
    titleX: 63,
    titleY: -34,
    titleFontSize: 18,
    bodyX: 63,
    bodyY: -1,
    bodyWidth: 248,
    bodyFontSize: 12,
    selectedY: 32,
    selectedFontSize: 9,
    idleAlpha: 0.88,
    selectedAlpha: 1,
  }),
  status: Object.freeze({ y: 266, fontSize: 13 }),
  start: Object.freeze({ y: 305, width: 510, height: 42, fontSize: 16 }),
  footer: Object.freeze({
    y: 293,
    leftX: -389,
    rightX: 389,
    fontSize: 9,
  }),
});
