export const NEW_RUN_SETUP_CONFIG = Object.freeze({
  depth: 4250,
  panel: Object.freeze({ width: 1040, height: 660 }),
  title: Object.freeze({ y: -250, fontSize: 30 }),
  subtitle: Object.freeze({ y: -214, fontSize: 13 }),
  sectionLabels: Object.freeze({
    mode: Object.freeze({ x: 0, y: -177, text: "1  •  CHOOSE EXPEDITION RULES" }),
    tutorial: Object.freeze({ x: 0, y: 30, text: "2  •  CHOOSE OPENING ROUTE" }),
  }),
  cards: Object.freeze({
    xOffset: 222,
    modeY: -92,
    tutorialY: 112,
    width: 398,
    height: 146,
    iconX: -132,
    iconY: -5,
    iconSize: 70,
    casualIconWidth: 116,
    casualIconHeight: 27,
    titleX: 30,
    titleY: -28,
    titleFontSize: 18,
    bodyX: 30,
    bodyY: 3,
    bodyWidth: 250,
    bodyFontSize: 12,
    selectedY: 49,
    selectedFontSize: 10,
    idleAlpha: 0.68,
    selectedAlpha: 1,
  }),
  status: Object.freeze({ y: 218, fontSize: 13 }),
  start: Object.freeze({ y: 263, width: 310, height: 48 }),
  footer: Object.freeze({ y: 307, fontSize: 12 }),
  copy: Object.freeze({
    title: "NEW EXPEDITION",
    subtitle: "Both choices belong to this save and cannot be silently replaced.",
    casualTitle: "CASUAL",
    casualBody: "Complete game  •  no life loss\nZero GP disables abilities, never the save.",
    hardcoreTitle: "HARDCORE  •  PRIMARY",
    hardcoreBody: "2 lives  •  first revive free\nArms after Flight  •  save stays intact.",
    oneLifeTitle: "ONE-LIFE HARDCORE  •  HIDDEN",
    oneLifeBody: "1 life  •  no free revive\nArms after Flight  •  save stays intact.",
    guidedTitle: "GUIDED OPENING",
    guidedBody: "Move → Dig → Flight → Portal\nSell → Upgrade → Resume.",
    skipTitle: "SKIP TUTORIAL",
    skipBody: "Start with Flight  •  no guided route\nType YES so skipping is deliberate.",
    startLabel: "START EXPEDITION",
    guidedStatus: "GUIDED ROUTE SELECTED  •  ENTER OR CLICK START",
    skipStatus: "TYPE YES TO CONFIRM TUTORIAL SKIP: {value}",
    footer: "ARROWS / A-D  CHOOSE   •   ENTER  START   •   ESC  CANCEL",
    selected: "SELECTED",
    hiddenSequence: "ONELIFE",
    skipConfirmation: "YES",
  }),
});
