export const OBSERVATORY_AUTHORED_LAYERS_REVIEW = Object.freeze({
  sceneKey: "ObservatoryAuthoredLayersReview",
  cloudStreamPipelineKey: "ObservatoryCloudStreamPipeline",
  emissivePipelineKey: "ObservatoryAuthoredEmissivePipeline",
  skyPipelineKey: "ObservatoryAuthoredSkyPipeline",
  viewport: Object.freeze({ width: 1280, height: 720 }),
  sourceSize: Object.freeze({ width: 1672, height: 941 }),
  loopSeconds: 48,
  reference: Object.freeze({
    key: "observatory-reference",
    path: "../../../sprites/backgrounds/world-visual-v2/far/sky-cohesion-v1/2026-07-28-sky-13-level2-lower-iron-forge-haze-v1.webp",
  }),
  sky: Object.freeze({ key: "authored-sky", path: "./pack/sky-base-v3.png" }),
  stars: Object.freeze({ key: "authored-stars", path: "./pack/sky-stars-v4.png" }),
  architecture: Object.freeze({ key: "authored-architecture", path: "./pack/architecture-unlit-v3.png" }),
  emissive: Object.freeze({ key: "authored-emissive", path: "./pack/architecture-emissive-ids-v4.png" }),
  architectureModules: Object.freeze({
    atlasKey: "authored-architecture-modules", texturePath: "./pack/architecture-unlit-modules-v4.png", atlasPath: "./pack/architecture-unlit-modules-v4.json",
    emissiveAtlasKey: "authored-architecture-emissive-modules", emissiveTexturePath: "./pack/architecture-emissive-modules-v4.png", emissiveAtlasPath: "./pack/architecture-emissive-modules-v4.json",
    groupTravelX: 0.30, groupTravelY: 1.40, localTravelX: 0.65, localTravelY: 3.80, verticalHarmonic: 0.42,
    rotation: 0.0016, depthScaleRange: 0.007, groupCycles: 1, cycleVariants: 3, phaseOffset: 0.23,
    lifecycle: Object.freeze({
      indices: Object.freeze([2, 5, 6, 9, 10]),
      cycleDays: Object.freeze([28, 56, 84, 28, 56]),
      phaseDays: Object.freeze([0, 17, 41, 9, 33]),
      visibleDays: Object.freeze([18, 36, 54, 19, 35]),
      fadeDays: Object.freeze([3, 5, 7, 3, 5]),
      weatherVisibility: Object.freeze({ clear: 1.0, drizzle: 0.90, rain: 0.76, storm: 0.38, snow: 0.68 }),
      weatherLift: Object.freeze({ clear: 0.0, drizzle: 1.0, rain: 2.8, storm: 7.0, snow: 3.8 }),
      anchorWeatherResponse: 0.18, minAlpha: 0.0, cloudLift: 7.0, depthRetreat: 0.028,
    }),
  }),
  interiorLife: Object.freeze({
    atlasKey: "observatory-interior-life-existing-character",
    texturePath: "./pack/interior-life-existing-character-v1.png",
    atlasPath: "./pack/interior-life-existing-character-v1.json",
    frameSize: 40,
    tint: 0x74839a,
    rotation: 0.004,
    alphaBase: 0.97,
    alphaRange: 0.03,
    figures: Object.freeze([
      Object.freeze({ moduleIndex: 0, sourceX: 216, sourceY: 488, action: "talk", height: 22, cycles: 8, phaseOffset: 0.07, travelX: 0.45, travelY: 0.18, opacity: 0.94, flipX: false }),
      Object.freeze({ moduleIndex: 0, sourceX: 261, sourceY: 488, action: "mine", height: 22, cycles: 10, phaseOffset: 0.41, travelX: 0.28, travelY: 0.24, opacity: 0.92, flipX: true }),
      Object.freeze({ moduleIndex: 0, sourceX: 246, sourceY: 568, action: "walk", height: 16, cycles: 7, phaseOffset: 0.68, travelX: 1.25, travelY: 0.10, opacity: 0.88, flipX: false }),
      Object.freeze({ moduleIndex: 4, sourceX: 653, sourceY: 525, action: "talk", height: 16, cycles: 8, phaseOffset: 0.22, travelX: 0.32, travelY: 0.12, opacity: 0.88, flipX: true }),
      Object.freeze({ moduleIndex: 7, sourceX: 940, sourceY: 519, action: "mine", height: 14, cycles: 10, phaseOffset: 0.54, travelX: 0.22, travelY: 0.18, opacity: 0.84, flipX: false }),
      Object.freeze({ moduleIndex: 8, sourceX: 1028, sourceY: 677, action: "walk", height: 15, cycles: 7, phaseOffset: 0.81, travelX: 1.05, travelY: 0.08, opacity: 0.88, flipX: true }),
      Object.freeze({ moduleIndex: 9, sourceX: 1127, sourceY: 511, action: "talk", height: 14, cycles: 8, phaseOffset: 0.35, travelX: 0.30, travelY: 0.10, opacity: 0.84, flipX: false }),
      Object.freeze({ moduleIndex: 12, sourceX: 1284, sourceY: 541, action: "mine", height: 13, cycles: 10, phaseOffset: 0.73, travelX: 0.20, travelY: 0.16, opacity: 0.82, flipX: true }),
      Object.freeze({ moduleIndex: 13, sourceX: 1428, sourceY: 521, action: "talk", height: 17, cycles: 8, phaseOffset: 0.15, travelX: 0.34, travelY: 0.12, opacity: 0.90, flipX: false }),
      Object.freeze({ moduleIndex: 13, sourceX: 1452, sourceY: 579, action: "walk", height: 16, cycles: 7, phaseOffset: 0.92, travelX: 1.10, travelY: 0.08, opacity: 0.88, flipX: true }),
    ]),
  }),
  lightIds: Object.freeze({ key: "authored-light-ids", path: "./pack/architecture-light-ids-v3.png" }),
  layerReview: Object.freeze({ key: "authored-layer-review", path: "./pack/layer-review-v3.png" }),
  cloudLayers: Object.freeze([
    Object.freeze({ key: "upper", atlasKey: "authored-upper-stream-wisps", texturePath: "./pack/upper-cloud-wisps-v5.png", atlasPath: "./pack/upper-cloud-wisps-v5.json", travelX: 14.0, travelY: -1.2, baseCycles: 1, cycleVariants: 2, phaseOffset: 0.11, resetFeather: 0.170, opacity: 0.98 }),
    Object.freeze({ key: "horizon", atlasKey: "authored-horizon-stream-wisps", texturePath: "./pack/horizon-cloud-wisps-v5.png", atlasPath: "./pack/horizon-cloud-wisps-v5.json", travelX: 32.0, travelY: -1.8, baseCycles: 1, cycleVariants: 2, phaseOffset: 0.37, resetFeather: 0.190, opacity: 0.82 }),
    Object.freeze({ key: "lower", atlasKey: "authored-lower-stream-wisps", texturePath: "./pack/lower-cloud-wisps-v5.png", atlasPath: "./pack/lower-cloud-wisps-v5.json", travelX: 18.0, travelY: -0.8, baseCycles: 1, cycleVariants: 2, phaseOffset: 0.63, resetFeather: 0.170, opacity: 0.98 }),
    Object.freeze({ key: "near", atlasKey: "authored-near-stream-wisps", texturePath: "./pack/near-cloud-wisps-v5.png", atlasPath: "./pack/near-cloud-wisps-v5.json", travelX: 26.0, travelY: -1.4, baseCycles: 1, cycleVariants: 2, phaseOffset: 0.82, resetFeather: 0.190, opacity: 0.88 }),
  ]),
  motionSystems: Object.freeze(["cloud-streams", "island-buoyancy", "island-lifecycles", "window-occupancy", "window-flame", "star-classes", "interior-figures"]),
  worldChronology: Object.freeze({
    daysPerWeek: 7, daysPerMonth: 28, reviewMaximumDay: 168, defaultDay: 12, defaultHour: 22, defaultWeather: "clear",
    weatherKinds: Object.freeze(["clear", "drizzle", "rain", "storm", "snow"]),
    weatherCloudFlow: Object.freeze({ clear: 1.0, drizzle: 1.08, rain: 1.25, storm: 1.62, snow: 0.78 }),
    weatherCloudOpacity: Object.freeze({ clear: 1.0, drizzle: 1.02, rain: 1.05, storm: 1.10, snow: 1.07 }),
  }),
  defaults: Object.freeze({ view: "split", paused: false, motionStrength: 1.0, islandStrength: 1.0, lightStrength: 1.08, starStrength: 0.90 }),
  limits: Object.freeze({ motionStrength: 1.25, islandStrength: 1.25, lightStrength: 1.35, starStrength: 1.0 }),
  lightMotion: Object.freeze({
    baseIntensity: 0.82, microFlickerRange: 0.07, flameFlickerRange: 0.05, offIntensity: 0.0,
    occupancyThreshold: 0.38, occupancyFeather: 0.12, shadowThreshold: 0.76, shadowFeather: 0.12, shadowDepth: 0.76,
    steadyClassEnd: 0.38, occupiedClassEnd: 0.76, shadowClassEnd: 0.93, bloomGain: 1.20,
  }),
  skyMotion: Object.freeze({
    baseIntensity: 0.025, steadyLevel: 0.66, steadyDepth: 0.28, twinkleDepth: 1.02, microRange: 0.08,
    deepClassThreshold: 0.54, sparkleClassThreshold: 0.84, extinguishLow: 0.28, extinguishHigh: 0.56,
    twinkleGain: 1.18, sparkleGain: 1.34,
  }),
  viewModes: Object.freeze(["source", "runtime", "split", "layers", "lights"]),
});
