// ==================== OPENING FLIGHT ARTIFACT ====================
// Pure onboarding configuration. Runtime state and Phaser objects live in
// systems/onboarding/.

const COPY = Object.freeze({
  objectiveTitle: "FIND THE FLIGHT GEM",
  objectiveSurface: "Follow the huge arrows to the marked starter shaft",
  objectiveMine: "Aim DOWN and mine through the glowing seam",
  artifactLabel: "GEM OF FLIGHT",
  artifactSubLabel: "BREAK THE GLOWING BLOCK",
  approachHint: "The Flight Gem is below you — aim DOWN and mine!",
  starterLevelUp: "LEVEL {level} — mining power increased!",
  pickupToast: "GEM OF FLIGHT FOUND — permanent flight unlocked!",
  trialReady: "Hold {flyKey} to fly out — 30 seconds of flight are free",
  trialStarted: "FREE FLIGHT ACTIVE — GP will not drain",
  trialTitle: "FREE FLIGHT",
  trialReadyLine: "HOLD {flyKey} TO LAUNCH  •  {seconds}s FREE",
  trialActiveLine: "HOLD {flyKey}  •  {seconds}s FREE",
  returnSuccess: "Perfect! Dig → collect → fly home. That is the core loop.",
  trialComplete: "Free flight complete — future flight uses GP",
  gpExplainer: "GP powers flight and refills while you are not flying.",
  merchantHint: "The Gem of Great Power is buried beneath the huge arrows at the starter shaft.",
});

const COLORS = Object.freeze({
  cyan: 0x59f4ff,
  cyanText: "#59f4ff",
  cyanBright: 0xc8fbff,
  blue: 0x277dff,
  violet: 0x9d66ff,
  gold: 0xffd45a,
  white: 0xffffff,
  ink: 0x07101f,
  panel: 0x091426,
  panelStroke: 0x6fefff,
  objectiveTitle: "#fff2a8",
  objectiveBody: "#d7f9ff",
  artifactTitle: "#fff2a8",
  artifactBody: "#bff8ff",
  trialTitle: "#fff2a8",
  trialBody: "#d7f9ff",
  textStroke: "#08111f",
});

export const OPENING_FLIGHT_ARTIFACT_CONFIG = Object.freeze({
  enabled: true,
  saveVersion: 1,
  upgradeId: "gemPowerUnlock",
  flyActionId: "fly",
  trialDurationMs: 30000,
  pickupStatusDurationMs: 3600,
  starterLevelUpToastDurationMs: 2200,
  gpExplainerDelayMs: 900,
  pickupRadiusTiles: 0.9,
  approachRadiusTiles: 4,
  starterSeam: Object.freeze({
    tileXOffsetFromLegacySpawn: 0,
    surfaceRowOffset: 0,
    artifactDepthTiles: 5,
    bottomDepthTiles: 6,
    tileHp: 1,
    tileTypeNames: Object.freeze([
      "DIRT",
      "DIRT",
      "STONE",
      "DIRT",
      "DIRT",
    ]),
    bottomTileTypeName: "BEDROCK",
  }),
  worldView: Object.freeze({
    depth: 46,
    artifactRadiusPx: 38,
    artifactGlowAlpha: 0.24,
    artifactRingRadiusPx: 50,
    artifactRingWidthPx: 4,
    artifactRingAlpha: 0.88,
    gemWidthPx: 46,
    gemHeightPx: 62,
    gemHighlight: Object.freeze({
      leftXRatio: -0.2,
      topYRatio: -0.22,
      rightXRatio: 0.08,
      rightYRatio: -0.34,
      bottomXRatio: -0.02,
      bottomYRatio: 0,
      alpha: 0.72,
    }),
    artifactLabelOffsetYPx: 74,
    artifactSubLabelOffsetYPx: 98,
    artifactTitleFontSize: "18px",
    artifactBodyFontSize: "13px",
    arrowCount: 3,
    arrowWidthPx: 78,
    arrowHeightPx: 48,
    arrowGapPx: 44,
    arrowTopOffsetTiles: 2.25,
    arrowLabelOffsetYPx: -44,
    arrowLabelFontSize: "22px",
    pulseDurationMs: 720,
    pulseEase: "Sine.inOut",
    pulseAlphaFrom: 0.35,
    pulseAlphaTo: 1,
    pulseScaleFrom: 0.88,
    pulseScaleTo: 1.14,
    bobDistancePx: 12,
    bobDurationMs: 560,
    bobEase: "Sine.inOut",
  }),
  screenView: Object.freeze({
    depth: 3650,
    objectiveY: 34,
    objectiveWidthPx: 520,
    objectiveHeightPx: 64,
    objectiveTitleOffsetYPx: -12,
    objectiveBodyOffsetYPx: 13,
    objectiveTitleFontSize: "18px",
    objectiveBodyFontSize: "14px",
    pointerRadiusPx: 42,
    pointerArrowLengthPx: 70,
    pointerArrowWidthPx: 44,
    pointerEdgeMarginPx: 76,
    pointerPlayerClearancePx: 112,
    pointerMaxTravelViewportRatio: 0.36,
    trialYFromBottomPx: 82,
    trialWidthPx: 440,
    trialHeightPx: 72,
    trialTitleOffsetYPx: -15,
    trialBodyOffsetYPx: 10,
    trialBarOffsetYPx: 29,
    trialBarWidthPx: 368,
    trialBarHeightPx: 7,
    trialTitleFontSize: "18px",
    trialBodyFontSize: "15px",
    panelAlpha: 0.9,
    panelStrokeWidthPx: 2,
    panelStrokeAlpha: 0.95,
    trialBarBgAlpha: 0.9,
    trialBarFillAlpha: 1,
  }),
  typography: Object.freeze({
    titleFontFamily: "Trebuchet MS, Segoe UI, sans-serif",
    bodyFontFamily: "Consolas, monospace",
    titleFontStyle: "bold",
  }),
  collectionFx: Object.freeze({
    sparkCount: 18,
    sparkRadiusPx: 4,
    travelMinPx: 72,
    travelMaxPx: 150,
    distanceSteps: 5,
    durationMs: 620,
    ease: "Cubic.out",
    startAlpha: 1,
    endScale: 0.1,
  }),
  colors: COLORS,
  copy: COPY,
});

export function sanitizeOpeningFlightArtifactData(data) {
  const config = OPENING_FLIGHT_ARTIFACT_CONFIG;
  const artifactCollected = data?.artifactCollected === true;
  const rawRemainingMs = Number.isFinite(data?.trialRemainingMs)
    ? data.trialRemainingMs
    : 0;
  const trialRemainingMs = artifactCollected
    ? Math.max(0, Math.min(config.trialDurationMs, rawRemainingMs))
    : 0;
  return {
    version: Number.isInteger(data?.version) ? data.version : config.saveVersion,
    artifactCollected,
    trialStarted: artifactCollected && data?.trialStarted === true,
    trialRemainingMs,
    trialComplete: artifactCollected
      && (data?.trialComplete === true || trialRemainingMs <= 0),
    surfaceReturnCelebrated: artifactCollected && data?.surfaceReturnCelebrated === true,
  };
}
