// ==================== PAUSE FEATURE LOADING ====================
// Compact authored loading presentation used inside deferred ESC tabs.

const phase = (at, label, detail, stageIndex) => Object.freeze({
  at,
  label,
  detail,
  stageIndex,
});

const theme = ({
  eyebrow,
  title,
  readyTitle,
  readyPhase,
  readyDetail,
  footer,
  countNoun,
  socketAsset,
  stages,
  phases,
}) => Object.freeze({
  eyebrow,
  title,
  readyTitle,
  readyPhase,
  readyDetail,
  footer,
  countNoun,
  socketAsset,
  stages: Object.freeze(stages),
  phases: Object.freeze(phases),
});

export const PAUSE_FEATURE_LOADING_CONFIG = Object.freeze({
  revision: "pause-feature-loading-v1-20260730",
  diagnosticsGlobalKey: "__jkdPauseFeatureLoading",
  assets: Object.freeze({
    starlightCrest: Object.freeze({
      key: "ui-starlight-modal-crest-v2",
      path: "sprites/UI/starlight-talent-tree-v3/constellation-crest-v2.png",
    }),
  }),
  layout: Object.freeze({
    referenceWidthPx: 1116,
    referenceHeightPx: 467,
    minimumScale: 0.72,
    foundationWidthPx: 1044,
    foundationHeightPx: 424,
    foundationGlowScale: 1.018,
    headerYpx: -145,
    headerWidthPx: 630,
    headerHeightPx: 72,
    eyebrowYpx: -157,
    titleYpx: -134,
    apertureYpx: -58,
    apertureSizePx: 104,
    flareSizePx: 88,
    phaseYpx: 8,
    detailYpx: 33,
    progressYpx: 103,
    progressWidthPx: 780,
    progressHeightPx: 92,
    progressPercentOffsetXpx: 332,
    progressCountXpx: -332,
    progressCountYpx: 8,
    progressPercentYpx: 8,
    progressSparkSizePx: 48,
    progressEnergyOffsetYpx: -25,
    progressSegmentCount: 12,
    progressSegmentSizePx: 25,
    progressSegmentAngleDeg: 45,
    stagesYpx: 181,
    stageXpx: Object.freeze([-250, 0, 250]),
    stageWidthPx: 220,
    stageHeightPx: 46,
    footerYpx: 215,
  }),
  motion: Object.freeze({
    pollIntervalMs: 80,
    enterMs: 180,
    enterOffsetYpx: 6,
    fillEaseMs: 150,
    completeHoldMs: 220,
    apertureSpinMs: 14000,
    flarePulseMs: 1550,
    flareMinAlpha: 0.34,
    flareMaxAlpha: 0.68,
    flareMinScale: 0.9,
    flareMaxScale: 1.08,
    foundationPulseMs: 2200,
    foundationMinAlpha: 0.18,
    stageFlareStaggerMs: 130,
    foundationMaxAlpha: 0.3,
    stageTweenMs: 140,
    stageActiveScale: 1.035,
    stageIdleScale: 0.975,
  }),
  presentation: Object.freeze({
    foundationAlpha: 0.96,
    progressBaseAlpha: 0.3,
    progressSegmentAlpha: 0.94,
    progressSegmentFutureAlpha: 0.1,
    stagePastAlpha: 0.82,
    stageActiveAlpha: 1,
    stageFutureAlpha: 0.42,
    targetAlpha: 0.78,
    textStrokeColor: "#02060A",
    textStrokeThicknessPx: 3,
    titleColor: "#F0DFC2",
    eyebrowColor: "#D6A84A",
    phaseColor: "#E9F7FF",
    detailColor: "#91BBD1",
    countColor: "#C8DAE8",
    percentColor: "#F3C85E",
    footerColor: "#D6A84A",
    stagePastTint: 0x7d9bb1,
    stageActiveTint: 0xffffff,
    stageFutureTint: 0x536575,
    foundationGlowTint: 0x6ea8d8,
    apertureTint: 0x9fe8ff,
    progressFillTint: 0xffd66c,
    titleFontSizePx: 23,
    eyebrowFontSizePx: 10,
    phaseFontSizePx: 17,
    detailFontSizePx: 11,
    progressFontSizePx: 12,
    stageFontSizePx: 10,
    footerFontSizePx: 9,
  }),
  themes: Object.freeze({
    starlight: theme({
      eyebrow: "STARLIGHT TALENT ARCHIVE",
      title: "ATTUNING THE STAR MAP",
      readyTitle: "STAR MAP READY",
      readyPhase: "ATTUNEMENT COMPLETE",
      readyDetail: "Every constellation is aligned.",
      footer: "FULL-QUALITY CONSTELLATION ART  ·  OPENS AUTOMATICALLY",
      countNoun: "ART PIECES",
      socketAsset: "starlightCrest",
      stages: ["SIGNS", "TALENT SIGILS", "STAR ENGINES"],
      phases: [
        phase(0, "OPENING THE OBSERVATORY", "Preparing the celestial archive.", 0),
        phase(0.2, "ALIGNING CONSTELLATION SIGNS", "Bringing each permanent talent into focus.", 0),
        phase(0.55, "CHARGING TALENT SIGILS", "Restoring full-resolution seals and plaques.", 1),
        phase(0.84, "AWAKENING STAR ENGINES", "Final engine art is entering the map.", 2),
      ],
    }),
    titanArchive: theme({
      eyebrow: "TITAN FIELD ARCHIVE",
      title: "RESTORING THE DEEP RECORD",
      readyTitle: "ARCHIVE READY",
      readyPhase: "RESTORATION COMPLETE",
      readyDetail: "Every recovered chamber record is available.",
      footer: "FULL-QUALITY TITAN ART  ·  OPENS AUTOMATICALLY",
      countNoun: "RECORDS",
      socketAsset: null,
      stages: ["TRACES", "CHAMBERS", "LORE"],
      phases: [
        phase(0, "OPENING THE DEEP ARCHIVE", "Preparing recovered field records.", 0),
        phase(0.24, "RESOLVING TITAN TRACES", "Restoring full-resolution silhouettes.", 0),
        phase(0.58, "REBUILDING CHAMBER RECORDS", "Bringing discovery art into focus.", 1),
        phase(0.86, "SEALING THE FIELD LORE", "Completing the archive index.", 2),
      ],
    }),
  }),
});

export function resolvePauseFeatureLoadingTheme(
  themeId,
  config = PAUSE_FEATURE_LOADING_CONFIG,
) {
  return config.themes[themeId] || config.themes.starlight;
}

export function getPauseFeatureLoadingDecorationAssets(
  config = PAUSE_FEATURE_LOADING_CONFIG,
) {
  return Object.freeze(
    Object.values(config.assets)
      .map(({ key, path }) => Object.freeze({ key, path })),
  );
}
