export const PERFORMANCE_TELEMETRY_CONFIG = Object.freeze({
  schemaVersion: 1,
  enabled: true,
  globals: Object.freeze({
    monitor: "__jkdPerformance",
  }),
  events: Object.freeze({
    preStep: "prestep",
    postStep: "poststep",
    preRender: "prerender",
    postRender: "postrender",
  }),
  sceneKeys: Object.freeze({
    play: "PlayScene",
  }),
  samples: Object.freeze({
    frameWindowSize: 600,
    spanWindowSize: 120,
    maxTrackedFrameMs: 1000,
    phaseEveryFrames: 30,
  }),
  phases: Object.freeze({
    playHudProgression: "play-hud-progression",
    playGameplay: "play-gameplay",
    playWorldEnvironment: "play-world-environment",
    playVisualEffects: "play-visual-effects",
    playCameraLighting: "play-camera-lighting",
    scenicContinuous: "scenic-continuous",
  }),
  percentiles: Object.freeze({
    median: 0.5,
    p95: 0.95,
    p99: 0.99,
  }),
  thresholds: Object.freeze({
    longFrameMs: 50,
  }),
  formatting: Object.freeze({
    precisionDigits: 1,
    millisecondsPerSecond: 1000,
  }),
  ui: Object.freeze({
    labels: Object.freeze({
      performance: "Frame time",
      p95: "p95",
      p99: "p99",
      worst: "worst",
      onePercentLow: "1% low",
      longFrames: "long",
      hotPaths: "Hot paths p95",
      streaming: "Streaming",
      backgroundUpdates: "background updates",
      backgroundSkipped: "skipped",
      backgroundCandidates: "candidates",
      texturesQueued: "textures queued",
      tileBatches: "tile batches",
      tileCommits: "commits",
      tilePending: "pending",
      scenicSyncs: "scenic syncs",
      scenicSkipped: "skipped",
      scenicLastSync: "last sync",
      assetsPending: "assets pending",
      assetsResident: "resident",
      assetsCancelled: "cancelled",
      demandStreaming: "visible demand",
      demandedAssets: "visible assets",
      scheduler: "scheduler",
      enabled: "on",
      disabled: "off",
      milliseconds: "ms",
      framesPerSecond: "FPS",
      unavailable: "n/a",
    }),
    phaseOrder: Object.freeze([
      "play-hud-progression",
      "play-gameplay",
      "play-world-environment",
      "play-visual-effects",
      "play-camera-lighting",
      "scenic-continuous",
    ]),
    phaseLabels: Object.freeze({
      "play-hud-progression": "HUD",
      "play-gameplay": "gameplay",
      "play-world-environment": "world",
      "play-visual-effects": "effects",
      "play-camera-lighting": "camera/light",
      "scenic-continuous": "scenic",
    }),
    separator: " · ",
  }),
});
