// Shared player-facing words for UI surfaces whose mechanics live elsewhere.
// Keep these strings direct, action-led, and free of implementation language.

export const MAIN_MENU_COPY = Object.freeze({
  tagline: "Dig deep. Grow stronger. Find what waits below.",
  play: "PLAY",
  settings: "SETTINGS",
  credits: "CREDITS",
  creditsLayout: Object.freeze({ width: 800, height: 480 }),
  fullAudioCredits: Object.freeze({
    label: "All 562 Freesound source credits and licenses ↗",
    path: "sound/soundEffects/approved-freesound-2026-09-03/CREDITS.txt",
    bottomOffset: 64, fontSize: "12px",
  }),
  audioCredits: Object.freeze([
    "Audio",
    "Level Up 01 by rhodesmas · CC BY 4.0",
    "freesound.org/people/rhodesmas/sounds/320655/",
    "creativecommons.org/licenses/by/4.0/",
    "Shockwave by qubodup · CC0 1.0",
    "Level up by Bastianhallo · CC0 1.0",
  ]),
  navigationHint: "Tab / Arrows: choose  •  Enter / Space: select  •  Esc: back",
  closeHint: "Esc: close",
});

export const NEW_RUN_COPY = Object.freeze({
  title: "NEW EXPEDITION",
  subtitle: "PERMANENT FOR THIS SAVE",
  modeSection: "DIFFICULTY",
  tutorialSection: "CHOOSE YOUR START",
  casualTitle: "CASUAL",
  casualBody: "Explore without losing lives.\nRunning out of GP only disables powers.",
  hardcoreTitle: "HARDCORE",
  hardcoreBody: "1 life  •  no revives\nStarts when Flight unlocks; save remains.",
  oneLifeTitle: "ONE-LIFE HARDCORE",
  oneLifeBody: "1 life  •  no revives\nStarts when Flight unlocks; save remains.",
  guidedTitle: "GUIDED OPENING",
  guidedBody: "Learn movement, digging, Flight, gates,\nshops, and how to continue deeper.",
  skipTitle: "SKIP TUTORIAL",
  skipBody: "Start immediately with Flight unlocked.\nType YES to skip the guided route.",
  startLabel: "START EXPEDITION",
  guidedStatus: "GUIDED START SELECTED  •  PRESS ENTER OR CLICK START",
  skipStatus: "TYPE YES TO SKIP THE TUTORIAL: {value}",
  footer: "ARROWS / A-D  CHOOSE   •   ENTER  START   •   ESC  BACK",
  footerLeft: "ARROWS / A-D  CHOOSE",
  footerRight: "ENTER  START  •  ESC  BACK",
  selected: "SELECTED",
  hiddenSequence: "ONELIFE",
  skipConfirmation: "YES",
});

export const SETTINGS_COPY = Object.freeze({
  tabs: Object.freeze(["AUDIO", "CONTROLS", "DISPLAY", "GAMEPLAY"]),
  audioSaved: "SFX toggle also mutes voices. Changes save instantly.",
  rebindTitle: "Choose a new key for {action}",
  rebindHint: "Press any available key  •  Esc cancels",
  rebindCancelled: "Key change cancelled.",
  rebindSuccess: "Now bound to {key}.",
  reservedKeyHint: "{key} is reserved for fullscreen. Select a control, then press a new key. Esc cancels.",
  defaultRestored: "Default restored.",
  displayTitle: "Display",
  fullscreen: "FULLSCREEN",
  fullscreenBlocked: "Your browser blocked fullscreen. Try again.",
  fullscreenUnavailable: "Fullscreen is not available in this browser.",
  controlHints: "Show Control Hints",
  cameraShake: "Camera Shake",
  cameraShakeIntensity: "Shake Intensity",
  shakeFlash: "Flash During Shakes",
  shakeEvents: "Shake for These Events",
  resetControls: "RESET CONTROLS",
  resetSettings: "RESET SETTINGS",
  controlsReset: "Controls restored to defaults.",
  settingsReset: "Settings restored to defaults.",
  feedbackTitle: "On-screen Feedback",
  currentPrefix: "Currently",
  feedbackFooter: "These choices only change what you see. Progress and rewards stay the same.",
});

export const PAUSE_MENU_COPY = Object.freeze({
  title: "PAUSED",
  subtitle: "Manage this run, your saves, and settings",
  actionsTitle: "RUN ACTIONS",
  resume: "RESUME GAME",
  save: "SAVE GAME",
  returnToSafety: "RETURN TO SAFETY",
  mainMenu: "MAIN MENU",
  snapshotTitle: "CURRENT RUN",
  snapshotSubtitle: "Your progress right now",
  noActiveCampfire: "NONE ACTIVE",
  featureLoadFailed: "That screen could not be opened. Please try again.",
  navigationHint: "Tab: next control  •  Ctrl+Tab: section  •  Arrows: move / adjust  •  Enter: select  •  Esc: resume",
});

export const RECOVERY_COPY = Object.freeze({
  title: "GAME PAUSED FOR SAFETY",
  subtitle: "Your last valid save is safe",
  body: Object.freeze([
    "Something went wrong, so the game paused before saving damaged progress.",
    "Your last valid save has not been replaced.",
    "",
    "Reload that save or return to the main menu.",
  ]),
  reload: "RELOAD SAFE SAVE",
  mainMenu: "MAIN MENU",
});

export const WORLD_LOAD_COPY = Object.freeze({
  slotSubtitle: "SAVE SLOT {slot}",
  loadingSlot: "Opening save slot {slot}...",
  preparingWorld: "Preparing the mine...",
  loadingAssets: "Preparing the game...",
  preparingCharacter: "Preparing your miner and the nearby world...",
  preparingNearbyWorld: "Preparing the nearby world...",
  enteringMine: "Entering the mine...",
  almostReady: "Almost ready...",
  buildingWorld: "Restoring your world...",
  restoringSave: "Loading your progress...",
  failureTitle: "WE COULDN'T OPEN THIS SAVE",
  failureBody: "Your save is still safe. Try loading it again.",
  failureDetailPrefix: "Details",
  retry: "TRY AGAIN",
});

export const WORLD_MAP_COPY = Object.freeze({
  title: "WORLD MAP",
  discovered: "DISCOVERED",
  activityLayers: "MAP MARKERS",
  worldStatus: "YOUR LOCATION",
  visualRegion: "AREA",
  noActivityLayers: "NO OPTIONAL MARKERS",
  noActivityHint: "New markers appear as you discover them",
  dragPan: "DRAG TO PAN",
  wheelZoom: "WHEEL TO ZOOM",
  center: "CENTER PLAYER [F]",
  close: "CLOSE MAP [M]",
  layerOn: "ON",
  layerOff: "OFF",
  mapSize: "MAP SIZE",
  currentDepth: "DEPTH",
  zoom: "ZOOM",
  knownSignals: "KNOWN SIGNALS",
  visibleBiomes: "VISIBLE BIOMES",
  player: "YOU",
  titanResonance: "Titan Resonance",
  tracked: "TRACKED",
  starTerritory: "STAR TERRITORY",
  starAnchorBiome: "ANCHOR BIOME",
  unidentifiedStar: "UNIDENTIFIED STAR SIGNAL",
  starRefugeDetail: "SAFE LIGHT • RESTORES GP • CALMS PANIC",
  starSignalDetail: "FOLLOW THE ROUTE TO THIS STAR",
  starScarSuffix: "SCAR",
  starRefugeLost: "THIS STAR REFUGE IS GONE",
  starRoute: "REFUGE ROUTE",
  starLostRoute: "SCAR ROUTE",
  knownStarTerritories: "KNOWN STAR LINKS",
  lostStarTerritories: "LOST",
  noUndergroundStar: "SURFACE • NO STAR NEARBY",
});

export const STAR_SANCTUARY_COPY = Object.freeze({
  acknowledgement: Object.freeze({
    confirmationWord: "DESTROY",
    title: "DESTROY THIS STAR REFUGE?",
    subtitle: "THIS CANNOT BE UNDONE",
    body: [
      "This Star is a safe refuge.",
      "",
      "Destroying it permanently removes:",
      "LIGHT  •  MATERIAL YIELD  •  GP RECOVERY  •  PANIC RELIEF",
      "",
      "Its entire territory will become a scar.",
      "Panic builds four times faster there.",
      "Destroying the last Star scars the whole underground.",
    ].join("\n"),
    typedInstruction: "TYPE DESTROY, THEN PRESS ENTER",
    footer: "ESC  KEEP THE STAR",
    footerColor: "#d6a84a",
  }),
  hold: Object.freeze({
    title: "DESTROYING STAR REFUGE",
    status: "HOLD MINE  •  {percent}%",
    consequence: "YOU WILL LOSE LIGHT, MATERIALS, GP RECOVERY, AND PANIC RELIEF  •  RELEASE TO CANCEL",
  }),
});

export const SHOP_COPY = Object.freeze({
  defaultTitle: "MERCHANT",
  defaultSubtitle: "Choose an item to see what it does and what it costs",
  help: "Click: select  •  W/S or arrows: move  •  PgUp/PgDn: page  •  A/D or Tab: switch  •  {interact}/Enter: choose  •  Esc: close",
  resourcesTitle: "YOUR RESOURCES",
  schematicsTitle: "ARC FORGE RECIPES",
  upgradesTitle: "UPGRADES",
  requirementsTitle: "WHAT YOU NEED",
  currentLevel: "CURRENT LEVEL",
  maximum: "MAX LEVEL",
  alreadyForged: "You already forged this core.",
  needMoreRelics: "Find more Ancient Relics first.",
  forgeUnavailable: "The forge is not ready. Close it and try again.",
  unavailable: "This upgrade is not available yet.",
  requirementsMissing: "You do not meet this purchase's requirements yet.",
  saleHint: "Sell what you carry. Your bonuses are already included.",
});
