// Public recording policy; credentials and server storage paths never belong here.
export const PLAYER_SESSION_LOGGING = Object.freeze({
  schemaVersion: 1,
  endpoint: './api/player-data.php',
  productionHosts: Object.freeze(['www.nextgen.run', 'nextgen.run']),
  productionPath: '/diggame-beta-1/',
  testParameter: 'playerDataTest',
  disableParameter: 'sessionLogging',
  databaseName: 'understar-player-data-v1',
  databaseVersion: 1,
  queueStore: 'outbox',
  metadataStore: 'identity',
  maxQueuedBatches: 96,
  maxQueueBytes: 4 * 1024 * 1024,
  queueLifetimeMs: 24 * 60 * 60 * 1000,
  maxMemoryEvents: 2048,
  maxBatchEvents: 128,
  maxBatchBytes: 48 * 1024,
  maxFields: 40,
  maxStringLength: 80,
  maxFieldDepth: 3,
  flushIntervalMs: 5000,
  sampleIntervalMs: 250,
  stateIntervalMs: 5000,
  pointerIntervalMs: 250,
  idleAfterMs: 30000,
  unknownGapAfterMs: 10000,
  requestTimeoutMs: 8000,
  retryMaxMs: 60000,
  backupIntervalMs: 60000,
  maxBackupBytes: 8 * 1024 * 1024,
  maxQueuedBackups: 3,
  gamepadDeadzone: 0.2,
  toggleKey: 'F8',
  menuKeys: Object.freeze(['ArrowUp', 'ArrowDown', 'ArrowLeft', 'ArrowRight', 'Enter', 'Space', 'Escape', 'Home', 'Tab']),
  dataFields: Object.freeze([
    'action', 'result', 'reason', 'code', 'button', 'pointer', 'x', 'y', 'worldX', 'worldY',
    'heldMs', 'synthetic', 'scene', 'phase', 'slot', 'level', 'xp', 'gp', 'hp', 'depth',
    'gold', 'flying', 'running', 'paused', 'fps', 'revision', 'bytes', 'count', 'dropped',
    'tileX', 'tileY', 'tileType', 'damage', 'destroyed', 'success', 'upgrade', 'rank',
    'progress', 'line', 'column', 'file', 'visible', 'focused', 'state', 'totals',
    'gameplay', 'idle', 'menu', 'loading', 'pausedTime', 'hidden', 'unfocused', 'unknown',
    'axis', 'index', 'value', 'from', 'to', 'elapsedMs', 'build', 'stage', 'amount',
    'shop', 'dialogue', 'inventory', 'map', 'dead',
  ]),
  notice: Object.freeze({
    enabled: 'Playtest logging ON: game inputs, actions and timing. F8 to turn off.',
    disabled: 'Playtest logging OFF. F8 to turn on.',
    fontSize: '11px', bottom: 28,
  }),
});
