/** Local, save-disabled diagnostic controls; never a production collision mode. */
export const PLAYER_COLLISION_REVIEW_CONFIG = Object.freeze({
  queryParam: "collisionReview",
  queryValue: "1",
  harnessQueryParam: "jkd_e2e",
  standOffCode: "F6",
  toggleCode: "F7",
  freezeCode: "F8",
  materialQueryParam: "impactMaterial",
  materialNames: Object.freeze(["STONE", "COPPER", "DIRT", "GLOW_CRYSTAL"]),
  facingQueryParam: "impactFacing",
  leftFacingValue: "left",
  targetOffsetX: 1,
  ceilingOffsetY: -1,
  targetHp: 100000,
  breakQueryParam: "impactBreak",
  breakTargetHp: 1,
  afterQueryParam: "impactAfter",
  afterDelaysMs: Object.freeze([80, 180]),
  impactMetrics: Object.freeze({
    prefix: "FEEL / NATIVE", hold: "hold", shake: "shake",
    captureMs: 240, maximumSamples: 32, logPrefix: "[ImpactReview]", renderEvent: "render",
  }),
  particle: Object.freeze({
    queryParam: "particleReview", queryValue: "1", floorRadiusTiles: 5,
    catchCode: "F7", walkCode: "F8", walkDurationMs: 1800,
    leftCode: "KeyA", leftKey: "a", leftKeyCode: 65,
    historyCount: 4,
    controls: "Ctrl+F7: catch foot contact | Ctrl+F8: 1.8 s review walk left | normal A/D still work",
    prefix: "FOOT", waiting: "WAITING FOR FOOT CONTACT",
  }),
  caption: Object.freeze({
    x: 22,
    y: 154,
    fontSizePx: 19,
    lineSpacing: 3,
    title: "DIG CLIPPING A/B - TEST WALL - SAVES OFF",
    maskOn: "A: limb mask ON",
    maskOff: "B: limb mask OFF",
    standOffOn: "wall hold-back ON",
    standOffOff: "wall hold-back OFF",
    frozen: "FROZEN",
    running: "LIVE",
    controls: "F6 hold-back | F7 limb mask | F8 freeze/resume | F1 reset wall",
    contactControls: "Shift+F8: catch the next actual impact",
    contactArmed: "WAITING FOR CONTACT",
    contactPrefix: "IMPACT",
    physics: "Floor/wall collision stays ON. Hold-back changes apply to the next moving dig.",
    unchanged: "Last mask toggle: same frame, pose, size and body position.",
    changed: "Last mask toggle changed presentation state - inspect before comparing.",
  }),
});
