// Review-only broader Leo trigger proposal. No runtime imports.
export const LEO_TRIGGER_REVIEW = {
  "id": "leo-trigger-breadth-v2",
  "version": "2026-09-08-breadth-v2",
  "reviewOnly": true,
  "approvalUrl": "./2026-09-07-approved-selection.json",
  "defaultMoment": "work",
  "storageKey": "understar-leo-trigger-breadth-v2",
  "exportName": "leo-trigger-breadth-decisions-v2.json",
  "catalogHash": "678a3d6c30870ae87d2288f57268a41097996455d3ec410bcd549f364eb0b99b",
  "background": "/sprites/infinate-loops/underground-0-1000/depth-200-400.png",
  "oreImage": "/sprites/tiles/tiles-under-1000/resource-{material}-tile/{material}-full-hp.webp",
  "timing": {"normalGapMs": 25000, "oreGapMs": 45000, "maxInWindow": 8, "windowMs": 300000, "afterOtherSpeechMs": 1200, "urgentGapMs": 45000, "randomMinMs": 1620000, "randomMaxMs": 1980000, "randomQuietMs": 20000, "randomAfterLeoMs": 90000, "randomWindowMs": 120000, "downMs": 900, "leadMs": 450, "captionMs": 2800, "holdMs": 450, "upMs": 2400, "duck": 0.24},
  "copy": {"ready": "Ready. The highlighted confirmation will earn the line.", "cue": "Visible event confirmed. Music starts easing down.", "speaking": "Leo reacts while the same cue is still visible.", "restore": "Sentence finished. Music returns gently.", "finished": "Preview finished. No late follow-up is stored.", "npc": "Silent: NPC / narration owns the moment. This reaction is discarded.", "stale": "Silent: the cue has passed. Leo does not explain an old event.", "cooldown": "Silent: Leo just spoke. A new event can qualify after the gap.", "occupied": "Other speech keeps the shared music bed low. Leo adds no new fade.", "review": "Text timing only. No sound plays and no voice is generated.", "randomCue": "Quiet thought. It makes no claim about a recent event.", "randomBlock": "No quiet opening: skip this thought window; never build a backlog."},
  "cadence": [],
  "draftLines": [{"id": "D01", "text": "Finally. Stubborn little bastard.", "emotion": "exasperated", "decision": "draft", "group": "new-draft"}, {"id": "D02", "text": "Airborne. Against my better judgement.", "emotion": "nervous amusement", "decision": "draft", "group": "new-draft"}, {"id": "D03", "text": "Feet down. Pride mostly intact.", "emotion": "relieved", "decision": "draft", "group": "new-draft"}, {"id": "D04", "text": "Power gone. Easy on the landing.", "emotion": "focused", "decision": "draft", "group": "new-draft"}, {"id": "D05", "text": "Rock wins this round.", "emotion": "grudging", "decision": "draft", "group": "new-draft"}, {"id": "D06", "text": "Warm fire. Low ambitions.", "emotion": "content", "decision": "draft", "group": "new-draft"}, {"id": "D07", "text": "Rich in dirt. Short on cash.", "emotion": "wry", "decision": "draft", "group": "new-draft"}, {"id": "D08", "text": "Still missing materials. Of course.", "emotion": "resigned", "decision": "draft", "group": "new-draft"}, {"id": "D09", "text": "Paid. Briefly a respectable profession.", "emotion": "pleased", "decision": "draft", "group": "new-draft"}],
  "moments": [
    {
      "id": "work",
      "title": "Doing the work",
      "repeat": "At most one work remark per 90 s. Fresh activity earns an opportunity; holding the dig button never becomes a speech timer.",
      "change": "Recognize ordinary mining, including work that awards no special ore.",
      "avoid": "No idle timer, paused game, swings into empty air or invented exhaustion.",
      "line": "L011",
      "before": "You have not started mining",
      "cue": "A real mining hit lands",
      "trigger": "The first successful mining hit after leaving Town or deliberately starting a new work stretch. An impact, damaged tile or broken block is enough evidence.",
      "delivery": "A resigned little smile. This is his job, unfortunately.",
      "delayMs": 450,
      "expiryMs": 2500,
      "place": "DOING THE WORK",
      "caseTitle": "Start digging",
      "situations": [
        {"title": "Start digging", "line": "L011", "before": "You have not started mining", "cue": "A real mining hit lands", "trigger": "The first successful mining hit after leaving Town or deliberately starting a new work stretch. An impact, damaged tile or broken block is enough evidence.", "delivery": "A resigned little smile. This is his job, unfortunately.", "delayMs": 450, "expiryMs": 6000, "place": "DOING THE WORK", "script": {"id": "L011", "text": "Smells like work. Unfortunate.", "emotion": "dry", "decision": "yes"}},
        {"title": "Get back to work", "line": "L007", "before": "A real break or travel stretch", "cue": "Mining resumes · the wall takes damage", "trigger": "Resume successful digging after a real break or travel segment. React while the player is actually mining, without requiring depth, rare ore or a new record.", "delivery": "A private bad joke, already back to the grind.", "delayMs": 450, "expiryMs": 6000, "place": "DOING THE WORK", "script": {"id": "L007", "text": "Well, this beats another interview.", "emotion": "amused", "decision": "yes"}},
        {"title": "A stubborn rock breaks", "line": "D01", "before": "Several effective hits on the same hard rock", "cue": "That damaged rock finally breaks", "trigger": "The same resistant tile finally breaks after repeated successful hits. Confirm its destruction; do not infer frustration from elapsed time alone.", "delivery": "One exasperated breath. Emphasize “hard way”.", "delayMs": 450, "expiryMs": 2500, "place": "DOING THE WORK", "script": {"id": "D01", "text": "Finally. Stubborn little bastard.", "emotion": "exasperated", "decision": "draft"}},
      ]
    },
    {
      "id": "travel",
      "title": "Going somewhere",
      "repeat": "One line per meaningful departure, arrival or region crossing. Repeated boundary shuffling does not create new journeys.",
      "change": "Remove the 20 m departure and 100 m return gates. Actual travelling and work establish the context.",
      "avoid": "No save-load, opening a map, a tiny boundary loop, or a daylight line at night.",
      "line": "L001",
      "before": "Leaving Town for the mine",
      "cue": "You enter the underground passage",
      "trigger": "A real departure enters underground space. Walking, digging or flying there all qualify; no exact depth milestone is required.",
      "delivery": "A small sigh, then getting on with it.",
      "delayMs": 450,
      "expiryMs": 2500,
      "place": "GOING SOMEWHERE",
      "caseTitle": "Head underground",
      "situations": [
        {"title": "Head underground", "line": "L001", "before": "Leaving Town for the mine", "cue": "You enter the underground passage", "trigger": "A real departure enters underground space. Walking, digging or flying there all qualify; no exact depth milestone is required.", "delivery": "A small sigh, then getting on with it.", "delayMs": 450, "expiryMs": 2500, "place": "GOING SOMEWHERE", "script": {"id": "L001", "text": "Down we go. Rent won't pay itself.", "emotion": "wry", "decision": "yes"}},
        {"title": "Come back with a trip behind you", "line": "L196", "before": "You have actually worked or collected underground", "cue": "You arrive in Town", "trigger": "Re-enter Town after an actual underground work stretch, collection trip or exploration segment. The visible arrival is enough; a numeric depth minimum is not.", "delivery": "His shoulders drop. He really wants that chair.", "delayMs": 450, "expiryMs": 2500, "place": "GOING SOMEWHERE", "script": {"id": "L196", "text": "Town again. Gods, I need a chair.", "emotion": "relieved", "decision": "yes"}},
        {"title": "The surroundings change", "line": "L101", "before": "Moving between visibly different surroundings", "cue": "Different scenery surrounds you", "trigger": "Cross into a visibly different region, including revisiting it after travelling elsewhere. New scenery or a named region transition is enough; it need not be a first-ever discovery.", "delivery": "Interested, a little wary. He notices the place.", "delayMs": 450, "expiryMs": 2500, "place": "GOING SOMEWHERE", "script": {"id": "L101", "text": "This part of the mine feels different.", "emotion": "curious", "decision": "yes"}},
      ]
    },
    {
      "id": "ore",
      "title": "Finding something worth taking",
      "repeat": "One ore reaction per 45 s across materials. First pickup, a new vein, resumed mining and a fresh find after travelling all qualify.",
      "change": "Many ordinary collection contexts feed this family. The actual awarded material chooses the sentence.",
      "avoid": "Never substitute one material for another. Seeing a vein, earning coins and a failed pickup do not count as collecting ore.",
      "line": "L019",
      "oreMaterial": "bronze",
      "before": "Bronze has not entered the haul",
      "cue": "+ Bronze · collection confirmed",
      "trigger": "Any fresh positive bronze award after the gap: first bronze, another vein, returning to mining or a later collection burst. Pickup feedback OR a visible inventory increase is enough.",
      "delivery": "Practical approval. Something he can use.",
      "delayMs": 450,
      "expiryMs": 2500,
      "place": "FINDING SOMETHING WORTH TAKING",
      "caseTitle": "Bronze collected",
      "situations": [
        {"title": "Bronze collected", "line": "L019", "oreMaterial": "bronze", "before": "Bronze has not entered the haul", "cue": "+ Bronze · collection confirmed", "trigger": "Any fresh positive bronze award after the gap: first bronze, another vein, returning to mining or a later collection burst. Pickup feedback OR a visible inventory increase is enough.", "delivery": "Practical approval. Something he can use.", "delayMs": 450, "expiryMs": 2500, "place": "FINDING SOMETHING WORTH TAKING", "script": {"id": "L019", "text": "Bronze. I can work with that.", "emotion": "steady", "decision": "yes"}},
        {"title": "Iron collected", "line": "L029", "oreMaterial": "iron", "before": "Iron has not entered the haul", "cue": "+ Iron · collection confirmed", "trigger": "A fresh positive iron award, whether ordinary mining, a newly reached deposit or collection after travel. Choose an iron sentence only.", "delivery": "Appreciation, then a dry jab at the old employer.", "delayMs": 450, "expiryMs": 2500, "place": "FINDING SOMETHING WORTH TAKING", "script": {"id": "L029", "text": "Iron. Useful. Unlike my last employer.", "emotion": "dry", "decision": "yes"}},
        {"title": "Silver collected", "line": "L042", "oreMaterial": "silver", "before": "Silver has not entered the haul", "cue": "+ Silver · collection confirmed", "trigger": "A fresh positive silver award. A pickup cue or inventory change corroborates collection; no first-ever flag, bag band or visible floating label is mandatory.", "delivery": "A little real financial relief.", "delayMs": 450, "expiryMs": 2500, "place": "FINDING SOMETHING WORTH TAKING", "script": {"id": "L042", "text": "Ah, silver. My debts look smaller.", "emotion": "relieved", "decision": "yes"}},
        {"title": "Gold ore collected", "line": "L056", "oreMaterial": "gold", "before": "Gold ore has not entered the haul", "cue": "+ Gold ore · collection confirmed", "trigger": "A fresh positive gold-ore award in any normal collection context. Its pickup cue, inventory increase or material reward feedback establishes the connection.", "delivery": "Warm delight. Smile on “bad influence”.", "delayMs": 450, "expiryMs": 2500, "place": "FINDING SOMETHING WORTH TAKING", "script": {"id": "L056", "text": "Gold. My favourite bad influence.", "emotion": "warm", "decision": "yes"}},
      ]
    },
    {
      "id": "haul",
      "title": "A productive stretch",
      "repeat": "One haul remark per 90 s while fresh collection supports it. A haul line wins over a generic ore line from the same pickup.",
      "change": "A good haul can be recognized before the bag reaches its final visual band.",
      "avoid": "No inventory capacity claim. Old saved stock, a purchase or a single trivial pickup is not a productive mining stretch.",
      "line": "L185",
      "before": "Mining a productive patch",
      "cue": "Several ore awards join the haul",
      "trigger": "A cluster of successful ore awards builds a clearly noticeable haul. The recent pickup sequence itself provides the cue; no final bag band is required.",
      "delivery": "Supper is becoming a realistic prospect.",
      "delayMs": 450,
      "expiryMs": 2500,
      "place": "A PRODUCTIVE STRETCH",
      "caseTitle": "Several useful finds together",
      "situations": [
        {"title": "Several useful finds together", "line": "L185", "before": "Mining a productive patch", "cue": "Several ore awards join the haul", "trigger": "A cluster of successful ore awards builds a clearly noticeable haul. The recent pickup sequence itself provides the cue; no final bag band is required.", "delivery": "Supper is becoming a realistic prospect.", "delayMs": 450, "expiryMs": 2500, "place": "A PRODUCTIVE STRETCH", "script": {"id": "L185", "text": "All that ore. Supper's looking better.", "emotion": "hopeful", "decision": "yes"}},
        {"title": "A valuable haul improves", "line": "L189", "before": "Carrying the ore earned this trip", "cue": "A fresh valuable pickup improves the haul", "trigger": "A fresh valuable award materially improves what was earned this trip. Judge the actual collected mix, not a universal bag percentage.", "delivery": "A small, satisfied grin.", "delayMs": 450, "expiryMs": 2500, "place": "A PRODUCTIVE STRETCH", "script": {"id": "L189", "text": "Bag's looking profitable. Finally.", "emotion": "amused", "decision": "yes"}},
        {"title": "The bag visibly fills out", "line": "L181", "before": "The bag is below its next visual band", "cue": "Fresh ore · bag visibly fills out", "trigger": "New collection crosses a noticeable bag-display band. Any substantial visible increase may qualify; it does not have to be the last band.", "delivery": "Pleased, with an affectionate complaint about his back.", "delayMs": 450, "expiryMs": 2500, "place": "A PRODUCTIVE STRETCH", "script": {"id": "L181", "text": "Quite a haul. My back noticed.", "emotion": "weary", "decision": "yes"}},
      ]
    },
    {
      "id": "flight",
      "title": "Using flight",
      "repeat": "One travel/flight remark per 90 s. A brief hop or repeated Shift tapping does not count. Power-loss warnings are separate urgent opportunities.",
      "change": "Add reactions to a movement tool the player actually uses.",
      "avoid": "No takeoff line while grounded. No “power gone” claim unless powered flight really loses its reserve.",
      "line": "D02",
      "before": "Grounded, about to use powered flight",
      "cue": "Powered flight carries you clear of the ground",
      "trigger": "A grounded-to-airborne powered takeoff becomes sustained travel. Let the player visibly leave the ground before the remark.",
      "delivery": "A little thrill under the nerves.",
      "delayMs": 450,
      "expiryMs": 2500,
      "place": "USING FLIGHT",
      "caseTitle": "A real takeoff",
      "situations": [
        {"title": "A real takeoff", "line": "D02", "before": "Grounded, about to use powered flight", "cue": "Powered flight carries you clear of the ground", "trigger": "A grounded-to-airborne powered takeoff becomes sustained travel. Let the player visibly leave the ground before the remark.", "delivery": "A little thrill under the nerves.", "delayMs": 450, "expiryMs": 2500, "place": "USING FLIGHT", "script": {"id": "D02", "text": "Airborne. Against my better judgement.", "emotion": "nervous amusement", "decision": "draft"}},
        {"title": "Land after a flight", "line": "D03", "before": "Finishing a sustained flight", "cue": "Your feet settle on solid ground", "trigger": "A real airborne flight ends in stable grounded contact. A jump, a momentary collision and still falling do not qualify.", "delivery": "Relief with a dent in his dignity.", "delayMs": 450, "expiryMs": 2500, "place": "USING FLIGHT", "script": {"id": "D03", "text": "Feet down. Pride mostly intact.", "emotion": "relieved", "decision": "draft"}},
        {"title": "Power runs out in the air", "line": "D04", "urgent": true, "before": "Powered flight with remaining reserve", "cue": "Reserve empties · powered flight cuts out", "trigger": "The flight reserve actually becomes empty while airborne and powered motion stops. The empty meter or loss of thrust is the cue.", "delivery": "Clear and focused. No comic delay.", "delayMs": 0, "expiryMs": 900, "place": "USING FLIGHT", "script": {"id": "D04", "text": "Power gone. Easy on the landing.", "emotion": "focused", "decision": "draft"}},
      ]
    },
    {
      "id": "danger",
      "title": "Something is actually wrong",
      "repeat": "Once per new danger episode. Never speak over another voice; the visual warning remains available.",
      "change": "Cover distinct actionable trouble with distinct words, rather than routing every problem to a rockfall sentence.",
      "avoid": "No distant quake warnings, Normal-mode stress claims or repeating a refusal every frame.",
      "line": "L135",
      "before": "No active fall zone threatens you",
      "cue": "Rockfall threatens your immediate position",
      "trigger": "A live falling-rock threat reaches the player area. The danger marker, visible approaching rocks or actual fall-zone overlap can establish relevance.",
      "delivery": "Immediate and unmistakable.",
      "delayMs": 0,
      "expiryMs": 900,
      "place": "SOMETHING IS ACTUALLY WRONG",
      "caseTitle": "Rocks threaten your position",
      "situations": [
        {"title": "Rocks threaten your position", "line": "L135", "urgent": true, "before": "No active fall zone threatens you", "cue": "Rockfall threatens your immediate position", "trigger": "A live falling-rock threat reaches the player area. The danger marker, visible approaching rocks or actual fall-zone overlap can establish relevance.", "delivery": "Immediate and unmistakable.", "delayMs": 0, "expiryMs": 900, "place": "SOMETHING IS ACTUALLY WRONG", "script": {"id": "L135", "text": "Rocks coming down. Move!", "emotion": "alarmed", "decision": "yes"}},
        {"title": "Hardcore stress becomes critical", "line": "L164", "urgent": true, "before": "Stress is below critical", "cue": "Critical stress becomes visible", "trigger": "Hardcore stress really crosses into critical and remains actionable. Use its warning or meter transition; no unrelated injury assumption.", "delivery": "Trying to steady himself while staying understandable.", "delayMs": 0, "expiryMs": 900, "place": "SOMETHING IS ACTUALLY WRONG", "script": {"id": "L164", "text": "Easy. Get safe. Then breathe.", "emotion": "self-reassuring", "decision": "yes"}},
        {"title": "The surface cannot be mined", "line": "D05", "before": "Trying to mine the surface in front of you", "cue": "Mining is refused · surface remains intact", "trigger": "A deliberate mining attempt is rejected because this surface is unbreakable, with refusal feedback. A mere miss or an ordinary tough tile does not qualify.", "delivery": "Grudging acceptance, not a gameplay instruction.", "delayMs": 450, "expiryMs": 2500, "place": "SOMETHING IS ACTUALLY WRONG", "script": {"id": "D05", "text": "Rock wins this round.", "emotion": "grudging", "decision": "draft"}},
      ]
    },
    {
      "id": "relief",
      "title": "Getting through it",
      "repeat": "One relief response per resolved episode. Choose the warning or the aftermath if both would be crowded; do not force a pair.",
      "change": "Relief follows the actual end of a threat, with a brief contextual window while the player remains safe.",
      "avoid": "No joke during renewed danger, after death, or about a quake that never threatened the player.",
      "line": "L147",
      "before": "A rockfall genuinely threatened you",
      "cue": "The falling rocks stop · you are safe",
      "trigger": "A personally threatening quake or rockfall ends and the player remains safe. Use the ended hazard and current safety; an extra reward or summary popup is unnecessary.",
      "delivery": "A rattled exhale. The laugh is almost involuntary.",
      "expiryMs": 6000,
      "delayMs": 450,
      "place": "GETTING THROUGH IT",
      "caseTitle": "A close call is over",
      "situations": [
        {"title": "A close call is over", "line": "L147", "before": "A rockfall genuinely threatened you", "cue": "The falling rocks stop · you are safe", "trigger": "A personally threatening quake or rockfall ends and the player remains safe. Use the ended hazard and current safety; an extra reward or summary popup is unnecessary.", "delivery": "A rattled exhale. The laugh is almost involuntary.", "expiryMs": 6000, "delayMs": 450, "place": "GETTING THROUGH IT", "script": {"id": "L147", "text": "Fuck me. Still breathing.", "emotion": "breathless", "decision": "yes"}},
        {"title": "Your nerve comes back", "line": "L175", "before": "A real critical-stress episode", "cue": "Stress settles · its warning clears", "trigger": "A real Hardcore stress episode returns to calm. The changed meter, cleared warning and safe state establish the moment without another special event.", "delivery": "Quiet relief and fond self-mockery.", "expiryMs": 6000, "delayMs": 450, "place": "GETTING THROUGH IT", "script": {"id": "L175", "text": "There's my nerve. Welcome back.", "emotion": "warm", "decision": "yes"}},
      ]
    },
    {
      "id": "money",
      "title": "Buying, selling and being broke",
      "repeat": "One reaction per transaction outcome, with a shared 60 s transaction gap. NPC dialogue owns the whole conversation, including pauses.",
      "change": "Remove the wallet-percentage gate and add clear failure and sale outcomes.",
      "avoid": "Never say “bought” after failure, “paid” without a sale payout, or “short on cash” when materials are the actual problem.",
      "line": "L212",
      "before": "A real upgrade purchase is pending",
      "cue": "Upgrade purchased · the new state appears",
      "trigger": "Any deliberate paid upgrade succeeds and shows its confirmation or changed level. It does not need to spend 20% of the wallet.",
      "delivery": "A little buyer’s remorse, then a crooked smile.",
      "delayMs": 450,
      "expiryMs": 2500,
      "place": "BUYING, SELLING AND BEING BROKE",
      "caseTitle": "An upgrade succeeds",
      "situations": [
        {"title": "An upgrade succeeds", "line": "L212", "before": "A real upgrade purchase is pending", "cue": "Upgrade purchased · the new state appears", "trigger": "Any deliberate paid upgrade succeeds and shows its confirmation or changed level. It does not need to spend 20% of the wallet.", "delivery": "A little buyer’s remorse, then a crooked smile.", "delayMs": 450, "expiryMs": 2500, "place": "BUYING, SELLING AND BEING BROKE", "script": {"id": "L212", "text": "Upgrade paid. Complaining is still free.", "emotion": "dry", "decision": "yes"}},
        {"title": "Not enough money", "line": "D07", "before": "Trying to buy an upgrade", "cue": "Purchase refused · not enough money", "trigger": "A deliberate buy attempt returns the specific insufficient-money result and its feedback is visible. Wait only if the same moment remains current and the merchant is finished.", "delivery": "Resigned amusement. A very familiar problem.", "delayMs": 450, "expiryMs": 2500, "place": "BUYING, SELLING AND BEING BROKE", "script": {"id": "D07", "text": "Rich in dirt. Short on cash.", "emotion": "wry", "decision": "draft"}},
        {"title": "Missing materials", "line": "D08", "before": "Trying to buy an upgrade", "cue": "Purchase refused · required materials missing", "trigger": "The actual purchase failure is missing materials, with visible feedback. Do not confuse this with money, level locks or maxed upgrades.", "delivery": "A sigh that stops short of a tantrum.", "delayMs": 450, "expiryMs": 2500, "place": "BUYING, SELLING AND BEING BROKE", "script": {"id": "D08", "text": "Still missing materials. Of course.", "emotion": "resigned", "decision": "draft"}},
        {"title": "Ore becomes money", "line": "D09", "before": "A deliberate sale is pending", "cue": "Ore sold · payment received", "trigger": "A real sale commits: sold resources decrease and the wallet receives the payout. Single-material sales and selling the haul both qualify after the merchant releases speech.", "delivery": "Genuinely pleased, then undercutting his own dignity.", "delayMs": 450, "expiryMs": 2500, "place": "BUYING, SELLING AND BEING BROKE", "script": {"id": "D09", "text": "Paid. Briefly a respectable profession.", "emotion": "pleased", "decision": "draft"}},
      ]
    },
    {
      "id": "progress",
      "title": "Getting better at this",
      "repeat": "One response per real advancement. Multiple rewards from the same award share one reaction.",
      "change": "Use actual advancement and a visible change; extra depth, wallet and first-session gates are unnecessary.",
      "avoid": "No level-up sentence on ordinary XP. No “new talent” on a hover or repeated rank.",
      "line": "L221",
      "before": "XP below the next level",
      "cue": "Level increases · level-up feedback",
      "trigger": "Gameplay XP increases the actual level. The new level number or its level-up effect is enough; a second notification is not required.",
      "delivery": "Let him take honest pride in it.",
      "delayMs": 450,
      "expiryMs": 2500,
      "place": "GETTING BETTER AT THIS",
      "caseTitle": "A level gained",
      "situations": [
        {"title": "A level gained", "line": "L221", "before": "XP below the next level", "cue": "Level increases · level-up feedback", "trigger": "Gameplay XP increases the actual level. The new level number or its level-up effect is enough; a second notification is not required.", "delivery": "Let him take honest pride in it.", "delayMs": 450, "expiryMs": 2500, "place": "GETTING BETTER AT THIS", "script": {"id": "L221", "text": "Another level. Earned that one.", "emotion": "satisfied", "decision": "yes"}},
        {"title": "A new talent learned", "line": "L232", "before": "The talent is not yet owned", "cue": "Talent purchased · its node lights up", "trigger": "An intentional first-rank talent purchase succeeds. The lit node or successful unlock confirmation is enough, after any tutorial speech.", "delivery": "Amused by his own age, with one small unanswered question.", "delayMs": 450, "expiryMs": 2500, "place": "GETTING BETTER AT THIS", "script": {"id": "L232", "text": "Learned something new. At my age.", "emotion": "surprised", "decision": "yes"}},
        {"title": "Your old depth record is beaten", "line": "L121", "before": "Approaching the previous personal best", "cue": "Old best passed · new record confirmed", "trigger": "The player genuinely passes the previous record. The best-depth HUD or record feedback confirms it; a milestone occurring too receives no second line.", "delivery": "Proud enough that pretending otherwise is funny.", "delayMs": 450, "expiryMs": 2500, "place": "GETTING BETTER AT THIS", "script": {"id": "L121", "text": "New record. Act casual.", "emotion": "pleased", "decision": "yes"}},
        {"title": "A depth milestone reached", "line": "L115", "before": "Approaching a real depth milestone", "cue": "Depth milestone reached · feedback appears", "trigger": "A real depth milestone is reached and its depth or reward feedback appears. It can qualify even when it is not a new personal best; overlapping record and milestone get only one line.", "delivery": "A proud little complaint from his knees.", "delayMs": 450, "expiryMs": 2500, "place": "GETTING BETTER AT THIS", "script": {"id": "L115", "text": "That's progress. My knees disagree.", "emotion": "amused", "decision": "yes"}},
      ]
    },
    {
      "id": "home",
      "title": "The fire and the things he cares about",
      "repeat": "One response per deliberate rest, activation or growth. Merely passing the same prop never retriggers the family.",
      "change": "Allow a quiet, intentional rest to show warmth as well as rare upgrades.",
      "avoid": "No automatic-refill blessing claim, imagined healing, ordinary flame flicker or swaying-leaf growth claim.",
      "line": "D06",
      "before": "Returning from actual work or travel",
      "cue": "You stop and settle beside the fire",
      "trigger": "After work or travel, deliberately remain beside the campfire for a quiet rest. No charge, tier upgrade or healing event is required; passing by does not qualify.",
      "delivery": "Soft, comfortable and a little pleased with his low standards.",
      "expiryMs": 6000,
      "delayMs": 450,
      "place": "THE FIRE AND THE THINGS HE CARES ABOUT",
      "caseTitle": "Settle beside the fire",
      "situations": [
        {"title": "Settle beside the fire", "line": "D06", "before": "Returning from actual work or travel", "cue": "You stop and settle beside the fire", "trigger": "After work or travel, deliberately remain beside the campfire for a quiet rest. No charge, tier upgrade or healing event is required; passing by does not qualify.", "delivery": "Soft, comfortable and a little pleased with his low standards.", "expiryMs": 6000, "delayMs": 450, "place": "THE FIRE AND THE THINGS HE CARES ABOUT", "script": {"id": "D06", "text": "Warm fire. Low ambitions.", "emotion": "content", "decision": "draft"}},
        {"title": "Ignite a blessing", "line": "L244", "before": "A blessing has not been activated", "cue": "A charge is spent · blessing ignites", "trigger": "A deliberate campfire action successfully activates a blessing. The ignition or changed active-blessing state confirms it.", "delivery": "Simple gratitude to an old friend.", "delayMs": 450, "expiryMs": 2500, "place": "THE FIRE AND THE THINGS HE CARES ABOUT", "script": {"id": "L244", "text": "Blessing taken. Thank you, old friend.", "emotion": "tender", "decision": "yes"}},
        {"title": "The campfire grows", "line": "L257", "before": "The flame is at its previous growth tier", "cue": "An upgrade reveals a larger fire", "trigger": "A real tier upgrade makes the flame visibly larger. Its visible growth is enough; another toast is not required.", "delivery": "Already imagining a longer break.", "delayMs": 450, "expiryMs": 2500, "place": "THE FIRE AND THE THINGS HE CARES ABOUT", "script": {"id": "L257", "text": "Bigger flame. Bigger excuse to sit.", "emotion": "amused", "decision": "yes"}},
        {"title": "Worldroot grows", "line": "L269", "before": "The tree remains at its previous stage", "cue": "The tree’s silhouette expands", "trigger": "A new growth stage actually becomes visible. When the same action also grows the fire, choose the more prominent visible change and speak once.", "delivery": "Affection disguised as teasing.", "delayMs": 450, "expiryMs": 2500, "place": "THE FIRE AND THE THINGS HE CARES ABOUT", "script": {"id": "L269", "text": "The tree grew. Show-off.", "emotion": "playful", "decision": "yes"}},
      ]
    },
    {
      "id": "discovery",
      "title": "Finding the strange things",
      "repeat": "One response per real find or encounter. These remain rarer character moments; everyday mining carries ordinary frequency.",
      "change": "Accept the relevant object or reward state as evidence; do not require every presentation cue simultaneously.",
      "avoid": "No line over a cinematic, no recognition of an off-screen face, and no collected-Star claim on a zero reward.",
      "line": "L062",
      "before": "An Ember find has not resolved",
      "cue": "Ember gained · reveal finishes",
      "trigger": "A real new Ember award resolves. The Ember, reward feedback or changed charge state confirms the find after the reveal.",
      "delivery": "Tender, almost protective.",
      "delayMs": 450,
      "expiryMs": 2500,
      "place": "FINDING THE STRANGE THINGS",
      "caseTitle": "An Ember found",
      "situations": [
        {"title": "An Ember found", "line": "L062", "before": "An Ember find has not resolved", "cue": "Ember gained · reveal finishes", "trigger": "A real new Ember award resolves. The Ember, reward feedback or changed charge state confirms the find after the reveal.", "delivery": "Tender, almost protective.", "delayMs": 450, "expiryMs": 2500, "place": "FINDING THE STRANGE THINGS", "script": {"id": "L062", "text": "Hello, little Ember. Let's get you home.", "emotion": "warm", "decision": "yes"}},
        {"title": "A Star collected", "line": "L073", "before": "A Star is still being revealed", "cue": "Star collected · its light remains", "trigger": "A positive Star award commits. After narration, its visible light gives “that light” a clear referent; no extra inventory popup is required.", "delivery": "Recognition he did not mean to let slip.", "delayMs": 1200, "expiryMs": 2500, "place": "FINDING THE STRANGE THINGS", "script": {"id": "L073", "text": "I remember that light.", "emotion": "tender", "decision": "yes"}},
        {"title": "A Titan revealed", "line": "L088", "before": "The Titan introduction still owns speech", "cue": "The introduction ends · the Titan remains visible", "trigger": "A real Titan introduction ends with that Titan still in view. Its face is the link; do not insist on a second unlock toast after the cinematic.", "delivery": "Startled personal recognition. There is history here.", "delayMs": 1200, "expiryMs": 2500, "place": "FINDING THE STRANGE THINGS", "script": {"id": "L088", "text": "Ah, shit. You again.", "emotion": "startled", "decision": "yes"}},
      ]
    },
    {
      "id": "random",
      "title": "A rare unprompted thought",
      "repeat": "One opportunity after 27–33 active minutes; keep the two-minute quiet window and never catch up missed thoughts.",
      "change": "This is the only event-free family. Broader everyday coverage does not turn into more random chatter.",
      "avoid": "No danger, NPC conversation, narration, menus or hidden-tab time. A fresh event takes priority.",
      "line": "L289",
      "random": true,
      "before": "Active play has not reached a quiet opportunity",
      "cue": "27–33 active minutes · a safe quiet opening",
      "trigger": "After 27–33 active minutes, allow a thought while safe, after 20 s without other speech and 90 s since Leo. No claim that the player just found or did something.",
      "delivery": "An absent recollection that leaves even him a little uncertain.",
      "expiryMs": 0,
      "delayMs": 450,
      "place": "A RARE UNPROMPTED THOUGHT",
      "caseTitle": "A quiet thought",
      "situations": [
        {"title": "A quiet thought", "line": "L289", "random": true, "before": "Active play has not reached a quiet opportunity", "cue": "27–33 active minutes · a safe quiet opening", "trigger": "After 27–33 active minutes, allow a thought while safe, after 20 s without other speech and 90 s since Leo. No claim that the player just found or did something.", "delivery": "An absent recollection that leaves even him a little uncertain.", "expiryMs": 0, "delayMs": 450, "place": "A RARE UNPROMPTED THOUGHT", "script": {"id": "L289", "text": "Some nights, I remember a different moon.", "emotion": "wistful", "decision": "yes"}},
      ]
    },
  ]
};
