// Shared player advice: the pause library and the generated public wiki.
export const PLAYER_HINTS = Object.freeze([
  { id: "mining", title: "How do I dig?", category: "Getting started", section: "core-loop", keywords: "mine mining stuck cannot break blocks mouse click pickaxe",
    body: "Stand beside a solid tile, aim with {moveLeft}/{moveRight}/{aimUp}/{aimDown}, and hold {dig}. You can also hold the primary mouse button over a nearby tile. Tough blocks take several hits. Close menus before digging." },
  { id: "flight", title: "How do I fly?", category: "Movement", section: "flight", keywords: "fly flying flight shift jump gem unlock tutorial",
    body: "After the opening gives you Flight, hold {fly} in the air. Steer with {moveLeft}/{moveRight}; {aimUp}/{aimDown} build vertical momentum. Release Flight to stop its GP drain. {jump} is a separate, fixed-height jump." },
  { id: "low-gp", title: "Low on Gem Power", category: "Survival", section: "flight", keywords: "gp energy empty mana refill regenerate out of power stuck underground",
    body: "Land in a safe, lit place. Release {fly} and {quickslash}, and stop powered movement so GP can recover. Lower the torch intensity if needed; in Hardcore, keep enough light to control stress. Return through an activated portal when you can afford its displayed cost." },
  { id: "torch", title: "Seeing in the dark", category: "Survival", section: "abilities", keywords: "torch darkness dark light lamp brightness intensity wheel",
    body: "Press {torch} to toggle your torch. Click or wheel its HUD meter to adjust intensity. Brighter light uses more GP. In Hardcore, darkness raises stress, so find light before letting your reserve run out." },
  { id: "run", requiresAction: "run", title: "Run along the ground", category: "Movement", section: "controls", keywords: "run sprint ctrl control fast walk",
    body: "Hold {run} while moving with {moveLeft}/{moveRight} to run. Running consumes GP; release it to walk and conserve power. Use {fly} for powered movement in the air." },
  { id: "portals", title: "Return without losing your route", category: "Exploration", section: "portals", keywords: "portal teleport gate surface town return resume go back",
    body: "Approach a discovered portal and press {interact} when its prompt appears. Activated portals preserve return routes. Back in town, Esc > General offers Resume Deepest Portal when a usable destination exists. Check its GP cost first." },
  { id: "sell", title: "Turn your haul into upgrades", category: "Town", section: "town", keywords: "sell selling cargo money monster merchant coins bag full storage capacity",
    body: "Visit the Money Monster and press {interact} to sell your mined resources. Buy upgrades with the proceeds. Your bag picture shows how much you carry; it is not a hard inventory limit. Check {inventory} for exact holdings." },
  { id: "upgrades", title: "Why is an upgrade locked?", category: "Progression", section: "town", keywords: "buy unlock locked shop bobo pickaxe level depth relic requirement",
    body: "Read the requirement shown on the shop row. Upgrades can require player level, deepest depth, Relics, money, or materials. Buying an earlier rank does not bypass the next unlock requirement. Journey shows your progress." },
  { id: "talents", title: "Talent Points and Stars", category: "Progression", section: "celestial", keywords: "talent points tp star points sp spend skill tree level three 3",
    body: "Open Esc > Stars. The trees open at player level 3. Level-earned Talent Points unlock new nodes; Star Points improve ranks on nodes you already own. Select a node to read its prerequisites and price, then use its action button." },
  { id: "powers", title: "Choose a Celestial power", category: "Progression", section: "celestial", keywords: "wayward star hollow sun stellar lance rage engine ability power activate",
    body: "Esc > Stars contains Wayward Star, Hollow Sun, and Stellar Lance. Unlock a tree's ability node, then use its Celestial action-bar control. Read the displayed GP cost and cooldown. The base abilities and their later talent ranks are separate purchases." },
  { id: "ember", title: "Ember and the Campfire", category: "Town", section: "town", keywords: "ember ore charges campfire fire blessing refills rest fuel",
    body: "Ember Ore adds Campfire charges. Return to the Campfire and press {interact} to inspect its blessings, stored charges, and upgrades. Choose a blessing in the Campfire menu, then use its action-bar control to spend a charge." },
  { id: "earthquake", title: "An earthquake is warning you", category: "Survival", section: "events", keywords: "earthquake quake falling rocks rubble hazard warning",
    body: "Move out of the marked falling-rock area before impact. Walk or fly toward clear ground and keep an exit open. Once the fall ends, the rubble can be mined. Watch the actual warning markers, not just the screen shake." },
  { id: "wurm", title: "Avoid the Graveborer Wurm", category: "Survival", section: "events", keywords: "worm wurm graveborer breach noise danger",
    body: "Mining noise can draw a Graveborer Wurm. Watch its breach warning and move out of the marked path before it arrives. Preserve GP for an escape and avoid standing on the breach line." },
  { id: "hardcore", title: "Protect a Hardcore run", category: "Survival", section: "modes", keywords: "hardcore life lives death stress panic zero gp safe",
    body: "Once Hardcore is armed, hazards and loss of GP can cost a revive or life. Light, nearby Stars, and the surface help recovery. Keep a powered escape route. Importing or restoring a backup does not rewind Hardcore lives." },
  { id: "codex", title: "Identify a resource or Star", category: "Exploration", section: "interface", keywords: "inventory codex star atlas rarity resource ore inspect material colors",
    body: "Open {inventory}. Holdings shows quantities, Resource Codex explains materials, and Special Blocks explains unusual finds. Star Codex appears when its progression unlocks; browse its Star identities by rarity and page to inspect artwork and discovery details." },
  { id: "save", title: "Keep a backup of this save", category: "Menus", section: "modes", keywords: "save backup export import download lost progress json browser",
    body: "Open Esc > Saves to save or export this slot as a JSON file. Import replaces the selected slot after keeping a backup. Keep exported files somewhere safe, especially before clearing browser data or changing browser profiles." },
]);

export const PLAYER_HINT_CONFIG = Object.freeze({
  lowGpRatio: 0.25,
  recommendedScore: 30,
  priority: Object.freeze({ mining: 10, portals: 30, sell: 30, ember: 45, talents: 50, hardcore: 40,
    torch: 55, lowGp: 80, earthquake: 100, wurm: 110, currentStep: 90 }),
  skinKey: "ui-hud-approved-buff-chip",
  copy: Object.freeze({ tab: "HINTS", title: "FIELD GUIDE", subtitle: "Advice for this run comes first. Browse any topic below.",
    current: "YOUR NEXT STEP", relevant: "USEFUL RIGHT NOW", reference: "REFERENCE", page: "{page} / {pages}",
    previous: "PREVIOUS", next: "NEXT", wiki: "READ IN WIKI", all: "BROWSE THE WIKI",
    lowGp: "Your GP reserve is low.", underground: "You are underground.", town: "You are back in town.",
    talent: "You have unspent Talent Points.", ember: "You have Campfire charges.", warning: "A hazard warning is active.",
    darkness: "Your surroundings are dark.", hardcore: "Hardcore is armed." }),
  layout: Object.freeze({ inset: 18, gap: 28, listRatio: 0.38, listMaxWidth: 370,
    titleSize: 19, bodySize: 17, smallSize: 12, listSize: 14, rowHeight: 48, rowGap: 10,
    headerHeight: 66, footerHeight: 54, maxRows: 6, buttonHeight: 38, bodyGap: 22, lineSpacing: 7,
    minTextScale: 0.72, depth: 2504 }),
});
