// Owns the silent Leo trigger-review proposal; no game system imports this file.
export const LEO_TRIGGER_REVIEW = {
  id: 'leo-trigger-review-v1', version: '2026-09-08', reviewOnly: true,
  approvalUrl: './2026-09-07-approved-selection.json', defaultMoment: 'gold',
  storageKey: 'understar-leo-trigger-review-v1', exportName: 'leo-trigger-decisions-v1.json',
  catalogHash: '678a3d6c30870ae87d2288f57268a41097996455d3ec410bcd549f364eb0b99b',
  background: '/sprites/infinate-loops/underground-0-1000/depth-200-400.png',
  oreImage: '/sprites/tiles/tiles-under-1000/resource-{material}-tile/{material}-full-hp.webp',
  timing: { normalGapMs: 25000, oreGapMs: 45000, maxInWindow: 8, windowMs: 300000,
    afterOtherSpeechMs: 1200, urgentGapMs: 45000, randomMinMs: 1620000, randomMaxMs: 1980000,
    randomQuietMs: 20000, randomAfterLeoMs: 90000, randomWindowMs: 120000,
    downMs: 900, leadMs: 450, captionMs: 2800, holdMs: 450, upMs: 2400, duck: .24 },
  copy: {
    ready: 'Ready. The highlighted confirmation will earn the line.',
    cue: 'Visible event confirmed. Music starts easing down.',
    speaking: 'Leo reacts while the same cue is still visible.',
    restore: 'Sentence finished. Music returns gently.',
    finished: 'Preview finished. No late follow-up is stored.',
    npc: 'Silent: NPC / narration owns the moment. This reaction is discarded.',
    stale: 'Silent: the cue has passed. Leo does not explain an old event.',
    cooldown: 'Silent: Leo just spoke. A new event can qualify after the gap.',
    occupied: 'Other speech keeps the shared music bed low. Leo adds no new fade.',
    review: 'Text timing only. No sound plays and no voice is generated.',
    randomCue: 'Quiet thought. It makes no claim about a recent event.',
    randomBlock: 'No quiet opening: skip this thought window; never build a backlog.'
  },
  cadence: [
    { at: '00:08', group: 'descent', line: 'L002', cue: 'Cross 20 m on a new trip', result: 'speak' },
    { at: '00:19', group: 'bronze', line: 'L013', cue: 'Bronze pickup, only 11 s later', result: 'skip', reason: 'Breathing room. The next fresh pickup can qualify.' },
    { at: '00:39', group: 'bronze', line: 'L013', cue: 'Another bronze pickup', result: 'speak' },
    { at: '00:54', group: 'bronze', line: 'L013', cue: 'More bronze, only 15 s later', result: 'skip', reason: 'No remark for every block.' },
    { at: '01:26', group: 'iron', line: 'L029', cue: 'Iron joins the haul, 47 s later', result: 'speak' },
    { at: '01:58', group: 'level', line: 'L221', cue: 'Level-up effect appears', result: 'speak' },
    { at: '02:12', group: 'gold', line: 'L056', cue: 'Gold pickup during NPC dialogue', result: 'skip', reason: 'The NPC keeps the speech channel. No delayed gold line.' },
    { at: '02:50', group: 'gold', line: 'L056', cue: 'Fresh gold pickup in quiet gameplay', result: 'speak' },
    { at: '30:00', group: 'random', line: 'L289', cue: 'A quiet opening after active play', result: 'thought', reason: 'Example opportunity inside the 27–33 minute window.' }
  ],
  moments: [
    { id: 'descent', title: 'Start a mining trip', place: 'MINE ENTRANCE', line: 'L002',
      before: 'You are still above 20 m', cue: '20 m crossed · underground view',
      trigger: 'Walk or dig below 20 m on a real trip from Town. The mine is visible and you are safe.',
      repeat: 'Once per trip. A loaded save or teleport never counts as a new departure.',
      change: 'Repeat on new trips instead of only once per save.', avoid: 'No surface stroll, save-load or invisible depth update.',
      delivery: 'A tired smile. Let “lovely” carry the joke.', delayMs: 450, expiryMs: 2500 },
    { id: 'bronze', title: 'Collect bronze', place: 'ORE PICKUP', line: 'L013', ore: true,
      before: 'Bronze is exposed, still in the wall', cue: '+ Bronze · added to your haul',
      trigger: 'A positive bronze award lands and the bronze pickup label is visible.',
      repeat: 'Fresh pickups can qualify again. All four ore types share a 45 s gap.',
      change: 'Repeatable collection, replacing the once-per-save discovery gate.', avoid: 'Seeing or hitting bronze is not collecting it.',
      delivery: 'Small, honest satisfaction. An ordinary win.', delayMs: 450, expiryMs: 2500 },
    { id: 'iron', title: 'Collect iron', place: 'ORE PICKUP', line: 'L029', ore: true,
      before: 'Iron is exposed, still in the wall', cue: '+ Iron · added to your haul',
      trigger: 'A positive iron award lands and its iron pickup label is visible.',
      repeat: 'Fresh pickups can qualify again. Shared ore gap: 45 s.',
      change: 'Repeatable collection, replacing the once-per-save discovery gate.', avoid: 'No bronze, steel, currency or restored inventory.',
      delivery: 'Appreciative at first. A dry little dig at the old boss.', delayMs: 450, expiryMs: 2500 },
    { id: 'silver', title: 'Collect silver', place: 'ORE PICKUP', line: 'L042', ore: true,
      before: 'Silver glints in an unbroken rock', cue: '+ Silver · added to your haul',
      trigger: 'A positive silver award lands and its silver pickup label is visible.',
      repeat: 'Fresh pickups can qualify again. Shared ore gap: 45 s.',
      change: 'Repeatable collection, replacing the once-per-save discovery gate.', avoid: 'No silver scenery, failed pickup or wallet change.',
      delivery: 'Relief, with a little hope he tries to hide.', delayMs: 450, expiryMs: 2500 },
    { id: 'gold', title: 'Collect gold ore', place: 'ORE PICKUP', line: 'L056', ore: true,
      before: 'Gold is exposed, still in the wall', cue: '+ Gold ore · added to your haul',
      trigger: 'You collect actual gold ore. Its named pickup confirmation is still visible.',
      repeat: 'Fresh pickups can qualify again. Shared ore gap: 45 s.',
      change: 'Repeatable collection, replacing the once-per-save discovery gate.', avoid: 'Coins, selling, purchases and merely seeing gold cannot trigger this.',
      delivery: 'Delighted, a little tempted. Smile on “bad influence”.', delayMs: 450, expiryMs: 2500 },
    { id: 'ember', title: 'Find an Ember', place: 'EMBER REVEAL', line: 'L062',
      before: 'The Ember reveal is still playing', cue: 'Ember gained · reveal complete',
      trigger: 'A new Ember grants a charge; its reveal finishes with the Ember or award still visible.',
      repeat: 'Once per real find. Regular breathing room still applies.',
      change: 'Anchor the line to the finished reveal.', avoid: 'No automatic refill, loaded charge or ordinary glowing ore.',
      delivery: 'Unexpected tenderness. Like taking in a stray.', delayMs: 450, expiryMs: 2500 },
    { id: 'star', title: 'Collect a Star', place: 'STAR REVEAL', line: 'L073',
      before: 'Star reveal / narration owns the moment', cue: 'Star gained · its light remains',
      trigger: 'A new Star gives a positive reward. The reveal and narration end; its light stays visible.',
      repeat: 'Once per Star. The expiry clock starts after the reveal, not at discovery.',
      change: 'A visible Star gives “that light” a clear referent.', avoid: 'No zero reward, normal block or replayed collection.',
      delivery: 'Brief recognition, then a guarded warmth. No theatrical whisper.', delayMs: 1200, expiryMs: 2500 },
    { id: 'titan', title: 'Meet a Titan', place: 'TITAN REVEAL', line: 'L088',
      before: 'The Titan introduction is still playing', cue: 'Introduction ends · Titan still visible',
      trigger: 'A new Titan unlocks. Wait for its cinematic and narration to finish while that Titan remains on screen.',
      repeat: 'Once per Titan. The expiry clock starts when its introduction releases speech.',
      change: 'The face comes first. Leo’s history with it follows.', avoid: 'No voice over the introduction or after the Titan leaves view.',
      delivery: 'A startled, personal recognition. “Again” sounds like unfinished business.', delayMs: 1200, expiryMs: 3000 },
    { id: 'biome', title: 'Enter different scenery', place: 'NEW REGION', line: 'L097',
      before: 'The camera is crossing into new scenery', cue: 'Different stone · stable for 2 s',
      trigger: 'A new region identity and a visible scenery change agree. Hold that view for 2 s.',
      repeat: 'First visible visit to that region this session; no boundary hopping.',
      change: 'Visible scenery, with one opportunity each session instead of a permanent first-only gate.', avoid: 'No hidden depth band or a save loading into this scenery.',
      delivery: 'Recognise the change, then mutter about the job.', delayMs: 450, expiryMs: 2500 },
    { id: 'milestone', title: 'Reach a depth milestone', place: 'DEPTH FEEDBACK', line: 'L115',
      before: 'Depth increases without a milestone', cue: 'Depth milestone · reward appears',
      trigger: 'A real new depth threshold is confirmed by a visible milestone or reward.',
      repeat: 'Once per threshold. If it is also a personal best, choose just one reaction.',
      change: 'No chance roll after an eligible milestone.', avoid: 'No line for every metre or invisible threshold.',
      delivery: 'Proud, then the knees get the last word.', delayMs: 450, expiryMs: 2500 },
    { id: 'record', title: 'Beat your depth record', place: 'PERSONAL BEST', line: 'L121',
      before: 'Your previous best has not been beaten', cue: 'New depth record · confirmed',
      trigger: 'Beat the previous best and show the record confirmation.',
      repeat: 'Once per trip. Coalesce with a simultaneous milestone.',
      change: 'The visible record, not ongoing depth updates, earns the line.', avoid: 'No repeated remarks for every metre beyond the old record.',
      delivery: 'Clearly pleased with himself. Fails slightly at acting casual.', delayMs: 450, expiryMs: 2500 },
    { id: 'rocks', title: 'Rocks threaten you', place: 'YOUR FALL ZONE', line: 'L135', urgent: true,
      before: 'A quake is distant; you are safe', cue: 'Falling-rock warning · overlaps you',
      trigger: 'Your position overlaps a live fall zone and the visible warning is still actionable.',
      repeat: 'Once per quake; urgent remarks share a 45 s gap. Never interrupt any speech.',
      change: 'Direct danger only. Bypass normal chatter cooldown, never speech ownership.', avoid: 'No distant rumble, safe shelter or late warning after the fall.',
      delivery: 'Immediate and clear. No joke, pause or spooky delivery.', delayMs: 0, expiryMs: 900 },
    { id: 'aftermath', title: 'Survive a near miss', place: 'AFTER THE ROCKFALL', line: 'L147',
      before: 'Rocks are still falling around you', cue: 'Debris stops · safe for 3 s',
      trigger: 'This quake personally threatened you. Survive it, then hold safety for 3 s after debris stops.',
      repeat: 'Once per quake. It can follow a warning only after the normal 25 s gap.',
      change: 'Relief needs a real scare. If it would arrive too late, skip it.', avoid: 'No joke while danger continues; no reaction to a distant quake.',
      delivery: 'An involuntary exhale, shaken relief, a small disbelieving laugh.', delayMs: 450, expiryMs: 3000 },
    { id: 'panic', title: 'Hardcore stress turns critical', place: 'HARDCORE WARNING', line: 'L164', urgent: true,
      before: 'Stress is below critical', cue: 'Critical stress · warning turns on',
      trigger: 'In Hardcore, stress crosses into critical and its visible warning remains active.',
      repeat: 'Once per episode; urgent remarks share a 45 s gap.',
      change: 'Tie the sentence to the visible stress warning.', avoid: 'No Normal-mode warning or invented injury.',
      delivery: 'Trying to steady himself. Firm, audible, vulnerable.', delayMs: 0, expiryMs: 900 },
    { id: 'recovery', title: 'Regain your composure', place: 'HARDCORE RECOVERY', line: 'L175',
      before: 'Your critical stress warning is active', cue: 'Warning clears · safe for 3 s',
      trigger: 'An experienced stress episode ends: the warning clears and you stay safe for 3 s.',
      repeat: 'Once per episode. Normal 25 s gap still applies; never queue late relief.',
      change: 'React to visible recovery from actual stress.', avoid: 'No spawning calm, ordinary refill or new threat.',
      delivery: 'Quiet relief with a little fondness for his unreliable courage.', delayMs: 450, expiryMs: 2500 },
    { id: 'haul', title: 'Bring in a proper haul', place: 'BAG FEEDBACK', line: 'L185',
      before: 'Your bag indicator is below its top band', cue: 'Fresh ore · bag enters the top band',
      trigger: 'A meaningful fresh pickup crosses the bag HUD’s top visual band.',
      repeat: 'Once per trip. Choose haul OR material if one pickup triggers both.',
      change: 'Celebrate the visible haul; never imply a carrying limit.', avoid: 'No “bag full” claim, forced-selling advice or restored inventory.',
      delivery: 'Warm and practical. Tonight might be a little better.', delayMs: 450, expiryMs: 2500 },
    { id: 'return', title: 'Return to Town', place: 'TOWN ARRIVAL', line: 'L196',
      before: 'You are still underground', cue: 'Town comes into view · trip ended',
      trigger: 'Return above ground after a trip that reached 100 m or more. Town and the return feedback are visible.',
      repeat: 'Once per completed trip. Night and day use suitable lines.',
      change: 'Proposed threshold: 100 m instead of 300 m, so ordinary early trips count.', avoid: 'No tiny surface loop, NPC conversation or daylight line at night.',
      delivery: 'His shoulders drop. A chair is suddenly the most important thing alive.', delayMs: 450, expiryMs: 3000 },
    { id: 'purchase', title: 'Buy a meaningful upgrade', place: 'UPGRADE CONFIRMATION', line: 'L212',
      before: 'Upgrade is selected; nothing bought yet', cue: 'Upgrade purchased · confirmation glows',
      trigger: 'A purchase succeeds, spends at least 20% of the previous wallet, and shows its confirmation.',
      repeat: 'At most once per 60 s of purchases. The merchant must have released dialogue.',
      change: 'The transaction is the cue. A silent purchase panel can allow Leo.', avoid: 'No failed purchase, shop greeting, hover or speech over the merchant.',
      delivery: 'Wallet pain, followed by a tiny private victory.', delayMs: 450, expiryMs: 2000 },
    { id: 'level', title: 'Gain a level', place: 'LEVEL-UP FEEDBACK', line: 'L221',
      before: 'XP increases, but the level is unchanged', cue: 'Level up · new level appears',
      trigger: 'Gameplay XP increases your level and the level-up effect is visible.',
      repeat: 'Once per award; at most once per 60 s. Multi-level awards get one line.',
      change: 'A common progression moment receives its own clear reaction.', avoid: 'No remark on every XP award or loaded level.',
      delivery: 'Genuine, modest pride. Give him a small win.', delayMs: 450, expiryMs: 2500 },
    { id: 'talent', title: 'Learn a new talent', place: 'TALENT UNLOCK', line: 'L232',
      before: 'The talent node is only highlighted', cue: 'First rank purchased · node lights up',
      trigger: 'A deliberate first-rank purchase succeeds; the new talent lights up after tutorial speech ends.',
      repeat: 'Once per new talent. At most once per 60 s of purchases.',
      change: 'Wait for the successful unlock, not a hover or menu open.', avoid: 'No repeated rank, debug grant or claimed physical effect before use.',
      delivery: 'Amused by his own age. Let the uncertainty linger very briefly.', delayMs: 450, expiryMs: 2500 },
    { id: 'blessing', title: 'Ignite a blessing', place: 'CAMPFIRE', line: 'L244',
      before: 'The campfire menu is open', cue: 'Charge spent · blessing ignites',
      trigger: 'You deliberately spend a charge at the campfire and the blessing visibly ignites.',
      repeat: 'Once per activation; at most once per 60 s.',
      change: 'A chosen action gives “old friend” a visible recipient.', avoid: 'No walking past, automatic refill or failed activation.',
      delivery: 'Sincere gratitude. He knows the fire better than he admits.', delayMs: 450, expiryMs: 2500 },
    { id: 'firegrowth', title: 'Grow the campfire', place: 'CAMPFIRE GROWTH', line: 'L257',
      before: 'The current flame is only flickering', cue: 'Tier upgrade · larger flame revealed',
      trigger: 'A real tier upgrade commits and its reveal ends with a visibly larger flame.',
      repeat: 'Once per tier. Choose fire OR tree if both grow from the same upgrade.',
      change: 'The growth must be visible before the comment.', avoid: 'No routine flicker, blessing activation or hidden upgrade.',
      delivery: 'Comfortable affection. Already imagining putting his feet up.', delayMs: 450, expiryMs: 2500 },
    { id: 'treegrowth', title: 'Watch Worldroot grow', place: 'WORLDROOT', line: 'L269',
      before: 'Leaves sway; the tree has not grown', cue: 'New growth stage · silhouette expands',
      trigger: 'A new growth stage finishes its visible reveal while you can see the tree.',
      repeat: 'Once per stage. One shared reaction if the campfire also grows.',
      change: 'Affection follows a visible achievement.', avoid: 'No moving leaves, off-screen change or restored save.',
      delivery: 'Fond teasing. “Show-off” is almost a compliment.', delayMs: 450, expiryMs: 2500 },
    { id: 'random', title: 'A rare wandering thought', place: 'QUIET ACTIVE PLAY', line: 'L289', random: true,
      before: 'The active-play clock is still running', cue: '27–33 active minutes · a quiet opening',
      trigger: 'After 27–33 active minutes, wait for safety, 20 s without other speech and 90 s since Leo last spoke.',
      repeat: 'One thought opportunity. Allow a 2 min quiet window, then skip it and schedule anew.',
      change: 'Keep mystery rare and independent of events; events take priority.', avoid: 'Menus, pause and hidden tabs do not count. No thoughts during danger or NPC dialogue.',
      delivery: 'An absent, puzzled recollection. He hears himself say it too.', delayMs: 450, expiryMs: 0 }
  ]
};
