// Cross-system progression graph used by the ESC Journey view.
// This graph explains how permanent upgrades, exploration, return routes, and
// the Arc Forge feed one another without creating a second progression system.

export const JOURNEY_DEPTH_MILESTONES = Object.freeze([100, 300, 1000]);

export const JOURNEY_PROGRESSION_GRAPH = Object.freeze([
  Object.freeze({
    id: "depth-100",
    lane: "primary",
    kind: "depthGate",
    target: 100,
    requiresAcceptedGate: null,
    connection: "Town upgrades → first deep layer → stronger materials.",
  }),
  Object.freeze({
    id: "depth-300",
    lane: "primary",
    kind: "depthGate",
    target: 300,
    requiresAcceptedGate: 100,
    connection: "Build strength → harsher depth band → better upgrade income.",
  }),
  Object.freeze({
    id: "depth-1000",
    lane: "primary",
    kind: "depthGate",
    target: 1000,
    requiresAcceptedGate: 300,
    connection: "Deep mining → 1000m gate → World Two access.",
  }),
  Object.freeze({
    id: "world-two-key",
    lane: "primary",
    kind: "worldTwoKey",
    requiresAcceptedGate: 1000,
    connection: "Deep ore + money → Bobo's key → the separated build region.",
  }),
  Object.freeze({
    id: "heavenblock-discovery",
    lane: "primary",
    kind: "heavenblockDiscovery",
    requiresUpgrade: "worldTwoTunnelAccess",
    target: 3,
    connection: "World Two regions → Heavenblock parts → Arc Core blueprint.",
  }),
  Object.freeze({
    id: "heavenblock-installation",
    lane: "primary",
    kind: "heavenblockInstallation",
    requiresDiscoveredParts: 3,
    target: 3,
    connection: "Discovered parts → installed machine → Forge readiness.",
  }),
  Object.freeze({
    id: "arc-core-forge",
    lane: "primary",
    kind: "arcCoreForge",
    requiresInstalledParts: 3,
    connection: "Relics + Heavenblocks + mined materials → Arc Core.",
  }),
  Object.freeze({
    id: "omega-vaults",
    lane: "primary",
    kind: "omegaVaults",
    requiresUpgrade: "arcCoreVehicle",
    target: 3,
    connection: "Arc Core exploration → reopened vaults → Zenith Keystone.",
  }),
  Object.freeze({
    id: "omega-arc-core",
    lane: "primary",
    kind: "omegaArcCoreForge",
    requiresOpenedVaults: 3,
    connection: "Zenith Keystone + deep relics + materials → Omega Arc Core.",
  }),
  Object.freeze({
    id: "first-permanent-upgrade",
    lane: "support",
    kind: "permanentUpgrade",
    target: 1,
    priority: 100,
    connection: "Mining funds the town; the town improves the next descent.",
  }),
  Object.freeze({
    id: "first-return-route",
    lane: "support",
    kind: "returnRoute",
    minimumDepth: 75,
    target: 1,
    priority: 90,
    connection: "Exploration → portal activation → faster resource return trips.",
  }),
  Object.freeze({
    id: "campfire-tier-two",
    lane: "support",
    kind: "campfireTier",
    minimumDepth: 100,
    target: 2,
    priority: 70,
    connection: "Town earnings → stronger blessing → more productive descent.",
  }),
  Object.freeze({
    id: "first-constellation",
    lane: "support",
    kind: "constellation",
    minimumStars: 1,
    target: 1,
    priority: 60,
    connection: "Collected stars → constellation unlock → permanent ability buffs.",
  }),
  Object.freeze({
    id: "tracked-titan",
    lane: "support",
    kind: "titanClue",
    priority: 50,
    connection: "Purchased clue → tracked trail → Titan discovery.",
  }),
]);
