const mode = ({
  flashAlpha,
  ringCount,
  rayCount,
  particleCount,
  arrivalParticleCount,
  ringScaleMotion,
  tokenTravel,
}) => Object.freeze({
  flashAlpha,
  ringCount,
  rayCount,
  particleCount,
  arrivalParticleCount,
  ringScaleMotion,
  tokenTravel,
});

export const RELIC_DISCOVERY_FX_CONFIG = Object.freeze({
  enabled: true,
  maxConcurrentSequences: 2,
  reducedMotionMediaQuery: "(prefers-reduced-motion: reduce)",
  coordinateSpaces: Object.freeze({
    world: "world",
    screen: "screen",
  }),
  viewportFallback: Object.freeze({
    widthPx: 1280,
    heightPx: 720,
    hudTargetXRatio: 0.91,
    hudTargetYRatio: 0.12,
  }),
  depths: Object.freeze({
    flash: 3390,
    localFx: 3400,
    token: 3410,
    countReveal: 3420,
  }),
  blendMode: "ADD",
  colors: Object.freeze({
    highlight: 0xfff7ce,
    violet: 0x9c73ff,
    ink: "#100b20",
  }),
  flash: Object.freeze({
    durationMs: 180,
    ease: "Quad.Out",
  }),
  ring: Object.freeze({
    radiusPx: 30,
    lineWidthPx: 3,
    alpha: 0.88,
    startScale: 0.72,
    endScale: 3.15,
    staggerMs: 76,
    durationMs: 560,
    ease: "Sine.Out",
  }),
  rays: Object.freeze({
    widthPx: 5,
    lengthPx: 92,
    alpha: 0.68,
    startScaleY: 0.18,
    endScaleY: 1,
    durationMs: 410,
    ease: "Quad.Out",
    rotationOffsetRadians: 0.16,
    fullTurnRadians: 6.283185307179586,
  }),
  particles: Object.freeze({
    radiusPx: Object.freeze({ min: 2, max: 4.4 }),
    travelPx: Object.freeze({ min: 34, max: 92 }),
    distanceSteps: 5,
    alpha: 0.94,
    endScale: 0.18,
    durationMs: 500,
    ease: "Cubic.Out",
    rotationOffsetRadians: -0.24,
    fullTurnRadians: 6.283185307179586,
  }),
  token: Object.freeze({
    displaySizePx: 58,
    startScale: 0.52,
    popScale: 1.16,
    settledScale: 1,
    popDurationMs: 190,
    holdBeforeFlightMs: 80,
    popEase: "Back.Out",
    reducedDisplaySizePx: 42,
  }),
  flight: Object.freeze({
    durationMs: 640,
    lowFxDurationMs: 460,
    controlLiftPx: 150,
    controlSidePx: 54,
    spinRadians: 3.141592653589793,
    ease: "Cubic.InOut",
  }),
  arrival: Object.freeze({
    ringRadiusPx: 18,
    ringStartScale: 0.78,
    ringEndScale: 2.25,
    ringAlpha: 0.84,
    ringLineWidthPx: 2,
    ringDurationMs: 300,
  }),
  countReveal: Object.freeze({
    template: "{title}\n{shortName}S  {count}",
    offsetYPx: 48,
    screenMarginPx: 88,
    fontFamily: "Trebuchet MS, Segoe UI, sans-serif",
    fontSize: "18px",
    fontStyle: "bold",
    align: "center",
    strokeThicknessPx: 5,
    startScale: 0.82,
    risePx: 12,
    inDurationMs: 180,
    holdMs: 820,
    fadeDurationMs: 260,
    ease: "Back.Out",
  }),
  modes: Object.freeze({
    full: mode({
      flashAlpha: 0.2,
      ringCount: 2,
      rayCount: 12,
      particleCount: 18,
      arrivalParticleCount: 8,
      ringScaleMotion: true,
      tokenTravel: true,
    }),
    lowFx: mode({
      flashAlpha: 0.1,
      ringCount: 1,
      rayCount: 0,
      particleCount: 4,
      arrivalParticleCount: 3,
      ringScaleMotion: true,
      tokenTravel: true,
    }),
    reducedMotion: mode({
      flashAlpha: 0.07,
      ringCount: 1,
      rayCount: 0,
      particleCount: 0,
      arrivalParticleCount: 0,
      ringScaleMotion: false,
      tokenTravel: false,
    }),
  }),
});
