export const REWARD_FLIGHT_CHANNELS = Object.freeze({
  loot: "loot",
  xp: "xp",
});

export const REWARD_FLIGHT_MOTION_CONFIG = Object.freeze({
  selector: Object.freeze({
    recentWindow: 4,
    strictRecentExclusion: true,
    immediateRepeatMultiplier: 0,
    recentProfileMultiplier: 0.16,
    matchingResourceMultiplier: 2.35,
    neutralResourceMultiplier: 1.05,
    otherResourceMultiplier: 0.68,
    matchingAmountMultiplier: 3,
    adjacentAmountMultiplier: 1.15,
    otherAmountMultiplier: 0.2,
    specialLargeMultiplier: 1.35,
    levelUpSurgeMultiplier: 1.9,
    specialMinimumBandIndex: 2,
    levelUpMinimumBandIndex: 3,
    starRareMinimumRarity: 2,
    routingFloorBands: Object.freeze({
      star: "large",
      rareStar: "surge",
      special: "large",
      levelUp: "surge",
    }),
  }),
  random: Object.freeze({
    hashOffset: 2166136261,
    hashPrime: 16777619,
    unsignedDivisor: 4294967296,
    selectionSalt: 17,
    control1XSalt: 31,
    control1YSalt: 43,
    control2XSalt: 59,
    control2YSalt: 71,
    durationSalt: 89,
    routeAmplitudeSalt: 97,
    routeCyclesSalt: 101,
    routePhaseSalt: 107,
  }),
  geometry: Object.freeze({
    minimumDistancePx: 1,
    sideDistanceFactor: 0.18,
    sideMinimumPx: 20,
    sideMaximumPx: 84,
    liftDistanceFactor: 0.22,
    liftMinimumPx: 38,
    liftMaximumPx: 116,
    controlJitterXPx: 10,
    controlJitterYPx: 7,
    durationJitterRatio: 0.07,
    durationMinimumMs: 280,
    durationMaximumMs: 640,
    routeVariationId: "normal-wave",
    routeWaveDistanceFactor: 0.014,
    routeWaveMinimumPx: 4,
    routeWaveMaximumPx: 14,
    routeWaveAmplitudeMinimumRatio: 0.58,
    routeWaveCyclesMinimum: 0.7,
    routeWaveCyclesMaximum: 1.45,
    routeWaveBandStepRatio: 0.08,
    routeWaveTangentMinimum: 0.001,
    routeWaveFullTurnRadians: 6.283185307179586,
  }),
  channels: Object.freeze({
    loot: Object.freeze({ baseDurationMs: 455, durationPerIndexMs: 24, rotationRadians: 0.52 }),
    xp: Object.freeze({ baseDurationMs: 405, durationPerIndexMs: 32, rotationRadians: 0.16 }),
  }),
  amountBandOrder: Object.freeze(["small", "medium", "large", "surge"]),
  amountBands: Object.freeze({
    loot: Object.freeze([
      Object.freeze({ id: "small", max: 1 }),
      Object.freeze({ id: "medium", max: 3 }),
      Object.freeze({ id: "large", max: 7 }),
      Object.freeze({ id: "surge", max: null }),
    ]),
    xp: Object.freeze([
      Object.freeze({ id: "small", max: 75 }),
      Object.freeze({ id: "medium", max: 300 }),
      Object.freeze({ id: "large", max: 1000 }),
      Object.freeze({ id: "surge", max: null }),
    ]),
  }),
  resourceFamilies: Object.freeze({
    dirt: "earth",
    stone: "earth",
    darkDirtNormal: "earth",
    darkDirtStrong: "earth",
    copper: "metal",
    steel: "metal",
    iron: "metal",
    bronze: "metal",
    silver: "metal",
    gold: "precious",
    lavaDirt: "heat",
    obsidian: "heat",
    emberOre: "heat",
    magmaCrystal: "heat",
  }),
  starResourceFamily: "star",
  neutralResourceFamily: "any",
  profiles: Object.freeze([
    Object.freeze({
      id: "low-drift-left", resourceAffinity: "earth", amountAffinity: "small",
      lootWeight: 30, xpWeight: 38, control1Progress: 0.2, control2Progress: 0.74,
      side1: -0.2, side2: -0.08, lift1: 0.24, lift2: 0.12,
      durationMultiplier: 0.88, rotationMultiplier: -0.55, ease: "Sine.easeInOut",
    }),
    Object.freeze({
      id: "low-drift-right", resourceAffinity: "earth", amountAffinity: "small",
      lootWeight: 29, xpWeight: 36, control1Progress: 0.22, control2Progress: 0.76,
      side1: 0.18, side2: 0.1, lift1: 0.26, lift2: 0.14,
      durationMultiplier: 0.9, rotationMultiplier: 0.5, ease: "Sine.easeInOut",
    }),
    Object.freeze({
      id: "soft-rise-left", resourceAffinity: "metal", amountAffinity: "small",
      lootWeight: 27, xpWeight: 34, control1Progress: 0.18, control2Progress: 0.7,
      side1: -0.1, side2: -0.2, lift1: 0.44, lift2: 0.25,
      durationMultiplier: 0.92, rotationMultiplier: -0.4, ease: "Cubic.easeInOut",
    }),
    Object.freeze({
      id: "soft-rise-right", resourceAffinity: "metal", amountAffinity: "small",
      lootWeight: 26, xpWeight: 32, control1Progress: 0.2, control2Progress: 0.72,
      side1: 0.12, side2: 0.22, lift1: 0.46, lift2: 0.27,
      durationMultiplier: 0.94, rotationMultiplier: 0.42, ease: "Cubic.easeInOut",
    }),
    Object.freeze({
      id: "long-sweep-left", resourceAffinity: "earth", amountAffinity: "medium",
      lootWeight: 24, xpWeight: 29, control1Progress: 0.16, control2Progress: 0.68,
      side1: -0.48, side2: -0.18, lift1: 0.56, lift2: 0.3,
      durationMultiplier: 0.98, rotationMultiplier: -0.7, ease: "Cubic.easeInOut",
    }),
    Object.freeze({
      id: "long-sweep-right", resourceAffinity: "metal", amountAffinity: "medium",
      lootWeight: 23, xpWeight: 27, control1Progress: 0.17, control2Progress: 0.69,
      side1: 0.5, side2: 0.2, lift1: 0.58, lift2: 0.32,
      durationMultiplier: 1, rotationMultiplier: 0.72, ease: "Cubic.easeInOut",
    }),
    Object.freeze({
      id: "early-hook-left", resourceAffinity: "precious", amountAffinity: "medium",
      lootWeight: 21, xpWeight: 25, control1Progress: 0.12, control2Progress: 0.64,
      side1: -0.68, side2: 0.06, lift1: 0.76, lift2: 0.3,
      durationMultiplier: 1.02, rotationMultiplier: -0.8, ease: "Quart.easeInOut",
    }),
    Object.freeze({
      id: "early-hook-right", resourceAffinity: "metal", amountAffinity: "medium",
      lootWeight: 20, xpWeight: 23, control1Progress: 0.13, control2Progress: 0.65,
      side1: 0.7, side2: -0.04, lift1: 0.78, lift2: 0.32,
      durationMultiplier: 1.04, rotationMultiplier: 0.82, ease: "Quart.easeInOut",
    }),
    Object.freeze({
      id: "late-hook-left", resourceAffinity: "heat", amountAffinity: "large",
      lootWeight: 18, xpWeight: 21, control1Progress: 0.28, control2Progress: 0.84,
      side1: -0.08, side2: -0.66, lift1: 0.4, lift2: 0.68,
      durationMultiplier: 1.05, rotationMultiplier: -0.9, ease: "Cubic.easeInOut",
    }),
    Object.freeze({
      id: "late-hook-right", resourceAffinity: "precious", amountAffinity: "large",
      lootWeight: 17, xpWeight: 19, control1Progress: 0.3, control2Progress: 0.85,
      side1: 0.1, side2: 0.68, lift1: 0.42, lift2: 0.7,
      durationMultiplier: 1.06, rotationMultiplier: 0.92, ease: "Cubic.easeInOut",
    }),
    Object.freeze({
      id: "soft-s-left", resourceAffinity: "heat", amountAffinity: "large",
      lootWeight: 15, xpWeight: 17, control1Progress: 0.2, control2Progress: 0.76,
      side1: -0.56, side2: 0.42, lift1: 0.5, lift2: 0.4,
      durationMultiplier: 1.07, rotationMultiplier: -0.65, ease: "Sine.easeInOut",
    }),
    Object.freeze({
      id: "soft-s-right", resourceAffinity: "metal", amountAffinity: "large",
      lootWeight: 14, xpWeight: 16, control1Progress: 0.21, control2Progress: 0.77,
      side1: 0.58, side2: -0.44, lift1: 0.52, lift2: 0.42,
      durationMultiplier: 1.08, rotationMultiplier: 0.68, ease: "Sine.easeInOut",
    }),
    Object.freeze({
      id: "high-arc-left", resourceAffinity: "precious", amountAffinity: "large",
      lootWeight: 12, xpWeight: 14, control1Progress: 0.18, control2Progress: 0.72,
      side1: -0.28, side2: -0.2, lift1: 1, lift2: 0.74,
      durationMultiplier: 1.1, rotationMultiplier: -1, ease: "Quart.easeInOut",
    }),
    Object.freeze({
      id: "high-arc-right", resourceAffinity: "star", amountAffinity: "large",
      lootWeight: 11, xpWeight: 13, control1Progress: 0.19, control2Progress: 0.73,
      side1: 0.3, side2: 0.22, lift1: 1.02, lift2: 0.76,
      durationMultiplier: 1.11, rotationMultiplier: 1.02, ease: "Quart.easeInOut",
    }),
    Object.freeze({
      id: "comet-left", resourceAffinity: "heat", amountAffinity: "surge",
      lootWeight: 9, xpWeight: 11, control1Progress: 0.12, control2Progress: 0.7,
      side1: -0.82, side2: -0.18, lift1: 0.76, lift2: 0.22,
      durationMultiplier: 1.12, rotationMultiplier: -1.08, ease: "Cubic.easeInOut",
    }),
    Object.freeze({
      id: "comet-right", resourceAffinity: "star", amountAffinity: "surge",
      lootWeight: 8, xpWeight: 10, control1Progress: 0.13, control2Progress: 0.71,
      side1: 0.84, side2: 0.2, lift1: 0.78, lift2: 0.24,
      durationMultiplier: 1.13, rotationMultiplier: 1.1, ease: "Cubic.easeInOut",
    }),
    Object.freeze({
      id: "ribbon-left", resourceAffinity: "precious", amountAffinity: "surge",
      lootWeight: 7, xpWeight: 9, control1Progress: 0.16, control2Progress: 0.78,
      side1: -0.7, side2: 0.6, lift1: 0.64, lift2: 0.62,
      durationMultiplier: 1.15, rotationMultiplier: -0.76, ease: "Sine.easeInOut",
    }),
    Object.freeze({
      id: "ribbon-right", resourceAffinity: "heat", amountAffinity: "surge",
      lootWeight: 6, xpWeight: 8, control1Progress: 0.17, control2Progress: 0.79,
      side1: 0.72, side2: -0.62, lift1: 0.66, lift2: 0.64,
      durationMultiplier: 1.16, rotationMultiplier: 0.78, ease: "Sine.easeInOut",
    }),
    Object.freeze({
      id: "crown-left", resourceAffinity: "star", amountAffinity: "surge",
      lootWeight: 4, xpWeight: 6, control1Progress: 0.14, control2Progress: 0.76,
      side1: -0.56, side2: 0.3, lift1: 1.16, lift2: 0.84,
      durationMultiplier: 1.18, rotationMultiplier: -1.15, ease: "Quart.easeInOut",
    }),
    Object.freeze({
      id: "crown-right", resourceAffinity: "any", amountAffinity: "surge",
      lootWeight: 3, xpWeight: 5, control1Progress: 0.15, control2Progress: 0.77,
      side1: 0.58, side2: -0.32, lift1: 1.18, lift2: 0.86,
      durationMultiplier: 1.2, rotationMultiplier: 1.18, ease: "Quart.easeInOut",
    }),
    Object.freeze({
      id: "slingshot-left", resourceAffinity: "star", amountAffinity: "surge",
      lootWeight: 6.6, xpWeight: 8.6, control1Progress: 0.08, control2Progress: 0.62,
      side1: -0.95, side2: 0.72, lift1: 0.42, lift2: 0.9,
      durationMultiplier: 1.17, rotationMultiplier: -1.04, ease: "Expo.easeInOut",
    }),
    Object.freeze({
      id: "slingshot-right", resourceAffinity: "any", amountAffinity: "surge",
      lootWeight: 5.6, xpWeight: 7.6, control1Progress: 0.09, control2Progress: 0.63,
      side1: 0.96, side2: -0.74, lift1: 0.44, lift2: 0.92,
      durationMultiplier: 1.19, rotationMultiplier: 1.06, ease: "Expo.easeInOut",
    }),
    Object.freeze({
      id: "halo-dive-left", resourceAffinity: "star", amountAffinity: "surge",
      lootWeight: 4.6, xpWeight: 6.6, control1Progress: 0.24, control2Progress: 0.88,
      side1: -0.18, side2: -0.82, lift1: 1.28, lift2: 0.15,
      durationMultiplier: 1.21, rotationMultiplier: -1.22, ease: "Quart.easeInOut",
    }),
    Object.freeze({
      id: "halo-dive-right", resourceAffinity: "any", amountAffinity: "surge",
      lootWeight: 3.6, xpWeight: 5.6, control1Progress: 0.25, control2Progress: 0.89,
      side1: 0.2, side2: 0.84, lift1: 1.3, lift2: 0.17,
      durationMultiplier: 1.22, rotationMultiplier: 1.24, ease: "Quart.easeInOut",
    }),
  ]),
});
