import { FREESOUND_APPROVED_ASSETS } from "./generated/approved-freesound/index.js";
import { PLAYER_DEFERRED_ASSET_PACK_IDS } from "./playerDeferredAssetPacks.js";

// Session entry and town-rest presentation. These values do not scale simulation time.
export const SESSION_AWAKENING = Object.freeze({
  enabled: true,
  query: "awakening",
  reviewQuery: "awakeningVariant",
  historyKey: "session-awakening-last-variant",
  reducedMotionQuery: "(prefers-reduced-motion: reduce)",
  durationJitter: 0.055,
  minSkipMs: 320,
  skipFadeMs: 240,
  reducedDurationMs: 750,
  maxDeltaMs: 80,
  releaseAt: 0.8,
  hudFrom: 0.7,
  hudTo: 0.94,
  holdMs: 50,
  animationSlow: 0.65,
  animationSettleMs: 650,
  cameraRisePx: 5,
  cameraZoom: 0,
  blurQuality: 0,
  blurSteps: 2,
  blurRadius: 1.15,
  blurFrom: 0.15,
  blurTo: 0.74,
  art: Object.freeze({
    key: "session-awakening-eyelids-v1",
    path: "sprites/fx/session-awakening-v1/eyelids-v1.png",
    upperFrame: "awakening-upper",
    lowerFrame: "awakening-lower",
    coverFrame: "awakening-cover",
    coverCropPx: 64,
    depth: 14000,
    tint: 0x000000,
    widthScale: 1.1,
    heightScale: 1.3,
    topInset: -0.05,
    travel: 1.25,
    fadeFrom: 0.57,
    fadeTo: 0.8,
    hudMinDepth: 950,
    nativeFullscreenId: "fs-btn",
  }),
  audio: Object.freeze({
    breath: FREESOUND_APPROVED_ASSETS["freesound-410390"],
    heartbeat: FREESOUND_APPROVED_ASSETS["freesound-418788"],
    breathStartSeconds: 0.3,
    breathGain: 0.16,
    heartbeatGain: 0.105,
    heartbeatWindowSeconds: 0.72,
    heartbeatTimes: Object.freeze([0.08, 0.37]),
    breathDelay: 0.08,
    fadeIn: 0.16,
    fadeOutFrom: 0.65,
    musicFloor: 0.13,
    worldFloor: 0.32,
    worldFrom: 0.5,
    worldTo: 0.84,
    musicFrom: 0.73,
    musicTo: 1,
  }),
  sleep: Object.freeze({
    blurChance: 0.65, blurStrength: 0.6, breathRate: 0.96, breathGain: 0.11,
    hudTo: 0.3, coverFrom: 0.88, coverTo: 0.98,
    mixFrom: 0.08, mixTo: 0.88,
    eye: Object.freeze([[0, 1], [0.15, 0.52], [0.26, 0.76], [0.45, 0.24],
      [0.56, 0.4], [0.82, 0.035], [0.94, 0], [1, 0]]),
  }),
  variants: Object.freeze([
    Object.freeze({ id: "first-breath", durationMs: 2320, blurChance: 0.25,
      blurStrength: 0.65, cameraScale: 0.8, breathRate: 1,
      eye: Object.freeze([[0, 0], [0.17, 0], [0.29, 0.09], [0.43, 0.2], [0.63, 0.69], [0.8, 1], [1, 1]]) }),
    Object.freeze({ id: "sleepy-blink", durationMs: 2520, blurChance: 0.5,
      blurStrength: 0.85, cameraScale: 0.65, breathRate: 0.97,
      eye: Object.freeze([[0, 0], [0.12, 0], [0.3, 0.31], [0.4, 0.055], [0.49, 0.075], [0.67, 0.66], [0.8, 1], [1, 1]]) }),
    Object.freeze({ id: "finding-focus", durationMs: 2460, blurChance: 0.85,
      blurStrength: 1.1, cameraScale: 1, breathRate: 1.02,
      eye: Object.freeze([[0, 0], [0.16, 0], [0.34, 0.19], [0.49, 0.21], [0.65, 0.6], [0.8, 1], [1, 1]]) }),
  ]),
});

export function withAwakeningPlayerAssets(profile, search = globalThis.location?.search || "") {
  if (!SESSION_AWAKENING.enabled || new URLSearchParams(search).get(SESSION_AWAKENING.query) === "0") return profile;
  return Object.freeze({ ...profile, preloadDeferredAnimationPackIds: Object.freeze([
    ...new Set([...(profile.preloadDeferredAnimationPackIds || []), PLAYER_DEFERRED_ASSET_PACK_IDS.teleport]),
  ]) });
}
