import { ASSET_KEYS } from "./assetKeys.js";
import { TILE_TYPES } from "./tileTypes.js";

export const SHADOW_MINER_VISUAL_CONFIG = Object.freeze({
  renderMode: "solid-purple-silhouette",
  tint: 0x8b3fe0,
  echoTint: 0xd6a2ff,
  alpha: 0.88,
  echoAlpha: 0.36,
  echoPulseAlpha: 0.06,
  echoScale: 1.08,
  arrivalEchoAlpha: 0.68,
  arrivalEchoScale: 1.24,
  observeEchoAlpha: 0.18,
  observeEchoScale: 1.015,
  observeHoverMultiplier: 0.08,
  lightRecoilTint: 0xe2c4ff,
  starLightRecoilTint: 0xffecff,
  lightRecoilEchoAlpha: 0.68,
  lightRecoilEchoScale: 1.2,
  lightExposureTintBlend: 0.72,
  lightExposureEchoAlpha: 0.6,
  lightExposureEchoScale: 1.14,
  lightExposureJitterPx: 2.4,
  lightExposureJitterCycleMs: 92,
  fleeFacingMinimumDeltaPx: 0.5,
  echoOffsetXPx: 0,
  echoOffsetYPx: 0,
  hoverAmplitudePx: 2,
  hoverCycleMs: 1_600,
  scaleMultiplier: 1,
  spawnScaleMultiplier: 0.92,
  vanishScaleMultiplier: 0.82,
  depth: 19.85,
  echoDepth: 19.75,
  awareness: Object.freeze({
    enabled: true,
    flashColor: 0x721bc4,
    flashAlpha: 0.3,
    flashMaximumAlpha: 0.38,
    flashDurationMs: 450,
    message: "SHADOW MINER NEARBY",
    leftPrefix: "◀  ",
    rightSuffix: "  ▶",
    messageColor: "#d9b3ff",
    messageDurationMs: 2_200,
    messageFontFamily: "Cinzel, Georgia, serif",
    messageFontSizePx: 27,
    messageYpx: 150,
    messageDepth: 1_003,
    messageStrokeColor: "#21052f",
    messageStrokeThickness: 8,
    messageInitialScale: 0.94,
    messageEnterMs: 90,
    messageFadeMs: 180,
    messageLetterSpacingPx: 3,
  }),
  phantomDig: Object.freeze({
    enabled: true,
    stageTileTypes: Object.freeze([
      TILE_TYPES.STONE,
      TILE_TYPES.DARK_DIRT_STRONG,
      TILE_TYPES.OBSIDIAN,
    ]),
    stageTextureKeysByTileType: Object.freeze({
      [TILE_TYPES.STONE]: ASSET_KEYS.shadowMiner.phantomBlocks.stone,
      [TILE_TYPES.DARK_DIRT_STRONG]: ASSET_KEYS.shadowMiner.phantomBlocks.darkDirtStrong,
      [TILE_TYPES.OBSIDIAN]: ASSET_KEYS.shadowMiner.phantomBlocks.obsidian,
    }),
    crackTextureKeys: Object.freeze([...ASSET_KEYS.shadowMiner.phantomBlocks.cracks]),
    damageStageCount: 5,
    tint: 0x8b3fe0,
    glowTint: 0xd6a2ff,
    alpha: 0.82,
    glowAlpha: 0.22,
    glowScale: 1.08,
    glowPulseAlpha: 0.05,
    glowPulseScale: 0.025,
    glowPulseCycleMs: 620,
    displayTiles: 0.94,
    anchorYOffsetTiles: -0.5,
    depth: 19.58,
    glowDepth: 19.52,
    crackDepth: 19.6,
    crackAlpha: 0.92,
    crackTint: 0xe8ceff,
    crackStepMs: 105,
    breakAtMs: 535,
    breakFadeMs: 210,
    breakScale: 0.72,
    breakCoreTextureKey: "tile-destruction-core-v3",
    breakCoreFrame: "hard-p03",
    breakCoreDisplayTiles: 1.08,
    breakCoreAlpha: 0.78,
    breakShardTextureKey: "tile-destruction-shards-v3",
    breakShardFrames: Object.freeze(["hard-s01", "hard-s02", "hard-s03"]),
    breakShardDisplayTiles: 0.16,
    breakShardTravelTiles: 0.32,
    breakShardLiftTiles: 0.12,
    breakShardFadeMs: 260,
    maximumFxSprites: 7,
  }),
  residue: Object.freeze({
    maximumSprites: 3,
    intervalMs: 120,
    durationMs: 850,
    alpha: 0.28,
    fadeScaleMultiplier: 0.94,
    tint: 0xa65bff,
    starTint: 0xf0c7ff,
    depth: 19.7,
    enabledInReducedMotion: false,
  }),
  reducedMotionMediaQuery: "(prefers-reduced-motion: reduce)",
});
