import { SIGNAL_REWARDS } from "./signalRisk.js";

export const SIGNAL_EVENT = Object.freeze({
  type: "signal", durationMs: 110000, minDepth: 18, realChance: 0.35, fatalChance: 0.5,
  hearingDistance: 42, rewardStars: SIGNAL_REWARDS.attackStars, minDistance: 7, maxDistance: 24, searchHeight: 13, nearDistance: 4,
  middleDistance: 11, interactDistance: 2, callGapMinMs: 12000, callGapMaxMs: 24000,
  firstCallMs: 1400, captionTailMs: 800, sourceSalt: 39019, survivorSalt: 71143,
  fatalSalt: 90473, cadenceSalt: 57203, historyLimit: 12,
  camp: Object.freeze({ radius: 3, height: 4, key: "signal-minicamp-v1", source: "sprites/npc/signal-survivors-v1/minicamp.png", widthTiles: 7, originY: 0.86 }),
  calls: Object.freeze({ far: ["farA", "farB", "middle"], middle: ["middle", "farB", "farA"], near: ["near", "middle"] }),
  audio: Object.freeze({ gain: 0.9, nearGain: 0.9, farGain: 0.42, nearHz: 16000, farHz: 950, loadTimeoutMs: 15000, echoChance: 0.22, echoDelay: 0.48, echoGain: 0.24, fadeSeconds: 0.015, peakTarget: 0.8, maxGain: 3 }),
  art: Object.freeze({ frameSize: 627, columns: 2, worldHeight: 112, worldDepth: 902, originY: 0.95,
    pose: Object.freeze({ rest: 0, call: 1, gift: 2, guard: 3 }) }),
  cue: Object.freeze({ depth: 3470, radius: 100, inset: 90, width: 510, height: 70,
    bottom: 145, pulseMs: 1400, drift: 13, arrowSize: 28, textSize: 16, directionSize: 12,
    color: "#d4e9e7", panel: "ui-hud-approved-notification" }),
  cinema: Object.freeze({ depth: 5500, width: 1100, height: 650, margin: 0.94,
    shade: 0x02060b, shadeAlpha: 0.89, portraitX: -335, portraitY: 103, portraitSize: 330,
    stripY: -40, shotHeight: 355, shotInset: 12, shotCampY: 112, shotCampRatio: 0.563, shotCampAlpha: 0.8,
    shotPortraitY: 3, shotPortraitHeight: 320, shotSideAlpha: 0.6,
    shots: Object.freeze([{ x: -131, width: 82 }, { x: 0, width: 178 }, { x: 131, width: 82 }]),
    titleX: -115, titleY: -192, roleY: -150, subtitleY: -48, subtitleWidth: 600,
    titleSize: 36, roleSize: 15, subtitleSize: 24, buttonSize: 17, detailSize: 14,
    choicesY: 184, choiceGap: 338, choiceWidth: 322, choiceHeight: 88, footerY: 282,
    enterMs: 280, lineGapMs: 600, minimumLineMs: 2200, riskY: 45,
    giftNavY: 119, giftNavHeight: 28, giftRows: 5, giftStartY: -99, giftRowGap: 45, giftWidth: 580 }),
  copy: Object.freeze({
    echo: "ODD ECHO", title: "SIGNAL", unknown: "A man's voice", far: "DISTANT", middle: "CLOSER", near: "NEARBY",
    silence: "[The calls stop. No one is here.]", meet: "{key} · APPROACH THE SURVIVOR",
    kill: "+" + SIGNAL_REWARDS.attackStars + " STARPOWER", killTitle: "FEED HIM TO THE STARS", give: "GIVE SUPPLIES", ignore: "LEAVE HIM BE",
    risk: "50% chance he kills you.", hardcoreRisk: "HARDCORE: YOUR ONLY LIFE WILL BE LOST.",
    casualRisk: "You lose ALL carried resources and GP, then return to the surface.",
    confirmAttack: "ATTACK · ACCEPT THE RISK", back: "GO BACK", continue: "CONTINUE",
    giftTitle: "GIVE WHAT YOU CAN SPARE",
    giftHelp: "Select a resource. Type an exact amount. Tab moves to the next. Enter gives your selection.",
    giftSubmit: "GIVE SELECTED SUPPLIES", giftEmpty: "Choose at least one resource to give.",
    giftInvalid: "Enter whole amounts you actually carry.", giftSaved: "Your kindness is remembered.",
    giftFooter: "A/D: PAGE · TAB: RESOURCE · TYPE AMOUNT · ESC: BACK",
    savedError: "Could not save this choice. Nothing was taken. Try again.",
    won: stars => "+" + stars + " STARPOWER · The voice is gone.", lost: "You wake at the surface. Your pack and GP are empty.",
    leave: "The survivor disappears into the dark.", captionFallbackMsPerWord: 380,
  }),
});
