const freezeActors = actors => Object.freeze(actors.map(actor => Object.freeze(actor)));

export const SKYLINE_WEATHER_VFX = Object.freeze({
  enabled: true,
  queryParam: "skylineVfx",
  queryEnableValues: Object.freeze(["1", "on", "true", "imagegen"]),
  queryDisableValues: Object.freeze(["0", "off", "false", "procedural"]),
  assetBasePath: "sprites/environment/v11-skyline-weather-vfx-v1/",
  sheets: Object.freeze({
    clouds: Object.freeze({ file: "clouds-screen.webp", layoutRows: Object.freeze([3, 3, 3]) }),
    atmosphere: Object.freeze({ file: "atmosphere-screen.webp", layoutRows: Object.freeze([4, 4, 4]) }),
    lightning: Object.freeze({ file: "lightning-screen.webp", layoutRows: Object.freeze([4, 4, 4]) }),
  }),
  particleSheet: Object.freeze({
    file: "weather-particles-v2.png",
    frameWidth: 256,
    frameHeight: 256,
    contentSafeAreaPx: 224,
  }),
  particleFrames: Object.freeze({
    rainStreaks: Object.freeze([0, 1, 2, 3]),
    snowFlakes: Object.freeze([4, 5, 6, 7, 8, 9, 10, 11]),
    rainSplashes: Object.freeze([12, 13, 14, 15]),
    rainRipples: Object.freeze([16, 17, 18, 19]),
    waterDrops: Object.freeze([20, 21]),
    rainSpray: Object.freeze([22, 23]),
    snowPowder: Object.freeze([24, 25, 26]),
    steam: Object.freeze([27, 28]),
    smoke: Object.freeze([29, 30]),
    groundMist: Object.freeze([31]),
  }),
  particlePresentation: Object.freeze({
    drip: Object.freeze({
      frameGroup: "waterDrops",
      speedX: Object.freeze({ min: -12, max: 12 }),
      speedY: Object.freeze({ min: 150, max: 320 }),
      scale: Object.freeze({ min: 0.035, max: 0.070 }),
      alpha: Object.freeze({ start: 0.78, end: 0.06 }),
      lifespan: Object.freeze({ min: 900, max: 1500 }),
      blendMode: "normal",
    }),
    mist: Object.freeze({
      frameGroup: "groundMist",
      speedX: Object.freeze({ min: -20, max: 26 }),
      speedY: Object.freeze({ min: -28, max: -4 }),
      scale: Object.freeze({ start: 0.28, end: 1.15 }),
      alpha: Object.freeze({ start: 0, end: 0.16 }),
      lifespan: Object.freeze({ min: 1800, max: 3600 }),
      blendMode: "screen",
    }),
    dust: Object.freeze({
      frameGroup: "smoke",
      speedX: Object.freeze({ min: -45, max: 60 }),
      speedY: Object.freeze({ min: -18, max: -3 }),
      scale: Object.freeze({ start: 0.12, end: 0.34 }),
      alpha: Object.freeze({ start: 0.16, end: 0 }),
      lifespan: Object.freeze({ min: 900, max: 1800 }),
      blendMode: "screen",
    }),
    steam: Object.freeze({
      frameGroup: "steam",
      speedX: Object.freeze({ min: -18, max: 18 }),
      speedY: Object.freeze({ min: -34, max: -7 }),
      scale: Object.freeze({ start: 0.14, end: 0.48 }),
      alpha: Object.freeze({ start: 0.10, end: 0 }),
      lifespan: Object.freeze({ min: 1400, max: 2600 }),
      blendMode: "screen",
    }),
    ripple: Object.freeze({
      frameGroup: "rainRipples",
      speedX: Object.freeze({ min: -3, max: 3 }),
      speedY: Object.freeze({ min: -1, max: 1 }),
      scale: Object.freeze({ start: 0.16, end: 0.38 }),
      alpha: Object.freeze({ start: 0.24, end: 0 }),
      lifespan: Object.freeze({ min: 420, max: 760 }),
      blendMode: "normal",
    }),
    ambientMist: Object.freeze({
      frameGroup: "groundMist",
      widthPx: Object.freeze([190, 320]),
      heightPx: Object.freeze([48, 82]),
      alpha: Object.freeze([0.045, 0.085]),
      blendMode: "screen",
    }),
    ambientWind: Object.freeze({
      frameGroup: "smoke",
      sizePx: Object.freeze([32, 58]),
      alpha: Object.freeze([0.14, 0.28]),
      fadePerFrame: 0.0045,
      blendMode: "screen",
    }),
  }),
  frames: Object.freeze({
    clouds: Object.freeze({ distant: Object.freeze([0, 1, 2]), midground: Object.freeze([3, 4, 5]), storm: Object.freeze([6, 7, 8]) }),
    atmosphere: Object.freeze({ fog: Object.freeze([0, 1, 2, 3]), smoke: Object.freeze([4, 5, 6, 7]), steam: Object.freeze([8, 9]), groundMist: Object.freeze([10, 11]) }),
    lightning: Object.freeze({ bolts: Object.freeze([0, 1, 2, 3]), flashes: Object.freeze([8, 9, 10, 11]) }),
  }),
  renderDepths: Object.freeze({ cloudsFar: -4.745, clouds: 14, fog: 57.2, wisps: -4.70, lightning: 994 }),
  clouds: Object.freeze({
    minimumClearCover: 0.12,
    nightAlphaBoost: 0.10,
    spacingTiles: 8,
    wrapMarginTiles: 8,
    bobPeriodSeconds: 14,
    bobAmplitudeTiles: 0.08,
    actors: freezeActors([
      { layer: "far", altitudeTiles: 6.80, widthTiles: 4.8, heightTiles: 1.12, speed: 7, alpha: 0.10 },
      { layer: "far", altitudeTiles: 7.55, widthTiles: 4.2, heightTiles: 1.02, speed: 9, alpha: 0.09 },
      { layer: "far", altitudeTiles: 8.10, widthTiles: 5.7, heightTiles: 1.42, speed: 13, alpha: 0.11 },
      { layer: "far", altitudeTiles: 8.85, widthTiles: 5.3, heightTiles: 1.30, speed: 17, alpha: 0.12 },
      { layer: "far", altitudeTiles: 9.60, widthTiles: 6.3, heightTiles: 1.52, speed: 22, alpha: 0.14 },
      { layer: "far", altitudeTiles: 10.35, widthTiles: 6.8, heightTiles: 1.62, speed: 25, alpha: 0.12 },
    ]),
  }),
  fog: Object.freeze({ count: 4, widthFraction: 0.42, heightFraction: 0.18, yFraction: 0.72, maxAlpha: 0.32 }),
  wisps: Object.freeze({ sizePx: 72, smokeAlpha: 0.22, steamAlpha: 0.18, cullMarginPx: 220 }),
  lightning: Object.freeze({ boltWidthPx: 210, boltHeightPx: 310, flashWidthPx: 460, flashHeightPx: 260, maxBoltAlpha: 0.58, maxFlashAlpha: 0.28 }),
  performance: Object.freeze({ reducedBelowFps: 48, updateIntervalMs: 16, reducedUpdateIntervalMs: 33 }),
});
