// ==================== STARLIGHT TALENT TREE ====================
// Shared ESC / Star Pillar presentation, first-star reveal, and health contract.

const QUICKSLASH_RESOURCES = Object.freeze([
  "dirt",
  "copper",
  "steel",
  "bronze",
  "silver",
]);

const THUNDERSTRIKE_RESOURCES = Object.freeze([
  "stone",
  "darkDirtNormal",
  "iron",
  "darkDirtStrong",
  "gold",
]);

export const STARLIGHT_TALENT_RESOURCE_ORDER = Object.freeze([
  ...QUICKSLASH_RESOURCES,
  ...THUNDERSTRIKE_RESOURCES,
]);

export const STARLIGHT_TALENT_TREE_CONFIG = Object.freeze({
  assets: Object.freeze({
    basePath: "sprites/UI/starlight-talent-tree-v4/",
    files: Object.freeze({
      modalShell: "starlight-modal-shell-v2.png",
      modalCrest: "constellation-crest-v2.png",
      modalClose: "celestial-close-v2.png",
      treePanel: "starlight-tree-panel-v2.png",
      detailPanel: "starlight-detail-panel-v2.png",
      enginePage: "starlight-engine-page-v2.png",
      nodeQuickslash: "node-frame-quickslash-v2.png",
      nodeThunderstrike: "node-frame-thunderstrike-v2.png",
      nodeLocked: "node-frame-bobo-locked-v2.png",
      nodeSelected: "node-selection-halo-v2.png",
      boboLock: "bobo-lock-seal-v2.png",
      starHeartSocket: "star-heart-socket-v2.png",
      connectorQuickslash: "connector-quickslash-v2.png",
      connectorThunderstrike: "connector-thunderstrike-v2.png",
      starHeart: "star-heart-ui-v2.png",
      waywardStar: "wayward-star-ui-v2.png",
      hollowSun: "hollow-sun-ui-v2.png",
      cometEngine: "comet-engine-ui-v2.png",
      ultrawideFoundation: "starlight-mockup-foundation-v4.png",
      navigationPlaqueIdle: "navigation-plaque-idle-v3.png",
      navigationPlaqueSelected: "navigation-plaque-selected-v3.png",
      talentRibbonIdle: "talent-ribbon-idle-v3.png",
      talentRibbonSelected: "talent-ribbon-selected-v3.png",
      statusSeal: "status-seal-v3.png",
      progressPlaque: "progress-plaque-v3.png",
      carouselLeft: "carousel-left-v3.png",
      carouselRight: "carousel-right-v3.png",
      carouselStepIdle: "carousel-step-idle-v3.png",
      carouselStepActive: "carousel-step-active-v3.png",
    }),
  }),
  branches: Object.freeze([
    Object.freeze({
      id: "quickslash",
      label: "QUICK SLASH",
      accent: 0xb985ff,
      cssAccent: "#C19AFF",
      prerequisiteLabel: "BUY QUICK SLASH FROM BOBO",
      resourceTypes: QUICKSLASH_RESOURCES,
    }),
    Object.freeze({
      id: "thunderstrike",
      label: "THUNDER STRIKE",
      accent: 0x63cfff,
      cssAccent: "#71D9FF",
      prerequisiteLabel: "BUY THUNDER STRIKE FROM BOBO",
      resourceTypes: THUNDERSTRIKE_RESOURCES,
    }),
  ]),
  pages: Object.freeze([
    Object.freeze({
      id: "quickslash",
      label: "QUICK SLASH",
      startIndex: 0,
      itemCount: 5,
    }),
    Object.freeze({
      id: "thunderstrike",
      label: "THUNDER STRIKE",
      startIndex: 5,
      itemCount: 5,
    }),
    Object.freeze({
      id: "engines",
      label: "STAR ENGINES",
      startIndex: 10,
      itemCount: 3,
    }),
  ]),
  resources: Object.freeze({
    dirt: Object.freeze({ shortName: "SHOVEL", material: "DIRT" }),
    stone: Object.freeze({ shortName: "MOUNTAIN", material: "STONE" }),
    copper: Object.freeze({ shortName: "ANVIL", material: "COPPER" }),
    darkDirtNormal: Object.freeze({ shortName: "CAVE", material: "DARK DIRT" }),
    steel: Object.freeze({ shortName: "SWORD", material: "STEEL" }),
    iron: Object.freeze({ shortName: "HAMMER", material: "IRON" }),
    bronze: Object.freeze({ shortName: "SHIELD", material: "BRONZE" }),
    darkDirtStrong: Object.freeze({ shortName: "FORTRESS", material: "HARD DIRT" }),
    silver: Object.freeze({ shortName: "CRESCENT", material: "SILVER" }),
    gold: Object.freeze({ shortName: "CROWN", material: "GOLD" }),
  }),
  copy: Object.freeze({
    title: "STARLIGHT TALENT TREE",
    detailTitle: "TALENT DETAIL",
    subtitle: "Each sign boosts matching Star Blocks and mutates its Bobo ability.",
    mastered: "MASTERED",
    partial: "IN PROGRESS",
    locked: "LOCKED",
    boboLocked: "BOBO LOCK",
    abilityOwned: "ABILITY OWNED",
    abilityLocked: "LOCKED  •  BUY FROM BOBO",
    abilityLockedHint: "STARS SAVED  •  BUY BASE ABILITY FROM BOBO",
    mutationActive: "MUTATION ACTIVE",
    mutationPending: "MUTATION ON MASTERY",
    firstStar: "FIRST STAR DISCOVERED",
    firstStarHint: "This material section will not interrupt you again.",
    starHeart: "STAR HEART",
    starHeartGate: "MASTER ALL CONSTELLATIONS TO ATTUNE YOUR FIRST ENGINE",
    engines: "CELESTIAL ENGINES",
    engineRule: "ALL 3 OWNABLE  •  1 EQUIPPED",
    pauseHint: "Select a sign to inspect its permanent reward.",
    pillarHint: "Inspect talents or choose one of three Celestial Engines.",
    pillarOnly: "Visit the Star Pillar to attune or equip Celestial Engines.",
    engineOwned: "OWNED",
    engineEquipped: "EQUIPPED",
    engineGodMode: "FREE",
    engineAvailable: "ATTUNE",
    engineLocked: "SEALED",
    pageHint: "UP / DOWN  •  CHANGE PAGE",
    engineAction: "CLICK CENTER TO ATTUNE OR EQUIP",
  }),
  layout: Object.freeze({
    referenceWidthPx: 1116,
    referenceHeightPx: 628,
    foundationAspectRatio: 1.7768331562,
    foundationUnderlayEnabled: false,
    foundationUnderlayAlpha: 0.72,
    foundationUnderlayCropXFraction: 0.28,
    foundationUnderlayCropYFraction: 0.68,
    foundationUnderlayCropWidthFraction: 0.44,
    foundationUnderlayCropHeightFraction: 0.18,
    minimumLayoutScale: 0.76,
    immersiveInsetPx: 8,
    pauseHeaderTitleOffsetYPx: 57,
    pauseHeaderSubtitleOffsetYPx: 97,
    pauseHeaderTitleFontSizePx: 44,
    pauseHeaderTitleMinimumFontSizePx: 32,
    pauseHeaderTitleLetterSpacingPx: 5,
    pauseHeaderSubtitleFontSizePx: 16,
    pauseHeaderSubtitleMinimumFontSizePx: 13,
    pageTabYOffsetPx: 142,
    pageTabXFractions: Object.freeze([0.25, 0.5, 0.75]),
    pageTabWidthPx: 232,
    pageTabHeightPx: 60,
    pageTabPlaqueWidthPx: 230,
    pageTabPlaqueHeightPx: 58,
    pageTabShowIcons: false,
    pageTabIconSizePx: 0,
    pageTabIconOffsetXPx: 0,
    pageTabLabelOffsetXPx: 0,
    pageTabFontSizePx: 20,
    pageTabMinimumFontSizePx: 15,
    pageTabIdleAlpha: 0.72,
    pageTabSelectedAlpha: 1,
    pageTabIdleScale: 0.97,
    pageTabSelectedScale: 1.035,
    pageTabTweenMs: 140,
    branchHeaderXFraction: 0.125,
    branchHeaderOffsetYPx: 180,
    branchHeaderFontSizePx: 16,
    branchHeaderMinimumFontSizePx: 13,
    branchStatusXFraction: 0.885,
    branchStatusOffsetYPx: 180,
    branchStatusWidthPx: 174,
    branchStatusHeightPx: 52,
    branchStatusSealEnabled: false,
    branchStatusFontSizePx: 12,
    branchStatusMinimumFontSizePx: 10,
    branchStatusTextWidthFraction: 0.72,
    nodeRowOffsetYPx: 293,
    carouselSlotXFractions: Object.freeze([0.25, 0.5, 0.75]),
    carouselCenterSlotIndex: 1,
    carouselVisibleCards: 3,
    carouselArrowXFractions: Object.freeze([0.043, 0.957]),
    carouselArrowOffsetYPx: 293,
    carouselArrowSizePx: 76,
    carouselArrowIdleAlpha: 0,
    carouselArrowHoverTravelPx: 8,
    carouselTweenMs: 190,
    carouselFlankScale: 0.82,
    carouselCenterScale: 1,
    carouselFlankAlpha: 0.72,
    carouselFlankLabelAlpha: 0.9,
    carouselCenterRibbonEmbedded: true,
    nodeWidthPx: 250,
    nodeHeightPx: 290,
    nodeSelectionHaloPx: 230,
    nodeArtMaxWidthPx: 215,
    nodeArtMaxHeightPx: 220,
    nodeArtOffsetYPx: -12,
    nodeRibbonWidthPx: 205,
    nodeRibbonHeightPx: 68,
    nodeRibbonOffsetYPx: 112,
    nodeNameOffsetYPx: 108,
    nodeProgressOffsetYPx: 142,
    nodeNameFontSizePx: 22,
    nodeNameMinimumFontSizePx: 17,
    nodeProgressFontSizePx: 14,
    nodeProgressMinimumFontSizePx: 11,
    nodeXpBarVisible: false,
    nodeXpBarWidthPx: 108,
    nodeXpBarHeightPx: 9,
    nodeXpBarOffsetYPx: 94,
    nodeLockSizePx: 116,
    nodeLockOffsetXPx: 0,
    nodeLockOffsetYPx: -12,
    nodeTextStrokeColor: "#02060A",
    nodeTextStrokeThicknessPx: 2,
    detailLockSizePx: 120,
    detailSignXFraction: 0.19,
    detailSignOffsetYPx: 515,
    detailSignMaxPx: 190,
    detailTextXFraction: 0.35,
    detailTextRightPaddingFraction: 0.22,
    detailTitleOffsetYPx: 456,
    detailBuffOffsetYPx: 491,
    detailDescriptionOffsetYPx: 524,
    detailPassiveOffsetYPx: 558,
    detailProgressOffsetYPx: 590,
    detailProgressPlaqueVisible: false,
    detailProgressPlaqueHeightPx: 46,
    detailXpBarHorizontalPaddingPx: 32,
    detailXpBarHeightPx: 11,
    detailXpBarOffsetYPx: 14,
    detailTitleFontSizePx: 30,
    detailTitleMinimumFontSizePx: 22,
    detailBuffFontSizePx: 18,
    detailBuffMinimumFontSizePx: 14,
    detailBodyFontSizePx: 15,
    detailBodyMinimumFontSizePx: 12,
    detailMetaFontSizePx: 13,
    detailMetaMinimumFontSizePx: 10,
    detailHeartXFraction: 0.84,
    detailHeartOffsetYPx: 515,
    detailHeartSizePx: 150,
    detailHeartLabelOffsetYPx: 50,
    detailHeartCountOffsetYPx: 72,
    detailHeartLabelFontSizePx: 14,
    detailHeartLabelMinimumFontSizePx: 11,
    detailHeartCountFontSizePx: 12,
    detailHeartCountMinimumFontSizePx: 10,
    engineCardWidthPx: 250,
    engineCardHeightPx: 290,
    engineArtMaxPx: 215,
    engineArtOffsetYPx: -12,
    engineSelectionHaloPx: 230,
    engineRibbonWidthPx: 205,
    engineRibbonHeightPx: 68,
    engineRibbonOffsetYPx: 112,
    engineNameOffsetYPx: 108,
    engineStatusOffsetYPx: 142,
    engineNameFontSizePx: 22,
    engineNameMinimumFontSizePx: 17,
    engineStatusFontSizePx: 14,
    engineStatusMinimumFontSizePx: 11,
    engineLockedAlpha: 0.56,
    engineLockedTint: 0x8294a8,
    selectedPulseScale: 1.035,
    ambientPulseMs: 1900,
    pillarMaxWidthPx: 1160,
    pillarMaxHeightPx: 690,
    pillarHeaderHeightPx: 122,
    pillarHeaderIconOffsetXPx: 110,
    pillarHeaderIconOffsetYPx: 98,
    pillarHeaderIconSizePx: 76,
    pillarHeaderTitleOffsetXPx: 176,
    pillarHeaderTitleOffsetYPx: 62,
    pillarHeaderSubtitleOffsetYPx: 92,
    pillarHeaderCloseOffsetXPx: 45,
    pillarHeaderCloseOffsetYPx: 45,
    pillarHeaderCloseSizePx: 34,
  }),
  reveal: Object.freeze({
    storageKey: "dig-game-talent-first-star-reveals-v1",
    openDelayMs: 520,
    maxPending: 10,
  }),
  health: Object.freeze({
    expectedConstellations: 10,
    expectedEngineOptions: 3,
    expectedPages: 3,
    expectedVisibleBranchCards: 3,
    maximumSteadyMotionLoops: 1,
  }),
});
