// ==================== STAR SANCTUARY ====================
// Intact Stars are small, reusable refuges. Removing one keeps the normal
// Star reward but permanently leaves a fixed, non-spreading Starless Scar.

const temperament = (
  id,
  label,
  description,
  gpRateScale,
  gpCapBonus,
  radiusScale,
  stressRecoveryScale,
) => Object.freeze({
  id,
  label,
  description,
  gpRateScale,
  gpCapBonus,
  radiusScale,
  stressRecoveryScale,
});

export const STAR_SANCTUARY_CONFIG = Object.freeze({
  id: "star-sanctuary-v1",
  queryParam: "starSanctuary",
  enabledByDefault: true,
  maximumFrameMs: 100,
  refuge: Object.freeze({
    baseRadiusTiles: 1.5,
    maximumRadiusTiles: 2.2,
    restWarmupMs: 900,
    maximumRestSpeedTilesPerSecond: 0.38,
    gpPerSecondByRarity: Object.freeze([5, 6, 7.5, 9.5, 12, 16]),
    gpCapRatioByRarity: Object.freeze([0.6, 0.65, 0.7, 0.76, 0.84, 1]),
    gpRateVariation: Object.freeze([0.92, 1.08]),
    gpCapVariation: Object.freeze([-0.02, 0.02]),
    radiusVariation: Object.freeze([0.96, 1.04]),
    stressRecoveryVariation: Object.freeze([0.94, 1.06]),
    minimumGpCapRatio: 0.5,
    maximumGpCapRatio: 1,
    minimumStressRecoveryScale: 0.8,
    maximumStressRecoveryScale: 1.65,
    gpPulseIntervalMs: 700,
  }),
  temperaments: Object.freeze([
    temperament(
      "wellspring",
      "WELLSPRING",
      "Charges GP faster",
      1.35,
      0,
      0.96,
      0.95,
    ),
    temperament(
      "reservoir",
      "RESERVOIR",
      "Charges GP to a higher reserve",
      0.84,
      0.12,
      0.97,
      0.95,
    ),
    temperament(
      "haven",
      "HAVEN",
      "Has a wider refuge and stronger Panic relief",
      0.9,
      0,
      1.18,
      1.42,
    ),
  ]),
  consumption: Object.freeze({
    confirmationHoldMs: 1000,
    maximumAttemptGapMs: 1400,
    acknowledgement: Object.freeze({
      storageKeyPrefix: "dig-game-star-consumption-ack-v1-slot-",
      storageVersion: 1,
      confirmationWord: "DESTROY",
      title: "DESTROY A STAR REFUGE?",
      subtitle: "PERMANENT WORLD DAMAGE",
      body: [
        "THIS STAR IS A MINI-BASE.",
        "",
        "DESTROYING IT PERMANENTLY REMOVES:",
        "LIGHT  •  GP RECOVERY  •  PANIC RELIEF",
        "",
        "A 4-TILE STARLESS SCAR WILL REMAIN.",
        "DARKNESS PANIC BUILDS 60% FASTER INSIDE IT.",
      ].join("\n"),
      typedInstruction: "TYPE DESTROY, THEN PRESS ENTER",
      footer: "ESC  KEEP THE STAR",
      footerColor: "#d6a84a",
      footerColor: "#d6a84a",
    }),
    preview: Object.freeze({
      worldDepth: 53,
      fillAlpha: 0.24,
      ringAlpha: 0.9,
      ringWidthTiles: 0.065,
      pulsePeriodMs: 900,
      pulseMinimum: 0.82,
      pulseMaximum: 1,
    }),
    holdUi: Object.freeze({
      holdFrameKey: "ui-hud-approved-xp",
      holdFramePath: "sprites/UI/hud-approved-v1/xp-frame.png",
      depth: 4100,
      yRatio: 0.82,
      widthRatio: 0.38,
      minimumWidthPx: 300,
      maximumWidthPx: 520,
      viewportMaximumRatio: 0.86,
      frameAspectRatio: 13.18,
      fillWidthRatio: 0.94,
      fillHeightRatio: 0.24,
      fillColor: 0xff795f,
      fillAlpha: 0.96,
      titleY: -34,
      statusY: 0,
      consequenceY: 34,
      titleFontPx: 17,
      statusFontPx: 14,
      consequenceFontPx: 12,
      titleColor: "#ffd0bd",
      statusColor: "#fff0c2",
      consequenceColor: "#ff9f91",
      strokeColor: "#090205",
      strokeThickness: 4,
      title: "PERMANENT STAR SACRIFICE",
      status: "HOLD MINE  •  {percent}%",
      consequence: "LIGHT • GP • PANIC REFUGE WILL BE LOST  •  RELEASE TO CANCEL",
    }),
  }),
  scar: Object.freeze({
    radiusTiles: 4,
    darknessStressMultiplier: 1.6,
    visual: Object.freeze({
      baseDepth: 2.3,
      rimDepth: 2.31,
      baseColor: 0x08050d,
      coreColor: 0x030106,
      ashColor: 0x281522,
      veinColor: 0x8f6b7e,
      baseAlpha: 0.54,
      coreAlpha: 0.62,
      ashAlpha: 0.3,
      rimAlpha: 0.16,
      veinAlpha: 0.6,
      edgeLobes: 17,
      ashPatches: 18,
      coreArcSegments: 9,
      veinCount: 13,
      cullMarginTiles: 5,
    }),
  }),
  feedback: Object.freeze({
    refugeEntered: "{name} • {temperament} REFUGE • REST FOR GP",
    charging: "{name} • +{rate} GP/s TO {cap}%",
    warning: "REMOVING THIS STAR WILL CONSUME THE SURROUNDING LAND • HOLD MINE",
    acknowledgementAccepted: "WARNING UNDERSTOOD • HOLD MINE AGAIN TO PREVIEW THE SCAR",
    acknowledgementCancelled: "STAR KEPT • THE REFUGE REMAINS SAFE",
    confirmed: "STAR SACRIFICE CONFIRMED • THIS REFUGE WILL BE LOST",
    scarEntered: "STARLESS SCAR • DARKNESS PANIC +60%",
    refugeColor: "#7de7ff",
    chargingColor: "#71f5c8",
    warningColor: "#ffbf69",
    scarColor: "#d56b93",
    messageDurationMs: 2400,
    warningDurationMs: 3200,
  }),
  diagnostics: Object.freeze({
    globalKey: "__jkdStarSanctuary",
  }),
});

export function isStarSanctuaryEnabled(
  search = globalThis?.location?.search || "",
  config = STAR_SANCTUARY_CONFIG,
) {
  const value = new URLSearchParams(search).get(config.queryParam);
  if (value === null) return config.enabledByDefault;
  return value !== "0" && value.toLowerCase() !== "false";
}
