// ==================== STAR SANCTUARY ====================
// Intact Stars are small, reusable refuges. Removing one keeps the normal
// Star reward but permanently leaves a large, territory-bound Starless Scar.

const temperament = (
  id,
  label,
  description,
  gpRateScale,
  gpCapBonus,
  radiusScale,
  stressRecoveryScale,
) => Object.freeze({
  id,
  label,
  description,
  gpRateScale,
  gpCapBonus,
  radiusScale,
  stressRecoveryScale,
});

export const STAR_SANCTUARY_CONFIG = Object.freeze({
  id: "star-sanctuary-v2",
  queryParam: "starSanctuary",
  enabledByDefault: true,
  maximumFrameMs: 100,
  refuge: Object.freeze({
    baseRadiusTiles: 1.5,
    maximumRadiusTiles: 2.2,
    restWarmupMs: 900,
    maximumRestSpeedTilesPerSecond: 0.38,
    gpPerSecondByRarity: Object.freeze([5, 6, 7.5, 9.5, 12, 16]),
    gpCapRatioByRarity: Object.freeze([0.6, 0.65, 0.7, 0.76, 0.84, 1]),
    gpRateVariation: Object.freeze([0.92, 1.08]),
    gpCapVariation: Object.freeze([-0.02, 0.02]),
    radiusVariation: Object.freeze([0.96, 1.04]),
    stressRecoveryVariation: Object.freeze([0.94, 1.06]),
    minimumGpCapRatio: 0.5,
    maximumGpCapRatio: 1,
    minimumStressRecoveryScale: 0.8,
    maximumStressRecoveryScale: 1.65,
    gpPulseIntervalMs: 700,
  }),
  temperaments: Object.freeze([
    temperament(
      "wellspring",
      "WELLSPRING",
      "Charges GP faster",
      1.35,
      0,
      0.96,
      0.95,
    ),
    temperament(
      "reservoir",
      "RESERVOIR",
      "Charges GP to a higher reserve",
      0.84,
      0.12,
      0.97,
      0.95,
    ),
    temperament(
      "haven",
      "HAVEN",
      "Has a wider refuge and stronger Panic relief",
      0.9,
      0,
      1.18,
      1.42,
    ),
  ]),
  consumption: Object.freeze({
    confirmationHoldMs: 1000,
    maximumAttemptGapMs: 1400,
    acknowledgement: Object.freeze({
      storageKeyPrefix: "dig-game-star-consumption-ack-v2-slot-",
      storageVersion: 2,
      confirmationWord: "DESTROY",
      title: "DESTROY A STAR REFUGE?",
      subtitle: "PERMANENT WORLD DAMAGE",
      body: [
        "THIS STAR IS A MINI-BASE.",
        "",
        "DESTROYING IT PERMANENTLY REMOVES:",
        "LIGHT  •  MATERIAL YIELD  •  GP RECOVERY  •  PANIC RELIEF",
        "",
        "THE STAR'S ENTIRE TERRITORY WILL BECOME A SCAR.",
        "DEADZONE PANIC BUILDS AT 4X THE NORMAL RATE.",
        "DESTROYING THE LAST STAR SCARS THE WHOLE UNDERGROUND.",
      ].join("\n"),
      typedInstruction: "TYPE DESTROY, THEN PRESS ENTER",
      footer: "ESC  KEEP THE STAR",
      footerColor: "#d6a84a",
    }),
    preview: Object.freeze({
      worldDepth: 53,
      fillAlpha: 0.24,
      boundaryAlpha: 0.05,
      ringAlpha: 0.72,
      ringWidthTiles: 0.045,
      pulsePeriodMs: 900,
      pulseMinimum: 0.82,
      pulseMaximum: 1,
    }),
    holdUi: Object.freeze({
      holdFrameKey: "ui-hud-approved-xp",
      holdFramePath: "sprites/UI/hud-approved-v1/xp-frame.png",
      depth: 4100,
      yRatio: 0.82,
      widthRatio: 0.38,
      minimumWidthPx: 300,
      maximumWidthPx: 520,
      viewportMaximumRatio: 0.86,
      frameAspectRatio: 13.18,
      fillWidthRatio: 0.94,
      fillHeightRatio: 0.24,
      fillColor: 0xff795f,
      fillAlpha: 0.96,
      titleY: -34,
      statusY: 0,
      consequenceY: 34,
      titleFontPx: 17,
      statusFontPx: 14,
      consequenceFontPx: 12,
      titleColor: "#ffd0bd",
      statusColor: "#fff0c2",
      consequenceColor: "#ff9f91",
      strokeColor: "#090205",
      strokeThickness: 4,
      title: "PERMANENT STAR SACRIFICE",
      status: "HOLD MINE  •  {percent}%",
      consequence: "LIGHT • MATERIALS • GP • PANIC RELIEF WILL BE LOST  •  RELEASE TO CANCEL",
    }),
  }),
  scar: Object.freeze({
    // Radius remains the no-territory fallback. Production scars own the full
    // nearest-Star territory so every underground cell has one clear fate.
    radiusTiles: 14,
    territoryBound: true,
    coversEntireTerritory: true,
    minimumDepthOffsetTiles: 1,
    panicStressMultiplier: 4,
    resourceDepletion: Object.freeze({
      enabled: true,
      presentation: Object.freeze({
        refreshIntervalMs: 80,
        reducedMotionMediaQuery: "(prefers-reduced-motion: reduce)",
        cullMarginTiles: 2,
        maxAnimatedCells: 42,
        reducedMotionMaxAnimatedCells: 16,
      }),
    }),
    spread: Object.freeze({
      holdStartRadiusTiles: 1.25,
      holdEndRadiusTiles: 9,
      postBreakStartRadiusTiles: 9,
      postBreakEndRadiusTiles: 36,
      postBreakDurationMs: 2600,
      cellPaddingTiles: 0.8,
      easingExponent: 1.8,
    }),
    visual: Object.freeze({
      baseDepth: 2.29,
      groundDepth: 2.3,
      paletteGroundDepth: 2.303,
      materialDepth: 2.305,
      palettePropDepth: 2.306,
      centerDepth: 2.307,
      paletteCenterDepth: 2.3075,
      frontierDepth: 2.309,
      paletteFrontierDepth: 2.3095,
      rimDepth: 2.31,
      assets: Object.freeze({
        ground: Object.freeze({
          key: "environment-starless-scar-walkable-ground-v3",
          path: "sprites/environment/starless-scar-v3/starless-scar-walkable-ground-v3.png",
        }),
        corruption: Object.freeze({
          key: "environment-starless-scar-territory-material-v2",
          path: "sprites/environment/starless-scar-v2/starless-scar-territory-material-v2.png",
        }),
        center: Object.freeze({
          key: "environment-starless-scar-dead-center-v3",
          path: "sprites/environment/starless-scar-v3/starless-scar-dead-center-v3.png",
        }),
        frontier: Object.freeze({
          key: "environment-starless-scar-frontier-edge-v3",
          path: "sprites/environment/starless-scar-v3/starless-scar-frontier-edge-v3.png",
        }),
      }),
      baseColor: 0x08050d,
      edgeShadowColor: 0x020106,
      veinColor: 0x8f6b7e,
      baseAlpha: 0.3,
      groundAlpha: 1,
      groundTileScale: 0.38,
      materialAlpha: 0.24,
      materialTileScale: 0.62,
      centerAlpha: 0.96,
      centerPreviewMinimumAlpha: 0.42,
      centerSizeTiles: 5.6,
      frontierAlpha: 0.78,
      frontierSizeTiles: 1.55,
      frontierInsetTiles: 0.1,
      paletteGroundAlpha: 1,
      paletteGroundTileScale: 0.78,
      paletteCenterAlpha: 0.98,
      paletteCenterSizeTiles: 7.2,
      paletteFrontierAlpha: 0.9,
      paletteFrontierSizeTiles: 2.7,
      palettePropAlpha: 0.9,
      palettePropSizeTilesMin: 2.8,
      palettePropSizeTilesMax: 4.8,
      paletteMaximumVisibleProps: 18,
      cellOverlapRatio: 0.035,
      edgeShadowWidthTiles: 0.24,
      edgeShadowAlpha: 0.4,
      edgeWidthTiles: 0.045,
      edgeAlpha: 0.28,
      coreHaloRadiusTiles: 2.2,
      coreRimWidthTiles: 0.055,
      coreRimAlpha: 0.24,
      cullMarginTiles: 3,
    }),
  }),
  feedback: Object.freeze({
    refugeEntered: "{name} • {temperament} REFUGE • REST FOR GP",
    charging: "{name} • +{rate} GP/s TO {cap}%",
    warning: "REMOVING THIS STAR WILL EXHAUST ITS TERRITORY • HOLD MINE",
    acknowledgementAccepted: "WARNING UNDERSTOOD • HOLD MINE AGAIN TO PREVIEW THE SCAR",
    acknowledgementCancelled: "STAR KEPT • THE REFUGE REMAINS SAFE",
    confirmed: "STAR SACRIFICE CONFIRMED • ITS TERRITORY WILL BE EXHAUSTED",
    scarEntered: "STARLESS SCAR • MATERIALS DEPLETED • DEADZONE PANIC 4X",
    refugeColor: "#7de7ff",
    chargingColor: "#71f5c8",
    warningColor: "#ffbf69",
    scarColor: "#d56b93",
    messageDurationMs: 2400,
    warningDurationMs: 3200,
  }),
  diagnostics: Object.freeze({
    globalKey: "__jkdStarSanctuary",
  }),
});

export function isStarSanctuaryEnabled(
  search = globalThis?.location?.search || "",
  config = STAR_SANCTUARY_CONFIG,
) {
  const value = new URLSearchParams(search).get(config.queryParam);
  if (value === null) return config.enabledByDefault;
  return value !== "0" && value.toLowerCase() !== "false";
}
