// ==================== STARLIGHT TALENT TREE ====================
// Shared ESC / Star Pillar presentation, first-star reveal, and health contract.

const QUICKSLASH_RESOURCES = Object.freeze([
  "dirt",
  "copper",
  "steel",
  "bronze",
  "silver",
]);

const THUNDERSTRIKE_RESOURCES = Object.freeze([
  "stone",
  "darkDirtNormal",
  "iron",
  "darkDirtStrong",
  "gold",
]);

export const STARLIGHT_TALENT_RESOURCE_ORDER = Object.freeze([
  ...QUICKSLASH_RESOURCES,
  ...THUNDERSTRIKE_RESOURCES,
]);

export const STARLIGHT_TALENT_TREE_CONFIG = Object.freeze({
  assets: Object.freeze({
    basePath: "sprites/UI/starlight-talent-tree-v3/",
    files: Object.freeze({
      modalShell: "starlight-modal-shell-v2.png",
      modalCrest: "constellation-crest-v2.png",
      modalClose: "celestial-close-v2.png",
      treePanel: "starlight-tree-panel-v2.png",
      detailPanel: "starlight-detail-panel-v2.png",
      enginePage: "starlight-engine-page-v2.png",
      nodeQuickslash: "node-frame-quickslash-v2.png",
      nodeThunderstrike: "node-frame-thunderstrike-v2.png",
      nodeLocked: "node-frame-bobo-locked-v2.png",
      nodeSelected: "node-selection-halo-v2.png",
      boboLock: "bobo-lock-seal-v2.png",
      starHeartSocket: "star-heart-socket-v2.png",
      connectorQuickslash: "connector-quickslash-v2.png",
      connectorThunderstrike: "connector-thunderstrike-v2.png",
      starHeart: "star-heart-ui-v2.png",
      waywardStar: "wayward-star-ui-v2.png",
      hollowSun: "hollow-sun-ui-v2.png",
      cometEngine: "comet-engine-ui-v2.png",
      ultrawideFoundation: "starlight-ultrawide-foundation-v3.png",
      navigationPlaqueIdle: "navigation-plaque-idle-v3.png",
      navigationPlaqueSelected: "navigation-plaque-selected-v3.png",
      talentRibbonIdle: "talent-ribbon-idle-v3.png",
      talentRibbonSelected: "talent-ribbon-selected-v3.png",
      statusSeal: "status-seal-v3.png",
      progressPlaque: "progress-plaque-v3.png",
      carouselLeft: "carousel-left-v3.png",
      carouselRight: "carousel-right-v3.png",
      carouselStepIdle: "carousel-step-idle-v3.png",
      carouselStepActive: "carousel-step-active-v3.png",
    }),
  }),
  branches: Object.freeze([
    Object.freeze({
      id: "quickslash",
      label: "QUICK SLASH",
      accent: 0xb985ff,
      cssAccent: "#C19AFF",
      prerequisiteLabel: "BUY QUICK SLASH FROM BOBO",
      resourceTypes: QUICKSLASH_RESOURCES,
    }),
    Object.freeze({
      id: "thunderstrike",
      label: "THUNDER STRIKE",
      accent: 0x63cfff,
      cssAccent: "#71D9FF",
      prerequisiteLabel: "BUY THUNDER STRIKE FROM BOBO",
      resourceTypes: THUNDERSTRIKE_RESOURCES,
    }),
  ]),
  pages: Object.freeze([
    Object.freeze({
      id: "quickslash",
      label: "QUICK SLASH",
      startIndex: 0,
      itemCount: 5,
    }),
    Object.freeze({
      id: "thunderstrike",
      label: "THUNDER STRIKE",
      startIndex: 5,
      itemCount: 5,
    }),
    Object.freeze({
      id: "engines",
      label: "STAR ENGINES",
      startIndex: 10,
      itemCount: 3,
    }),
  ]),
  resources: Object.freeze({
    dirt: Object.freeze({ shortName: "SHOVEL", material: "DIRT" }),
    stone: Object.freeze({ shortName: "MOUNTAIN", material: "STONE" }),
    copper: Object.freeze({ shortName: "ANVIL", material: "COPPER" }),
    darkDirtNormal: Object.freeze({ shortName: "CAVE", material: "DARK DIRT" }),
    steel: Object.freeze({ shortName: "SWORD", material: "STEEL" }),
    iron: Object.freeze({ shortName: "HAMMER", material: "IRON" }),
    bronze: Object.freeze({ shortName: "SHIELD", material: "BRONZE" }),
    darkDirtStrong: Object.freeze({ shortName: "FORTRESS", material: "HARD DIRT" }),
    silver: Object.freeze({ shortName: "CRESCENT", material: "SILVER" }),
    gold: Object.freeze({ shortName: "CROWN", material: "GOLD" }),
  }),
  copy: Object.freeze({
    title: "STARLIGHT TALENT TREE",
    detailTitle: "TALENT DETAIL",
    subtitle: "Each sign boosts matching Star Blocks and mutates its Bobo ability.",
    mastered: "MASTERED",
    partial: "IN PROGRESS",
    locked: "LOCKED",
    boboLocked: "BOBO LOCK",
    abilityOwned: "ABILITY OWNED",
    abilityLocked: "LOCKED  •  BUY FROM BOBO",
    abilityLockedHint: "STARS SAVED  •  BUY BASE ABILITY FROM BOBO",
    mutationActive: "MUTATION ACTIVE",
    mutationPending: "MUTATION ON MASTERY",
    firstStar: "FIRST STAR DISCOVERED",
    firstStarHint: "This material section will not interrupt you again.",
    starHeart: "STAR HEART",
    starHeartGate: "MASTER ALL CONSTELLATIONS TO ATTUNE YOUR FIRST ENGINE",
    engines: "CELESTIAL ENGINES",
    engineRule: "ALL 3 OWNABLE  •  1 EQUIPPED",
    pauseHint: "Select a sign to inspect its permanent reward.",
    pillarHint: "Inspect talents or choose one of three Celestial Engines.",
    pillarOnly: "Visit the Star Pillar to attune or equip Celestial Engines.",
    engineOwned: "OWNED",
    engineEquipped: "EQUIPPED",
    engineGodMode: "FREE",
    engineAvailable: "ATTUNE",
    engineLocked: "SEALED",
    pageHint: "UP / DOWN  •  CHANGE PAGE",
    engineAction: "CLICK CENTER TO ATTUNE OR EQUIP",
  }),
  layout: Object.freeze({
    referenceWidthPx: 1116,
    referenceHeightPx: 467,
    foundationAspectRatio: 2.3908754624,
    foundationUnderlayAlpha: 0.72,
    foundationUnderlayCropXFraction: 0.28,
    foundationUnderlayCropYFraction: 0.68,
    foundationUnderlayCropWidthFraction: 0.44,
    foundationUnderlayCropHeightFraction: 0.18,
    minimumLayoutScale: 0.76,
    pageTabYOffsetPx: 63,
    pageTabXFractions: Object.freeze([0.285, 0.5, 0.715]),
    pageTabWidthPx: 226,
    pageTabHeightPx: 62,
    pageTabPlaqueWidthPx: 224,
    pageTabPlaqueHeightPx: 60,
    pageTabIconSizePx: 32,
    pageTabIconOffsetXPx: -72,
    pageTabLabelOffsetXPx: 18,
    pageTabFontSizePx: 14,
    pageTabMinimumFontSizePx: 11,
    pageTabIdleAlpha: 0.72,
    pageTabSelectedAlpha: 1,
    pageTabIdleScale: 0.97,
    pageTabSelectedScale: 1.035,
    pageTabTweenMs: 140,
    branchHeaderXFraction: 0.125,
    branchHeaderOffsetYPx: 64,
    branchHeaderFontSizePx: 13,
    branchHeaderMinimumFontSizePx: 10,
    branchStatusXFraction: 0.885,
    branchStatusOffsetYPx: 64,
    branchStatusWidthPx: 174,
    branchStatusHeightPx: 52,
    branchStatusFontSizePx: 9,
    branchStatusMinimumFontSizePx: 8,
    branchStatusTextWidthFraction: 0.72,
    nodeRowOffsetYPx: 198,
    carouselSlotXFractions: Object.freeze([0.235, 0.5, 0.765]),
    carouselCenterSlotIndex: 1,
    carouselVisibleCards: 3,
    carouselArrowXFractions: Object.freeze([0.085, 0.915]),
    carouselArrowOffsetYPx: 198,
    carouselArrowSizePx: 58,
    carouselArrowIdleAlpha: 0.86,
    carouselArrowHoverTravelPx: 7,
    carouselTweenMs: 170,
    carouselFlankScale: 0.78,
    carouselCenterScale: 1.08,
    carouselFlankAlpha: 0.56,
    carouselFlankLabelAlpha: 0.76,
    nodeWidthPx: 160,
    nodeHeightPx: 220,
    nodeSelectionPaddingPx: 16,
    nodeArtMaxWidthPx: 92,
    nodeArtMaxHeightPx: 96,
    nodeArtOffsetYPx: -34,
    nodeRibbonWidthPx: 142,
    nodeRibbonHeightPx: 50,
    nodeRibbonOffsetYPx: 67,
    nodeNameOffsetYPx: 61,
    nodeProgressOffsetYPx: 77,
    nodeNameFontSizePx: 14,
    nodeNameMinimumFontSizePx: 11,
    nodeProgressFontSizePx: 9,
    nodeProgressMinimumFontSizePx: 8,
    nodeLockSizePx: 88,
    nodeLockOffsetXPx: 0,
    nodeLockOffsetYPx: -34,
    nodeTextStrokeColor: "#02060A",
    nodeTextStrokeThicknessPx: 2,
    detailLockSizePx: 82,
    detailSignXFraction: 0.17,
    detailSignOffsetYPx: 374,
    detailSignMaxPx: 94,
    detailTextXFraction: 0.255,
    detailTextRightPaddingFraction: 0.22,
    detailTitleOffsetYPx: 322,
    detailBuffOffsetYPx: 346,
    detailDescriptionOffsetYPx: 369,
    detailPassiveOffsetYPx: 387,
    detailProgressOffsetYPx: 405,
    detailProgressPlaqueHeightPx: 34,
    detailTitleFontSizePx: 18,
    detailTitleMinimumFontSizePx: 14,
    detailBuffFontSizePx: 12,
    detailBuffMinimumFontSizePx: 11,
    detailBodyFontSizePx: 10,
    detailBodyMinimumFontSizePx: 10,
    detailMetaFontSizePx: 9,
    detailMetaMinimumFontSizePx: 9,
    detailHeartXFraction: 0.84,
    detailHeartOffsetYPx: 374,
    detailHeartSizePx: 88,
    detailHeartLabelOffsetYPx: 25,
    detailHeartCountOffsetYPx: 38,
    detailHeartLabelFontSizePx: 12,
    detailHeartLabelMinimumFontSizePx: 9,
    detailHeartCountFontSizePx: 9,
    detailHeartCountMinimumFontSizePx: 8,
    engineCardWidthPx: 160,
    engineCardHeightPx: 220,
    engineArtMaxPx: 110,
    engineArtOffsetYPx: -32,
    engineSelectionHaloPx: 132,
    engineRibbonWidthPx: 144,
    engineRibbonHeightPx: 52,
    engineRibbonOffsetYPx: 68,
    engineNameOffsetYPx: 61,
    engineStatusOffsetYPx: 78,
    engineNameFontSizePx: 13,
    engineNameMinimumFontSizePx: 10,
    engineStatusFontSizePx: 8,
    engineStatusMinimumFontSizePx: 7,
    engineLockedAlpha: 0.56,
    engineLockedTint: 0x8294a8,
    selectedPulseScale: 1.035,
    ambientPulseMs: 1900,
    pillarMaxWidthPx: 1160,
    pillarMaxHeightPx: 690,
    pillarHeaderHeightPx: 122,
    pillarHeaderIconOffsetXPx: 110,
    pillarHeaderIconOffsetYPx: 98,
    pillarHeaderIconSizePx: 76,
    pillarHeaderTitleOffsetXPx: 176,
    pillarHeaderTitleOffsetYPx: 62,
    pillarHeaderSubtitleOffsetYPx: 92,
    pillarHeaderCloseOffsetXPx: 105,
    pillarHeaderCloseOffsetYPx: 98,
    pillarHeaderCloseSizePx: 38,
  }),
  reveal: Object.freeze({
    storageKey: "dig-game-talent-first-star-reveals-v1",
    openDelayMs: 520,
    maxPending: 10,
  }),
  health: Object.freeze({
    expectedConstellations: 10,
    expectedEngineOptions: 3,
    expectedPages: 3,
    expectedVisibleBranchCards: 3,
    maximumSteadyMotionLoops: 1,
  }),
});
