const candidate = (definition) => Object.freeze(definition);

export const SURVIVAL_RUN_REVIEW_CONFIG = Object.freeze({
  version: "survival-run-review-v1-20260720",
  frameSizePx: 256,
  cadenceModes: Object.freeze({ gameMatched: "game-matched", native: "native" }),
  defaultCadenceMode: "game-matched",
  viewScales: Object.freeze({ live: 1, inspection: 2 }),
  defaultViewScale: 1,
  speedControl: Object.freeze({ minimumPxPerSec: 100, maximumPxPerSec: 320, stepPxPerSec: 10 }),
  inspection: Object.freeze({
    timelineDurationMs: 6000,
    stepDurationSeconds: 1 / 30,
    stageHeightPx: 246,
    groundYRatio: 0.72,
    zoomGroundOffsetPx: 30,
    maxDevicePixelRatio: 2,
  }),
  candidates: Object.freeze([
    candidate({
      id: "blender-run",
      option: "A",
      label: "Natural forward run",
      badge: "Current mesh · Blender v2",
      tone: "selected",
      reviewStatus: "rejected",
      summary: "The current production Survival character run from the approved Blender v2 runtime sheet.",
      evidence: "Best control for judging whether the current game run feels too upright or too floaty.",
      file: "../../../sprites/character/survival-character-blender-v2/runtime/survival-character-blender-v2-run-sheet.png",
      frameCount: 28,
      columns: 16,
      fps: 16,
      displaySizePx: 109,
      originY: 226 / 256,
      sourceClip: "MINER_run",
    }),
    candidate({
      id: "unreal-run",
      option: "B",
      label: "Epic GASP forward jog",
      badge: "Epic UE5 sample · retargeted",
      tone: "recommended",
      reviewStatus: "rejected",
      summary: "Epic’s Unreal Game Animation Sample forward jog retargeted onto the current Survival character.",
      evidence: "Best fit for this game: clear forward intent, readable foot travel, and enough weight for the mining suit.",
      file: "../../../sprites/character/survival-character-unreal-v1/runtime/survival-character-unreal-v1-run-sheet.png",
      frameCount: 28,
      columns: 16,
      fps: 16,
      displaySizePx: 109,
      originY: 226 / 256,
      sourceClip: "MF_Unarmed_Jog_Fwd",
    }),
    candidate({
      id: "ual-jog",
      option: "C",
      label: "Compact UAL jog",
      badge: "Unreal IK retarget",
      tone: "power",
      reviewStatus: "selected",
      summary: "The current Survival skin carrying the UAL Jog_Fwd_Loop through the UE5 IK Retargeter path.",
      evidence: "Compact, readable cadence with less dead time; useful if the current run lacks urgency.",
      file: "../../../sprites/character/survival-ual-player-v1/runtime/survival-ual-player-v1-run-sheet.webp",
      frameCount: 28,
      columns: 16,
      fps: 30,
      displaySizePx: 109,
      originY: 247 / 256,
      sourceClip: "Jog_Fwd_Loop",
    }),
    candidate({
      id: "blender-walk-run",
      option: "D",
      label: "Long planted stride",
      badge: "Walk source stress test",
      tone: "recommended",
      reviewStatus: "rejected",
      summary: "The production Survival walk source evaluated inside the run slot at the live travel speed.",
      evidence: "Most stable feet and torso; a strong fallback if the run needs weight more than speed.",
      file: "../../../sprites/character/survival-character-blender-v2/runtime/survival-character-blender-v2-walk-sheet.png",
      frameCount: 24,
      columns: 16,
      fps: 16,
      displaySizePx: 109,
      originY: 224 / 256,
      sourceClip: "MINER_walk",
    }),
    candidate({
      id: "unreal-walk-run",
      option: "E",
      label: "Controlled Unreal gait",
      badge: "Walk source stress test",
      tone: "heavy",
      reviewStatus: "rejected",
      summary: "The Unreal-retargeted Survival walk evaluated as a faster traversal gait.",
      evidence: "Most deliberate and grounded; likely strongest for a heavy mining suit, but may need more urgency.",
      file: "../../../sprites/character/survival-character-unreal-v1/runtime/survival-character-unreal-v1-walk-sheet.png",
      frameCount: 24,
      columns: 16,
      fps: 16,
      displaySizePx: 109,
      originY: 224 / 256,
      sourceClip: "UE5 retargeted walk",
    }),
  ]),
});
