export const TELEPORT_PORTAL_CONFIG = Object.freeze({
  gateFilename: "prop_048_eclipse_gate.webp",
  authoredSourcePath: "sprites/background-props/generated-runtime-v1/prop_048_eclipse_gate.webp",
  canonicalAssetPath: "exports/dig_game_runtime_bg_props_v1/sprites/background-props/generated-runtime-v1/prop_048_eclipse_gate.webp",
  authoredTextureKey: "authored-bg-prop-048-eclipse-gate-webp",
  maxActiveSkyPortals: 4,
  fallbackTilePx: 94,
  apertureOffsetX: 0.5,
  apertureOffsetY: 0.46,
  glowRadiusScale: 0.27,
  glowColor: 0x7bdcff,
  glowAlphaMin: 0.2,
  glowAlphaMax: 0.62,
  glowScaleMin: 0.92,
  glowScaleMax: 1.12,
  glowDurationMs: 900,
  glowDepth: 2.5,
  glowTextureKey: "sky-portal-aperture-glow",
  glowTextureSize: 128,
  safeReturnRadius: 2,
});
