export const THUNDER_STRIKE_CHAIN_PHASES = Object.freeze({
  IDLE: "idle",
  CHARGE: "charge",
  STRIKE: "strike",
  TIMING: "timing",
  READY: "ready",
  COMPLETE: "complete",
  FAILED: "failed",
});

const stage = (number, damageMultiplier, timing, visual) => Object.freeze({
  number,
  damageMultiplier,
  timing: timing ? Object.freeze(timing) : null,
  visual: Object.freeze(visual),
});

export const THUNDER_STRIKE_CHAIN_CONFIG = Object.freeze({
  upfrontCostMultiplier: 3,
  followUpCost: 0,
  stages: Object.freeze([
    stage(1, 1, null, {
      label: "I",
      accent: 0x7fdcff,
      accentCss: "#7fdcff",
      boltThickness: 3,
      glowThickness: 12,
      branchCount: 3,
      ringCount: 2,
      sparkCount: 12,
      flashAlpha: 0.12,
      shakeSignature: "thunderStrike.slam1",
      fallbackShakeDurationMs: 130,
      fallbackShakeIntensity: 0.006,
    }),
    stage(2, 3, {
      durationMs: 940,
      targetProgress: 0.66,
      windowMs: 90,
    }, {
      label: "II",
      accent: 0xb58cff,
      accentCss: "#b58cff",
      boltThickness: 5,
      glowThickness: 18,
      branchCount: 6,
      ringCount: 3,
      sparkCount: 22,
      flashAlpha: 0.2,
      shakeSignature: "thunderStrike.slam2",
      fallbackShakeDurationMs: 180,
      fallbackShakeIntensity: 0.01,
    }),
    stage(3, 10, {
      durationMs: 720,
      targetProgress: 0.79,
      windowMs: 30,
    }, {
      label: "III",
      accent: 0xffd36b,
      accentCss: "#ffd36b",
      boltThickness: 8,
      glowThickness: 28,
      branchCount: 10,
      ringCount: 5,
      sparkCount: 38,
      flashAlpha: 0.32,
      shakeSignature: "thunderStrike.slam3",
      fallbackShakeDurationMs: 260,
      fallbackShakeIntensity: 0.017,
    }),
  ]),
  feedback: Object.freeze({
    timingHitText: "PERFECT — FREE SLAM",
    chainBrokenText: "CHAIN BROKEN",
    finalHitText: "10× STORM PERFECT",
    followUpsFreeText: "FOLLOW-UP SLAMS FREE",
    timingHintText: "PRESS {key} INSIDE THE FLASH",
    successLingerMs: 260,
    failureLingerMs: 620,
    finalLingerMs: 850,
  }),
  timingBar: Object.freeze({
    width: 520,
    height: 160,
    top: 22,
    depth: 3700,
    cornerRadius: 14,
    panelColor: 0x070c19,
    panelAlpha: 0.94,
    innerColor: 0x101a31,
    innerAlpha: 0.97,
    frameColor: 0xb98545,
    frameHighlightColor: 0xffd58a,
    trackColor: 0x17233d,
    trackBorderColor: 0x58739f,
    targetColor: 0xffeaa0,
    targetGlowColor: 0xffb84d,
    needleColor: 0xffffff,
    titleColor: "#f7e2b2",
    mutedColor: "#91a0bd",
    freeColor: "#7fffd4",
    dangerColor: "#ff607c",
    titleFont: "Georgia, serif",
    bodyFont: "Consolas, monospace",
    titleFontSize: "18px",
    bodyFontSize: "13px",
    promptFontSize: "16px",
    titleY: 8,
    stageY: 48,
    trackX: 28,
    trackY: 82,
    trackWidth: 464,
    trackHeight: 18,
    promptY: 108,
    freeLabelY: 136,
    needleWidth: 4,
    needleOverhang: 9,
    resizeDebounceMs: 0,
  }),
  impactFx: Object.freeze({
    depth: 44,
    boltSkyHeightTiles: 7,
    boltSegments: 16,
    boltJitterPx: 18,
    branchLengthPx: 42,
    boltLifetimeMs: 190,
    ringLifetimeMs: 420,
    sparkLifetimeMs: 460,
    flashLifetimeMs: 170,
    labelRisePx: 52,
    labelLifetimeMs: 680,
    labelFont: "Georgia, serif",
    labelFontSizes: Object.freeze(["24px", "31px", "42px"]),
    coreColor: 0xf7fbff,
    glowColor: 0x72b8ff,
    flashColor: 0xd9ecff,
  }),
});

export function getThunderStrikeStage(stageIndex = 0) {
  const clamped = Math.max(
    0,
    Math.min(THUNDER_STRIKE_CHAIN_CONFIG.stages.length - 1, Math.trunc(stageIndex)),
  );
  return THUNDER_STRIKE_CHAIN_CONFIG.stages[clamped];
}
