const scenario = (id, label, title, description) => Object.freeze({ id, label, title, description });

export const UAL_ANIMATION_TUNING_LAB_CONFIG = Object.freeze({
  version: "ual-animation-tuning-lab-v3-20260726-animation-polish",
  productionAssetRoot: "../../../sprites/character/ual-native-player-v1/runtime",
  productionManifestPath: "../../../sprites/character/ual-native-player-v1/runtime/manifest.json",
  selectedWalkDraft: Object.freeze({
    option: "C",
    sourceClip: "Jog_Fwd_Loop",
    productionAction: "run",
  }),
  defaults: Object.freeze({
    scenarioId: "locomotion",
    selectedActionId: "idle",
    aim: "RIGHT",
    playing: true,
    playbackRate: 1,
    cadenceMode: "matched",
    facingLeft: false,
    zoom: 1,
    showGuides: true,
    showCollider: true,
    showRig: true,
    showContact: true,
    showOnion: false,
    showProductionGhost: true,
  }),
  scenarios: Object.freeze([
    scenario("locomotion", "Locomotion", "Immediate jog · stop · flip", "Every grounded movement speed uses the run-slot Jog and preserves its cycle through reversals."),
    scenario("ladder", "Jog speeds", "Single-gait speed ladder", "Tests the same Jog from low-speed input through upgraded movement speeds."),
    scenario("air", "Air / landing", "Soft skip · impact · move cancel", "Reviews impact-gated landing and its short movement-cancellable recovery."),
    scenario("flight", "Flight", "Native rollback flight phases", "Reviews the UAL rollback phases; Survivor uses one continuous production flight loop."),
    scenario("mining", "Mining / combo", "Cooldown-paced contact and recovery", "Shows contact truth, neutral uppercut recovery and cancellable post-contact recovery."),
    scenario("library", "Full library", "All production actions", "Raw source review with honest metadata coverage."),
  ]),
  view: Object.freeze({
    canvasHeightPx: 510,
    maxDevicePixelRatio: 2,
    groundYRatio: 0.76,
    eventLimit: 42,
    onionAlpha: 0.18,
  }),
  controls: Object.freeze({
    playbackRates: Object.freeze([0.25, 0.5, 1, 2]),
    zoomLevels: Object.freeze([1, 1.5, 2]),
    cadenceModes: Object.freeze(["matched", "native"]),
    aims: Object.freeze(["RIGHT", "LEFT", "UP", "DOWN", "UP-RIGHT", "UP-LEFT", "DOWN-RIGHT", "DOWN-LEFT"]),
    speed: Object.freeze({ minimum: 0, maximum: 504, step: 2 }),
    stride: Object.freeze({ minimum: 0.6, maximum: 2.8, step: 0.01 }),
    cadence: Object.freeze({ minimum: 0.2, maximum: 4, step: 0.05 }),
    trim: Object.freeze({ minimum: 1, step: 1 }),
    runThreshold: Object.freeze({ minimum: 0, maximum: 504, step: 2 }),
    landingFrames: Object.freeze({ minimum: 1, step: 1 }),
    holdSeconds: Object.freeze({ minimum: 0.1, maximum: 4, step: 0.05 }),
    comboGapMs: Object.freeze({ minimum: 0, maximum: 400, step: 10 }),
    contactFrameOffset: Object.freeze({ minimum: -10, maximum: 10, step: 1 }),
    contactScale: Object.freeze({ minimum: 0.5, maximum: 1.5, step: 0.05 }),
    bodyWidth: Object.freeze({ minimum: 10, maximum: 94, step: 1 }),
    bodyHeight: Object.freeze({ minimum: 20, maximum: 94, step: 1 }),
    bodyOffset: Object.freeze({ minimum: -94, maximum: 94, step: 0.5 }),
    contactOffset: Object.freeze({ minimum: -94, maximum: 94, step: 0.5 }),
    contactAxisScale: Object.freeze({ minimum: 0.25, maximum: 3, step: 0.05 }),
    markerOffset: Object.freeze({ minimum: -96, maximum: 96, step: 0.25 }),
    poseOffset: Object.freeze({ minimum: -94, maximum: 94, step: 0.5 }),
    poseRotation: Object.freeze({ minimum: -45, maximum: 45, step: 0.25 }),
    poseScale: Object.freeze({ minimum: 0.5, maximum: 1.5, step: 0.01 }),
    frameHold: Object.freeze({ minimum: 0.1, maximum: 6, step: 0.05 }),
  }),
  editor: Object.freeze({
    schema: "ual-animation-pose-contact-patch-v3",
    tools: Object.freeze(["body", "contact", "hand", "pose"]),
    scopes: Object.freeze(["frame", "action"]),
    editableMarkers: Object.freeze(["hand_l", "hand_r", "foot_l", "foot_r"]),
    defaults: Object.freeze({
      activeTool: "body",
      scope: "frame",
      selectedMarker: "hand_r",
      snapToPixels: false,
      bodyOffsetXPx: 0,
      bodyOffsetYPx: 0,
      contactOffsetXPx: 0,
      contactOffsetYPx: 0,
      contactWidthScale: 1,
      contactHeightScale: 1,
      poseOffsetXPx: 0,
      poseOffsetYPx: 0,
      poseRotationDeg: 0,
      poseScaleX: 1,
      poseScaleY: 1,
      frameHold: 1,
      markerOffsetXPx: 0,
      markerOffsetYPx: 0,
    }),
    interaction: Object.freeze({
      handleRadiusPx: 7,
      hitPaddingPx: 9,
      boxHitPaddingPx: 2,
      markerRadiusPx: 8,
      nudgePx: 1,
      largeNudgePx: 5,
      minimumBoxPx: 4,
      maximumRangeFrames: 512,
    }),
    historyLimit: 80,
  }),
  timeline: Object.freeze({
    locomotion: Object.freeze({ idleLeadSeconds: 0.8, jogLoopSeconds: 2.2, idleMiddleSeconds: 0.35, reversalLoopSeconds: 1.3 }),
    ladder: Object.freeze({ idleLeadSeconds: 0.5, phaseSeconds: Object.freeze([1.15, 1.35, 1.35, 1.35, 1.35, 1.15]), speedsPxPerSec: Object.freeze([100, 200, 270, 320, 504, 230]) }),
    air: Object.freeze({ fallSeconds: 1.25, idleRecoverSeconds: 0.8 }),
    flight: Object.freeze({ hoverSeconds: 1.1, travelSeconds: 1.6, fallSeconds: 0.72 }),
    mining: Object.freeze({ recoveryGapSeconds: 0 }),
    libraryLoopSeconds: 3,
  }),
  mining: Object.freeze({
    sideComboClipIds: Object.freeze(["jab", "cross", "jab", "cross"]),
    upComboClipIds: Object.freeze(["up-jab", "up-cross"]),
    upSideComboClipIds: Object.freeze(["up-side-jab", "up-side-cross"]),
    repeatedHitCount: 3,
  }),
});
