import { GAME_CONFIG } from "./gameConfig.js";

const deepFreeze = (value) => {
  if (!value || typeof value !== "object" || Object.isFrozen(value)) return value;
  Object.values(value).forEach(deepFreeze);
  return Object.freeze(value);
};

const motion = (action, from, to, mode = "loop", rate = 1) => ({
  action,
  from,
  to,
  mode,
  rate,
});

export const UAL_FLIGHT_LAB_VARIANTS = deepFreeze([
  {
    id: "A",
    name: "Current rocket",
    short: "Baseline",
    description: "Current Shield Dash travel, production-style hover, no prop.",
    pivot: "origin",
    boardMode: "off",
    trailStyle: "wake",
    pitchByPhase: { takeoff: 0, hover: 0, cruise: 2, boost: 5, brake: 1, land: 0 },
    boardOpacityByPhase: {},
    motionByPhase: {
      hover: motion("airborne", 8, 16, "pingpong", 0.72),
      cruise: motion("fly", 6, 12, "pingpong", 0.9),
      boost: motion("fly", 2, 12, "pingpong", 1.2),
      brake: motion("landing", 0, 13, "once", 0.8),
    },
  },
  {
    id: "B",
    name: "Legacy hoverboard",
    short: "Upright board",
    description: "Readable upright stance with the old purple-board energy language.",
    pivot: "feet",
    boardMode: "always",
    trailStyle: "thrusters",
    pitchByPhase: { takeoff: -2, hover: 0, cruise: -3, boost: -7, brake: 5, land: 0 },
    boardOpacityByPhase: { takeoff: 0.7, hover: 1, cruise: 1, boost: 1, brake: 1, land: 0.75 },
    motionByPhase: {
      hover: motion("idle", 0, 74, "loop", 0.8),
      cruise: motion("idle", 0, 74, "loop", 1),
      boost: motion("idle", 0, 74, "loop", 1.15),
      brake: motion("idle", 0, 74, "loop", 0.72),
    },
  },
  {
    id: "C",
    name: "Hoverboard carve",
    short: "Crouch surf",
    description: "Low centre of gravity, stronger banking, sparks, and a long board ribbon.",
    pivot: "feet",
    boardMode: "always",
    trailStyle: "ribbon",
    pitchByPhase: { takeoff: -2, hover: -1, cruise: -6, boost: -10, brake: 7, land: 0 },
    boardOpacityByPhase: { takeoff: 0.78, hover: 1, cruise: 1, boost: 1, brake: 1, land: 0.72 },
    motionByPhase: {
      hover: motion("crouch", 0, 87, "loop", 0.72),
      cruise: motion("crouch", 0, 87, "loop", 1),
      boost: motion("crouch", 0, 87, "loop", 1.28),
      brake: motion("crouch", 0, 87, "loop", 0.65),
    },
  },
  {
    id: "D",
    name: "Blender Superman flight",
    short: "One-arm hero",
    description: "Approved Survivor mesh, layered Push Loop, one lead arm, tucked hand, and stretched trailing legs.",
    pivot: "pelvis",
    boardMode: "off",
    trailStyle: "hero",
    hitboxMode: "review-flight",
    pitchByPhase: { takeoff: 0, hover: 4, cruise: 10, boost: 14, brake: 6, land: 0 },
    boardOpacityByPhase: {},
    motionByPhase: {
      hover: motion("superman-flight", 0, 10, "loop", 0.64),
      cruise: motion("superman-flight", 8, 28, "loop", 1),
      boost: motion("superman-flight", 10, 35, "loop", 1.22),
      brake: motion("superman-flight", 26, 35, "loop", 0.65),
    },
  },
  {
    id: "E",
    name: "Board-to-hero hybrid",
    short: "Adaptive boost",
    description: "Board for hover and control; it dissolves as Superman boost takes over.",
    pivot: "pelvis",
    boardMode: "hybrid",
    trailStyle: "hybrid",
    pitchByPhase: { takeoff: -2, hover: -1, cruise: 18, boost: 36, brake: 5, land: 0 },
    boardOpacityByPhase: { takeoff: 0.75, hover: 1, cruise: 0.32, boost: 0, brake: 0.85, land: 0.7 },
    motionByPhase: {
      hover: motion("crouch", 0, 87, "loop", 0.72),
      cruise: motion("wall-push", 0, 79, "loop", 0.95),
      boost: motion("wall-push", 0, 79, "loop", 1.28),
      brake: motion("crouch", 0, 87, "loop", 0.68),
    },
  },
]);

export const UAL_FLIGHT_STYLE_LAB_CONFIG = deepFreeze({
  version: "ual-flight-style-lab-v1-20260718",
  defaultVariantId: "C",
  defaultCharacterId: "survivalUal",
  defaultPhaseId: "sequence",
  productionChanged: false,
  characters: {
    survivalUal: "Approved Survival body",
    ualNative: "UAL source body",
  },
  actions: ["airborne", "landing", "fly", "idle", "crouch", "wall-push", "falling", "superman-flight"],
  reviewActions: {
    survivalUal: {
      "superman-flight": {
        manifestPath: "testing/blender-animation-lab-v1/review-drafts/superman-flight-push-layer-v1/runtime/manifest.json",
        reviewManifestPath: "testing/blender-animation-lab-v1/review-drafts/superman-flight-push-layer-v1/review-manifest.json",
        sourceActionId: "superman-flight",
      },
    },
  },
  fallbackActions: {
    "superman-flight": "wall-push",
  },
  phases: [
    { id: "sequence", label: "Full flight" },
    { id: "takeoff", label: "Takeoff" },
    { id: "hover", label: "Hover" },
    { id: "cruise", label: "Cruise" },
    { id: "boost", label: "Boost" },
    { id: "brake", label: "Brake" },
    { id: "land", label: "Land" },
  ],
  sequence: [
    { phase: "takeoff", durationMs: 1050 },
    { phase: "hover", durationMs: 1350 },
    { phase: "cruise", durationMs: 2350 },
    { phase: "boost", durationMs: 1550 },
    { phase: "brake", durationMs: 1050 },
    { phase: "land", durationMs: 1300 },
  ],
  sharedMotion: {
    takeoff: motion("airborne", 0, 17, "once", 0.72),
    land: motion("landing", 0, 38, "once", 0.82),
  },
  phasePreviewDurationMs: 3200,
  phaseSpeedFactor: {
    takeoff: 0.18,
    hover: 0.04,
    cruise: 1,
    boost: 1.58,
    brake: 0.32,
    land: 0.08,
  },
  stage: {
    width: 1180,
    height: 620,
    anchorXRatio: 0.61,
    anchorYRatio: 0.53,
    tileSizePx: GAME_CONFIG.tileSize,
    detailScale: 2.2,
    gameScale: 1,
    gridAlpha: 0.13,
  },
  controls: {
    speed: { min: 0, max: 440, step: 10, default: 220 },
    pitch: { min: -30, max: 55, step: 1, default: 0 },
    boardY: { min: -28, max: 32, step: 1, default: 4 },
    boardScale: { min: 0.7, max: 1.45, step: 0.05, default: 1 },
    trailScale: { min: 0.35, max: 1.8, step: 0.05, default: 1 },
    effectScale: { min: 0.2, max: 1.6, step: 0.05, default: 1 },
    playbackRate: { min: 0.35, max: 1.65, step: 0.05, default: 1 },
  },
  board: {
    widthPx: 80,
    heightPx: 11,
    noseLiftPx: 6,
    jetOffsetXPx: 20,
    jetLengthPx: 15,
    hoverBobPx: 3.5,
    hoverHz: 1.65,
    deckTop: "#26364a",
    deckBottom: "#081019",
    rim: "#60eaff",
    energy: "#b25cff",
    hotCore: "#f1efff",
  },
  input: {
    maxBankDeg: 10,
    liftPx: 34,
    bodyBobPx: 2.5,
    bodyBobHz: 1.15,
  },
  palette: {
    cyan: "#5cecff",
    blue: "#397dff",
    violet: "#b55cff",
    white: "#f4f5ff",
    cave: "#07101b",
    caveEdge: "#142234",
    danger: "#ffb15c",
  },
  bodyFallback: {
    frameWidth: 256,
    frameHeight: 256,
    originX: 0.5,
    originY: 0.96484375,
    displaySizePx: 109,
    colliderWidthPx: 31,
    colliderHeightPx: 75,
  },
});
