const range = (length) => Object.freeze(Array.from({ length }, (_, index) => index));
const segment = (start, endExclusive) => Object.freeze(
  Array.from({ length: endExclusive - start }, (_, index) => start + index),
);
const reversed = (frames) => Object.freeze([...frames].reverse());
const concatFrames = (...groups) => Object.freeze(groups.flat());

const SHEETS = Object.freeze({
  idle: "ual-native-v1-idle-sheet",
  idleTalk: "ual-native-v1-idle-talk-sheet",
  walk: "ual-native-v1-walk-sheet",
  run: "ual-native-v1-run-sheet",
  airborne: "ual-native-v1-airborne-sheet",
  falling: "ual-native-v1-falling-sheet",
  crouch: "ual-native-v1-crouch-sheet",
  fly: "ual-native-v1-fly-sheet",
  climb: "ual-native-v1-climb-sheet",
  punchJab: "ual-native-v1-punch-jab-sheet",
  punchCross: "ual-native-v1-punch-cross-sheet",
  pickaxeMining: "ual-native-v1-pickaxe-mining-sheet",
  uppercut: "ual-native-v1-uppercut-sheet",
  meleeHook: "ual-native-v1-melee-hook-sheet",
  meleeKick: "ual-native-v1-melee-kick-sheet",
  digUp: "ual-native-v1-dig-up-sheet",
  groundStrike: "ual-native-v1-ground-strike-sheet",
  landing: "ual-native-v1-landing-sheet",
  wallPush: "ual-native-v1-wall-push-sheet",
  teleport: "ual-native-v1-teleport-sheet",
  thunderCharge: "ual-native-v1-thunder-charge-sheet",
  hitReact: "ual-native-v1-hit-react-sheet",
  death: "ual-native-v1-death-sheet",
});
const ACTIVE_SHEETS = Object.freeze([
  "idle", "idleTalk", "walk", "run", "airborne", "falling", "crouch", "fly", "climb",
  "punchJab", "punchCross", "uppercut", "groundStrike", "landing", "wallPush", "teleport",
  "thunderCharge", "hitReact", "death",
].map((name) => SHEETS[name]));

const FRAMES = Object.freeze({
  idle: range(75),
  idleTalk: range(88),
  walk: range(28),
  run: range(28),
  airborne: range(41),
  falling: range(75),
  crouch: range(88),
  fly: range(14),
  climb: range(20),
  punchJab: range(27),
  punchCross: range(31),
  pickaxeMining: range(29),
  uppercut: range(15),
  meleeHook: range(33),
  meleeKick: range(26),
  digUp: range(17),
  groundStrike: range(41),
  landing: range(39),
  wallPush: range(80),
  teleport: range(45),
  thunderCharge: range(63),
  hitReact: range(11),
  death: range(73),
});

const DIG_UP_RISING_FRAMES = concatFrames(
  segment(0, 13),
  Object.freeze([14, 16]),
  reversed(segment(0, 16)),
);
const GROUND_STRIKE_DOWN_FRAMES = segment(4, 41);
const THUNDER_GROUND_STRIKE_FRAMES = segment(7, 41);
const QUICKSLASH_NATIVE_FRAMES = segment(3, 18);
const UPPERCUT_RECOVERY_FRAMES = Object.freeze([
  0, 1, 2, 2, 3, 3, 4, 5, 6, 7, 8, 9,
  10, 11, 12, 13, 14, 12, 10, 8, 6, 4, 2, 0,
]);
const LANDING_RECOVERY_FRAMES = Object.freeze([
  0, 2, 4, 6, 8, 10, 12, 15, 18, 21, 24, 28, 33, 38,
]);
const FLIGHT_HOVER_FRAMES = concatFrames(segment(8, 16), reversed(segment(9, 15)));
const FLIGHT_TRAVEL_LOOP_FRAMES = concatFrames(segment(8, 14), reversed(segment(9, 13)));
const FLIGHT_ENTER_FRAMES = segment(0, 17);
const FLIGHT_EXIT_FRAMES = segment(16, 25);
const WALK_CONTACT_TRANSITION_FRAMES = segment(3, 6);
const PUNCH_JAB_KEY = "ual-native-v1-punch-jab-anim";

const DIG_SIDE_KEYS = Object.freeze([
  PUNCH_JAB_KEY,
  "ual-native-v1-dig-side-cross-anim",
  PUNCH_JAB_KEY,
  "ual-native-v1-dig-side-cross-anim",
]);
const DIG_UP_KEYS = Object.freeze([
  "ual-native-v1-dig-up-jab-anim",
  "ual-native-v1-dig-up-cross-anim",
]);
const DIG_UP_SIDE_KEYS = Object.freeze([
  "ual-native-v1-dig-up-side-jab-anim",
  "ual-native-v1-dig-up-side-cross-anim",
]);
const DIG_DOWN_KEY = "ual-native-v1-dig-down-ground-strike-anim";
const WALK_DISPLAY_SIZE_PX = 123;
const DISPLAY_SIZE_BY_ANIMATION = Object.freeze({
  "ual-native-v1-walk-start-anim": WALK_DISPLAY_SIZE_PX,
  "ual-native-v1-walk-loop-anim": WALK_DISPLAY_SIZE_PX,
  "ual-native-v1-run-anim": WALK_DISPLAY_SIZE_PX,
  "ual-native-v1-walk-stop-anim": WALK_DISPLAY_SIZE_PX,
});

function punchVariant(key, useCross) {
  return Object.freeze({
    key,
    sheet: useCross ? SHEETS.punchCross : SHEETS.punchJab,
    frames: useCross ? FRAMES.punchCross : FRAMES.punchJab,
    frameRate: 30,
    repeat: 0,
  });
}

function nativeVariant(key, sheet, frames) {
  return Object.freeze({ key, sheet, frames, frameRate: 30, repeat: 0 });
}

function uppercutVariant(key) {
  return nativeVariant(key, SHEETS.uppercut, UPPERCUT_RECOVERY_FRAMES);
}

const DIG_ANIMATION_VARIANTS = Object.freeze([
  punchVariant(DIG_SIDE_KEYS[1], true),
  uppercutVariant(DIG_UP_KEYS[0]),
  uppercutVariant(DIG_UP_KEYS[1]),
  uppercutVariant(DIG_UP_SIDE_KEYS[0]),
  uppercutVariant(DIG_UP_SIDE_KEYS[1]),
]);
const DIG_ANIMS = Object.freeze(Array.from(new Set([
  DIG_DOWN_KEY,
  ...DIG_SIDE_KEYS,
  ...DIG_UP_KEYS,
  ...DIG_UP_SIDE_KEYS,
])));
const PUNCH_ACTION_ANIMS = Object.freeze(Array.from(new Set([
  ...DIG_ANIMS,
  PUNCH_JAB_KEY,
  "ual-native-v1-attack-down-ground-strike-anim",
])));

export const UAL_NATIVE_PLAYER_ASSET_PROFILE = Object.freeze({
  characterId: "ualNative",
  isUalNative: true,
  renderPipeline: "native-ual-game-rig-v2-zero-weapon",
  weaponPolicy: "none",
  preserveNativeActionCadence: false,
  immediateDigImpactFeedback: false,
  basePath: "sprites/character/ual-native-player-v1/runtime",
  version: "ual-native-player-v1-four-hit-jab-cross-ground-strike-20260724",
  rigManifestKey: "ual-native-v1-rig-manifest",
  rigManifestFile: "manifest.json",
  rigMarkerSchemaVersion: 1,
  frameWidth: 256,
  frameHeight: 256,
  textureFilter: "LINEAR",
  physicalHeightMeters: 1.75,
  targetVisibleHeightTiles: 0.8,
  referenceIdleVisibleWidthPx: 72,
  referenceIdleVisibleHeightPx: 177,
  displaySizePx: 109,
  displaySizePxByAnimation: DISPLAY_SIZE_BY_ANIMATION,
  playerBodyWidthPx: 31,
  playerBodyHeightPx: 75,
  visualOriginX: 0.5,
  visualOriginY: 247 / 256,

  sourceClips: Object.freeze({
    idle: "Idle_Loop",
    idleTalk: "Idle_Talking_Loop",
    walk: "Jog_Fwd_Loop",
    run: "Jog_Fwd_Loop",
    airborne: "Jump_Start",
    falling: "Jump_Loop",
    crouch: "Crouch_Idle_Loop",
    fly: "Shield_Dash",
    climb: "ClimbUp_1m",
    punchJab: "Punch_Jab",
    punchCross: "Punch_Cross",
    uppercut: "Melee_Hook",
    sideFinisher: "Punch_Cross",
    digUpPrimary: "Melee_Hook",
    digUpSecondary: "Melee_Hook_Rec",
    groundStrike: "OverhandThrow",
    digDown: "OverhandThrow",
    flyHover: "Jump_Start",
    landing: "Jump_Land",
    wallPush: "Push_Loop",
    teleport: "Roll",
    thunderCharge: "Spell_Simple_Idle_Loop",
    thunderStrike: "OverhandThrow",
    hitReact: "Hit_Chest",
    death: "Death01",
  }),
  rejectedSourceClips: Object.freeze({
    digDown: "Farm_Harvest",
    sideMining: "TreeChopping_Loop",
    thunderStrike: "Spell_Simple_Shoot",
    fly: "Swim_Fwd_Loop",
    flyHover: "Swim_Idle_Loop",
    ninjaHover: "NinjaJump_Idle_Loop",
    sideFinisher: "Authored_Grounded_Side_Kick_v1",
    digUpActive: "Sword_Regular_C",
  }),
  rejectedAnimationKeys: Object.freeze(["ual-native-v1-dig-side-jab-anim"]),

  idleSheet: SHEETS.idle,
  idleTalkSheet: SHEETS.idleTalk,
  walkSheet: SHEETS.walk,
  walkStartSheet: SHEETS.walk,
  walkLoopSheet: SHEETS.walk,
  walkRunSheet: SHEETS.run,
  walkStopSheet: SHEETS.walk,
  airborneSheet: SHEETS.airborne,
  fallingSheet: SHEETS.falling,
  duckSheet: SHEETS.crouch,
  digDownSheet: SHEETS.groundStrike,
  digSidewaysSheet: SHEETS.punchJab,
  digUpSheet: SHEETS.uppercut,
  digUpSidewaysSheet: SHEETS.uppercut,
  digUpLookSheet: SHEETS.thunderCharge,
  wallPushSheet: SHEETS.wallPush,
  leanAgainstWallSheet: SHEETS.idleTalk,
  combatIdleRecoverSheet: SHEETS.idleTalk,
  combatIdleToNormalIdleSheet: SHEETS.idleTalk,
  climbSheet: SHEETS.climb,
  flySheet: SHEETS.fly,
  flyClimbSheet: SHEETS.airborne,
  flightEnterSheet: SHEETS.airborne,
  flightTravelEnterSheet: SHEETS.fly,
  flightTravelLoopSheet: SHEETS.fly,
  flightHoverSheet: SHEETS.airborne,
  flightExitSheet: SHEETS.airborne,
  landingSheet: SHEETS.landing,
  quickslashSheet: SHEETS.punchJab,
  teleportInSheet: SHEETS.teleport,
  thunderStrikeChargeSheet: SHEETS.thunderCharge,
  thunderStrikeStrikeSheet: SHEETS.groundStrike,
  attackDownSheet: SHEETS.groundStrike,
  earthquakeReactSheet: SHEETS.hitReact,
  deathSheet: SHEETS.death,
  punchJabSheet: SHEETS.punchJab,
  punchCrossSheet: SHEETS.punchCross,
  pickaxeMiningSheet: SHEETS.pickaxeMining,
  uppercutSheet: SHEETS.uppercut,
  meleeHookSheet: SHEETS.meleeHook,
  meleeKickSheet: SHEETS.meleeKick,
  groundStrikeSheet: SHEETS.groundStrike,

  idleFrames: FRAMES.idle,
  idleTalkFrames: FRAMES.idleTalk,
  walkFrames: FRAMES.walk,
  walkStartFrames: WALK_CONTACT_TRANSITION_FRAMES,
  walkLoopFrames: FRAMES.walk,
  walkRunFrames: FRAMES.run,
  walkStopFrames: reversed(WALK_CONTACT_TRANSITION_FRAMES),
  airborneFrames: FRAMES.airborne,
  fallingFrames: FRAMES.falling,
  duckFrames: FRAMES.crouch,
  digDownFrames: GROUND_STRIKE_DOWN_FRAMES,
  digSidewaysFrames: QUICKSLASH_NATIVE_FRAMES,
  digUpFrames: UPPERCUT_RECOVERY_FRAMES,
  digUpSidewaysFrames: UPPERCUT_RECOVERY_FRAMES,
  digUpLookFrames: FRAMES.thunderCharge,
  wallPushFrames: FRAMES.wallPush,
  leanAgainstWallFrames: segment(64, 88),
  combatIdleRecoverFrames: segment(40, 64),
  combatIdleToNormalIdleFrames: segment(64, 88),
  climbFrames: FRAMES.climb,
  flyFrames: FLIGHT_TRAVEL_LOOP_FRAMES,
  flyClimbFrames: FLIGHT_HOVER_FRAMES,
  flightEnterFrames: FLIGHT_ENTER_FRAMES,
  flightTravelEnterFrames: FRAMES.fly,
  flightTravelLoopFrames: FLIGHT_TRAVEL_LOOP_FRAMES,
  flightHoverFrames: FLIGHT_HOVER_FRAMES,
  flightExitFrames: FLIGHT_EXIT_FRAMES,
  landingFrames: LANDING_RECOVERY_FRAMES,
  quickslashFrames: QUICKSLASH_NATIVE_FRAMES,
  teleportInFrames: FRAMES.teleport,
  thunderStrikeChargeFrames: segment(0, 30),
  thunderStrikeStrikeFrames: THUNDER_GROUND_STRIKE_FRAMES,
  attackDownFrames: GROUND_STRIKE_DOWN_FRAMES,
  earthquakeReactFrames: FRAMES.hitReact,
  deathFrames: FRAMES.death,
  punchJabFrames: FRAMES.punchJab,
  punchCrossFrames: FRAMES.punchCross,
  pickaxeMiningFrames: FRAMES.pickaxeMining,
  uppercutFrames: FRAMES.uppercut,
  uppercutPlaybackFrames: UPPERCUT_RECOVERY_FRAMES,
  meleeHookFrames: FRAMES.meleeHook,
  meleeKickFrames: FRAMES.meleeKick,
  groundStrikeSourceFrames: FRAMES.groundStrike,
  landingSourceFrames: FRAMES.landing,
  flySourceFrames: FRAMES.fly,
  thunderChargeSourceFrames: FRAMES.thunderCharge,

  idleAnim: "ual-native-v1-idle-anim",
  walkAnim: "ual-native-v1-walk-loop-anim",
  walkStartAnim: "ual-native-v1-walk-start-anim",
  walkLoopAnim: "ual-native-v1-walk-loop-anim",
  walkRunAnim: "ual-native-v1-run-anim",
  walkStopAnim: "ual-native-v1-walk-stop-anim",
  airborneAnim: "ual-native-v1-airborne-anim",
  fallingAnim: "ual-native-v1-falling-anim",
  duckAnim: "ual-native-v1-crouch-anim",
  digDownAnim: DIG_DOWN_KEY,
  digSidewaysAnim: DIG_SIDE_KEYS[0],
  digUpAnim: DIG_UP_KEYS[0],
  digUpSidewaysAnim: DIG_UP_SIDE_KEYS[0],
  digUpLookAnim: "ual-native-v1-dig-up-look-anim",
  wallPushAnim: "ual-native-v1-wall-push-anim",
  leanAgainstWallAnim: "ual-native-v1-lean-wall-anim",
  combatIdleRecoverAnim: "ual-native-v1-combat-recover-anim",
  combatIdleToNormalIdleAnim: "ual-native-v1-combat-return-anim",
  climbAnim: "ual-native-v1-climb-anim",
  flyAnim: "ual-native-v1-fly-anim",
  flyClimbAnim: "ual-native-v1-fly-climb-anim",
  flightEnterAnim: "ual-native-v1-flight-enter-anim",
  flightTravelEnterAnim: "ual-native-v1-flight-travel-enter-anim",
  flightTravelLoopAnim: "ual-native-v1-flight-travel-loop-anim",
  flightHoverAnim: "ual-native-v1-flight-hover-anim",
  flightExitAnim: "ual-native-v1-flight-exit-anim",
  airborneRiseAnim: "ual-native-v1-airborne-anim",
  airborneFallAnim: "ual-native-v1-falling-anim",
  landingAnim: "ual-native-v1-landing-anim",
  quickslashAnim: PUNCH_JAB_KEY,
  teleportInAnim: "ual-native-v1-roll-anim",
  thunderStrikeChargeAnim: "ual-native-v1-spell-charge-anim",
  thunderStrikeStrikeAnim: "ual-native-v1-thunder-ground-strike-anim",
  attackDownAnim: "ual-native-v1-attack-down-ground-strike-anim",
  earthquakeReactAnim: "ual-native-v1-hit-react-anim",
  deathAnim: "ual-native-v1-death-anim",
  pickaxeMiningAnim: "ual-native-v1-pickaxe-mining-anim",
  uppercutAnim: "ual-native-v1-uppercut-anim",

  digSidewaysHitAnims: DIG_SIDE_KEYS,
  digUpHitAnims: DIG_UP_KEYS,
  digUpSidewaysHitAnims: DIG_UP_SIDE_KEYS,
  digDownHitAnims: Object.freeze([DIG_DOWN_KEY]),
  digDownSidewaysHitAnims: Object.freeze([DIG_DOWN_KEY]),
  digAnimationVariants: DIG_ANIMATION_VARIANTS,
  digAnims: DIG_ANIMS,
  punchActionAnims: PUNCH_ACTION_ANIMS,
  walkAnims: Object.freeze(["ual-native-v1-walk-start-anim", "ual-native-v1-walk-loop-anim", "ual-native-v1-run-anim", "ual-native-v1-walk-stop-anim"]),
  walkMovingAnims: Object.freeze(["ual-native-v1-walk-start-anim", "ual-native-v1-walk-loop-anim", "ual-native-v1-run-anim"]),
  footstepFrameIndices: Object.freeze({
    "ual-native-v1-walk-start-anim": Object.freeze([1]),
    "ual-native-v1-walk-loop-anim": Object.freeze([13, 27]),
    "ual-native-v1-run-anim": Object.freeze([13, 27]),
    "ual-native-v1-walk-stop-anim": Object.freeze([3]),
  }),
  locomotionTransitionAnims: Object.freeze([
    "ual-native-v1-walk-start-anim",
    "ual-native-v1-walk-stop-anim",
    "ual-native-v1-flight-enter-anim",
    "ual-native-v1-flight-travel-enter-anim",
    "ual-native-v1-flight-exit-anim",
    "ual-native-v1-landing-anim",
  ]),

  requiredSheets: ACTIVE_SHEETS,
  sheetFiles: Object.freeze([
    ["idleSheet", "ual-native-player-v1-idle-sheet.webp", "idleFrames"],
    ["idleTalkSheet", "ual-native-player-v1-idle-talk-sheet.webp", "idleTalkFrames"],
    ["walkSheet", "ual-native-player-v1-walk-sheet.webp", "walkFrames"],
    ["walkRunSheet", "ual-native-player-v1-run-sheet.webp", "walkRunFrames"],
    ["airborneSheet", "ual-native-player-v1-airborne-sheet.webp", "airborneFrames"],
    ["fallingSheet", "ual-native-player-v1-falling-sheet.webp", "fallingFrames"],
    ["duckSheet", "ual-native-player-v1-crouch-sheet.webp", "duckFrames"],
    ["flySheet", "ual-native-player-v1-fly-sheet.webp", "flyFrames"],
    ["climbSheet", "ual-native-player-v1-climb-sheet.webp", "climbFrames"],
    ["punchJabSheet", "ual-native-player-v1-punch-jab-sheet.webp", "punchJabFrames"],
    ["punchCrossSheet", "ual-native-player-v1-punch-cross-sheet.webp", "punchCrossFrames"],
    ["uppercutSheet", "ual-native-player-v1-punch-uppercut-sheet.webp", "uppercutFrames"],
    ["groundStrikeSheet", "ual-native-player-v1-ground-strike-sheet.webp", "groundStrikeSourceFrames"],
    ["landingSheet", "ual-native-player-v1-landing-sheet.webp", "landingSourceFrames"],
    ["wallPushSheet", "ual-native-player-v1-wall-push-sheet.webp", "wallPushFrames"],
    ["teleportInSheet", "ual-native-player-v1-teleport-sheet.webp", "teleportInFrames"],
    ["thunderStrikeChargeSheet", "ual-native-player-v1-thunder-charge-sheet.webp", "thunderChargeSourceFrames"],
    ["earthquakeReactSheet", "ual-native-player-v1-hit-react-sheet.webp", "earthquakeReactFrames"],
    ["deathSheet", "ual-native-player-v1-death-sheet.webp", "deathFrames"],
  ]),

  digSidewaysSourceFacesRight: true,
  digUpSourceFacesRight: true,
  digUpSidewaysSourceFacesRight: true,
  digDownSourceFacesRight: true,
  duckSourceFacesRight: true,
  quickslashSourceFacesRight: true,
  idleAnimationFps: 30,
  digUpLookAnimationFps: 30,
  walkAnimationFps: 30,
  walkRunAnimationFps: 30,
  airborneAnimationFps: 30,
  fallingAnimationFps: 30,
  digSidewaysAnimationFps: 30,
  digUpAnimationFps: 30,
  digDownAnimationFps: 30,
  duckAnimationFps: 30,
  climbAnimationFps: 30,
  flyClimbAnimationFps: 30,
  flyAnimationFps: 30,
  flightEnterAnimationFps: 30,
  flightTravelEnterAnimationFps: 30,
  flightTravelLoopAnimationFps: 30,
  flightHoverAnimationFps: 30,
  flightExitAnimationFps: 30,
  landingAnimationFps: 40,
  quickslashAnimationFps: 30,
  teleportInAnimationFps: 30,
  thunderStrikeChargeAnimationFps: 30,
  thunderStrikeStrikeAnimationFps: 42,
  wallPushAnimationFps: 30,
  leanAgainstWallAnimationFps: 30,
  combatIdleRecoverAnimationFps: 30,
  combatIdleToNormalIdleAnimationFps: 30,
  earthquakeReactAnimationFps: 30,
  deathAnimationFps: 30,
  walkAnimation: Object.freeze({
    baseSpeedPxPerSec: 200,
    baseFps: 30,
    minTimeScale: 0.65,
    maxTimeScale: 1.6,
    runSpeedRatioThreshold: 1.35,
  }),
});
