const candidate = (definition) => Object.freeze(definition);

export const UAL_WALK_REVIEW_CONFIG = Object.freeze({
  version: "ual-walk-review-v1-20260716",
  assetManifestPath: "./assets/manifest.json",
  selectionStorageKey: "dig-game-ual-walk-review-v1-choice",
  selectionQueryKey: "candidate",
  promotedCandidateId: "jog",
  cadenceModes: Object.freeze({
    gameMatched: "game-matched",
    native: "native",
  }),
  defaultCadenceMode: "game-matched",
  viewScales: Object.freeze({
    live: 1,
    inspection: 2,
  }),
  defaultViewScale: 1,
  speedControl: Object.freeze({
    minimumPxPerSec: 100,
    maximumPxPerSec: 320,
    stepPxPerSec: 10,
  }),
  inspection: Object.freeze({
    timelineDurationMs: 6000,
    stepDurationSeconds: 1 / 30,
    stageHeightPx: 246,
    groundYRatio: 0.72,
    zoomGroundOffsetPx: 30,
    maxDevicePixelRatio: 2,
  }),
  candidates: Object.freeze([
    candidate({
      id: "current",
      actionId: "walk-review-current",
      option: "A",
      label: "Previous walk",
      badge: "Rejected baseline",
      tone: "baseline",
      summary: "The rejected Walk_Loop baseline, retained so the promoted replacement has an honest reference.",
      evidence: "Largest upright pelvis sway in this five-clip set.",
    }),
    candidate({
      id: "formal",
      actionId: "walk-review-formal",
      option: "B",
      label: "Formal walk",
      badge: "Stability front-runner",
      tone: "recommended",
      summary: "Same authored duration as the baseline, with a calmer torso and cleaner planted read.",
      evidence: "About 42% less lateral and 33% less vertical pelvis motion than the current walk.",
    }),
    candidate({
      id: "jog",
      actionId: "walk-review-jog",
      option: "C",
      label: "Energetic jog",
      badge: "Selected + promoted",
      tone: "selected",
      summary: "The chosen native Jog loop, now promoted as the normal walk at real game speed.",
      evidence: "More bounce and urgency; strongest option if normal movement should feel athletic.",
    }),
    candidate({
      id: "sprint",
      actionId: "walk-review-sprint",
      option: "D",
      label: "Power gait",
      badge: "Forceful wildcard",
      tone: "power",
      summary: "The sprint loop slowed through the exact live walk stride-matching formula.",
      evidence: "Strong forward intent, but may read too urgent for ordinary traversal.",
    }),
    candidate({
      id: "carry",
      actionId: "walk-review-carry",
      option: "E",
      label: "Heavy carry walk",
      badge: "Weighty wildcard",
      tone: "heavy",
      summary: "A slower heavy-body cadence for a more deliberate mining-game silhouette.",
      evidence: "Good weight, though the arms can imply an invisible carried object.",
    }),
  ]),
});
