export const UI_FONTS = Object.freeze({
  display: "Bahnschrift SemiCondensed, Trebuchet MS, sans-serif",
  body: "Bahnschrift, Trebuchet MS, sans-serif",
  mono: "Cascadia Mono, Consolas, monospace",
});

export const UI_MODAL_LAYOUT = Object.freeze({
  margin: 24,
  compactMargin: 14,
  headerHeight: 82,
  footerHeight: 54,
  contentPadding: 22,
  cornerRadius: 9,
  cardRadius: 7,
  backdropAlpha: 0.82,
  enterDurationMs: 180,
  exitDurationMs: 130,
});

export const PAUSE_MENU_LAYOUT = Object.freeze({
  maxWidth: 940,
  maxHeight: 680,
  tabRowHeight: 32,
  tabRowOffsetY: 20,
  bodyTopOffset: 56,
});

export const SETTINGS_PANEL_LAYOUT = Object.freeze({
  compactWidth: 760,
  compactHeight: 420,
  tabCenterInsetY: 24,
  tabButtonHeight: 32,
  tabButtonWidth: 112,
  compactTabButtonWidth: 88,
  tabGap: 4,
  tabHorizontalInset: 18,
  contentTopInsetY: 56,
  contentBottomInsetY: 10,
  flashBottomInsetY: 18,
  audio: Object.freeze({
    firstRowOffsetY: 38,
    compactFirstRowOffsetY: 32,
    rowGap: 46,
    compactRowGap: 40,
    sliderMaxWidth: 520,
    compactSliderMaxWidth: 470,
    toggleGapY: 9,
    footerBottomInsetY: 30,
  }),
  controls: Object.freeze({
    instructionOffsetY: 3,
    firstRowOffsetY: 36,
    minRowGap: 32,
    rowGap: 37,
    compactRowGap: 33,
    threeColumnMinWidth: 780,
    columnGutter: 20,
  }),
  display: Object.freeze({
    compactReferenceHeight: 314,
    headerOffsetY: 0,
    fullscreenOffsetY: 34,
    fullscreenButtonHeight: 40,
    controlHintsOffsetY: 75,
    cameraShakeOffsetY: 113,
    intensityOffsetY: 156,
    flashOffsetY: 205,
    groupHeaderOffsetY: 228,
    groupStartOffsetY: 252,
    groupRowGap: 38,
    fiveColumnMinWidth: 500,
    threeColumnMinWidth: 360,
    groupHorizontalInset: 12,
    groupButtonMaxWidth: 58,
    groupButtonMinWidth: 38,
    groupButtonHeight: 26,
    groupButtonGap: 6,
    resetBottomInsetY: 19,
    resetButtonMaxWidth: 220,
    resetButtonHeight: 34,
    resetButtonGap: 16,
    shortFullscreenOffsetY: 28,
    shortFullscreenButtonHeight: 36,
    shortControlHintsOffsetY: 62,
    shortCameraShakeOffsetY: 92,
    shortIntensityOffsetY: 129,
    shortFlashOffsetY: 176,
    shortGroupHeaderOffsetY: 198,
    shortGroupStartOffsetY: 222,
    shortPrimaryButtonHeight: 30,
    shortGroupButtonHeight: 22,
    shortResetBottomInsetY: 17,
    shortResetButtonHeight: 30,
  }),
  gameplay: Object.freeze({
    compactReferenceHeight: 314,
    headerOffsetY: 0,
    floatingLabelOffsetY: 29,
    modeButtonOffsetY: 66,
    modeButtonHeight: 40,
    selectedSummaryOffsetY: 91,
    floatingHintOffsetY: 117,
    feedbackStartOffsetY: 160,
    feedbackRowGap: 54,
    feedbackHintOffsetY: 22,
    footerBottomInsetY: 10,
    modeButtonGap: 10,
    modeHorizontalInset: 18,
    modeButtonMaxWidth: 170,
    shortFloatingLabelOffsetY: 24,
    shortModeButtonOffsetY: 56,
    shortModeButtonHeight: 34,
    shortSelectedSummaryOffsetY: 78,
    shortFloatingHintOffsetY: 96,
    shortFeedbackStartOffsetY: 128,
    shortFeedbackRowGap: 40,
    shortFooterBottomInsetY: 8,
  }),
});

export const UI_DEPTHS = Object.freeze({
  hud: 1200,
  menu: 3000,
  modal: 3400,
  notification: 3800,
});

export const SHOP_MERCHANT_PROFILES = Object.freeze({
  gemPowerMerchant: Object.freeze({
    title: "GEM POWER WORKSHOP",
    role: "Aether Engineer",
    greeting: "Shape raw crystal power into flight, endurance, and control.",
  }),
  playerUpgrades: Object.freeze({
    title: "TRAINING HALL",
    role: "Combat Trainer",
    greeting: "Choose a discipline. I will show you exactly what improves next.",
  }),
  gearMerchant: Object.freeze({
    title: "GEAR FORGE",
    role: "Master Smith",
    greeting: "Tools for deeper stone. Check every material before you commit.",
  }),
  moneyMonster: Object.freeze({
    title: "MONEY MONSTER EXCHANGE",
    role: "Licensed Buyer",
    greeting: "Upgrade your market skills or convert gathered resources into money.",
  }),
  magmaMoneyMonster: Object.freeze({
    title: "MOLTEN ARC FORGE",
    role: "Arc Core Smith and Buyer",
    greeting: "Bring attuned Heavenblock parts and deep-world ore. I forge cores or buy surplus stock.",
  }),
  boboMerchant: Object.freeze({
    title: "BOBO'S COUNTER",
    role: "Collector of Useful Things",
    greeting: "Everything here has a purpose. Some purposes are stranger than others.",
  }),
  default: Object.freeze({
    title: "MERCHANT DESK",
    role: "Trader",
    greeting: "Select an item to inspect its effect, price, and requirements.",
  }),
});
