export const UI_NOTIFICATION_CAROUSEL_CONFIG = Object.freeze({
  enabled: false,
  visibleDurationMs: 7000,
  dedupeWindowMs: 15000,
  maxQueued: 6,
  routineGapMs: 1400,
  routineWindowMs: 7000,
  maxRoutineInWindow: 3,
  depth: 3600,
  defaultKind: "info",
  kinds: Object.freeze({
    info: Object.freeze({ title: "NOTICE", priority: 0 }),
    success: Object.freeze({ title: "UPDATE", priority: 1 }),
    warning: Object.freeze({ title: "WARNING", priority: 2 }),
    danger: Object.freeze({ title: "DANGER", priority: 3 }),
  }),
  input: Object.freeze({
    previous: "LEFT",
    next: "RIGHT",
    dismiss: "X",
  }),
  drag: Object.freeze({
    sideInsetPx: 12,
    topReservedPx: 84,
    bottomReservedPx: 132,
    collapsedAxisRatio: 0.5,
    idleCursor: "grab",
    activeCursor: "grabbing",
  }),
  transitions: Object.freeze({
    enterMs: 150,
    switchMs: 120,
    exitMs: 180,
    enterOffsetYPx: 18,
    exitOffsetYPx: 12,
    switchAlpha: 0.34,
  }),
  controls: Object.freeze({
    idleAlpha: 0.9,
    disabledAlpha: 0.38,
    hoverAlpha: 1,
    hoverScale: 1.08,
  }),
  fallback: Object.freeze({
    viewportInsetPx: 48,
    minWidthPx: 320,
    maxWidthPx: 520,
    minHeightPx: 76,
    iconInsetPx: 82,
    rightInsetPx: 92,
    verticalPaddingPx: 42,
    titleFontSizePx: 11,
    messageFontSizePx: 15,
    counterFontSizePx: 11,
    controlSizePx: 38,
    dismissSizePx: 30,
    titleTopInsetPx: 14,
    counterBottomInsetPx: 10,
    previousInsetXPx: 20,
    nextInsetXPx: 30,
    dismissInsetXPx: 17,
    dismissInsetYPx: 14,
    cycleOffsetYPx: 8,
    controlHitWidthPx: 52,
    controlHitHeightPx: 48,
    lineSpacingPx: 1,
    cornerRadiusPx: 6,
    borderWidthPx: 1,
    accentWidthPx: 5,
    backgroundAlpha: 0.94,
    borderAlpha: 0.95,
    accentAlpha: 0.95,
  }),
});
