const MOTION_ART_ROOT = "./";
const APPROVED_STATIC_ROOT =
  "sprites/backgrounds/world-visual-v2/depth/biome-variation-v2";
const REJECTED_VIDEO_ROOT =
  "sprites/backgrounds/world-visual-v2/depth/biome-motion-v2";

const card = ({
  id,
  regionId,
  biome,
  title,
  materialId,
  art,
  motionLabel,
  description,
}) => {
  const stem = art.replace(/^2026-07-26-/, "").replace(/\.png$/, "");
  return Object.freeze({
    id,
    regionId,
    biome,
    title,
    materialId,
    art: `${MOTION_ART_ROOT}${art}`,
    approvedStatic: `${APPROVED_STATIC_ROOT}/${stem}-motion-v1.webp`,
    rejectedVideo: `${REJECTED_VIDEO_ROOT}/${stem}-loop-v2.webm`,
    motionLabel,
    description,
  });
};

export const UNDERGROUND_BIOME_MOTION_REVIEW = Object.freeze({
  reviewOnly: true,
  productionChanged: false,
  status: "rejected",
  rejectionReason: "Choppy optical-flow deformation and low temporal quality",
  staticPromotion: Object.freeze({
    status: "approved",
    productionChanged: true,
  }),
  frame: Object.freeze({ width: 1536, height: 1024 }),
  cards: Object.freeze([
    card({
      id: "root-tide",
      regionId: "surface-entry",
      biome: "Weathered Roots",
      title: "Root-Tide Lantern Hollow",
      materialId: "townEarth",
      art: "2026-07-26-weathered-roots-root-tide-lantern-hollow.png",
      motionLabel: "Root flex / sap pulse / lantern sway / spores",
      description: "A slow organic breath that makes the entry layers feel alive without stealing focus.",
    }),
    card({
      id: "crystal-rain",
      regionId: "level1-blue",
      biome: "Blue Caverns",
      title: "Resonant Crystal Rain",
      materialId: "shallowBlue",
      art: "2026-07-26-blue-caverns-resonant-crystal-rain.png",
      motionLabel: "Crystal resonance / droplets / refracted sweep",
      description: "Cold pulses travel through three crystal depths while sparse rain gives scale.",
    }),
    card({
      id: "golden-dust",
      regionId: "level1-amber",
      biome: "Amber Depths",
      title: "Golden Dust Cathedral",
      materialId: "amberCrystal",
      art: "2026-07-26-amber-depths-golden-dust-cathedral.png",
      motionLabel: "Dust shafts / resin breath / chain sway",
      description: "Layered golden dustfall turns the cavern into a warm, ancient procession.",
    }),
    card({
      id: "mercury-fall",
      regionId: "level1-silver",
      biome: "Silver Core",
      title: "Mercury Shimmerfall",
      materialId: "silverCore",
      art: "2026-07-26-silver-core-mercury-shimmerfall.png",
      motionLabel: "Silver curtains / travelling glints / reflection wave",
      description: "Thin metallic falls and travelling highlights create elegance rather than noise.",
    }),
    card({
      id: "basalt-heart",
      regionId: "level1-magma",
      biome: "Core Magma",
      title: "Basalt Heartbeat",
      materialId: "magma",
      art: "2026-07-26-core-magma-basalt-heartbeat.png",
      motionLabel: "Lava pulse / embers / ash / heat roll",
      description: "A restrained volcanic heartbeat signals pressure through the distant rock.",
    }),
    card({
      id: "pressure-breath",
      regionId: "level2-slagworks",
      biome: "Slagworks",
      title: "Pressure-Breath Foundry",
      materialId: "magma",
      art: "2026-07-26-slagworks-pressure-breath-foundry.png",
      motionLabel: "Steam cycle / furnace breath / chain sway",
      description: "Alternating exhaust beats make the buried industry feel heavy and functional.",
    }),
    card({
      id: "violet-ash",
      regionId: "level2-obsidian",
      biome: "Obsidian Catacombs",
      title: "Violet Ash Procession",
      materialId: "obsidian",
      art: "2026-07-26-obsidian-catacombs-violet-ash-procession.png",
      motionLabel: "Ash curtains / crack procession / glass ripple",
      description: "Violet light moves like a ritual through falling ash and mirrored stone.",
    }),
    card({
      id: "condenser-surge",
      regionId: "level2-foundry",
      biome: "Pressure Foundry",
      title: "Condenser Surge",
      materialId: "foundry",
      art: "2026-07-26-pressure-foundry-condenser-surge.png",
      motionLabel: "Cyan pressure wave / pistons / staggered vents",
      description: "A readable energy route gives the foundry a mechanical cause-and-effect loop.",
    }),
    card({
      id: "prismatic-drift",
      regionId: "level2-blackglass",
      biome: "Blackglass Abyss",
      title: "Prismatic Star Drift",
      materialId: "blackglass",
      art: "2026-07-26-blackglass-abyss-prismatic-star-drift.png",
      motionLabel: "Orbiting motes / prism sweep / eclipse breath",
      description: "Sparse orbital motion preserves the abyss while adding uncanny cosmic scale.",
    }),
    card({
      id: "celestial-current",
      regionId: "level2-starfire",
      biome: "Starfire Rift",
      title: "Celestial Current",
      materialId: "starfire",
      art: "2026-07-26-starfire-rift-celestial-current.png",
      motionLabel: "Energy ribbons / starfall / ring rotation / nebula pulse",
      description: "Opposing cosmic currents deliver the strongest finale while keeping a dark play lane.",
    }),
  ]),
});
