import { UPGRADE_CATEGORIES } from "./upgradeCategories.js";
import { UPGRADE_RANK_COSTS } from "./upgradeRankBalance.js";
import {
  ARC_CORE_PURCHASE_COST,
  ARC_CORE_UPGRADE_ID,
  LEVEL_TWO_MERCHANT_ID,
  OMEGA_ARC_CORE_PURCHASE_COST,
  OMEGA_ARC_CORE_UPGRADE_ID,
} from "./arcCoreConfig.js";
import { EARTHQUAKE_SUPPRESSION_UPGRADE } from "./earthquakes.js";

export const FIRST_FIVE_STARTER_UPGRADE_ID = "agility";
export const LEGACY_FIRST_FIVE_STARTER_UPGRADE_ID = "minersGrip";
export const UPGRADE_PROGRESSION_VERSION = 3;

// ==================== UPGRADES DEFINITIONS ====================
export const UPGRADES = Object.freeze({
  // GEM POWER MERCHANT UPGRADES
  gemPowerUnlock: {
    id: "gemPowerUnlock",
    category: UPGRADE_CATEGORIES.GEM_POWER,
    name: "Gem of Great Power",
    description: "Take to the air with the Gem of Great Power. Hold your Flight key while you have GP.",
    goldCost: 100,
    baseEffect: 1,
    effectType: "gemPowerUnlocked",
    merchant: "gemPowerMerchant",
    oneTimePurchase: true,
    hiddenFromShop: true
  },
  gemPowerTank: {
    id: "gemPowerTank",
    category: UPGRADE_CATEGORIES.GEM_POWER,
    name: "Gem Power Tank",
    description: "Increase your maximum GP. In Hardcore, GP is your health.",
    baseCost: 45,
    rankCosts: UPGRADE_RANK_COSTS.gemPowerTank,
    baseEffect: 75,
    effectType: "gemPowerMax",
    merchant: "gemPowerMerchant",
    maxEffect: 600,
    linearEffect: true,
    maxLevel: 8,
    legacyMaxLevel: 15,
    legacyLevelsPerLevel: 4,
    legacyEffect: Object.freeze({ baseEffect: 40, maxEffect: 600 }),
  },
  gemPowerEfficiency: {
    id: "gemPowerEfficiency",
    category: UPGRADE_CATEGORIES.GEM_POWER,
    name: "Gem Power Efficiency",
    description: "Use less GP for Flight, abilities and your torch. In Hardcore, hits and panic cost less too.",
    baseCost: 75,
    rankCosts: UPGRADE_RANK_COSTS.gemPowerEfficiency,
    baseEffect: 0.05,
    effectType: "gemPowerCostReduction",
    maxEffect: 0.30,
    linearEffect: true,
    maxLevel: 6,
    merchant: "gemPowerMerchant",
    legacyMaxLevel: 10,
    legacyLevelsPerLevel: 4,
    legacyEffect: Object.freeze({ baseEffect: 0.03, maxEffect: 0.30 }),
  },
  gemPowerRegeneration: {
    id: "gemPowerRegeneration",
    category: UPGRADE_CATEGORIES.GEM_POWER,
    name: "Gem Power Regeneration",
    description: "Recover GP faster when you are not flying.",
    baseCost: 250,
    rankCosts: UPGRADE_RANK_COSTS.gemPowerRegeneration,
    baseEffect: 3.75,
    effectType: "gemPowerRegenIncrease",
    merchant: "gemPowerMerchant",
    maxEffect: 45,
    linearEffect: true,
    maxLevel: 12,
    legacyMaxLevel: 30,
    legacyLevelsPerLevel: 5,
    legacyEffect: Object.freeze({ baseEffect: 1.5, maxEffect: 45 }),
  },
  gemFlySpeed: {
    id: "gemFlySpeed",
    category: UPGRADE_CATEGORIES.GEM_POWER,
    name: "Gem Fly Speed",
    description: "Move faster while flying.",
    baseCost: 180,
    rankCosts: UPGRADE_RANK_COSTS.gemFlySpeed,
    baseEffect: 70,
    effectType: "levitationSpeed",
    merchant: "gemPowerMerchant",
    maxEffect: 400,
    linearEffect: true,
    maxLevel: 6,
    legacyMaxLevel: 10,
    legacyLevelsPerLevel: 4,
    legacyEffect: Object.freeze({ baseEffect: 40, maxEffect: 400 }),
  },

  // PLAYER UPGRADES MERCHANT UPGRADES
  [LEGACY_FIRST_FIVE_STARTER_UPGRADE_ID]: {
    id: LEGACY_FIRST_FIVE_STARTER_UPGRADE_ID,
    category: UPGRADE_CATEGORIES.PLAYER_STATS,
    name: "Miner's Grip",
    description: "Your Miner's Grip reward from the old tutorial is still active on this save.",
    goldCost: 4,
    baseEffect: 8,
    effectType: "digDamageAdditive",
    merchant: "playerUpgrades",
    oneTimePurchase: true,
    firstFiveOnly: true,
    hiddenFromShop: true,
  },
  agility: {
    id: "agility",
    category: UPGRADE_CATEGORIES.PLAYER_STATS,
    name: "Agility Training",
    description: "Move faster on the ground.",
    baseCost: 3,
    rankCosts: UPGRADE_RANK_COSTS.agility,
    baseEffect: 20,
    effectType: "walkSpeed",
    merchant: "playerUpgrades",
    maxLevel: 20,
    softcapLevel: 5,
    softcapValue: 100,
    maxValue: 200,
    legacyMaxLevel: 99,
    legacyLevelsPerLevel: 5,
    legacyEffect: Object.freeze({
      baseEffect: 20,
      softcapLevel: 5,
      softcapValue: 100,
      maxValue: 200,
    }),
  },
  strength: {
    id: "strength",
    category: UPGRADE_CATEGORIES.PLAYER_STATS,
    name: "Strength",
    description: "Break tough blocks in fewer hits.",
    baseCost: 18,
    rankCosts: UPGRADE_RANK_COSTS.strength,
    baseEffect: 4,
    effectType: "digDamageAdditive",
    merchant: "playerUpgrades",
    maxEffect: 40,
    linearEffect: true,
    maxLevel: 10,
    legacyMaxLevel: 20,
    legacyLevelsPerLevel: 4,
    legacyEffect: Object.freeze({ baseEffect: 2 }),
  },
  quickReflexes: {
    id: "quickReflexes",
    category: UPGRADE_CATEGORIES.PLAYER_STATS,
    name: "Quick Reflexes",
    description: "Dig faster.",
    baseCost: 24,
    rankCosts: UPGRADE_RANK_COSTS.quickReflexes,
    baseEffect: 0.03,
    effectType: "mineCooldownReduction",
    merchant: "playerUpgrades",
    maxEffect: 0.30,
    linearEffect: true,
    maxLevel: 10,
    legacyMaxLevel: 20,
    legacyLevelsPerLevel: 4,
    legacyEffect: Object.freeze({ baseEffect: 0.008, maxEffect: 0.30 }),
  },

  heavyPunch: {
    id: "heavyPunch",
    category: UPGRADE_CATEGORIES.PLAYER_STATS,
    name: "Heavy Punch",
    description: "Your digs also damage the block behind your target.",
    baseCost: 285,
    rankCosts: UPGRADE_RANK_COSTS.heavyPunch,
    baseEffect: 0.05,
    effectType: "heavyPunchDamage",
    merchant: "playerUpgrades",
    maxLevel: 20,
    softcapLevel: 5,
    softcapValue: 0.25,
    maxValue: 0.40,
    legacyMaxLevel: 99,
    legacyLevelsPerLevel: 5,
    legacyEffect: Object.freeze({
      baseEffect: 0.025,
      softcapLevel: 10,
      softcapValue: 0.25,
      maxValue: 0.40,
    }),
  },
  [EARTHQUAKE_SUPPRESSION_UPGRADE.id]: {
    ...EARTHQUAKE_SUPPRESSION_UPGRADE,
    category: UPGRADE_CATEGORIES.SPECIAL,
    baseCost: 0,
    baseEffect: 1,
    oneTimePurchase: true,
  },

  // GEAR MERCHANT - PICKAXES
  bronzePickaxe: {
    oneTimePurchase: true,
    id: "bronzePickaxe",
    category: UPGRADE_CATEGORIES.PICKAXES,
    name: "Bronze Pickaxe",
    description: "A reliable first pickaxe for Dirt, Stone and Copper.",
    goldCost: 30,
    resources: {
      copper: 5,
      stone: 10
    },
    baseDamage: 12,
    damageMultipliers: {
      dirt: 1.0,
      stone: 1.0,
      copper: 0.75,
      default: 0.5
    },
    metalTier: 1,
    merchant: "gearMerchant"
  },
  ironPickaxe: {
    oneTimePurchase: true,
    id: "ironPickaxe",
    category: UPGRADE_CATEGORIES.PICKAXES,
    name: "Iron Pickaxe",
    description: "Break Stone, Copper and Steel more easily.",
    goldCost: 150,
    resources: {
      copper: 20,
      stone: 50,
      steel: 5
    },
    baseDamage: 18,
    damageMultipliers: {
      steel: 1.0,
      copper: 1.0,
      stone: 1.0,
      default: 0.75
    },
    metalTier: 2,
    merchant: "gearMerchant"
  },
  steelPickaxe: {
    oneTimePurchase: true,
    id: "steelPickaxe",
    category: UPGRADE_CATEGORIES.PICKAXES,
    name: "Steel Pickaxe",
    description: "A balanced pickaxe with extra power against Bronze.",
    goldCost: 600,
    resources: {
      copper: 50,
      stone: 100,
      steel: 20,
      iron: 5
    },
    baseDamage: 15,
    damageMultipliers: {
      iron: 1.0,
      bronze: 1.5,
      default: 1.0
    },
    metalTier: 3,
    merchant: "gearMerchant"
  },
  mithrilPickaxe: {
    oneTimePurchase: true,
    id: "mithrilPickaxe",
    category: UPGRADE_CATEGORIES.PICKAXES,
    name: "Mithril Pickaxe",
    description: "A stronger all-round pickaxe with extra power against Steel.",
    goldCost: 3000,
    resources: {
      copper: 100,
      stone: 200,
      steel: 50,
      iron: 20,
      bronze: 10
    },
    baseDamage: 25,
    damageMultipliers: {
      silver: 1.0,
      default: 1.0,
      steel: 1.5
    },
    metalTier: 4,
    merchant: "gearMerchant"
  },
  adamantPickaxe: {
    oneTimePurchase: true,
    id: "adamantPickaxe",
    category: UPGRADE_CATEGORIES.PICKAXES,
    name: "Adamant Pickaxe",
    description: "Hit most materials much harder, but struggle with Gold.",
    goldCost: 15000,
    resources: {
      copper: 200,
      steel: 100,
      iron: 50,
      bronze: 25,
      silver: 5
    },
    baseDamage: 40,
    damageMultipliers: {
      gold: 0.5,
      default: 1.0,
      mithril: 1.5
    },
    metalTier: 5,
    merchant: "gearMerchant"
  },
  runePickaxe: {
    oneTimePurchase: true,
    id: "runePickaxe",
    category: UPGRADE_CATEGORIES.PICKAXES,
    name: "Rune Pickaxe",
    description: "Break every mineable material with heavy, reliable hits.",
    goldCost: 75000,
    resources: {
      iron: 100,
      steel: 200,
      bronze: 50,
      silver: 20,
      gold: 5
    },
    baseDamage: 60,
    damageMultipliers: {
      gold: 1.0,
      default: 1.0,
      adamant: 1.5
    },
    metalTier: 6,
    merchant: "gearMerchant"
  },
  dragonPickaxe: {
    oneTimePurchase: true,
    id: "dragonPickaxe",
    category: UPGRADE_CATEGORIES.PICKAXES,
    name: "Dragon Pickaxe",
    description: "Your strongest pickaxe, with extra power against Gold.",
    goldCost: 360000,
    resources: {
      iron: 200,
      steel: 400,
      silver: 50,
      gold: 20
    },
    baseDamage: 80,
    damageMultipliers: {
      gold: 1.5,
      default: 1.0
    },
    metalTier: 7,
    merchant: "gearMerchant"
  },

  // MONEY MONSTER UPGRADES
  sellAllButton: {
    id: "sellAllButton",
    category: UPGRADE_CATEGORIES.SPECIAL,
    name: "Sell All Button",
    description: "Empty your whole backpack into the exchange with one button. Perfect after a long mining run.",
    baseCost: 150,
    effectType: "sellAllUnlocked",
    merchant: "moneyMonster",
    oneTimePurchase: true
  },
  startResourcePrices: {
    id: "startResourcePrices",
    category: UPGRADE_CATEGORIES.SPECIAL,
    name: "Start Resource Prices",
    description: "Earn more from Dirt, Stone and Copper.",
    baseCost: 150,
    rankCosts: UPGRADE_RANK_COSTS.startResourcePrices,
    baseEffect: 0.20,
    effectType: "startResourceBonus",
    maxEffect: 1,
    linearEffect: true,
    maxLevel: 5,
    merchant: "moneyMonster",
    legacyMaxLevel: 10,
    legacyLevelsPerLevel: 4,
    legacyEffect: Object.freeze({ baseEffect: 0.10 }),
  },
  nextResourcePrices: {
    id: "nextResourcePrices",
    category: UPGRADE_CATEGORIES.SPECIAL,
    name: "Next Resource Prices",
    description: "Earn more from Iron, Bronze, Steel, Silver and Gold.",
    baseCost: 300,
    rankCosts: UPGRADE_RANK_COSTS.nextResourcePrices,
    baseEffect: 0.20,
    effectType: "nextResourceBonus",
    maxEffect: 1,
    linearEffect: true,
    maxLevel: 5,
    merchant: "moneyMonster",
    legacyMaxLevel: 10,
    legacyLevelsPerLevel: 4,
    legacyEffect: Object.freeze({ baseEffect: 0.10 }),
  },
  deepResourcePrices: {
    id: "deepResourcePrices",
    category: UPGRADE_CATEGORIES.SPECIAL,
    name: "Deep Market Contracts",
    description: "Make every Level Two haul worth more. The first two levels add 60% sale value each; the last adds 30%, for 150% total.",
    baseCost: 2500,
    baseEffect: 0.60,
    effectType: "deepResourceBonus",
    maxEffect: 1.5,
    maxLevel: 3,
    requires: "worldTwoTunnelAccess",
    merchant: "moneyMonster",
    depthEconomyOnly: true,
    legacyMaxLevel: 10,
    legacyLevelsPerLevel: 4,
    legacyEffect: Object.freeze({ baseEffect: 0.15 }),
  },
  marketInsight: {
    id: "marketInsight",
    category: UPGRADE_CATEGORIES.SPECIAL,
    name: "Market Insight",
    description: "Earn more from everything you sell.",
    baseCost: 600,
    rankCosts: UPGRADE_RANK_COSTS.marketInsight,
    baseEffect: 0.10,
    effectType: "marketBonus",
    maxEffect: 0.5,
    linearEffect: true,
    maxLevel: 5,
    merchant: "moneyMonster",
    legacyMaxLevel: 10,
    legacyLevelsPerLevel: 4,
    legacyEffect: Object.freeze({ baseEffect: 0.05 }),
  },
 

  // BOBO MERCHANT - ABILITY PURCHASES
  quickslashAbility: {
    id: "quickslashAbility",
    category: UPGRADE_CATEGORIES.SPECIAL,
    name: "Quick Slash",
    description: "Hold Q to mine left and right at the same time. Uses up to 12 GP per swing.",
    purchaseCopy: "Quick Slash unlocked! Hold Q to mine both sides at once.",
    baseCost: 0,
    goldCost: 100,
    baseEffect: 1,
    effectType: "unlockQuickslash",
    merchant: "boboMerchant",
    oneTimePurchase: true
  },
  thunderStrikeAbility: {
    id: "thunderStrikeAbility",
    category: UPGRADE_CATEGORIES.SPECIAL,
    name: "Thunder Strike",
    description: "Press V to unleash a 250-GP opening slam. Time each follow-up to chain up to nine more slams for free.",
    purchaseCopy: "Thunder Strike unlocked! Press V for the opening slam, then time up to nine free follow-ups.",
    baseCost: 0,
    goldCost: 250,
    baseEffect: 1,
    effectType: "unlockThunderStrike",
    merchant: "boboMerchant",
    oneTimePurchase: true
  },
  torchDrainEfficiency: {
    id: "torchDrainEfficiency",
    category: UPGRADE_CATEGORIES.SPECIAL,
    name: "Torch Drain Efficiency",
    description: "Keep your torch lit with less GP.",
    baseCost: 180,
    rankCosts: UPGRADE_RANK_COSTS.torchDrainEfficiency,
    baseEffect: 1,
    effectType: "torchDrainReduction",
    maxEffect: 5,
    linearEffect: true,
    maxLevel: 5,
    merchant: "boboMerchant",
    legacyMaxLevel: 10,
    legacyLevelsPerLevel: 5,
    legacyEffect: Object.freeze({ baseEffect: 0.75, maxEffect: 5 }),
  },
  torchRange: {
    id: "torchRange",
    category: UPGRADE_CATEGORIES.SPECIAL,
    name: "Torch Range",
    description: "Light up more of the mine.",
    baseCost: 140,
    rankCosts: UPGRADE_RANK_COSTS.torchRange,
    baseEffect: 0.3,
    effectType: "torchBonusRadius",
    maxEffect: 1.2,
    linearEffect: true,
    maxLevel: 4,
    merchant: "boboMerchant",
    legacyMaxLevel: 10,
    legacyLevelsPerLevel: 5,
    legacyEffect: Object.freeze({ baseEffect: 0.2, maxEffect: 1.2 }),
  },
  boboCaveEyes: {
    id: "boboCaveEyes",
    category: UPGRADE_CATEGORIES.SPECIAL,
    name: "Cave Eyes",
    description: "See farther without your torch. In Hardcore, panic drains less GP.",
    baseCost: 220,
    rankCosts: UPGRADE_RANK_COSTS.boboCaveEyes,
    baseEffect: 0.16,
    effectType: "noTorchMinVisibilityRadius",
    maxEffect: 0.8,
    linearEffect: true,
    maxLevel: 5,
    merchant: "boboMerchant",
    legacyMaxLevel: 10,
    legacyLevelsPerLevel: 4,
    legacyEffect: Object.freeze({ baseEffect: 0.08, maxEffect: 0.8 }),
    hardcorePanicReductionPerLevel: 0.06,
    hardcorePanicReductionMax: 0.30,
  },
  worldTwoTunnelAccess: {
    id: "worldTwoTunnelAccess",
    category: UPGRADE_CATEGORIES.SPECIAL,
    name: "World Two Tunnel Key",
    description: "Open the sealed tunnel at the far right of Town and gain access to Level Two.",
    baseCost: 0,
    goldCost: 25000,
    resources: {
      bronze: 50,
      silver: 25,
      gold: 10
    },
    requiresDepthGateAccepted: 1000,
    effectType: "worldTwoTunnelAccess",
    merchant: "boboMerchant",
    oneTimePurchase: true
  },
  [ARC_CORE_UPGRADE_ID]: {
    id: ARC_CORE_UPGRADE_ID,
    category: UPGRADE_CATEGORIES.SPECIAL,
    name: "Arc Core",
    description: "Climb into the Arc Core and mine a 2 x 2 area with each normal dig. Your movement, upgrades, and abilities still work.",
    baseCost: 0,
    goldCost: 0,
    resources: ARC_CORE_PURCHASE_COST,
    requires: "worldTwoTunnelAccess",
    effectType: "arcCoreVehicle",
    merchant: LEVEL_TWO_MERCHANT_ID,
    acquisitionMode: "craft",
    hiddenFromShop: true,
    oneTimePurchase: true
  },
  [OMEGA_ARC_CORE_UPGRADE_ID]: {
    id: OMEGA_ARC_CORE_UPGRADE_ID,
    category: UPGRADE_CATEGORIES.SPECIAL,
    name: "Omega Arc Core",
    description: "Transform the Arc Core into its final, four-times-larger form. Each normal dig mines an 8 x 8 area with all upgrades and abilities intact.",
    baseCost: 0,
    goldCost: 0,
    resources: OMEGA_ARC_CORE_PURCHASE_COST,
    requires: ARC_CORE_UPGRADE_ID,
    effectType: "omegaArcCoreVehicle",
    merchant: LEVEL_TWO_MERCHANT_ID,
    acquisitionMode: "craft",
    hiddenFromShop: true,
    oneTimePurchase: true
  },

  // BOBO MERCHANT SPECIAL
  mia: {
    id: "mia",
    category: UPGRADE_CATEGORIES.SPECIAL,
    name: "Mia",
    description: "Money cannot bring Mia home. Follow a dog\'s Signal underground, find the name on her leash, and rescue her. She will stay beside Bobo.",
    baseCost: 0,
    acquisitionMode: "signal",
    effectType: "special",
    merchant: "boboMerchant",
    oneTimePurchase: true
  },
  boboWisdom: {
    id: "boboWisdom",
    category: UPGRADE_CATEGORIES.SPECIAL,
    name: "Bobo's Wisdom",
    description: "Not sure how GP works? Ask Bobo to explain Flight, Quick Slash, and Thunder Strike for free.",
    baseCost: 0,
    effectType: "special",
    merchant: "boboMerchant",
  },
  
  // GEM POWER MERCHANT EASTER EGG
  upOrDown: {
    id: "upOrDown",
    category: UPGRADE_CATEGORIES.GEM_POWER,
    name: "Up or Down - It's a Matter of Perspective",
    description: "A secret waits for a miner carrying Angel's Heart and an impossible fortune. What happens if you choose it?",
    baseCost: 10000000000,
    effectType: "upOrDown",
    merchant: "gemPowerMerchant",
    oneTimePurchase: true,
    requiresAngelHeart: true
  }
});
