const stoneForegroundAtlas = Object.freeze({
  key: "dynamic-damage-review-blue-caverns",
  path: "sprites/backgrounds/world-visual-v2/depth/underground-foreground-textures-v6/blue-caverns-foreground-textures-atlas-v6.webp",
});

export const WORLD_VISUAL_DAMAGE_DYNAMIC_REVIEW = Object.freeze({
  reviewOnly: true,
  productionPainter: true,
  width: 1200,
  height: 790,
  tileSize: 94,
  firstColumnX: 192,
  firstRowY: 178,
  columnPitch: 100,
  rowPitch: 100,
  columns: 10,
  rows: 6,
  foregroundFrameWidth: 320,
  foregroundFrameHeight: 256,
  foregroundColumns: 5,
  foregroundFramePrefix: "dynamic-damage-review-foreground-",
  foregroundFrames: Object.freeze([0, 3, 6, 9, 12, 18]),
  foregroundDisplayWidth: 118,
  foregroundDisplayHeight: 94,
  foregroundAlpha: 0.66,
  foregroundAtlas: stoneForegroundAtlas,
  groundMaterial: "shallowBlue",
  tileType: "STONE",
  damageStateIndexes: Object.freeze([1, 3, 5, 7, 9, 11]),
  responseVariantCount: 10,
  targetStructuralVariant: 0,
  targetTransformIndex: 0,
  coordinateSearchRadius: 256,
  groundDepth: 1,
  foregroundDepth: 2.2,
  damageDepth: 2.45,
  backgroundColor: 0x07090d,
  title: "STONE DAMAGE V6 - 10 DYNAMIC RESPONSE LAYOUTS",
  subtitle: "DARK SLATE RESPONSE / 6 CUMULATIVE TIERS / FIXED 94 PX REGISTRATION",
  headerColor: "#f0dfbf",
  labelColor: "#dbe4ef",
  mutedColor: "#aeb9c8",
  familyColor: "#8290a5",
  fontFamily: "Segoe UI, sans-serif",
  titleFontSize: "22px",
  labelFontSize: "13px",
  stateFontSize: "11px",
});
