export const WORLD_VISUAL_DAMAGE_EXPANDED_REVIEW = Object.freeze({
  reviewOnly: true,
  productionPainter: true,
  width: 670,
  height: 1132,
  tileSize: 94,
  firstRowY: 88,
  panelX: 10,
  panelCount: 3,
  profilesPerPanel: 11,
  labelWidth: 154,
  states: Object.freeze([0, 2, 5, 8, 11]),
  backgroundColor: 0x07090d,
  groundDepth: 1,
  semanticDepth: 2.41,
  damageDepth: 2.45,
  title: "EXPANDED DAMAGE V4 - 33 EXACT TILE/RESOURCE PROFILES AT 94 PX",
  stateLabels: Object.freeze(["1 EARLY", "3 LIGHT", "6 MID", "9 HEAVY", "12 CRITICAL"]),
  headerColor: "#f0dfbf",
  labelColor: "#dbe4ef",
  mutedColor: "#aeb9c8",
  familyColor: "#8290a5",
  fontFamily: "Segoe UI, sans-serif",
  titleFontSize: "22px",
  labelFontSize: "13px",
  familyFontSize: "11px",
  stateFontSize: "12px",
  profiles: Object.freeze([
    Object.freeze({ tileType: "DIRT", family: "dirt", material: "townEarth" }),
    Object.freeze({ tileType: "STONE", family: "hard", material: "shallowBlue", resource: "stone" }),
    Object.freeze({ tileType: "COPPER", family: "copper", material: "shallowBlue", resource: "copper" }),
    Object.freeze({ tileType: "BEDROCK", family: "hard", material: "blackglass" }),
    Object.freeze({ tileType: "DARK_DIRT_NORMAL", family: "damp", material: "townEarth" }),
    Object.freeze({ tileType: "DARK_DIRT_STRONG", family: "damp", material: "townEarth" }),
    Object.freeze({ tileType: "BRONZE", family: "bronze", material: "shallowBlue", resource: "bronze" }),
    Object.freeze({ tileType: "STEEL", family: "steel", material: "shallowBlue", resource: "steel" }),
    Object.freeze({ tileType: "IRON", family: "iron", material: "shallowBlue", resource: "iron" }),
    Object.freeze({ tileType: "SILVER", family: "silver", material: "shallowBlue", resource: "silver" }),
    Object.freeze({ tileType: "GOLD", family: "gold", material: "magma", resource: "gold" }),
    Object.freeze({ tileType: "TELEPORT_TILE", family: "special", material: "blackglass" }),
    Object.freeze({ tileType: "GAMBLE_TILE", family: "special", material: "magma" }),
    Object.freeze({ tileType: "FLOOR_TOWN_1", family: "hard", material: "townEarth" }),
    Object.freeze({ tileType: "FLOOR_TOWN_2", family: "hard", material: "townEarth" }),
    Object.freeze({ tileType: "SKY_TILE", family: "crystal", material: "blackglass", semantic: "star" }),
    Object.freeze({ tileType: "GEM_POWER_BLOCK", family: "special", material: "shallowBlue", semantic: "special" }),
    Object.freeze({ tileType: "SPEED_BLOCK", family: "special", material: "blackglass", semantic: "special" }),
    Object.freeze({ tileType: "XP_BLOCK", family: "special", material: "blackglass", semantic: "special" }),
    Object.freeze({ tileType: "CRIT_BLOCK", family: "special", material: "magma", semantic: "special" }),
    Object.freeze({ tileType: "BERSERK_BLOCK", family: "special", material: "magma", semantic: "special" }),
    Object.freeze({ tileType: "COMBO_BLOCK", family: "special", material: "blackglass", semantic: "special" }),
    Object.freeze({ tileType: "LEGEND_BLOCK", family: "special", material: "shallowBlue", semantic: "special" }),
    Object.freeze({ tileType: "CAVE_WALL", family: "hard", material: "blackglass" }),
    Object.freeze({ tileType: "GEODE_INTERIOR", family: "geode", material: "shallowBlue" }),
    Object.freeze({ tileType: "GEODE_WALL", family: "geode", material: "blackglass" }),
    Object.freeze({ tileType: "CHEST", family: "relic", material: "magma" }),
    Object.freeze({ tileType: "GLOW_CRYSTAL", family: "crystal", material: "blackglass", semantic: "star" }),
    Object.freeze({ tileType: "LAVA_DIRT", family: "lava", material: "magma" }),
    Object.freeze({ tileType: "OBSIDIAN", family: "obsidian", material: "blackglass", resource: "obsidian" }),
    Object.freeze({ tileType: "EMBER_ORE", family: "ember", material: "magma", resource: "emberOre" }),
    Object.freeze({ tileType: "MAGMA_CRYSTAL", family: "magma", material: "blackglass", resource: "magmaCrystal" }),
    Object.freeze({ tileType: "ANCIENT_RELIC_CACHE", family: "relic", material: "blackglass", semantic: "special" }),
  ]),
});
