const openRange = (leftTile, rightTile) => Object.freeze({ leftTile, rightTile });

const placement = (
  id,
  assetId,
  chapterId,
  clusterId,
  tileX,
  lane,
  sizeVariant = "standard",
  flipX = false,
) => Object.freeze({
  id: `surface-v3-authored-${id}`,
  scope: "surface",
  assetId,
  worldRegion: chapterId,
  chapterId,
  clusterId,
  level: "level2",
  tileX,
  lane,
  sizeVariant,
  flipX,
});

const chapter = (
  id,
  label,
  leftTile,
  rightTile,
  primaryAnchorTileX,
  openRanges,
  placements,
) => Object.freeze({
  id,
  label,
  leftTile,
  rightTile,
  primaryAnchorTileX,
  openRanges: Object.freeze(openRanges),
  placements: Object.freeze(placements),
});

const SURFACE_CHAPTERS = Object.freeze([
  chapter(
    "arrival-forge",
    "Arrival Forge",
    151.5,
    162.5,
    155.2,
    [openRange(161.1, 162.5)],
    [
      placement("forge-coal-sacks", "arrival-forge-coal-sacks", "arrival-forge", "fuel-store", 153.1, "front"),
      placement("forge-scorched-brace", "arrival-forge-scorched-brace", "arrival-forge", "shelter-workface", 154.05, "rear", "feature"),
      placement("forge-cooling-trough", "arrival-forge-cooling-trough", "arrival-forge", "quench-station", 156.85, "front", "large"),
      placement("forge-ember-brazier", "arrival-forge-ember-brazier", "arrival-forge", "quench-station", 157.65, "mid"),
    ],
  ),
  chapter(
    "caravan-rest",
    "Caravan Rest",
    162.5,
    180,
    166.8,
    [openRange(169.2, 170.2), openRange(176.8, 178.1)],
    [
      placement("caravan-saddle-rack", "caravan-rest-pack-saddle-rack", "caravan-rest", "camp-hearth", 163.9, "rear", "feature"),
      placement("caravan-cooking-tripod", "caravan-rest-cooking-tripod", "caravan-rest", "camp-hearth", 167.75, "mid", "feature"),
      placement("caravan-water-keg", "caravan-rest-water-keg", "caravan-rest", "camp-hearth", 168.55, "front", "small"),
      placement("caravan-luggage", "caravan-rest-luggage-stack", "caravan-rest", "wagon-stop", 170.9, "mid"),
      placement("caravan-tether", "caravan-rest-tether-post", "caravan-rest", "wagon-stop", 173.7, "rear"),
      placement("caravan-feed-trough", "caravan-rest-feed-trough", "caravan-rest", "wagon-stop", 174.9, "front"),
    ],
  ),
  chapter(
    "starwell-herb",
    "Starwell Herb Court",
    180,
    200,
    193.8,
    [openRange(185.5, 190.5)],
    [
      placement("starwell-planter", "starwell-herb-herb-planter", "starwell-herb", "west-garden", 180.55, "front", "large"),
      placement("starwell-drying-rack", "starwell-herb-drying-rack", "starwell-herb", "west-garden", 182.35, "mid", "feature"),
      placement("starwell-rain-barrel", "starwell-herb-rain-barrel", "starwell-herb", "west-garden", 184.4, "rear", "small"),
      placement("starwell-mortar", "starwell-herb-mortar-station", "starwell-herb", "east-apothecary", 192.55, "mid"),
      placement("starwell-herb-basket", "starwell-herb-herb-basket", "starwell-herb", "east-apothecary", 194.75, "front", "small"),
      placement("starwell-moonflower", "starwell-herb-moonflower-trellis", "starwell-herb", "east-apothecary", 196.45, "rear", "feature"),
    ],
  ),
  chapter(
    "timberwright",
    "Timberwright Yard",
    200,
    219,
    207.6,
    [openRange(200, 201.35), openRange(215.8, 216.9)],
    [
      placement("timber-log-pile", "timberwright-log-pile", "timberwright", "timber-stock", 202.7, "rear", "feature"),
      placement("timber-sawhorses", "timberwright-sawhorses", "timberwright", "saw-bay", 203.75, "front"),
      placement("timber-workbench", "timberwright-saw-workbench", "timberwright", "saw-bay", 204.85, "mid"),
      placement("timber-rope-spool", "timberwright-rope-spool", "timberwright", "cart-load", 210.15, "front"),
      placement("timber-planks", "timberwright-plank-stack", "timberwright", "cart-load", 212.85, "rear", "large"),
      placement("timber-grindstone", "timberwright-grindstone", "timberwright", "cart-load", 214.15, "mid"),
    ],
  ),
  chapter(
    "observatory",
    "Heavenblocks Observatory",
    219,
    243,
    229.8,
    [openRange(219.5, 222.4), openRange(232.2, 234.0), openRange(240, 242.5)],
    [
      placement("observatory-weather-vane", "observatory-weather-vane", "observatory", "instrument-court", 225.9, "rear", "large"),
      placement("observatory-chart-table", "observatory-observatory-chart-table", "observatory", "instrument-court", 227.45, "mid", "feature"),
      placement("observatory-weights", "observatory-calibration-weights", "observatory", "instrument-court", 230.65, "front", "small"),
      placement("observatory-star-dial", "observatory-star-dial", "observatory", "instrument-court", 231.35, "front", "large"),
    ],
  ),
  chapter(
    "frontier-survey",
    "Frontier Survey Garden",
    243,
    260,
    248.4,
    [openRange(250.8, 252.2), openRange(254, 256.2)],
    [
      placement("frontier-seed-bed", "frontier-survey-seed-bed", "frontier-survey", "trial-garden", 244.2, "front", "large"),
      placement("frontier-sapling", "frontier-survey-young-sapling", "frontier-survey", "trial-garden", 245.3, "rear", "feature"),
      placement("frontier-irrigation", "frontier-survey-irrigation-jugs", "frontier-survey", "trial-garden", 246.15, "front", "small"),
      placement("frontier-tripod", "frontier-survey-survey-tripod", "frontier-survey", "survey-bench", 247.15, "mid", "feature"),
      placement("frontier-samples", "frontier-survey-soil-sample-crates", "frontier-survey", "survey-bench", 249.35, "mid"),
      placement("frontier-lantern", "frontier-survey-frontier-lantern", "frontier-survey", "east-handoff", 257.35, "rear"),
    ],
  ),
  chapter(
    "far-east",
    "Far-East Expedition Overlook",
    260,
    280,
    272,
    [openRange(265.5, 266.6), openRange(274, 275.3)],
    [
      placement("far-east-map-cases", "far-east-expedition-map-cases", "far-east", "wagon-load", 261.5, "front"),
      placement("far-east-climbing-crate", "far-east-climbing-crate", "far-east", "wagon-load", 263.1, "mid"),
      placement("far-east-telescope", "far-east-far-telescope", "far-east", "survey-overlook", 268.7, "rear", "feature"),
      placement("far-east-signal-lantern", "far-east-signal-lantern", "far-east", "expedition-shelter", 270.65, "mid"),
      placement("far-east-chests", "far-east-expedition-chests", "far-east", "expedition-shelter", 273.25, "front", "large"),
      placement("far-east-cairn", "far-east-expedition-cairn", "far-east", "expedition-shelter", 277.25, "rear"),
    ],
  ),
]);

export const WORLD_VISUAL_SURFACE_PROP_COMPOSITION_V3 = Object.freeze({
  version: "surface-props-v3-camera-composition-v3",
  designRule: "one-hero-functional-clusters-and-deliberate-negative-space",
  chapters: SURFACE_CHAPTERS,
  placements: Object.freeze(SURFACE_CHAPTERS.flatMap(item => item.placements)),
});
