export const WORLD_VISUAL_GAMEPLAY_EFFECTS = Object.freeze({
  blendMode: "ADD",
  performance: Object.freeze({
    maxSkyTiles: 72,
    maxChestTiles: 18,
    maxRootTiles: 180,
    maxCrystalTiles: 48,
    maxCrystalZones: 8,
  }),
  sky: Object.freeze({
    defaultColor: 0x87ceeb,
    highlightColor: 0xffffff,
    haloRadiusScale: 0.43,
    coreRadiusScale: 0.20,
    haloAlphaBase: 0.055,
    haloAlphaPulse: 0.045,
    coreAlphaBase: 0.08,
    rarityAlphaStep: 0.018,
    outlineAlpha: 0.30,
    outlineWidthScale: 0.018,
    diamondRadiusScale: 0.31,
    sparkleRadiusScale: 0.022,
    sparkleMinRarity: 1,
    coronaMinRarity: 2,
    coronaRadiusScale: 0.48,
    coronaAlpha: 0.22,
    pulsePeriodMsByRarity: Object.freeze([1000, 560, 320, 240, 180, 120]),
    resourceFlashPeriodMs: 2500,
    resourceFlashStart: 0.85,
    resourceFlashAlpha: 0.24,
  }),
  chest: Object.freeze({
    haloColor: 0xffd700,
    coreColor: 0xffaa00,
    highlightColor: 0xffffff,
    pulsePeriodMs: 1600,
    haloRadiusScale: 0.50,
    coreRadiusScale: 0.24,
    haloAlphaBase: 0.08,
    haloAlphaPulse: 0.10,
    coreAlphaBase: 0.18,
    coreAlphaPulse: 0.18,
    sparkleOrbitScale: 0.31,
    sparkleRadiusScale: 0.024,
  }),
  roots: Object.freeze({
    shallowColor: 0x6f4b2e,
    deepColor: 0x493044,
    shadowColor: 0x140f12,
    shallowAlpha: 0.54,
    deepAlpha: 0.60,
    shadowAlpha: 0.52,
    shadowWidthScale: 0.055,
    coreWidthScale: 0.026,
    insetScale: 0.10,
    bendScale: 0.18,
    branchLengthScale: 0.24,
  }),
  crystals: Object.freeze({
    defaultColor: 0x66e8ff,
    highlightColor: 0xffffff,
    pulsePeriodMs: 2850,
    glintPeriodMs: 1050,
    haloAlpha: 0.075,
    coreAlpha: 0.055,
    shardAlpha: 0.72,
    outlineAlpha: 0.38,
    haloPaddingTilesX: 1.8,
    haloPaddingTilesY: 1.25,
    shardHeightMinScale: 0.26,
    shardHeightRangeScale: 0.30,
    shardHalfWidthMinScale: 0.055,
    shardHalfWidthRangeScale: 0.06,
    shardBaseYScale: 0.82,
    sparkleRadiusScale: 0.018,
  }),
  compatibility: Object.freeze({
    legacyDirectOnly: Object.freeze([
      "createTilesheetTexture",
      "createLayer",
      "paintInitialWorld",
      "getRootOverlayRenderIndex",
      "applyRootOverlayUpdate",
      "map",
      "layer",
      "rootOverlayLayer",
    ]),
    specialBlockGlow: Object.freeze({
      owner: "WorldVisualFeedbackLayer",
      disposition: "visual-only-no-op",
      reason: "Special blocks already retain persistent semantic atlas markers; a second pulsing square overlay would duplicate and degrade them.",
    }),
  }),
});
