const foregroundAtlas = (biomeId) => Object.freeze({
  key: `aligned-damage-review-${biomeId}`,
  path: `sprites/backgrounds/world-visual-v2/depth/underground-foreground-textures-v6/${biomeId}-foreground-textures-atlas-v6.webp`,
});

export const WORLD_VISUAL_DAMAGE_ALIGNED_REVIEW = Object.freeze({
  reviewOnly: true,
  productionPainter: true,
  width: 1340,
  height: 1080,
  tileSize: 94,
  panelX: 180,
  firstRowY: 196,
  rowSpacing: 246,
  patchWidth: 282,
  patchHeight: 226,
  patchGap: 8,
  foregroundFrameWidth: 320,
  foregroundFrameHeight: 256,
  foregroundColumns: 5,
  foregroundFramePrefix: "aligned-damage-review-foreground-",
  patchCount: 4,
  groundDepth: 1,
  foregroundDepth: 2.2,
  damageDepth: 2.45,
  foregroundAlpha: 0.58,
  backgroundColor: 0x07090d,
  title: "ALIGNED DAMAGE V5 - 12 REAL STATES ON PRODUCTION FOREGROUND TEXTURES",
  subtitle: "FIXED 94 PX CENTER / FIXED SCALE / 7 PX TILE-SAFE INSET / 6 MATERIAL TIERS",
  headerColor: "#f0dfbf",
  labelColor: "#dbe4ef",
  mutedColor: "#aeb9c8",
  familyColor: "#8290a5",
  fontFamily: "Segoe UI, sans-serif",
  titleFontSize: "22px",
  labelFontSize: "14px",
  stateFontSize: "11px",
  stateLabels: Object.freeze([
    "01", "02", "03", "04", "05", "06",
    "07", "08", "09", "10", "11", "12",
  ]),
  profiles: Object.freeze([
    Object.freeze({
      label: "WEATHERED ROOTS / DIRT",
      biomeId: "weathered-roots",
      material: "townEarth",
      tileType: "DIRT",
      foregroundFrameIndex: 0,
      atlas: foregroundAtlas("weathered-roots"),
    }),
    Object.freeze({
      label: "BLUE CAVERNS / STONE",
      biomeId: "blue-caverns",
      material: "shallowBlue",
      tileType: "STONE",
      foregroundFrameIndex: 6,
      atlas: foregroundAtlas("blue-caverns"),
    }),
    Object.freeze({
      label: "CORE MAGMA / LAVA DIRT",
      biomeId: "core-magma",
      material: "magma",
      tileType: "LAVA_DIRT",
      foregroundFrameIndex: 12,
      atlas: foregroundAtlas("core-magma"),
    }),
    Object.freeze({
      label: "BLACKGLASS / OBSIDIAN",
      biomeId: "blackglass-abyss",
      material: "blackglass",
      tileType: "OBSIDIAN",
      foregroundFrameIndex: 18,
      atlas: foregroundAtlas("blackglass-abyss"),
    }),
  ]),
});
