// Review-only SSOT for the complete above-ground runtime map mockup.
// The mockup composes checked-in production libraries without changing gameplay.

const freezeList = values => Object.freeze(values.map(value => Object.freeze(value)));

export const WORLD_VISUAL_ABOVE_GROUND_COMPLETE_MAP_REVIEW = Object.freeze({
  reviewOnly: true,
  productionChanged: false,
  version: "above-ground-complete-map-runtime-review-v1-2026-08-30",
  assetPolicy: "checked-in-runtime-assets-only",
  backgroundPolicy: "production-scenic-surface-plus-sky-cohesion-and-v11-terrain",
  townVideoPolicy: "preserve-production-town-air-byte-for-byte",
  surfaceFarDepth: -5.5,
  skyFeatureDepth: -5.4,
  skyFeatureScale: 1.7,
  skyFeatureFeatherXPx: 120,
  skyFeatureFeatherYPx: 300,
  skyCohesionOwnsIslandBackdrop: true,
  skySurfaceBandAlpha: 0.86,
  title: "ABOVE-GROUND COMPLETE MAP",
  subtitle: "Production backgrounds + complete modular prop library",
  width: 1536,
  height: 864,
  backgroundColor: "#070a10",
  tileSize: 94,
  surfaceTileY: 65,
  map: Object.freeze({
    // Includes the exact v11 authored streaming buffer around the 0..280 play span.
    leftTile: -40,
    rightTileExclusive: 308,
    topTile: -40,
    bottomTileExclusive: 75,
  }),
  camera: Object.freeze({
    defaultZoom: 0.92,
    minimumZoom: 0.58,
    maximumZoom: 1.22,
    wheelZoomStep: 0.00055,
    panSpeedTilesPerSecond: 13,
    dragEnabled: true,
  }),
  defaultChapterId: "observatory",
  defaultBandId: "surface",
  chapters: freezeList([
    { id: "town", label: "Town Square", tileX: 9.5 },
    { id: "titan-walk", label: "Titan Walk", tileX: 38 },
    { id: "titan-walk-east", label: "Titan Walk East", tileX: 55 },
    { id: "titan-commons", label: "Titan Commons", tileX: 69 },
    { id: "skywell", label: "Skywell Verge", tileX: 91 },
    { id: "gates", label: "Surface Gates", tileX: 109 },
    { id: "threshold", label: "Bridge Threshold", tileX: 129 },
    { id: "arrival-forge", label: "Arrival Forge", tileX: 152.5 },
    { id: "caravan-rest", label: "Caravan Rest", tileX: 170 },
    { id: "starwell-herb", label: "Starwell Herb Court", tileX: 190 },
    { id: "timberwright", label: "Timberwright Yard", tileX: 209 },
    { id: "observatory", label: "Observatory Ridge", tileX: 230 },
    { id: "frontier-survey", label: "Frontier Survey", tileX: 249 },
    { id: "three-kings", label: "Three Kings Overlook", tileX: 264 },
    { id: "far-east", label: "Far East", tileX: 270 },
  ]),
  bands: freezeList([
    { id: "high-sky", label: "High sky islands", centerTileY: 15.5 },
    { id: "heavenblocks", label: "Heavenblocks", centerTileY: 31.5 },
    { id: "lower-sky", label: "Lower cloud reef", centerTileY: 48.5 },
    { id: "surface", label: "Surface", centerTileY: 62 },
  ]),
  background: Object.freeze({
    enabled: true,
    queryParam: "completeMapBackgrounds",
    queryEnableValues: Object.freeze(["1", "on", "true"]),
    queryDisableValues: Object.freeze(["0", "off", "false"]),
    depthEnabled: false,
    depthQueryParam: "completeMapDepth",
    universeSkyEnabled: true,
    universeSkyQueryParam: "completeMapReplaceSky",
    replacedSkyObjectPrefix: "sky-r",
    runtimeCropFill: Object.freeze({
      enabled: true,
      color: 0x070a10,
      alpha: 1,
      depth: -20,
    }),
    fallbackRenderDepth: -6,
    fallbackObjectDepthStep: 0.00001,
    preloadMarginTilesX: 5,
    preloadMarginTilesY: 5,
    unloadMarginTilesX: 16,
    unloadMarginTilesY: 12,
    streamScheduler: Object.freeze({
      enabled: true,
      queryParam: "completeMapStreamScheduler",
      spatialBandHeightTiles: 32,
      cameraStrideTilesX: 1,
      cameraStrideTilesY: 1,
      maxTexturesPerBatch: 4,
      updateMetricName: "above-ground-complete-map-background-stream",
    }),
    linearFiltering: true,
    surfaceArtAlignment: Object.freeze({
      enabled: true,
      groundPrefixes: Object.freeze(["level1-ground-", "level2-ground-"]),
      groundDownshiftTiles: 0,
      townPrefix: "town-ground-",
      townAlphaMultiplier: 0.86,
      townTint: 0xe4eaee,
    }),
    depthContinuation: Object.freeze({ enabled: false }),
  }),
});
