import { SPECIAL_BLOCKS_CONFIG } from "./specialBlocks.js";
import { TILE_TYPES } from "./tileTypes.js";

export const WORLD_VISUAL_GAMEPLAY_EFFECTS = Object.freeze({
  blendMode: "ADD",
  performance: Object.freeze({
    maxSkyTiles: 72,
    maxChestTiles: 18,
    maxCrystalTiles: 48,
    maxCrystalZones: 8,
    maxSpecialTiles: 12,
  }),
  sky: Object.freeze({
    defaultColor: 0x87ceeb,
    highlightColor: 0xffffff,
    haloRadiusScale: 0.43,
    coreRadiusScale: 0.20,
    haloAlphaBase: 0.055,
    haloAlphaPulse: 0.045,
    coreAlphaBase: 0.08,
    rarityAlphaStep: 0.018,
    outlineAlpha: 0.30,
    outlineWidthScale: 0.018,
    diamondRadiusScale: 0.31,
    sparkleRadiusScale: 0.022,
    sparkleMinRarity: 1,
    coronaMinRarity: 2,
    coronaRadiusScale: 0.48,
    coronaAlpha: 0.22,
    pulsePeriodMsByRarity: Object.freeze([1000, 560, 320, 240, 180, 120]),
    resourceFlashPeriodMs: 2500,
    resourceFlashStart: 0.85,
    resourceFlashAlpha: 0.24,
  }),
  chest: Object.freeze({
    haloColor: 0xffd700,
    coreColor: 0xffaa00,
    highlightColor: 0xffffff,
    pulsePeriodMs: 1600,
    haloRadiusScale: 0.50,
    coreRadiusScale: 0.24,
    haloAlphaBase: 0.08,
    haloAlphaPulse: 0.10,
    coreAlphaBase: 0.18,
    coreAlphaPulse: 0.18,
    sparkleOrbitScale: 0.31,
    sparkleRadiusScale: 0.024,
  }),
  crystals: Object.freeze({
    defaultColor: 0x66e8ff,
    highlightColor: 0xffffff,
    pulsePeriodMs: 2850,
    glintPeriodMs: 1050,
    haloAlpha: 0.075,
    coreAlpha: 0.055,
    shardAlpha: 0.72,
    outlineAlpha: 0.38,
    haloPaddingTilesX: 1.8,
    haloPaddingTilesY: 1.25,
    shardHeightMinScale: 0.26,
    shardHeightRangeScale: 0.30,
    shardHalfWidthMinScale: 0.055,
    shardHalfWidthRangeScale: 0.06,
    shardBaseYScale: 0.82,
    sparkleRadiusScale: 0.018,
  }),
  specialBlocks: Object.freeze({
    profilesByTileType: Object.freeze({
      [TILE_TYPES.ABILITY_BLOCK]: Object.freeze({
        color: SPECIAL_BLOCKS_CONFIG.glowEffects.abilityBlock.color,
        pulsePeriodMs: SPECIAL_BLOCKS_CONFIG.glowEffects.abilityBlock.pulseSpeed,
        haloRadiusScale: 0.62,
        haloAlphaBase: 0.09,
        haloAlphaPulse: 0.11,
        coreRadiusScale: 0.35,
        coreAlphaBase: 0.06,
        ringRadiusScale: 0.53,
        ringAlphaBase: 0.34,
        ringWidthScale: 0.022,
        sparkleCount: 5,
        sparkleOrbitScale: 0.54,
        sparkleRadiusScale: 0.026,
      }),
      [TILE_TYPES.LEGEND_BLOCK]: Object.freeze({
        color: SPECIAL_BLOCKS_CONFIG.glowEffects.legendBlock.color,
        pulsePeriodMs: SPECIAL_BLOCKS_CONFIG.glowEffects.legendBlock.pulseSpeed,
        haloRadiusScale: 0.86,
        haloAlphaBase: 0.16,
        haloAlphaPulse: 0.20,
        coreRadiusScale: 0.42,
        coreAlphaBase: 0.14,
        ringRadiusScale: 0.66,
        ringAlphaBase: 0.62,
        ringWidthScale: 0.035,
        sparkleCount: 8,
        sparkleOrbitScale: 0.73,
        sparkleRadiusScale: 0.038,
      }),
    }),
    highlightColor: 0xffffff,
  }),
  compatibility: Object.freeze({
    legacyDirectOnly: Object.freeze([
      "createTilesheetTexture",
      "createLayer",
      "paintInitialWorld",
      "map",
      "layer",
    ]),
    specialBlockGlow: Object.freeze({
      owner: "WorldVisualGameplayEffectLayer",
      disposition: "rare-block-corona-only",
      reason: "Ability and Crown blocks retain their semantic art while a capped circular corona makes their decision/reward value readable through darkness.",
    }),
  }),
});
