export const WORLD_VISUAL_DAMAGE_IMAGE_REVIEW = Object.freeze({
  reviewOnly: true,
  productionChanged: false,
  atlas: Object.freeze({
    key: "ground-damage-imggen-review-v1",
    path: "sprites/environment/ground-damage-imggen-v1/2026-07-29-ground-damage-fissure-atlas-rgba-v1.png",
    framePrefix: "damage-state-",
    stateCount: 12,
    columns: 4,
    frameSize: 341,
    columnStride: 384,
    rowOffsets: Object.freeze([0, 341, 683]),
  }),
  harness: Object.freeze({
    width: 1216,
    height: 672,
    tileSize: 64,
    firstTileX: 4,
    firstTileY: 1,
    labelX: 20,
    labelWidth: 220,
    headerY: 13,
    groundDepth: 1,
    damageDepth: 2.45,
    backgroundColor: 0x07090d,
    headerColor: "#f0dfbf",
    labelColor: "#b7c5d6",
    mutedColor: "#6d7785",
    fontFamily: "Consolas, monospace",
    headerFontSize: "16px",
    labelFontSize: "14px",
  }),
});
