export const WORLD_VISUAL_DAMAGE_RUNTIME_REVIEW = Object.freeze({
  reviewOnly: true,
  productionChanged: true,
  width: 1410,
  height: 940,
  tileSize: 94,
  firstTileX: 2,
  firstTileY: 1,
  stateColumns: 13,
  backgroundColor: 0x07090d,
  groundDepth: 1,
  damageDepth: 2.45,
  headerY: 18,
  labelX: 14,
  headerColor: "#f0dfbf",
  labelColor: "#dbe4ef",
  mutedColor: "#aeb9c8",
  fontFamily: "Segoe UI, sans-serif",
  titleFontSize: "24px",
  labelFontSize: "15px",
  stateFontSize: "13px",
});
