export const WORLD_MAP_CONFIG = Object.freeze({
  schemaVersion: 1,
  worldRevision: "foundation-v1",
  storageKey: "jkd-world-map-discovery",
  assetPath: "sprites/UI/map/world-map-frame-foundation-v1.png",
  symbolAtlas: Object.freeze({
    path: "sprites/UI/map/world-map-symbol-atlas-v2.png",
    frameWidth: 128,
    frameHeight: 128,
    endFrame: 6,
    frames: Object.freeze({
      player: 0,
      landmark: 1,
      titan: 2,
      portal: 3,
      biome: 4,
      resonance: 5,
      star: 6,
    }),
  }),
  depth: 2800,

  discovery: Object.freeze({
    cellSizeTiles: 4,
    revealRadiusTiles: 7,
    persistDelayMs: 1200,
    maxPersistedCells: 250000,
  }),

  view: Object.freeze({
    defaultZoom: 16,
    minZoom: 1,
    maxZoom: 768,
    zoomStep: 16,
    keyboardPanScreenPx: 72,
    maxDugTilesPerDraw: 12000,
    fogHatchGapPx: 18,
    fogHatchLengthPx: 28,
  }),

  terrainDetail: Object.freeze({
    enabled: true,
    minimumPixelsPerTile: 48,
    maximumVisibleTiles: 1200,
    sampleMarginTiles: 1,
    textureAlpha: 1,
    biomeBackdropAlpha: 0.16,
    maximumWorldRenderDepth: 999,
    worldScrollFactorEpsilon: 0.001,
    discoveryEraseOverlapWorldPx: 1,
  }),

  drawing: Object.freeze({
    fogHatchWidthPx: 1,
    fogHatchAlpha: 0.38,
    minimumCellPx: 1.5,
    cellPaddingPx: 0.75,
    cellAlpha: 0.92,
    cellOutlineMinimumPx: 5,
    cellOutlineWidthPx: 1,
    cellOutlineAlpha: 0.24,
    biomeBoundaryMinimumPx: 2.5,
    biomeBoundaryWidthPx: 1.25,
    biomeBoundaryAlpha: 0.68,
    tunnelAlpha: 0.9,
    worldOutlineWidthPx: 2,
    worldOutlineAlpha: 0.55,
    depthGridIntervalTiles: 100,
    depthGridMajorEvery: 5,
    depthGridWidthPx: 1,
    depthGridMinorAlpha: 0.14,
    depthGridMajorAlpha: 0.34,
    surfaceLineWidthPx: 2,
    surfaceLineAlpha: 0.64,
  }),

  starTerritories: Object.freeze({
    enabled: true, spatialBucketTiles: 64,
    undergroundOffsetTiles: 1,
    intactCellAlpha: 0.12, signalCellAlpha: 0.075, consumedCellAlpha: 0.48,
    consumedCellColor: 0x12060d, boundaryMinimumPixelsPerTile: 0.72,
    boundaryWidthPx: 1.35, boundaryAlpha: 0.58,
    consumedBoundaryColor: 0xd25b76, consumedBoundaryAlpha: 0.84,
    routeWidthPx: 2.4, routeAlpha: 0.9,
    routeLostColor: 0xe36b83, routeSignalColor: 0xe7c66a,
    routeTargetRadiusPx: 13, routeTargetInnerRadiusPx: 5,
    routeTargetAlpha: 0.9, signalMarkerAlpha: 0.58,
    consumedMarkerAlpha: 0.8, consumedMarkerTint: 0x7d4653,
    directionLabels: Object.freeze(["E", "SE", "S", "SW", "W", "NW", "N", "NE"]),
  }),

  annotations: Object.freeze({
    iconSizesPx: Object.freeze({
      player: 38,
      landmark: 30,
      titan: 34,
      portal: 32,
      biome: 28,
      resonance: 32,
      star: 34,
      default: 28,
      activity: 24,
      status: 30,
    }),
    markerLabelMinimumPixelsPerTile: 1.25,
    markerLabelOffsetYPx: 20,
    markerLabelFontSizePx: 10,
    markerLabelLineSpacingPx: 2,
    markerLabelStrokeThicknessPx: 3,
    markerLabelMaximumWidthPx: 164,
    markerLabelMinimumSeparationPx: 72,
    markerLabelViewportInsetPx: 12,
    markerLabelFlipInsetPx: 80,
    playerLabelCollisionPx: 60,
    maxMarkerLabels: 12,
    biomeLabelMinimumPixelsPerTile: 1.3,
    biomeLabelMinimumSeparationPx: 104,
    biomeMarkerLabelSeparationPx: 110,
    biomeLabelViewportInsetPx: 24,
    biomeLabelOffsetYPx: -42,
    biomeLabelFontSizePx: 11,
    biomeLabelStrokeThicknessPx: 4,
    biomeLabelAlpha: 0.88,
    biomeIdentityLift: 0.55,
    maxBiomeLabels: 8,
    textResolution: 2,
    markerPriorities: Object.freeze({
      town: 100,
      trackedTitan: 95,
      portal: 90,
      discoveredTitan: 80,
      resonance: 75,
      currentStar: 98,
      consumedStar: 88,
      star: 84,
      starSignal: 72,
      skyIsland: 70,
      landmark: 60,
      mineEntrance: 65,
      player: 110,
    }),
  }),

  input: Object.freeze({
    idleCursor: "grab",
    activeCursor: "grabbing",
    buttonCursor: "pointer",
    disabledCursor: "default",
    closeHitSizePx: 52,
    zoomHitSizePx: 48,
    centerHitWidthPx: 164,
    centerHitHeightPx: 38,
    activityHitWidthRatio: 0.18,
    activityHitHeightPx: 38,
    hoverScale: 1.08,
    pressScale: 0.94,
    pressDurationMs: 90,
    disabledAlpha: 0.42,
    keys: Object.freeze({
      center: "KeyF",
      zoomIn: Object.freeze(["Equal", "NumpadAdd"]),
      zoomOut: Object.freeze(["Minus", "NumpadSubtract"]),
      panLeft: "ArrowLeft",
      panRight: "ArrowRight",
      panUp: "ArrowUp",
      panDown: "ArrowDown",
    }),
  }),

  layout: Object.freeze({
    viewport: Object.freeze({ x: 0.117, y: 0.082, width: 0.643, height: 0.832 }),
    depthPanel: Object.freeze({ x: 0.012, y: 0.08, width: 0.095, height: 0.82 }),
    rightPanel: Object.freeze({ x: 0.772, y: 0.09, width: 0.205, height: 0.79 }),
    zoomControl: Object.freeze({ x: 0.719, y: 0.36, width: 0.035, height: 0.33 }),
    discoveryX: 0.874,
    discoveryY: 0.145,
    activityTitleX: 0.874,
    activityTitleY: 0.285,
    activityStartY: 0.325,
    activityIconX: 0.798,
    activityTextX: 0.816,
    activityCenterX: 0.874,
    activityRowGapRatio: 0.038,
    activityRowMinimumGapPx: 25,
    activityMaxRows: 7,
    statusX: 0.874,
    statusY: 0.655,
    statusBiomeIconX: 0.798,
    statusBiomeIconY: 0.706,
    statusStarIconX: 0.798,
    statusStarIconY: 0.758,
    footerY: 0.955,
    footerDragX: 0.29,
    footerWheelX: 0.45,
    footerCenterX: 0.61,
    footerCloseX: 0.73,
    titleY: 0.047,
    closeX: 0.968,
    closeY: 0.055,
  }),

  colors: Object.freeze({
    shade: 0x000000,
    fog: 0x071018,
    fogHatch: 0x23333f,
    grid: 0x2f4350,
    discoveredOutline: 0xc79a48,
    biomeBoundary: 0xe8d29a,
    surface: 0xf0c765,
    tunnel: 0xe2bd68,
    player: 0x65d8f2,
    marker: 0xf0c765,
    title: "#f0c765",
    body: "#d5dde2",
    hint: "#8297a5",
    active: "#65d8f2",
    inactive: "#6e7a82",
    annotationStroke: "#071018",
    biomeLabel: "#f3dfaa",
    depthBands: Object.freeze([
      0x4b4434,
      0x304451,
      0x263c46,
      0x3f3b35,
      0x4c3028,
    ]),
  }),

  coreActivities: Object.freeze({
    landmarks: Object.freeze({
      label: "LANDMARKS",
      color: 0xf0c765,
      iconFrame: "landmark",
      enabledByDefault: true,
    }),
    portals: Object.freeze({
      label: "PORTALS",
      color: 0x9f7cff,
      iconFrame: "portal",
      enabledByDefault: true,
    }),
    titans: Object.freeze({
      label: "TITANS",
      color: 0xff8a4e,
      iconFrame: "titan",
      enabledByDefault: true,
    }),
    stars: Object.freeze({
      label: "STAR TERRITORIES",
      color: 0xe7c66a,
      iconFrame: "star",
      enabledByDefault: true,
    }),
  }),

  landmarks: Object.freeze({
    townSquare: Object.freeze({
      id: "town-square",
      label: "Town Square",
      detail: "Milestone Pillar & merchants",
      tileX: 11,
    }),
    mineEntranceLabel: "Mine Entrance",
    mineEntranceDetail: "Surface cave access",
    skyIslandDetail: "Star Pillar",
    portalDepthSuffix: "descent",
    skyIslandLabels: Object.freeze({
      1: "Level 1 Sky Island",
      2: "Level 2 Sky Island",
    }),
    surfaceHeroLabels: Object.freeze({
      arrivalForgeShelter: "Arrival Forge",
      caravanWaystation: "Caravan Waystation",
      starwellPortalFrame: "Starwell Portal",
      timberwrightYard: "Timberwright Yard",
      observatoryTelescope: "Observatory",
      frontierSurveyPavilion: "Frontier Survey Pavilion",
      threeKingsOverlook: "Three Kings Overlook",
    }),
  }),

  copy: Object.freeze({
    title: "WORLD MAP",
    discovered: "DISCOVERED",
    activityLayers: "ACTIVITY LAYERS",
    worldStatus: "WORLD STATUS",
    visualRegion: "VISUAL REGION",
    noActivityLayers: "NO ACTIVITY MODULES",
    noActivityHint: "Systems can register live markers",
    dragPan: "DRAG TO PAN",
    wheelZoom: "WHEEL TO ZOOM",
    center: "CENTER PLAYER [F]",
    close: "CLOSE MAP [M]",
    layerOn: "ON",
    layerOff: "OFF",
    mapSize: "SURVEY",
    currentDepth: "DEPTH",
    zoom: "ZOOM",
    knownSignals: "KNOWN SIGNALS",
    visibleBiomes: "VISIBLE BIOMES",
    player: "YOU",
    titanResonance: "Titan Resonance",
    tracked: "TRACKED",
    starTerritory: "STAR TERRITORY",
    starAnchorBiome: "ANCHOR BIOME",
    unidentifiedStar: "UNIDENTIFIED STAR SIGNAL",
    starRefugeDetail: "LIGHT • GP • PANIC REFUGE",
    starSignalDetail: "FOLLOW THE LINK TO FIND ITS REFUGE",
    starScarSuffix: "SCAR",
    starRefugeLost: "REFUGE LOST • TERRITORY SEVERED",
    starRoute: "REFUGE ROUTE",
    starLostRoute: "SCAR ROUTE",
    knownStarTerritories: "KNOWN STAR LINKS",
    lostStarTerritories: "LOST",
    noUndergroundStar: "SURFACE • NO STAR TERRITORY",
  }),
});
