export const WORLD_VISUAL_DAMAGE_LAYERED_REVIEW = Object.freeze({
  reviewOnly: true,
  productionPainter: true,
  width: 1410,
  height: 940,
  tileSize: 94,
  firstRowY: 88,
  panelX: Object.freeze([14, 710]),
  labelWidth: 170,
  states: Object.freeze([0, 2, 5, 8, 11]),
  backgroundColor: 0x07090d,
  groundDepth: 1,
  semanticDepth: 2.41,
  damageDepth: 2.45,
  title: "LAYERED DAMAGE V3 - LIVE RESOURCE/TILE MIXER AT 94 PX",
  stateLabels: Object.freeze(["1 EARLY", "3 LIGHT", "6 MID", "9 HEAVY", "12 CRITICAL"]),
  headerColor: "#f0dfbf",
  labelColor: "#dbe4ef",
  mutedColor: "#aeb9c8",
  fontFamily: "Segoe UI, sans-serif",
  titleFontSize: "22px",
  labelFontSize: "14px",
  stateFontSize: "12px",
  families: Object.freeze([
    Object.freeze({ family: "dirt", tileType: "DIRT", material: "townEarth" }),
    Object.freeze({ family: "damp", tileType: "DARK_DIRT_STRONG", material: "townEarth" }),
    Object.freeze({ family: "hard", tileType: "STONE", material: "shallowBlue", resource: "stone" }),
    Object.freeze({ family: "copper", tileType: "COPPER", material: "shallowBlue", resource: "copper" }),
    Object.freeze({ family: "bronze", tileType: "BRONZE", material: "amberCrystal", resource: "bronze" }),
    Object.freeze({ family: "iron", tileType: "IRON", material: "amberCrystal", resource: "iron" }),
    Object.freeze({ family: "steel", tileType: "STEEL", material: "silverCore", resource: "steel" }),
    Object.freeze({ family: "silver", tileType: "SILVER", material: "silverCore", resource: "silver" }),
    Object.freeze({ family: "gold", tileType: "GOLD", material: "magma", resource: "gold" }),
    Object.freeze({ family: "lava", tileType: "LAVA_DIRT", material: "magma" }),
    Object.freeze({ family: "obsidian", tileType: "OBSIDIAN", material: "obsidian", resource: "obsidian" }),
    Object.freeze({ family: "ember", tileType: "EMBER_ORE", material: "foundry", resource: "emberOre" }),
    Object.freeze({ family: "magma", tileType: "MAGMA_CRYSTAL", material: "starfire", resource: "magmaCrystal" }),
    Object.freeze({ family: "crystal", tileType: "SKY_TILE", material: "blackglass", semantic: "star" }),
    Object.freeze({ family: "geode", tileType: "GEODE_INTERIOR", material: "amberCrystal" }),
    Object.freeze({ family: "relic", tileType: "ANCIENT_RELIC_CACHE", material: "blackglass", semantic: "special" }),
    Object.freeze({ family: "special", tileType: "SPEED_BLOCK", material: "starfire", semantic: "special" }),
  ]),
});
