const frozenList = values => Object.freeze([...values]);

const flightProfile = (overrides = {}) => {
  const {
    trailRatios = [0.48, 0.72],
    echoRatios = [0.58],
    ...values
  } = overrides;
  return Object.freeze({
    flutterAmplitudePx: 2.4,
    flutterCycles: 1.45,
    bobAmplitudePx: 0.8,
    bobCycles: 2.1,
    bankRadians: 0.075,
    bankCycles: 1.5,
    headingInfluence: 0.055,
    breathScale: 0.026,
    breathCycles: 2,
    squashScale: 0.015,
    echoAlpha: 0.12,
    echoSizeRatio: 0.82,
    echoDurationMs: 140,
    echoDriftPx: 4,
    arrivalEchoCount: 1,
    arrivalEchoStaggerMs: 24,
    arrivalEchoScale: 1.55,
    ...values,
    trailRatios: frozenList(trailRatios),
    echoRatios: frozenList(echoRatios),
  });
};

export const XP_GATHERING_CONFIG = Object.freeze({
  assetPaths: Object.freeze({
    routine: "sprites/UI/xp-gathering-v2/xp-mote-core-v2.png",
    routineFacet: "sprites/UI/xp-gathering-v2/xp-mote-facet-v2.png",
    routineCompass: "sprites/UI/xp-gathering-v2/xp-mote-compass-v2.png",
    routineKite: "sprites/UI/xp-gathering-v2/xp-mote-kite-v2.png",
    clusterTwin: "sprites/UI/xp-gathering-v2/xp-cluster-twin-v2.png",
    clusterOrbit: "sprites/UI/xp-gathering-v2/xp-cluster-orbit-v2.png",
    clusterTriad: "sprites/UI/xp-gathering-v2/xp-cluster-triad-v2.png",
    special: "sprites/UI/xp-gathering-v2/xp-sigil-core-v2.png",
    specialRune: "sprites/UI/xp-gathering-v2/xp-sigil-rune-v2.png",
    specialLegend: "sprites/UI/xp-gathering-v2/xp-sigil-legend-v2.png",
    levelUp: "sprites/UI/xp-gathering-v2/xp-crest-core-v2.png",
    levelCrown: "sprites/UI/xp-gathering-v2/xp-crest-crown-v2.png",
  }),
  iconLibraries: Object.freeze({
    routine: frozenList(["routine", "routineFacet", "routineCompass", "routineKite"]),
    cluster: frozenList(["clusterTwin", "clusterOrbit", "clusterTriad"]),
    surge: frozenList(["clusterOrbit", "routineKite", "specialRune"]),
    star: frozenList(["routineCompass", "clusterOrbit", "clusterTriad"]),
    special: frozenList(["special", "specialRune", "clusterOrbit"]),
    legend: frozenList(["specialLegend", "specialRune", "special"]),
    levelUp: frozenList(["levelUp", "levelCrown", "specialLegend"]),
  }),
  iconScaleById: Object.freeze({
    routineKite: 0.94,
    clusterOrbit: 0.94,
    special: 0.88,
    specialRune: 0.94,
    specialLegend: 0.93,
    levelCrown: 0.94,
  }),
  iconSelection: Object.freeze({
    recentWindow: 2,
    hashOffset: 2166136261,
    hashPrime: 16777619,
  }),
  sourceColors: Object.freeze({
    fallback: 0x8be889,
    xpBlock: 0xffe36b,
    legendBlock: 0xf2c96b,
  }),
  segments: Object.freeze({
    count: 10,
    gapPx: 2,
    radiusPx: 2,
    minimumFillPx: 2,
    emptyColor: 0x080e13,
    emptyAlpha: 0.96,
    legacyEmptyAlpha: 0.9,
    borderColor: 0x4c3b24,
    borderAlpha: 1,
    borderWidthPx: 1,
    fillColor: 0xf2d52b,
    fillHighlightColor: 0xfff1a0,
    fillAlpha: 0.92,
    legacyLowColor: 0x66ff66,
    legacyMidColor: 0xffff66,
    legacyHighColor: 0xffaa00,
    legacyBorderColor: 0x5566aa,
    legacyBorderWidthPx: 2,
    legacyLowThreshold: 0.3,
    legacyHighThreshold: 0.7,
  }),
  motion: Object.freeze({
    changeEpsilon: 0.004,
    fillDurationMs: 420,
    levelCompleteDurationMs: 220,
    levelResetHoldMs: 70,
    levelRemainderDurationMs: 260,
    fillEase: "Cubic.easeOut",
    pulseDurationMs: 260,
    pulseAlpha: 0.92,
    pulseEase: "Sine.easeOut",
  }),
  gainText: Object.freeze({
    fontFamily: "Consolas, monospace",
    fontStyle: "bold",
    color: "#fff0a6",
    stroke: "#090d12",
    strokeThickness: 4,
    fontSizePx: 15,
    startOffsetYPx: 8,
    risePx: 20,
    durationMs: 620,
    ease: "Cubic.easeOut",
    startScale: 0.82,
    maxAlpha: 0.82,
    fadeInRatio: 0.2,
    fadeOutStartRatio: 0.58,
  }),
  pickup: Object.freeze({
    coalesceWindowMs: 48,
    surgeThresholdXp: 300,
    offscreenMarginPx: 24,
    maxActiveSprites: 10,
    staggerMs: 46,
    popDurationMs: 112,
    popRisePx: 11,
    popStartScale: 0.7,
    popEndScale: 1.05,
    popRotationRadians: 0.035,
    popEase: "Sine.easeOut",
    travelFadeStartRatio: 0.86,
    travelScaleLossRatio: 0.34,
    flightSampleDelta: 0.012,
    flightPhaseStepRadians: 1.07,
    flightBobPhaseRatio: 0.47,
    flightTangentMinimum: 0.001,
    displaySizePx: 52,
    arrivalSizePx: 28,
    arrivalEchoAlphaMultiplier: 0.34,
    arrivalEchoDurationMs: 190,
    arrivalEchoEase: "Sine.easeOut",
    arrivalMicroScale: 0.72,
    arrivalMicroAlphaMultiplier: 0.55,
    spawnOffsetsPx: frozenList([-14, -5, 6, 15]),
    reducedMotion: Object.freeze({
      mediaQuery: "(prefers-reduced-motion: reduce)",
      durationMultiplier: 0.78,
      rotationMultiplier: 0.16,
    }),
    particles: Object.freeze({
      sourceDisplaySizePx: 16,
      sourceAlpha: 0.36,
      sourceAngleStartRadians: -2.45,
      sourceAngleStepRadians: 0.64,
      sourceDistanceBasePx: 8,
      sourceDistanceStepPx: 2,
      sourceDurationBaseMs: 190,
      sourceDurationStepMs: 22,
      sourceEase: "Sine.easeOut",
      trailDisplaySizePx: 13,
      trailAlpha: 0.24,
      trailFallPx: 4,
      trailDurationMs: 150,
      trailEase: "Sine.easeOut",
    }),
    variations: Object.freeze({
      routine: Object.freeze({
        iconLibrary: "routine", flight: "routine", pickupCount: 1, particleCount: 1,
        sizeMultiplier: 0.66, alpha: 0.69, pulseStrength: 0.28,
        showLabel: false, soundSpecial: false,
      }),
      cluster: Object.freeze({
        iconLibrary: "cluster", flight: "cluster", pickupCount: 2, particleCount: 2,
        sizeMultiplier: 0.75, alpha: 0.75, pulseStrength: 0.4,
        showLabel: false, soundSpecial: false,
      }),
      surge: Object.freeze({
        iconLibrary: "surge", flight: "surge", pickupCount: 3, particleCount: 3,
        sizeMultiplier: 0.82, alpha: 0.82, pulseStrength: 0.52,
        showLabel: true, soundSpecial: true,
      }),
      star: Object.freeze({
        iconLibrary: "star", flight: "star", pickupCount: 2, particleCount: 3,
        sizeMultiplier: 0.82, alpha: 0.84, pulseStrength: 0.5,
        showLabel: false, soundSpecial: false,
      }),
      special: Object.freeze({
        iconLibrary: "special", flight: "special", pickupCount: 2, particleCount: 3,
        sizeMultiplier: 0.88, alpha: 0.87, pulseStrength: 0.58,
        showLabel: true, soundSpecial: true,
      }),
      legend: Object.freeze({
        iconLibrary: "legend", flight: "legend", pickupCount: 3, particleCount: 4,
        sizeMultiplier: 0.9, alpha: 0.9, pulseStrength: 0.66,
        showLabel: true, soundSpecial: true,
      }),
      levelUp: Object.freeze({
        iconLibrary: "levelUp", flight: "levelUp", pickupCount: 3, particleCount: 4,
        sizeMultiplier: 0.94, alpha: 0.92, pulseStrength: 0.74,
        showLabel: true, soundSpecial: true,
      }),
    }),
    flightProfiles: Object.freeze({
      routine: flightProfile(),
      cluster: flightProfile({
        flutterAmplitudePx: 3.8, flutterCycles: 1.9, bobAmplitudePx: 1.2,
        bankRadians: 0.1, breathScale: 0.035,
        trailRatios: [0.38, 0.59, 0.76], echoRatios: [0.6],
      }),
      surge: flightProfile({
        flutterAmplitudePx: 5.2, flutterCycles: 2.45, bobAmplitudePx: 1.8,
        bankRadians: 0.14, bankCycles: 2.1, breathScale: 0.045,
        trailRatios: [0.28, 0.45, 0.62, 0.77], echoRatios: [0.44, 0.69],
        echoAlpha: 0.15, arrivalEchoCount: 2,
      }),
      star: flightProfile({
        flutterAmplitudePx: 5.8, flutterCycles: 2.7, bobAmplitudePx: 2,
        bobCycles: 2.8, bankRadians: 0.16, bankCycles: 2.4,
        headingInfluence: 0.075, breathScale: 0.05,
        trailRatios: [0.24, 0.41, 0.58, 0.74], echoRatios: [0.38, 0.64],
        echoAlpha: 0.16, arrivalEchoCount: 2,
      }),
      special: flightProfile({
        flutterAmplitudePx: 4.6, flutterCycles: 2.1, bobAmplitudePx: 1.4,
        bankRadians: 0.12, breathScale: 0.04,
        trailRatios: [0.3, 0.49, 0.67, 0.8], echoRatios: [0.46, 0.7],
        echoAlpha: 0.15, arrivalEchoCount: 2,
      }),
      legend: flightProfile({
        flutterAmplitudePx: 6.2, flutterCycles: 2.8, bobAmplitudePx: 2.2,
        bobCycles: 3, bankRadians: 0.18, bankCycles: 2.5,
        headingInfluence: 0.08, breathScale: 0.055, squashScale: 0.024,
        trailRatios: [0.2, 0.35, 0.5, 0.64, 0.77], echoRatios: [0.32, 0.54, 0.72],
        echoAlpha: 0.17, arrivalEchoCount: 2, arrivalEchoScale: 1.72,
      }),
      levelUp: flightProfile({
        flutterAmplitudePx: 6.8, flutterCycles: 3.1, bobAmplitudePx: 2.4,
        bobCycles: 3.2, bankRadians: 0.2, bankCycles: 2.7,
        headingInfluence: 0.085, breathScale: 0.06, squashScale: 0.028,
        trailRatios: [0.18, 0.32, 0.46, 0.6, 0.73, 0.82],
        echoRatios: [0.28, 0.48, 0.67], echoAlpha: 0.18,
        arrivalEchoCount: 3, arrivalEchoStaggerMs: 32, arrivalEchoScale: 1.82,
      }),
    }),
  }),
});
