export const XP_GATHERING_CONFIG = Object.freeze({
  assetPaths: Object.freeze({
    routine: "sprites/UI/xp-gathering-v1/xp-mote-routine.png",
    special: "sprites/UI/xp-gathering-v1/xp-sigil-special.png",
    levelUp: "sprites/UI/xp-gathering-v1/xp-crest-level.png",
  }),
  sourceColors: Object.freeze({
    fallback: 0x8be889,
    xpBlock: 0xffe36b,
    legendBlock: 0xf2c96b,
  }),
  segments: Object.freeze({
    count: 10,
    gapPx: 2,
    radiusPx: 2,
    minimumFillPx: 2,
    emptyColor: 0x080e13,
    emptyAlpha: 0.96,
    legacyEmptyAlpha: 0.9,
    borderColor: 0x4c3b24,
    borderAlpha: 1,
    borderWidthPx: 1,
    fillColor: 0xf2d52b,
    fillHighlightColor: 0xfff1a0,
    fillAlpha: 0.92,
    legacyLowColor: 0x66ff66,
    legacyMidColor: 0xffff66,
    legacyHighColor: 0xffaa00,
    legacyBorderColor: 0x5566aa,
    legacyBorderWidthPx: 2,
    legacyLowThreshold: 0.3,
    legacyHighThreshold: 0.7,
  }),
  motion: Object.freeze({
    changeEpsilon: 0.004,
    fillDurationMs: 420,
    levelCompleteDurationMs: 220,
    levelResetHoldMs: 70,
    levelRemainderDurationMs: 260,
    fillEase: "Cubic.easeOut",
    pulseDurationMs: 260,
    pulseAlpha: 0.92,
    pulseEase: "Sine.easeOut",
  }),
  gainText: Object.freeze({
    fontFamily: "Consolas, monospace",
    fontStyle: "bold",
    color: "#fff0a6",
    stroke: "#090d12",
    strokeThickness: 4,
    fontSizePx: 15,
    startOffsetYPx: 8,
    risePx: 20,
    durationMs: 620,
    ease: "Cubic.easeOut",
    startScale: 0.82,
    maxAlpha: 0.82,
    fadeInRatio: 0.2,
    fadeOutStartRatio: 0.58,
  }),
  pickup: Object.freeze({
    coalesceWindowMs: 48,
    offscreenMarginPx: 24,
    maxActiveSprites: 10,
    staggerMs: 52,
    popDurationMs: 110,
    popRisePx: 10,
    popStartScale: 0.72,
    popEndScale: 1.05,
    popRotationRadians: 0.035,
    popEase: "Sine.easeOut",
    travelFadeStartRatio: 0.84,
    travelScaleLossRatio: 0.36,
    trailEmitRatio: 0.54,
    displaySizePx: 52,
    arrivalSizePx: 28,
    arrivalEchoScale: 1.75,
    arrivalEchoAlphaMultiplier: 0.34,
    arrivalEchoDurationMs: 190,
    arrivalEchoEase: "Sine.easeOut",
    spawnOffsetsPx: Object.freeze([-12, -4, 6, 14]),
    particles: Object.freeze({
      sourceDisplaySizePx: 16,
      sourceAlpha: 0.36,
      sourceAngleStartRadians: -2.45,
      sourceAngleStepRadians: 0.64,
      sourceDistanceBasePx: 8,
      sourceDistanceStepPx: 2,
      sourceDurationBaseMs: 190,
      sourceDurationStepMs: 22,
      sourceEase: "Sine.easeOut",
      trailDisplaySizePx: 14,
      trailAlpha: 0.28,
      trailFallPx: 4,
      trailDurationMs: 150,
      trailEase: "Sine.easeOut",
    }),
    variations: Object.freeze({
      routine: Object.freeze({
        icon: "routine",
        pickupCount: 1,
        particleCount: 1,
        sizeMultiplier: 0.66,
        alpha: 0.66,
        pulseStrength: 0.28,
        showLabel: false,
      }),
      cluster: Object.freeze({
        icon: "routine",
        pickupCount: 2,
        particleCount: 2,
        sizeMultiplier: 0.76,
        alpha: 0.72,
        pulseStrength: 0.4,
        showLabel: false,
      }),
      special: Object.freeze({
        icon: "special",
        pickupCount: 2,
        particleCount: 3,
        sizeMultiplier: 0.9,
        alpha: 0.86,
        pulseStrength: 0.58,
        showLabel: true,
      }),
      levelUp: Object.freeze({
        icon: "levelUp",
        pickupCount: 3,
        particleCount: 3,
        sizeMultiplier: 0.96,
        alpha: 0.9,
        pulseStrength: 0.72,
        showLabel: true,
      }),
    }),
  }),
});
