"""Build phase-locked moving proxies for the approved complex SIDE family."""

from __future__ import annotations

import hashlib
import json
import re
import sys
from pathlib import Path
from typing import Any

import numpy as np
from PIL import Image, ImageChops, ImageStat


ROOT = Path(__file__).resolve().parents[2]
TOOLS = ROOT / "tools" / "piskel-mcp"
sys.path.insert(0, str(TOOLS))

from piskel_document import make_piskel, read_piskel, write_json  # noqa: E402


RUNTIME_ROOT = ROOT / "sprites" / "character" / "survival-ual-player-v1" / "runtime"
COMPLEX_RUNTIME_ROOT = ROOT / "sprites" / "character" / "survival-character-blender-v2" / "runtime"
MOVING_CONFIG_PATH = ROOT / "values" / "movingSideDigAnimation.generated.js"
COMPLEX_MANIFEST_PATH = COMPLEX_RUNTIME_ROOT / "mixamo-complex-dig-runtime-v1-manifest.json"
OUTPUT_FILE = "survival-ual-player-v1-moving-complex-dig-sheet.webp"
OUTPUT_PATH = RUNTIME_ROOT / OUTPUT_FILE
PISKEL_PATH = ROOT / "sprites" / "character" / "piskel" / "runtime-active" / "moving-complex-dig.piskel"
REPORT_PATH = RUNTIME_ROOT / "moving-complex-dig-piskel-report.json"
GENERATED_MODULE_PATH = ROOT / "values" / "movingComplexDigAnimation.generated.js"
FRAME_SIZE = 256
COLUMNS = 16
DISPLAY_SIZE_PX = 123
ORIGIN_Y = 247 / 256
SINGLE_CONTACT_INDEX = 6
DUAL_CONTACT_INDEXES = (6, 28)
DUAL_SAMPLE_INDEXES = tuple(range(22))


def load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def load_generated_config(path: Path) -> dict[str, Any]:
    source = path.read_text(encoding="utf-8")
    match = re.search(r"deepFreeze\((\{.*\})\);\s*$", source, flags=re.DOTALL)
    if not match:
        raise ValueError(f"cannot parse generated moving-side config: {path}")
    return json.loads(match.group(1))


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def extract(sheet: Image.Image, index: int) -> Image.Image:
    x = (index % COLUMNS) * FRAME_SIZE
    y = (index // COLUMNS) * FRAME_SIZE
    return sheet.crop((x, y, x + FRAME_SIZE, y + FRAME_SIZE)).convert("RGBA")


def suppress_green_artifacts(frame: Image.Image) -> tuple[Image.Image, int]:
    pixels = np.asarray(frame, dtype=np.uint8).copy()
    red = pixels[:, :, 0].astype(np.float32)
    green = pixels[:, :, 1].astype(np.float32)
    blue = pixels[:, :, 2].astype(np.float32)
    alpha = pixels[:, :, 3]
    mask = (
        (alpha > 16)
        & (green > 70)
        & (green > red * 1.22)
        & (green > blue * 1.10)
    )
    count = int(mask.sum())
    if count:
        replacement = np.maximum(red, blue)
        pixels[:, :, 1][mask] = np.clip(replacement[mask], 0, 255).astype(np.uint8)
    return Image.fromarray(pixels, "RGBA"), count


def suspicious_green_count(frame: Image.Image) -> int:
    pixels = np.asarray(frame, dtype=np.uint8)
    red = pixels[:, :, 0].astype(np.float32)
    green = pixels[:, :, 1].astype(np.float32)
    blue = pixels[:, :, 2].astype(np.float32)
    alpha = pixels[:, :, 3]
    return int((
        (alpha > 16)
        & (green > 70)
        & (green > red * 1.22)
        & (green > blue * 1.10)
    ).sum())


def visible_luminance(frame: Image.Image) -> float:
    mask = frame.getchannel("A").point(lambda value: 255 if value > 16 else 0)
    red, green, blue = ImageStat.Stat(frame.convert("RGB"), mask=mask).mean
    return 0.2126 * red + 0.7152 * green + 0.0722 * blue


def pack(frames: list[Image.Image]) -> Image.Image:
    rows = (len(frames) + COLUMNS - 1) // COLUMNS
    sheet = Image.new("RGBA", (COLUMNS * FRAME_SIZE, rows * FRAME_SIZE), (0, 0, 0, 0))
    for index, frame in enumerate(frames):
        sheet.alpha_composite(frame, ((index % COLUMNS) * FRAME_SIZE, (index // COLUMNS) * FRAME_SIZE))
    return sheet


def assert_pixel_identity(expected: list[Image.Image], actual: list[Image.Image], label: str) -> None:
    if len(expected) != len(actual):
        raise ValueError(f"{label}: frame count changed")
    for index, (left, right) in enumerate(zip(expected, actual)):
        if ImageChops.difference(left, right).getbbox() is not None:
            raise ValueError(f"{label}: frame {index} changed")


def max_phase_step(run_frames: list[int], count: int) -> int:
    return max((right - left) % count for left, right in zip(run_frames, run_frames[1:]))


def write_generated_module(payload: dict[str, Any]) -> None:
    source = (
        "// Generated by the moving complex-dig Piskel production builder.\n"
        "const deepFreeze = (value) => {\n"
        "  if (!value || typeof value !== \"object\" || Object.isFrozen(value)) return value;\n"
        "  Object.values(value).forEach(deepFreeze);\n"
        "  return Object.freeze(value);\n"
        "};\n\n"
        f"export const MOVING_COMPLEX_DIG_ANIMATION = deepFreeze({json.dumps(payload, indent=2)});\n"
    )
    GENERATED_MODULE_PATH.write_text(source, encoding="utf-8")


def main() -> None:
    moving = load_generated_config(MOVING_CONFIG_PATH)
    complex_manifest = load_json(COMPLEX_MANIFEST_PATH)
    handoff = moving["phaseHandoff"]
    variants = handoff["variants"]
    variant_by_id = {variant["id"]: variant for variant in variants}
    variant_by_start = {int(variant["runStartFrame"]): variant for variant in variants}
    sheet_paths = {
        moving["actions"]["jab"]["sheetKey"]: RUNTIME_ROOT / moving["actions"]["jab"]["fileName"],
        moving["actions"]["cross"]["sheetKey"]: RUNTIME_ROOT / moving["actions"]["cross"]["fileName"],
        handoff["atlas"]["sheetKey"]: RUNTIME_ROOT / handoff["atlas"]["fileName"],
    }
    sheets = {key: Image.open(path).convert("RGBA") for key, path in sheet_paths.items()}
    source_frames: dict[str, list[Image.Image]] = {}
    source_green = 0
    for variant in variants:
        cleaned = []
        for frame_index in variant["frames"]:
            frame, removed = suppress_green_artifacts(extract(sheets[variant["sheetKey"]], frame_index))
            source_green += removed
            cleaned.append(frame)
        source_frames[variant["id"]] = cleaned

    atlas_frames: list[Image.Image] = []
    phase_blocks: dict[str, dict[str, Any]] = {}
    for variant in variants:
        single_start = len(atlas_frames)
        single_frames = source_frames[variant["id"]]
        atlas_frames.extend(single_frames)
        single_indexes = list(range(single_start, single_start + len(single_frames)))

        second = variant_by_start[int(variant["resumeJogFrame"])]
        dual_frames = [source_frames[variant["id"]][index] for index in DUAL_SAMPLE_INDEXES]
        dual_frames.extend(source_frames[second["id"]][index] for index in DUAL_SAMPLE_INDEXES)
        dual_start = len(atlas_frames)
        atlas_frames.extend(dual_frames)
        dual_indexes = list(range(dual_start, dual_start + len(dual_frames)))
        single_run_frames = [int(value) for value in variant["runFrames"]]
        dual_run_frames = [int(variant["runFrames"][index]) for index in DUAL_SAMPLE_INDEXES]
        dual_run_frames.extend(int(second["runFrames"][index]) for index in DUAL_SAMPLE_INDEXES)
        phase_blocks[variant["id"]] = {
            "phaseVariantId": variant["id"],
            "runStartFrame": int(variant["runStartFrame"]),
            "singleFrames": single_indexes,
            "singleRunFrames": single_run_frames,
            "singleResumeJogFrame": int(variant["resumeJogFrame"]),
            "dualFrames": dual_indexes,
            "dualRunFrames": dual_run_frames,
            "dualResumeJogFrame": int(second["resumeJogFrame"]),
        }

    if max(suspicious_green_count(frame) for frame in atlas_frames) != 0:
        raise ValueError("moving complex-dig atlas still contains suspicious green pixels")
    bottoms = []
    for frame in atlas_frames:
        bounds = frame.getchannel("A").getbbox()
        if bounds is None or bounds[0] <= 0 or bounds[1] <= 0 or bounds[2] >= FRAME_SIZE or bounds[3] >= FRAME_SIZE:
            raise ValueError(f"moving complex-dig frame clips or is empty: {bounds}")
        bottoms.append(bounds[3] - 1)
    if max(bottoms) - min(bottoms) > 1:
        raise ValueError("moving complex-dig foot baseline exceeds one source pixel")
    for block in phase_blocks.values():
        if max_phase_step(block["singleRunFrames"], handoff["runFrameCount"]) > 1:
            raise ValueError(f"{block['phaseVariantId']}: single run phase skips")
        if max_phase_step(block["dualRunFrames"], handoff["runFrameCount"]) > 1:
            raise ValueError(f"{block['phaseVariantId']}: dual run phase skips")

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    packed = pack(atlas_frames)
    packed.save(OUTPUT_PATH, format="WEBP", lossless=True, quality=100, method=6)
    runtime_sheet = Image.open(OUTPUT_PATH).convert("RGBA")
    runtime_frames = [extract(runtime_sheet, index) for index in range(len(atlas_frames))]
    assert_pixel_identity(atlas_frames, runtime_frames, "runtime WebP")

    piskel_entry = {
        "id": "moving-complex-dig",
        "displayName": "Moving Complex Dig · phase locked",
        "frameSize": [FRAME_SIZE, FRAME_SIZE],
        "frameCount": len(atlas_frames),
        "sheetColumns": COLUMNS,
        "fps": int(moving["frameRate"]),
    }
    write_json(PISKEL_PATH, make_piskel(piskel_entry, atlas_frames))
    round_trip, width, height, fps = read_piskel(PISKEL_PATH)
    if width != FRAME_SIZE or height != FRAME_SIZE or fps != int(moving["frameRate"]):
        raise ValueError("moving complex-dig Piskel metadata changed")
    assert_pixel_identity(atlas_frames, round_trip, "Piskel")

    aliases = []
    variant_map: dict[str, dict[str, Any]] = {}
    defaults: dict[str, str] = {}
    all_phase_variants = []
    for sequence_index, clip_id in enumerate(complex_manifest["sideSequence"]):
        clip = complex_manifest["clips"][clip_id]
        base_animation_key = clip["animationKey"]
        contacts = clip["contact"].get("contacts") or [clip["contact"]]
        dual = len(contacts) > 1
        phase_map = {}
        for variant in variants:
            block = phase_blocks[variant["id"]]
            frames = block["dualFrames"] if dual else block["singleFrames"]
            run_frames = block["dualRunFrames"] if dual else block["singleRunFrames"]
            resume = block["dualResumeJogFrame"] if dual else block["singleResumeJogFrame"]
            safe_clip = clip_id.replace("_", "-")
            animation_key = f"survival-ual-player-v1-moving-complex-dig-{safe_clip}-{variant['id']}-anim"
            contact_indexes = DUAL_CONTACT_INDEXES if dual else (SINGLE_CONTACT_INDEX,)
            contact_spec = {
                "textureFrame": frames[contact_indexes[-1]],
                "sequenceIndex": contact_indexes[-1],
                "contacts": [
                    {"textureFrame": frames[index], "sequenceIndex": index}
                    for index in contact_indexes
                ],
                "sourceAction": f"moving-proxy:{clip['contact']['sourceAction']}",
                "markerGroup": "hands",
                "visualAlignmentEnabled": False,
            }
            alias = {
                "clipId": clip_id,
                "baseAnimationKey": base_animation_key,
                "phaseVariantId": variant["id"],
                "animationKey": animation_key,
                "frames": frames,
                "runFrames": run_frames,
                "runStartFrame": block["runStartFrame"],
                "resumeJogFrame": resume,
                "contact": contact_spec,
                "dualContact": dual,
            }
            aliases.append(alias)
            all_phase_variants.append(alias)
            phase_map[variant["id"]] = {
                "animationKey": animation_key,
                "resumeJogFrame": resume,
            }
        base_phase = "jab-phase-09" if sequence_index % 2 == 0 else "cross-phase-23"
        defaults[base_animation_key] = phase_map[base_phase]["animationKey"]
        variant_map[base_animation_key] = phase_map

    generated = {
        "version": "moving-complex-dig-piskel-v1-20260821",
        "enabledByDefault": True,
        "basePath": "sprites/character/survival-ual-player-v1/runtime",
        "sheet": {
            "key": "survival-ual-player-v1-moving-complex-dig-sheet",
            "fileName": OUTPUT_FILE,
            "frameCount": len(atlas_frames),
            "frames": list(range(len(atlas_frames))),
            "columns": COLUMNS,
        },
        "sourcePiskel": str(PISKEL_PATH.relative_to(ROOT)).replace("\\", "/"),
        "report": str(REPORT_PATH.relative_to(ROOT)).replace("\\", "/"),
        "displaySizePx": DISPLAY_SIZE_PX,
        "origin": {"x": 0.5, "y": ORIGIN_Y},
        "aliases": aliases,
        "phaseVariants": all_phase_variants,
        "defaultAnimationKeyByBaseAnimation": defaults,
        "variantByBaseAnimationAndPhaseVariantId": variant_map,
    }
    write_generated_module(generated)

    report = {
        "version": generated["version"],
        "generatedAt": "2026-08-21",
        "sourcePolicy": "approved phase-locked Jog plus moving Jab/Cross upper body",
        "stationaryComplexAnimationsChanged": False,
        "sourceGreenPixelsRemoved": source_green,
        "maximumSuspiciousGreenPixelsPerFrame": 0,
        "piskelRoundTripPixelExact": True,
        "runtimeWebpRoundTripPixelExact": True,
        "additionalRescaleApplied": False,
        "perFrameRecenteringApplied": False,
        "displaySizePx": DISPLAY_SIZE_PX,
        "origin": generated["origin"],
        "frameCount": len(atlas_frames),
        "animationAliases": len(aliases),
        "dualContactAliases": sum(1 for alias in aliases if alias["dualContact"]),
        "maximumFootBaselineDriftSourcePx": max(bottoms) - min(bottoms),
        "maximumRunPhaseStep": max(
            max_phase_step(alias["runFrames"], handoff["runFrameCount"])
            for alias in aliases
        ),
        "medianVisibleLuminance": round(float(np.median([
            visible_luminance(frame) for frame in atlas_frames
        ])), 3),
        "runtimeSha256": sha256(OUTPUT_PATH),
        "piskelSha256": sha256(PISKEL_PATH),
    }
    write_json(REPORT_PATH, report)
    print(json.dumps({"ok": True, **report}, indent=2))


if __name__ == "__main__":
    main()
