"""Write the generated JavaScript contract consumed by animation runtime selectors."""

from __future__ import annotations

import json
from copy import deepcopy
from pathlib import Path
from typing import Any

from piskel_document import ensure_parent


def write_runtime_module(
    root: Path,
    config: dict[str, Any],
    variants: list[dict[str, Any]],
    entry_ids: list[str],
    pivot_frames: list[int],
) -> None:
    runtime = deepcopy(config)
    action_frames = list(range(config["phaseHandoff"]["actionFrameCount"]))
    for action in runtime["actions"].values():
        action["frames"] = action_frames
        action["frameRate"] = config["frameRate"]
        action["contactFrame"] = config["contactFrame"]
        action["contactSequenceIndex"] = config["contactSequenceIndex"]
        action["resumeJogFrame"] = (
            action["runStartFrame"] + config["phaseHandoff"]["runPhaseAdvanceFrames"]
        ) % config["phaseHandoff"]["runFrameCount"]
    atlas_frames = [
        frame
        for variant in variants
        if variant["base"] is not True
        for frame in variant["frames"]
    ]
    handoff = runtime["phaseHandoff"]
    handoff["atlas"]["frames"] = atlas_frames
    handoff["atlas"]["frameCount"] = len(atlas_frames)
    handoff["variants"] = variants
    handoff["entryVariantIdByOutgoingJogFrame"] = entry_ids
    handoff["pivot"]["frameByOutgoingJogFrame"] = pivot_frames
    target = root / "values" / "movingSideDigAnimation.generated.js"
    payload = json.dumps(runtime, indent=2)
    source = (
        "// Generated by the moving-side-dig Piskel production builder.\n"
        "const deepFreeze = (value) => {\n"
        "  if (!value || typeof value !== \"object\" || Object.isFrozen(value)) return value;\n"
        "  Object.values(value).forEach(deepFreeze);\n"
        "  return Object.freeze(value);\n"
        "};\n\n"
        f"export const MOVING_SIDE_DIG_PRODUCTION = deepFreeze({payload});\n"
    )
    ensure_parent(target)
    target.write_text(source, encoding="utf-8")
