from pathlib import Path
p=Path('testing/2026-08-12-gameplay-capabilities-contract.mjs');s=p.read_text(encoding='utf-8').replace('DEFAULT_GAMEPLAY_CAPABILITIES.isEnabled(featureId), false, featureId','DEFAULT_GAMEPLAY_CAPABILITIES.isEnabled(featureId), featureId === GAMEPLAY_FEATURE_IDS.SCREEN_CAPTURE, featureId');p.write_text(s,encoding='utf-8')
p=Path('testing/2026-07-20-screen-record-contract.mjs');s=p.read_text(encoding='utf-8')
s=s.replace('defaultKey: "F9"[\\s\\S]*devOnly: true','defaultKey: "F9"')
s=s.replace(r'GAME_CONFIG\.debugMode \? addBoundKey\("screenRecord"\) : null',r'const screenRecord = addBoundKey\("screenRecord"\)')
s=s.replace(r'GAME_CONFIG\.debugMode && justDown\(keys\.screenRecord\)',r'_handleScreenRecordDown\(event\)')
s=s.replace(r'GAME_CONFIG\.debugMode \? new ScreenRecordSystem\(this\) : null',r'GAMEPLAY_FEATURE_IDS\.SCREEN_CAPTURE, this\.gameplayCapabilities,[\s\S]*new ScreenRecordSystem\(this\)')
s=s.replace(r'if \(!this\.enabled \|\| !GAME_CONFIG\.debugMode\) return false',r'if \(!this\.enabled\) return false')
s=s.replace('if (KEYBIND_ACTIONS.some(action => action.id === "screenRecord"))','if (!KEYBIND_ACTIONS.some(action => action.id === "screenRecord"))').replace('production keybind list exposes screenRecord','production keybind list omits screenRecord')
s=s.replace('if (Object.prototype.hasOwnProperty.call(createDefaultKeybinds(), "screenRecord"))','if (!Object.prototype.hasOwnProperty.call(createDefaultKeybinds(), "screenRecord"))').replace('production defaults expose screenRecord','production defaults omit screenRecord')
s=s.replace('|| RUNTIME_GAMEPLAY_CAPABILITIES.isEnabled(GAMEPLAY_FEATURE_IDS.SCREEN_CAPTURE)','|| !RUNTIME_GAMEPLAY_CAPABILITIES.isEnabled(GAMEPLAY_FEATURE_IDS.SCREEN_CAPTURE)')
s=s.replace('if (result !== false || prompted)', 'if (result !== false || !prompted)').replace('production recorder toggle reached the capture chooser','production recorder failed to reach the capture chooser')
p.write_text(s,encoding='utf-8')
p=Path('systems/screenrecord/readme.md');s=p.read_text(encoding='utf-8').replace('Production does not register the F9 action,\nconstruct the recorder, or expose it in Settings.','Production also supports F9 and downloads WebM recordings to the player\'s browser; it does not upload recordings to this directory.');p.write_text(s,encoding='utf-8')
p=Path('readme.md');s=p.read_text(encoding='utf-8').replace('developer cheats, and screen\ncapture.', 'developer cheats. Screen capture is available in the production demo.');p.write_text(s,encoding='utf-8')
