"""Build the runtime JS projection for the canonical LEO player voice catalog."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE_PATH = ROOT / "values/playerVoiceCharacterLeoV1.json"
OUTPUT_PATH = ROOT / "values/playerVoiceCharacterLeoV1.generated.js"
BASE_PATH = "sound/voice-lines/player-character-leo-v1/audio/"


def compact(value: object) -> str:
    return json.dumps(value, ensure_ascii=False, separators=(",", ":"))


def source_hash(payload: bytes) -> str:
    return hashlib.sha256(payload).hexdigest().upper()


def build_config(source: dict) -> dict:
    families = source["families"]
    runtime = source["runtime"]
    return {
        "schemaVersion": source["schemaVersion"],
        "libraryId": source["libraryId"],
        "characterId": source["character"]["id"],
        "voice": source["voice"],
        **runtime,
        "eventIds": {
            **{event_id: event_id for event_id in source.get("silentEventIds", [])},
            **{family["id"]: family["id"] for family in families},
        },
        "events": {family["id"]: family for family in families},
    }


def build_module(source: dict, digest: str) -> str:
    families: dict[str, list[dict]] = {family["id"]: [] for family in source["families"]}
    for clip in source["clips"]:
        families[clip["family"]].append(clip)
    lines = [
        "// Generated by ai-tools/2026-08-30-build-player-leo-runtime-catalog.py.",
        f'export const PLAYER_VOICE_SOURCE_SHA256 = "{digest}";',
        f'const PLAYER_VOICE_BASE_PATH = "{BASE_PATH}";',
        "",
        "function deepFreeze(value) {",
        "  if (!value || typeof value !== \"object\" || Object.isFrozen(value)) return value;",
        "  Object.values(value).forEach(deepFreeze);",
        "  return Object.freeze(value);",
        "}",
        "",
        "function asset(clip) {",
        "  return deepFreeze({",
        "    ...clip,",
        "    voice: \"leo\",",
        "    speaker: \"player\",",
        "    key: `" + source.get("assetKeyPrefix", "player-voice-leo-v1") + "-${clip.id}`,",
        "    path: `${PLAYER_VOICE_BASE_PATH}${clip.file}`,",
        "  });",
        "}",
        "",
        "const family = (...clips) => Object.freeze(clips.map(asset));",
        "",
        f"export const PLAYER_VOICE_CHARACTER = deepFreeze({compact(source['character'])});",
        f"export const PLAYER_VOICE_CONFIG = deepFreeze({compact(build_config(source))});",
        "",
        "export const PLAYER_VOICE_LIBRARY = deepFreeze({",
    ]
    for family_id, clips in families.items():
        lines.append(f"  {json.dumps(family_id)}: family(")
        for clip in clips:
            runtime_clip = {
                key: clip[key]
                for key in ("id", "family", "variant", "tags", "delivery", "file", "text")
            }
            lines.append(f"    {compact(runtime_clip)},")
        lines.append("  ),")
    lines.extend([
        "});",
        "",
        "export const PLAYER_VOICE_FAMILY_IDS = Object.freeze(",
        "  Object.keys(PLAYER_VOICE_LIBRARY),",
        ");",
        "",
    ])
    return "\n".join(lines)


def main() -> int:
    payload = SOURCE_PATH.read_bytes()
    source = json.loads(payload.decode("utf-8"))
    output = build_module(source, source_hash(payload))
    OUTPUT_PATH.write_text(output, encoding="utf-8", newline="\n")
    print(f"Built {OUTPUT_PATH.name}: {len(source['families'])} families, {len(source['clips'])} clips.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
