"""
Implementation Plan for importing v7 layered TMX:

1. Update export_tiled_runtime_override.py to:
   - Use the new v7 TMX file
   - Export root overlays from 01_OPTIONAL_root_overlays layer
   - Export background objects from v2-* layers with GID mapping

2. Update values/tiledWorldOverrideData.js (auto-generated by script)

3. Update WorldModel.js to apply root overlays from exported data

4. Create values/tiledBackgroundObjects.js for background object data

5. Update BackgroundRenderer.js to read and place exported background objects

The key insight: v7 TMX is 800x2120, same tilesets as v5, but now has:
- Authored root overlays (previously procedural)
- Authored 12-layer background objects (previously procedural)
- 3 extra tilesets for background props (firstgid=1693, 1770, 1882)
"""
print("Plan loaded")