export const HUD_QUICK_CONTROLS = Object.freeze({
  enabled: true,
  referenceViewport: Object.freeze({ width: 1280, height: 720 }),
  // Above gameplay/actionbar input, below canonical modal shells (3220+).
  depth: 1970,
  inventory: Object.freeze({
    right: 14,
    bottom: 13,
    width: 94,
    height: 94,
    hitPadding: 4,
    keyOffsetX: 27,
    keyOffsetY: 25,
    keycapWidth: 25,
    keycapHeight: 25,
    keycapAlpha: 0.92,
    keyFontSize: 11,
    keyColor: "#f4e8c8",
    keyStroke: "#061019",
    keyStrokeThickness: 2,
    hoverAlpha: 0.86,
    pressScale: 0.96,
    pulseScale: 1.14,
    strongPulseScale: 1.24,
    fullness: Object.freeze({
      // Presentation saturation only; inventory storage remains unbounded.
      visualCapacityUnits: 100,
      stateCount: 10,
      assetNames: Object.freeze([
        "inventoryFullness01",
        "inventoryFullness02",
        "inventoryFullness03",
        "inventoryFullness04",
        "inventoryFullness05",
        "inventoryFullness06",
        "inventoryFullness07",
        "inventoryFullness08",
        "inventoryFullness09",
        "inventoryFullness10",
      ]),
    }),
  }),
  pause: Object.freeze({
    right: 14,
    gapAboveInventory: 9,
    width: 154,
    height: 36,
    hitPaddingX: 5,
    hitPaddingY: 4,
    label: "{key}  MENU",
    fontSize: 13,
    color: "#f4e8c8",
    stroke: "#02060a",
    strokeThickness: 3,
    hoverAlpha: 0.86,
    pressScale: 0.97,
  }),
  map: Object.freeze({
    right: 14,
    gapAboveInventory: 9,
    gapAbovePause: 7,
    width: 154,
    height: 36,
    hitPaddingX: 5,
    hitPaddingY: 4,
    label: "{key}  WORLD MAP",
    fontSize: 13,
    color: "#bcecff",
    stroke: "#02060a",
    strokeThickness: 3,
    hoverAlpha: 0.86,
    pressScale: 0.97,
  }),
  motion: Object.freeze({
    pressMs: 70,
    pulseMs: 90,
  }),
});
